### ISSUE TITLE
Cursor is system's default when on GTK windows

### ISSUE THREAD

**Issue by Unlimiter** [baskerville/bspwm#1002]
When I hover my pointer over the desktop, it's the one I chose from `lxappearance`. But when I hover it over any window, it turns into what looks like a basic one, I believe it's the default one in the system.

I'm using "Ubuntu 18.04.3".

**Comment by dieggsy** [comment]
@Unlimiter I think I experienced the opposite of this? Hovering over the desktop gave me a `+` shaped cursor, otherwise i'd get what I specified in `.Xresources` - I "fixed" it by adding `xsetroot -cursor_name left_ptr` to my bspwmrc.

**Comment by Unlimiter** [comment]
@dieggsy It did not work as expected. My problem is with the cursor theme, not that the cursor is not "left_ptr" by default.

**Comment by GhostKraft** [comment]
Try enter the theme name of your cursor in the files:
/usr/share/icons/default/index.theme
add this 
Inherits=Cursor_Name

/usr/share/gtk-3.0/settings.ini
add this
gtk-cursor-theme-name=Cursor_Name

After rebooting, the cursor theme should display correctly.

**Comment by erdemgazeloglu** [comment]
> When I hover my pointer over the desktop, it's the one I chose from `lxappearance`. But when I hover it over any window, it turns into what looks like a basic one, I believe it's the default one in the system.
> 
> I'm using "Ubuntu 18.04.3".

i have the exact opposite i try what you wrote and nothing has changed still there is the same problem please help this is very annoying

**Comment by Blurgyy** [comment]
I think it's not a good practice to directly modify system-wide settings, so for anyone wish to achieve this in a user-specific manner, edit file `~/.icons/default/index.theme`:

```dosini
[Icon Theme]
Inherits = your_cursor_name
```

And optionally symlink it to `~/.local/share/icons/default/index.theme` if things are not working properly.
