### ISSUE TITLE
Weird behaviour with apps using qtwebengine

### ISSUE THREAD

**Issue by yousufinternet** [baskerville/bspwm#1008]
Hi, 

This is my first day with bspwm, everything is awesome, but I have noticed a weird behavior that occurs when using bspwm with apps that contain a qtwebengine widget, steps to recreate are:

1- open an app that uses qtwebengine (I tried this with qutebrowser, falkon and I even tried it with a PyQt5 interface that doesn't contain anything but qtwebengine) say on desktop 2.
2- switch to desktop 1. 
3- switch back to desktop 2.

what happens is that a 'Tab' key stroke is sent to qutebrowser (or falkon) window which causes the next element in the web page to get focus and therefore changes the location in page which is very annoying (e.g. if I am on the bottom of the page it immediately jumps to the top highlighting the first selectable element in the page) .

This doesn't happen with i3 and I tried it with qtile and it doesn't happen either. 
but I am not sure if sxhkd is causing it because I haven't tried it with sxhkd running under either of them. 

I am running Arch linux with all the latest updates: 
bspwm 0.9.9-1
sxhkd 0.6.1-1
falkon 3.1.0-6
qutebrowser 1.7.0-1
pyqtwebengine-common 5.13.0-1

Please ask me for any additional information and I will provide

(note: English is not my native language, sorry if you read something unclear)

**Comment by The-Compiler** [comment]
It's a bug in Qt, see [[QTBUG-76268] Tab key is sent to WebEngine view every time the window is minimized - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-76268) - it's fixed in Qt 5.13.1 which was released September 5th.
