### ISSUE TITLE
Window alignment after quit fullscreen mode

### ISSUE THREAD

**Issue by DMaxter** [baskerville/bspwm#1012]
When I set a window to fullscreen and then set to tiling, if that is the only window, it will be disaligned on the screen.
 If, for example, the browser is the only window open on a desktop, when I quit fullscreen mode the window can go out of the screen, not totally, but partially. 
If more windows are open on that desktop and if I focus on one of them, the window finds a position to fit. 
When changing to another desktop, and back to the one with this issue, the window is still not in place

**Comment by mdutra** [comment]
> When I set a window to fullscreen and then set to tiling

Are you sure you're going back to tiled, not pseudo_tiled or floating? Can you resize the window when this happens?

**Comment by DMaxter** [comment]
> > When I set a window to fullscreen and then set to tiling
> 
> Are you sure you're going back to tiled, not pseudo_tiled or floating? Can you resize the window when this happens?

I cannot resize the window, but thanks to your reply I was able to find the problem, I was moving the window
