### ISSUE TITLE
Xorg needs to be reloaded for external projectors and monitors to work

### ISSUE THREAD

**Issue by juacq97** [baskerville/bspwm#1016]
Every day I connect a projector to my laptop, when I do, the projector does not receive the signal automatically, I need to activate it with xrandr, which is fine.
The problem is that the projector does not show my wallpaper or show the windows I put on it, only the cursor is visible. I need to exit bspwm and re-enter, with the projector connected, to operate the projector as if it were a second monitor until the system reboots, which is the behavior I am looking for. Is there a way to avoid having to leave bspwm every time I connect a projector for the first time?
I've tried scripts like mons and set up monitors with arandr, but it still doesn't work. Thanks!

Here is my bspwmrc:

```bash
bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc monitor LVDS-1 -d 1 2 3 4 5 6
bspc monitor VGA-1 -d 7 8 9
bspc monitor HDMI-1 A S D
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config border_width        3
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#151b22"
bspc config active_border_color "#151b22"
bspc config focused_border_color "#3d587a"
bspc config presel_feedback_color "#3d587a"
```

**Comment by dann-merlin** [comment]
Have you tried resetting the newly connected monitor after setting it up with arandr like this:
`bspc monitor HDMI-1 --reset-desktops A S D `
?

Also note, that depending on the way you setup your wallpaper, you probably have to reset it, when connecting a new monitor. (At least with feh)

So the workflow for me when connecting a new monitor and manually configuring it would be:
`xrandr ... (I am mostly just using arandr for this)`
`bspc monitor $new_monitor -d $newmonitor_1 $new_monitor_2 ...`
`~/.fehbg`

**Comment by juacq97** [comment]
That was a very dumb issue with compton. I discovered when I tried to replicate the issue on other WM. The new version (picom) works fine
