### ISSUE TITLE
invisible mpv

### ISSUE THREAD

**Issue by nagy135** [baskerville/bspwm#1020]
I m using mpv as my youtube player (via youtube-dl)...sometimes this strange thing happens that my video is playing but it is invisible, it is not present on any workspace. I open another window right after that one and it open correctly (on correct WS according to my mpv rule) ...
I tested switching to the invisible one because sound is playing (and i can get it's pid) via this command
`xdotool windowactivate $(xdotool search --pid 26289 | tail -1)`
and correct mpv (visible one) gets focus while xdotool prints this error (for invisible one) 
`XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)`
Can someone give me hint how to fix this or at least how to make the window visible? Or is this completely out of bspwm's hands? (i m using bspwm 0.9.7-7-g8fa2185)

**Comment by 4n0nct** [comment]
same thing happens to me sometimes (it just happened right now), DE is kde plasma, no window, only sound. It's ok cause that invisible windows must have closed automatically, but it's quite confusing.

**Comment by nagy135** [comment]
pretty old issue, it didnt happen to me for some time now ...I will close it as this probably isnt bspwm issue. If anyone thinks otherwise, feels free to start discussion bellow

**Comment by bzbug** [comment]
If by any chance this happened to you recently, try running `mpv` with `--no-keepaspect-window` option and see if it solves the issue.
