### ISSUE TITLE
Color settings do not apply to the borders of specific windows.

### ISSUE THREAD

**Issue by GhostKraft** [baskerville/bspwm#1024]
**_Color settings do not apply to the borders of specific windows, such as:_**
urgent_border_color
focused_locked_border_color
active_locked_border_color
normal_locked_border_color
focused_sticky_border_color
active_sticky_border_color
normal_sticky_border_color
focused_private_border_color
active_private_border_color
normal_private_border_color

**_The specified color applies only with these options:_**
focused_border_color
normal border color
presel_feedback_color

**_Maybe I'm pointing something wrong in my configuration file, this is how I set the border color:_**
bspc config focused_border_color	"#6454A1"
bspc config normal_border_color	"#323248"
bspc config presel_feedback_color	"#2A303D"

bspc config urgent_border_color 	"#D3304B"
bspc config focused_locked_border_color "#D3304B"
bspc config normal_sticky_border_color    "#D3304B"
bspc config normal_locked_border_color   "#D3304B"
bspc config focused_sticky_border_color   "#D3304B"
**_But after rebooting, the color in the above windows remains unchanged_**

**Arch Linux
Bspwm 0.9.9-1**

**Comment by dotnetfox** [comment]
Of course they won't be working unless they really do exist. ``man bspwm`` says nothing about them. I believe this issue can be considered as invalid.

**Comment by GhostKraft** [comment]
Based on this document https://github.com/baskerville/bspwm/blob/master/doc/CHANGELOG.md and other people's configurations, I realized that these options were added in bspwm
![изображение](https://user-images.githubusercontent.com/48885256/68086489-bb578700-fe5d-11e9-9b7f-956d22584b75.png)

**Comment by dotnetfox** [comment]
Now I see what you mean. Those settings are mentioned as removed in the changelog, not vice-versa.

**Comment by GhostKraft** [comment]
Thanks for the help did not pay attention to the word "Removals".
Initially, I thought that these options were added rather than deleted, I was also misled by the fact that I met these options in some people in the configuration files, but apparently they were obsolete dotfiles.
