### ISSUE TITLE
Sticky Floating window doesn't change monitor

### ISSUE THREAD

**Issue by djohnson1865** [baskerville/bspwm#1025]
If a window is floating and is moved between monitors, the associated monitor does not change. As a result, if a floating window has the sticky flag toggled and is moved to a second monitor, it will stay visible when the desktop on the associated monitor is swapped, but if the desktop on the monitor it resides on is swapped, it will not stay visible.

**Comment by Ruwey** [comment]
This also happens to me. Did you find a fix?

**Comment by djohnson1865** [comment]
Not as such, I have a feeling it would require an actual patch, just have not had the impetus to dig through the codebase and try to write a fix myself as I no longer use two monitors with bspwm.

**Comment by baskerville** [comment]
Fixed by 5df311b12c06dca86f8e5a56ee522bd48d2178bc.
