### ISSUE TITLE
Terminal overwrites line once

### ISSUE THREAD

**Issue by Unlimiter** [baskerville/bspwm#1030]
Basically, when I write a command and I pass a certain character limit, the characters past that limit overwrite the ones already written from the beginning of the line. This only happens once. At the next limit break, the characters get written in a new line, as they should. Hopefully I described that right. Here's a screenshot:

![](https://i.postimg.cc/brWfyq9p/terminal-overwrite-line.png)

I've tested this in many terminals (xfce4-terminal, st, rxvt, termite, xterm), and with the same result.

EDIT: I've figured out that this happens only when the PS1 variable contains one or more \e[..m sequences.

**Comment by mighty9245** [comment]
it's not related to bspwm or wm at all, your ps1 is invalid. you must wrap unprintables (colors or other formatting codes) in `\[` and `\]`. for example: `\[\e[0m\]`.
