### ISSUE TITLE
How does --ratio work?

### ISSUE THREAD

**Issue by shashurup** [baskerville/bspwm#1034]
I suspect that I just don't understand something but bspc node --ratio 0.33 doesn't seem to do anything with either existing nodes split ratios nor with newly spawned ones.

**Comment by yad-tahir** [comment]
bspc --ratio changes the split ratio of two **selected** nodes. To see the effect, select two nodes, and then send this command via a keyboard shortcut.

**Comment by shashurup** [comment]
What does **selected** mean - focused, active, marked? I want a shortcut which would set some predefined ratio for an active window and its sibling. "Selecting" seems like overkill for me.

**Comment by yad-tahir** [comment]
selected = focused; sorry for the confusion.

If the ratio is 50%, you can re-balance them by using one of the following:
```
bspc node -B  # re-balance focused nodes
sh -c 'fwid=$(bspc query -N -n focused.local); bspc node any.local -f && bspc node -B && bspc node $fwid -f' # re-balance all local nodes passively, i.e. without changing focus.
```      
Othewise, choose the sibling by `bspc node -f @brother`  or `bspc node -f @parent`, and then execute `bspc --ration <your_ratio_between_0_1>`. You can adjust the `sh -c 'fwid....` script above to make the task seamless.

**Comment by shashurup** [comment]
Hm... 
`bspc node -f @brother` just moves the focus to the sibling and subsequent `bspc --ratio 0.33` does nothing. I mean I don't see a way to focus more than one window at time.

**Comment by yad-tahir** [comment]
How do you execute that? You need to key bind them. Check my sxhkb config https://github.com/yad-tahir/dotfiles/blob/master/sxhkb/.config/sxhkd/sxhkdrc. It works perfectly from my side.

**Comment by shashurup** [comment]
Aha, found what I did wrong
`bspc node -f @parent && bspc node --ratio 0.33` works.
Thank you!

**Comment by mighty9245** [comment]
@shashurup, if your problem is solved, close the issue, please.
