### ISSUE TITLE
Can I make a rule based on window title?

### ISSUE THREAD

**Issue by mrgreen3** [baskerville/bspwm#1036]
I have cmus running in a terminal that I want on workspace 6. Have set title to cmus but not sure how to get bspc to push terminal window to workspace 6. Is this possible?

**Comment by mogrein** [comment]
I think here is example how to create such a rule:
https://github.com/baskerville/bspwm/tree/master/examples/external_rules

**Comment by mrgreen3** [comment]
I am trying to get firefox to open on desktop 3 (which does work) then switch back to desktop 1

 `bspc desktop -f 1
`
But it simply stays on 3?
