### ISSUE TITLE
Won't use my config at ~/.config/bspwm/bspwmrc

### ISSUE THREAD

**Issue by ffuszthaler** [baskerville/bspwm#1037]
My config:
```
#!/bin/sh
bspc config border_width 1
bspc config window_gap 15
bspc config top-padding 25
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1
```

I am running this on:
* Arch Linux, Kernel: 5.4.2-arch1-1
* bspwm version:  0.9.7-10-g2ffd9c1

Also it works if I manually do ```bash ~/.config/bspwm/bspwmrc```

**Comment by Pilen** [comment]
Is the file executable?
`chmod +x ~/.config/bspwm/bspwmrc
`

**Comment by ffuszthaler** [comment]
Thanks, I think that fixed it
