### ISSUE TITLE
The meaning of :T@

### ISSUE THREAD

**Issue by yad-tahir** [baskerville/bspwm#1041]
When I subscribe to BSP events, sometimes I get ':T@'. What does the '@' mean? I checked the man page and the source code, but it is still ambiguous ;( 

I think it is related to having multiple nodes selected at the same time. Would you please confirm?

Thank you for your answer in advance.

**Comment by ortango** [comment]
yea that is correct. the code goes does the desktop have a focused node. does the node have a client? if not print @.

**Comment by yad-tahir** [comment]
Thank you for the explanation.
