### ISSUE TITLE
config -m modifying both monitors

### ISSUE THREAD

**Issue by mendess** [baskerville/bspwm#1047]
using `bspc config -m ^2 focused_window_color \#220022` change the border color of borders on both monitors.
```
~> bspwm -version
0.9.7-10-g2ffd9c1
```
```
~> uname -a
Linux tolaria 5.4.5-arch1-1 #1 SMP PREEMPT Wed, 18 Dec 2019 19:48:51 +0000 x86_64 GNU/Linux
```

For reference my dofiles as of now are [here](https://github.com/Mendess2526/spell-book/blob/master/runes/bspwmrc)

**Comment by Lythenas** [comment]
For me this command does not even work:

```sh
$ bspc config -m ^2 focused_border_color \#220022
config -m: Invalid descriptor found in 'focused_border_color'.
```

Same bspwm and linux versions.

However without the `-m ^2` it works but changes the setting globally.

Also this setting is listen in man page under *Global Settings* so this is probably the expected behavior.

**Comment by dotnetfox** [comment]
> change the border color of borders on both monitors.
> `bspc config -m ^2 focused_window_color \#220022`

`bspc config focused_border_color \#220022` is for all monitors you have.
`bspc config -m ^N focused_border_color \#220022` ― N is for your **one** monitor (1, 2, 3 etc).
