### ISSUE TITLE
Faiing to connect to socket

### ISSUE THREAD

**Issue by mlmitchell** [baskerville/bspwm#1057]
I don't know if anybody else is having problems but I've now had the same issue on both an Ubuntu and a Mint install.

I'm installing by downloading from the Git repository and making the binary with gcc as per:

[https://github.com/windelicato/dotfiles/wiki/bspwm-for-dummies](https://github.com/windelicato/dotfiles/wiki/bspwm-for-dummies)

 but after install  none of he key bindings work.

If I swap to a different login terminal I can confirm bspwm and sxhkd are both running.

Attempting to issue a command through bspc results in an error message "Failed to connect to socket".

/tmp/bspwm_0_0-socket has been created but the variable 'echo $BSPWM_SOCKET' is empty, even if I set it BSPWM_SOCKET='/tmp/bspwm_0_0-socket' that doesn't solve the problem.

Is this an issue or is there something wrong with my systems config.

**Comment by SpencerApel** [comment]
Same here
Running Arch Linux 5.4.11
Using bspwm 0.9.9-1

I start bspwm in my .xinitrc
When I reboot and login (through tty1) bspwm does not start and I stay in the tty1 terminal (versus launching bspwm)

So I decided to type bspwm to manually launch it and get the error: "The server closed the connection" can't parse display string"

I then type in "bspc query -M" (to display monitor names)
and get the error: "Failed to connect to the socket"

**Comment by mlmitchell** [comment]
Needed to change the line in bspwmrc to specify a monitor as per:

bspc monitor eDP-1 -d I II III IV .....

Can't believe it took me a week to figure out!

Obviously - this was never a real issue just a config error.
