### ISSUE TITLE
bspc desktops --swap does not work when swapping the focused desktop

### ISSUE THREAD

**Issue by vittorioerba** [baskerville/bspwm#1059]
Ehi! First of all, awesome job! I use bspwm daily and it's super well done.

Using the command (for example)
`bspc desktop II --swap IX`
when dektop II or IX is focused results in no sensible outcome, while if both desktop II and XI are out of focus it swaps desktops as expected.

Is it the correct behaviour? 
If so, how would I achieve a swap between the focused desktop and another one?

Thank you!

**Comment by Brn9hrd7** [comment]
I've just tried swapping desktops and for me it works even when one of the swapped desktop is focused.
Have you tried specifying only one desktop? e.g. `bspc desktop --swap IX`, this should swap the current focused desktop with desktop IX.

**Comment by vittorioerba** [comment]
Ok, seems that now is working; I can't even reproduce the behaviour that I was experiencing.
Thank you very much!
