### ISSUE TITLE
Simpler method to get "state=pseudo_tiled" to ignore dialog boxes?

### ISSUE THREAD

**Issue by Aicaya** [baskerville/bspwm#1062]
Setting a gtk+ program rule to `state=pseudo_tiled` affects all the dialog boxes (preference windows, file choosers, alerts, etc). Only way I could get around it was by using external rules for the programs I wanted in that state:

```
class=$2

if [ "$class" = "Lutris" ] || [ "$class" = "Liferea" ]; then
    title=$(xtitle "$wid")
    case "$title" in
        $class)
            echo "state=pseudo_tiled"
            ;;
        *)
            echo "state=floating"
            ;;
    esac
fi
```

(Both programs have static titles, so I can get away with just that `$class` case statement for now.)

Is there an easier way to get bspwm to ignore dialog boxes that I somehow missed (nothing I could find in the man page, at least), or is this a bug?

**Comment by baskerville** [comment]
You might want to rely on the intermediate consequences:
```sh
eval "$4"
[ "$state" = "tiled" ] && echo "state=pseudo_tiled"
```

**Comment by Aicaya** [comment]
That doesn't seem to do anything, though. I echo'd `$4` to a dummy file and `state` is always empty, so it will never equal "tiled" despite the programs always starting as such.

**Comment by baskerville** [comment]
My bad: `[ "$state" ] || echo "state=pseudo_tiled"`.

**Comment by Aicaya** [comment]
That works, thanks!

**Comment by baskerville** [comment]
Done.
