### ISSUE TITLE
move every desktops from monitor 2 to monitor 1

### ISSUE THREAD

**Issue by MeisterTea** [baskerville/bspwm#1063]
Hi, I tried this script 
```sh
for desktop in $(bspc query -D -m eDP1)
do
  bspc desktop $desktop --to-monitor HDMI2
done
```

The problem is, the last desktop won't move.

Any idea?

**Comment by SeerLite** [comment]
Each monitor needs at least 1 desktop AFAIK. Does it work if you create a "dummy" desktop at the start of the script? This desktop would replace the originally last one.

**Comment by MeisterTea** [comment]
it does, it could be more straightforward though imo
