### ISSUE TITLE
Any way to escape the colon (":") character belonging to a class name?

### ISSUE THREAD

**Issue by SeerLite** [baskerville/bspwm#1071]
For a node with a class such as `example:class`, it is impossible to define a rule since the colon `:` character is reserved as a separator between class and instance name. I have tried multiple ways to escape it such as `example\:class` and `example\\:class` yet bspwm seems to ignore this and understands anything after the colon to be the instance name.
Is there a way to escape it natively without the need for external_rules_command, or is this not implemented?

**Comment by MarcinWieczorek** [comment]
You could recompile bspwm after changing `COL_TOK` in `src/parse.h` or patch it so strtok understands escaped characters, which means replacing strtok with something else.
