### ISSUE TITLE
Focus doesn't follow the window when moving it to another monitor

### ISSUE THREAD

**Issue by AlexAegis** [baskerville/bspwm#1080]
I'm using this command to move the focus (I think its from the example config)

```sh
# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}
```
When staying in a single monitor the focused node swaps with the node in the given direction and keeps the focus.
When swapping the node in a direction where is another monitor it does the swap but the focus stays, so the focus now is on the node with what I swapped spaces.

**Comment by plitter** [comment]
Did you try the `--follow`?

**Comment by AlexAegis** [comment]
I did not know about the flag, I assumed it follows automatically because swapping within the screen it stays focused. Thank you!
