### ISSUE TITLE
Filtering nodes by active desktops not working

### ISSUE THREAD

**Issue by danjenson** [baskerville/bspwm#1094]
Repro:

1. Put a node/window on an inactive desktop
2. Query for active desktops, previous inactive desktop does not show up: `bspc query -D -d .active --names`
3. Select nodes only on active desktops: `bspc query -N -d .active` or `xtitle $(bspc query -N -d .active)`

The node/window on the inactive desktop is returned.

**Comment by Lythenas** [comment]
For me `bspc query -N -d .active` returns every window on every desktop (focused and unfocused) across two monitors. (Same with using `.focused`)

But `bspc query -N -d focused` only return the nodes on the current desktop.

According to the man page of the desktop selector:

>           focused
>               Selects the currently focused desktop.

...

>           [!]focused
>               Only consider the focused desktop.
>
>            [!]active
>               Only consider desktops that are the focused desktop of their monitor.

So I think if the desktop with the node is somewhere in the background (no matter which monitor, if you have multiple) `focused`, `.focused` and `.active` should not show that node.

Maybe this is a bug with the modifiers or we're not understanding something.

Also note that `bspc query -N -d any.active` returns only the nodes of one of the active desktops (on one monitor) but not all of the active desktops (on all monitors).
