### ISSUE TITLE
Sticky flag only works for one monitor

### ISSUE THREAD

**Issue by bbaserdem** [baskerville/bspwm#1098]
I have a floating window that has the sticky flag turned on that was generated on desktop 3 (on monitor 1). When I move the window to a desktop 8 on monitor 2; it does not work as sticky anymore. (Changing to a different desktop 6 also on monitor 2; the sticky window stays at 8.)

Moving the sticky window back to monitor 1 fixes the issue however.

**Comment by plitter** [comment]
`       sticky
           Stays in the focused desktop of its monitor.
`
I guess it might be up for interpretation, but it looks to be defined as sticky for the current monitor, so when you move it to another monitor it might not be sticky anymore. You can check what is happening with `bspc subscribe node_flag`.

**Comment by emanuele6** [comment]
Yeah, that's intended, if you want to have that behaviour you can use [this script](https://www.reddit.com/r/bspwm/comments/hq8ygu/making_floating_scratchpad_windows_follow_focused/fxx4giv?utm_source=share&utm_medium=web2x) if you want them to follow the focused desktop between monitors.

```sh
#!/bin/sh

while bspc subscribe monitor_focus -c 1 > /dev/null; do
    while bspc node 'any.!local.!hidden.sticky.window' -d focused; do
        :
    done
done
```

**Comment by emanuele6** [comment]
This issue can be closed imo.

**Comment by emanuele6** [comment]
Oh, I misread the issue, sorry.
