### ISSUE TITLE
When opening a window with the size of both my monitors combined from my left monitor, it has a weird negative offset

### ISSUE THREAD

**Issue by 6gk** [baskerville/bspwm#1099]
For example, with this rule.

    bspc rule -a sta state=floating border=off rectangle=3360x1080+0+0

when I make a new st window with the class `sta` from my main monitor (right) it covers both my monitors perfectly with no issues.

But if I open it from my 2nd monitor (left) it has a negative offset of that monitor.

I have no idea how to explain this better, and I know this is unclear, so I made a graphic.

https://cdn.discordapp.com/attachments/635625795695542272/699713748621066260/unknown.png

**Comment by plitter** [comment]
If the sta is referring to `feh` program it might be an issue with `feh` doing its own Xinerama stuff. Maybe try `--no-xinerama`? Maybe use `--geometry` in the `feh` command?

**Comment by GaugeK** [comment]
@plitter It does it with other applications too, like st.

**Comment by plitter** [comment]
Ok, I tried replicating it and I don't get your exact issue. I only tried st and giving it a custom class and instance. So when I open it in monitor 1 it opens correctly, monitor 2 just uses its current monitor. But specifying desktop and monitor in the rule made it open correctly when opening on monitor 2.

**Comment by GaugeK** [comment]
@plitter Specifying `monitor` seems to be an okay workaround for my specific issue.

> > Maybe use --geometry in the feh command?

> same issue

I was wrong here, I had forgotten the behavior. If I open it with the geometry `3360x1080` it opens with the offset of the focused monitor, but if I tell it to open with the geometry `3360x1082+0+-1` it does the same thing as I originally said in the issue.

**Comment by 6gk** [comment]
It appears that I can override this behaviour by specifying 'monitor' in the rule.
