### ISSUE TITLE
Window thumbnails in rofi.

### ISSUE THREAD

**Issue by m-kru** [baskerville/bspwm#1100]
A few months ago [rofi](https://github.com/davatorium/rofi) has added an option to show window thumbnail in window switcher https://github.com/davatorium/rofi/commit/aeecf34c279bbbf035f6d7be179d37936c5fe1a6:
```
-[no-]window-thumbnail     Show window thumbnail in window switcher if availalbe.
```
However, this feature does not work in `bspwm`. I really would like to have this functionality, but I do not know where the problem lies. Does it need to be supported also in bspwm or maybe I need to use proper compositor? I already use [picom](https://github.com/yshui/picom), but with the default configuration.

**Comment by plitter** [comment]
It works for me with `rofi -show window -no-config -show-icons`, you commented on this https://github.com/davatorium/rofi/issues/1099.

**Comment by codelif** [comment]
You need to use `rofi -show window -window-thumbnail`
