### ISSUE TITLE
Screen tear 

### ISSUE THREAD

**Issue by kushraj** [baskerville/bspwm#1101]
I'm encountering some weird type of screen tear in floating apps. Once I resize them greater than some specific dimension in either direction, the enlarged part is becoming transparent somehow.
Please take a look at this gif, as may be unable to explain the issue properly.
[https://media.giphy.com/media/SVZbovXNleP4g66Eir/giphy.gif](url)
This issue is most common in xpad (almost everytime), zoom(sometimes) and some save\open file dialogues. 
[https://imgur.com/a/Gn54p1G](url) here is another example of it
can you please take a look and advise on what is happening
Thanks in advance
Edit: The issue is unique to me in bspwm , No such occurence in i3/openbox/gnome
I am using Asus Rog gl552vw, which had an 960m but is toast now, so now relying on intel card only with disabled nouveau on boot (video-linux driver for graphic card  on manjaro is installed)

**Comment by rwilhelm** [comment]
The links are not working...

**Comment by kushraj** [comment]
Sorry, I completely forgot about this issue.
Actually on inspecting it more, turns out to be it was my nvidia gpu which was toasted completely. nouveau driver was what causing this issue. which was solved by blacklisting it and installing correct intel drivers. 
you can close it
