### ISSUE TITLE
Window lose focus

### ISSUE THREAD

**Issue by ask1234560** [baskerville/bspwm#1102]
`bspwm -v 0.9.7-10-g2ffd9c1`
`os- Arch linux `

Cannot able to focus a window with keyboard shortcuts, focus is only gained using mouse only.

To reproduce -

- Open 2 terminals
- Make one terminal in floating mode(currently it has the focus)
- Move focus to the other non floated terminal
- Then we cannot transfer focus back to the floated window

**Comment by Lythenas** [comment]
Focusing floating windows using a direction does not work. But using e.g. rofi (`rofi -show windowcd`) I can switch to floating windows. Or using something like `bspc node any.floating -f` also works. But only correctly if you only have one floating window.

**Comment by m-kru** [comment]
Actually, focusing floating windows using a direction works sometimes. Especially if the floating window is not too big and is close to some edge.

**Comment by plitter** [comment]
You could also do `bspc node -f {next,prev}` as well.

**Comment by ask1234560** [comment]
Yeah that works, but workspace also switches with it

**Comment by plitter** [comment]
You can do `bspc node -f {next,prev}.local` to keep it on current desktop.

**Comment by ask1234560** [comment]
Thanks that works
