### ISSUE TITLE
What is meant by <ip_id> in the node add event?

### ISSUE THREAD

**Issue by j-waters** [baskerville/bspwm#1107]
In the man page, the format for the node add event is as follows:
```node_add <monitor_id> <desktop_id> <ip_id> <node_id>```
What does `ip_id` refer to? Tried looking at the source but my C knowledge is not up to scratch.

Thanks

**Comment by emanuele6** [comment]
Seems to be the node who was previously focused.

**Comment by ortango** [comment]
insertion p[oint] (which is not always the previously focused node)

i'm not sure about the point part, but it would make sense.

**Comment by emanuele6** [comment]
Can you close this? @j-waters

**Comment by j-waters** [comment]
Ah yes, thanks for the input!
