### ISSUE TITLE
Newly created windows do not mark desktop as urgent

### ISSUE THREAD

**Issue by dakyskye** [baskerville/bspwm#1115]
I am trying to make bspwm mark the desktops a window was opened in as urgent, but I have been failing.  If I open foo program in bar workspace, I want bar workspace to be marked as urgent.

**Comment by emanuele6** [comment]
That's not how `bspwm` should behave, but you can easily achive that behaviour with a script.

```sh
bspc subscribe node_add | while read -a msg; do
	bspc query -D -d "${msg[2]}.!focused" \
		&& xdotool set_window --urgency 1 "${msg[4]}"
done
```

**Comment by dakyskye** [comment]
Oh nice, did not know about `bspc subscribe` at all! Even tho I have read bspc manpages a couple of times haha.

**Comment by dakyskye** [comment]
Okay, this was one of the reasons I deleted bspwm.  If I can get the other issue I had fixed, I am happily going to switch back to bspwm.  So, usually, bspwm somehow does not unfocuss Discord window, so I did always miss lots of messages!

**Comment by emanuele6** [comment]
You should just close this issue imho.

Anyways, you can read #811 to find a solution for that problem you are having with `discord` (it looks like it links to one of my reddit comments, lol).

**Comment by dakyskye** [comment]
Yes, I will subscribe to that issue. Thanks!
