### ISSUE TITLE
Build fails on gcc 10

### ISSUE THREAD

**Issue by rien333** [baskerville/bspwm#1119]
Should be relatively easy to fix, see: https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common.

While compiling, I get a ton of errors like the one outlined in the wiki mentioned above, for example:

``` shellsession
/usr/bin/ld: subscribe.o:(.bss+0x838): multiple definition of `screen_width'; bspwm.o:(.bss+0x1b8): first defined here
/usr/bin/ld: subscribe.o:(.bss+0x83c): multiple definition of `default_screen'; bspwm.o:(.bss+0x1bc): first defined here
/usr/bin/ld: subscribe.o:(.bss+0x840): multiple definition of `dpy'; bspwm.o:(.bss+0x1c0): first defined here
collect2: error: ld returned 1 exit status
make: *** [<builtin>: bspwm] Error 1
```

**Comment by fidasx** [comment]
same problem here since arch Linux ships GCC 10 by default

**Comment by shoober420** [comment]
Same issue here.

[bspwm-git-0.9.9.r7.gcf2d407-1-x86_64-build.log](https://github.com/baskerville/bspwm/files/4663598/bspwm-git-0.9.9.r7.gcf2d407-1-x86_64-build.log)

**Comment by rien333** [comment]
No idea if github mentions accomplish anything, but in case he hasn't seen this:  @baskerville

**Comment by raylssonjorge** [comment]
Same problem here. Does anyone have  any idea on how to solve this?

R001001

**Comment by shoober420** [comment]
@raylssonjorge 
You can issue this make build option during compile until this is fixed.

CFLAGS="-fcommon"
