### ISSUE TITLE
dmenu wmctrl window switcher unhide

### ISSUE THREAD

**Issue by kristoferus75** [baskerville/bspwm#1122]
Hi !

I use a dmenu script that shows me the opened windows (with wmctrl -l | dmenu)

if i hide a window with bspc node -g hidden key combination and then start my scipt i see that hidden window and if i select this window in the dmenu list it doesn't unhide (only focus to the right screen)

thanks

kristoferus

**Comment by kristoferus75** [comment]
i have solved it !

**Comment by JonahBranch** [comment]
Hi, I am having this issue. How did you solve it?
