### ISSUE TITLE
move window to current desktop

### ISSUE THREAD

**Issue by kristoferus75** [baskerville/bspwm#1123]
Hi !

I use dmenu as window switcher like wmctrl -l | dmenu
but in bspwm it doesnt open the selected window with
wmctrl -i -a $win 

so i adapt my script that it work with bspc like this :

`bspc node "$win" -g hidden=off -f`

But how can i achive that bspwm move the selected dmenu window to the current dektop like this:

`wmctrl -i -R $win`

-R
 Move the window to the current desktop and activate it.

Thanks !

kind regards 

kristoferus

**Comment by Lythenas** [comment]
You can get the focused desktop with `bspc query -D -d focused` and use `bspc node "$win" -d "$desktop"` to move the node. Or in short something like this:

```
bspc node "$win" -d $(bspc query -d -D focused)
```

Look in the man page for more commands/options like this.

**Comment by kristoferus75** [comment]
thanks !
