### ISSUE TITLE
Freeze after inactivity

### ISSUE THREAD

**Issue by skuzzymiglet** [baskerville/bspwm#1124]
After some inactive time, the screen sleeps, but sometimes when activity resumes, the only thing onscreen is the cursor. Switching to another TTY and back fixes this.

**Comment by skuzzymiglet** [comment]
Can I draw attention to this as it's quite important?

**Comment by skuzzymiglet** [comment]
This seems to apply even to DWM. Anyone else seen this? @baskerville

**Comment by SeerLite** [comment]
Maybe it's a problem with graphics drivers? Specially since switching to TTY and back fixes it.

What graphics card/drivers setup do you have?

**Comment by skuzzymiglet** [comment]
Intel drivers. Integrated GPU, using `xf86-video-intel`.

**Comment by jallbrit** [comment]
What's blanking your screen? A screen locker like `slock` or `i3lock`? Or is it just `dpms`? What's the output of `xset q | grep -A 4 DPMS`?

**Comment by skuzzymiglet** [comment]
```
DPMS (Energy Star):
  Standby: 600    Suspend: 600    Off: 600
  DPMS is Enabled
  Monitor is On
```

It is just dpms. No lockers

**Comment by jallbrit** [comment]
Sorry, I don't know what the problem is. My only idea is as @SeerLite said, it is likely a graphics driver problem.

**Comment by SeerLite** [comment]
> Intel drivers. Integrated GPU, using `xf86-video-intel`.

Try uninstalling `xf86-video-intel` and using the modesetting driver! Maybe that'll fix the problem
