### ISSUE TITLE
Monitor order doesn't persist

### ISSUE THREAD

**Issue by bcspragu** [baskerville/bspwm#1125]
I have two monitors, currently arranged something like:

```
+------------------------------+
|                              |
|                              |
|                              |
|            HDMI1             |
|                              |
|                              |
|                              |
+------------------------------+
                +--------------+
                |              |
                |     eDP1     |
                |              |
                +--------------+
```

Or, in xrandr terms:

```
xrandr --output HDMI1 --mode 3840x2160 --above eDP1
xrandr --output eDP1 --pos 1920x2160
```

I always like desktops 1 through 5 on eDP1, and 6 through 8 on HDMI1. Straight forward enough, I set that up with:

```
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8
```

Sometimes, the monitors end up in the wrong order (e.g. I hit Super+1 and it goes focuses desktop 6), so I switch this back with either of the following:

```
bspc monitor eDP1 --swap HDMI1
# or
bspc wm -O eDP1 HDMI1
```

My problem is that this doesn't stick. Any time I lock my screen, it *always* reverts the ordering to HDMI1, eDP1. It doesn't appear to matter which monitor I set as primary in xrandr either.

Is it a bug that it doesn't remember the explicit monitor ordering, or am I doing something incorrectly?

**Comment by motorto** [comment]
Having the same issue as you , I currently have two monitors HDMI1 and eDP1 (laptop screen) and when plugging the external monitor (HDMI1) , I have a function on bashrc that checks if HDM1 is connected, I do
```

`if xrandr | grep "HDMI1 disconnected"; then 
  bspc monitor eDP1 -n 0 -d  I II III IV V 
  tempo="$(date +%H)"
  if [ "$tempo" -lt 8 ] || [ "$tempo" -ge 20 ]
  then 
    redshift &
    hsetroot -full /hdd/Downloads/a.jpg -tint \#4a4a4a
  else
    hsetroot -full /hdd/Downloads/a.jpg -tint \#787878
  fi
else
  bspc monitor eDP1 -d I II III IV V 
  bspc monitor HDMI1 -d VI VII VIII IX X
  hsetroot -full /hdd/Downloads/a.jpg -tint \#787878
  mons -e left &
fi `

When pressed Super +  1 it goes to desktop 'VI' on monitor HDM1, and not 'I' in eDP1

**Comment by cupnoodles14** [comment]
@motorto you can order monitors explicitly like this
```diff
+ bspc wm -O eDP1 HDMI1
  bspc monitor eDP1 -d I II III IV V 
  bspc monitor HDMI1 -d VI VII VIII IX X
```
or
```diff
+ bspc monitor eDP1 -s '^1'
+ bspc monitor HDMI1 -s '^2'
  bspc monitor eDP1 -d I II III IV V 
  bspc monitor HDMI1 -d VI VII VIII IX X
```

OP's problem seems to be that the order resets after locking the screen. Maybe the screen locker is to blame?

**Comment by motorto** [comment]
Well thanks for the answer @cupnoodles14 but that doesnt seem to fix the problem ! Well I dont know if I should create my own issue then if so, tell me

**Comment by bcspragu** [comment]
@cupnoodles14 You know, the screen locker seems like a viable suspect. I'm using [xsecurelock](https://github.com/google/xsecurelock), and on first inspection nothing seems suspicious, but I'll keep looking. In the mean time, I'll close this bug, and report back if I find anything.
