### ISSUE TITLE
[Question/Feature Request] Swap Window Positions & Tabbed View?

### ISSUE THREAD

**Issue by grravity** [baskerville/bspwm#1134]
Is it not possible to swap windows around? For example if I had two tiled windows open side by side, and wanted to move the left one to be on the right, and move the right one on the left?

And secondly, is it possible to have a tabbed view? For example have two windows side by side, then merge them ontop of each other, and see through the top one into the bottom with transparency, and be able to swap between the two with ease? This is nice for situations where you want more screen realestate in your browser, but also need to type something from your browser, so you can just open up a terminal over browser and type while being able to see the full screen of the browser. Also good in many other situations.

If not, I'd like to request these two as features.

**Comment by g1ftzwerg** [comment]
Regarding your first question: 

If you are using sxhkd in its default configuration, you can swap nodes by using ```super + shift + {h,j,k,l}``` to send them west, south, north or east, respectively. 

You can also create a keybind to swap the focused node and the node that the cursor is currently hovering over, by adding a keybind to your sxhkdrc, e.g.: 
```
super + b
        bspc node -s pointed
```
You can also swap the focused node with the biggest node using ```	bspc node -s biggest```, which is mapped to ```super + g``` by default. 


Regarding your second question: 

Bspwm does not feature a tabbed layout as such, but the behaviour that you describe can be achieved by using the monocle layout (```	bspc desktop -l next```, which is mapped to ```super + m``` by default) and cycling through nodes using ```bspc node -f next.local``` and ```bspc node -f prev.local```. By default, these are mapped to ```super + c``` and ```super + shift + c```, respectively. 

[This](https://www.reddit.com/r/bspwm/comments/etfm3m/for_those_who_like_tabs/) thread on reddit regarding tabbing.

**Comment by grravity** [comment]
Thank you so much! I appreciate it!
