### ISSUE TITLE
bspc node -R did not work

### ISSUE THREAD

**Issue by 66RING** [baskerville/bspwm#1137]
bspc node -R 90|180|270 did not work

Is possible to rotate this

![2020-06-08-155343_2047x1279_scrot](https://user-images.githubusercontent.com/49358576/84005934-82a60000-a9a0-11ea-80ef-2de1725c564b.png)

to THIS without kill the window. Thanks a lot
![2020-06-08-155305_2047x1279_scrot](https://user-images.githubusercontent.com/49358576/84005954-889be100-a9a0-11ea-92d9-2e4e7350968d.png)

**Comment by Lythenas** [comment]
I'm using this to rotate:

```
bspc node @/ --rotate 90
```

You can also specify `-90` and I think all multiples of 90.

**Comment by 66RING** [comment]
> I'm using this to rotate:
> 
> ```
> bspc node @/ --rotate 90
> ```
> 
> You can also specify `-90` and I think all multiples of 90.

It work! Thank you \o/
