### ISSUE TITLE
segfault on start

### ISSUE THREAD

**Issue by syphoxy** [baskerville/bspwm#114]
I'm not really sure what to say about this. sxhkd seems to start up fine. bspwm seems to crash with a segfault.

**Distro Version:** Fedora release 18 (Spherical Cow)
**Kernel:** Linux neutron.syphoxy.net 3.11.10-100.fc18.x86_64 #1 SMP Mon Dec 2 20:28:38 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
**X Version:** X.Org X Server 1.13.3
**Nvidia Version:** 304.116

**Comment by svenstaro** [comment]
I guess this is now too old to be relevant and could be closed.
