### ISSUE TITLE
Bspwmrc does not start on latest version.

### ISSUE THREAD

**Issue by agoodfellow123** [baskerville/bspwm#1141]
Hello there, using VAIO vpceb4z1e with latest manjaro and kernel 5.4 in it. Problem is when I install the arch version or the aur git version of bspwm it does not run bspwmrc. I know its bspwm because it's not running nitrogen. Of course, because of that sxhkd doesn't run either so I can't do any form of operation inside. I normally would think there is a problem with my config however when I install the manjaro version of bspwm, bspwmrc does run although with some problems like not loading border colors or not being able to go to other desktops than the first one.

**Comment by RAR27** [comment]
It's your bspwmrc executable?

**Comment by agoodfellow123** [comment]
It's the Arch repo version so i believe it is.

**Comment by RAR27** [comment]
Make sure by going to `~/.config/bspwm` and running `chmod +x bspwmrc`

**Comment by agoodfellow123** [comment]
That did work! Can you tell me why exactly did that happen?

Also as another problem that happened this time, autostart does not run.

**Comment by RAR27** [comment]
That happened because bspwmrc is pretty much just a shell script that is run. If it's not executable, it cannot be run. Running `chmod +x bspwmrc` makes it executable. 

When you say autostart does not run, what exactly do you mean?

**Comment by agoodfellow123** [comment]
At autostart, I have some basic commands like nitrogen and picom but none works when I use the latest arch but they do work with latest manjaro.

**Comment by RAR27** [comment]
Can you start those programs from command line? Also, how does your bspwmrc look?

**Comment by agoodfellow123** [comment]
Yes I can start those programs from command line. Here is the bspwmrc: https://www.heypasteit.com/clip/0IUTU7

**Comment by RAR27** [comment]
What are you using to autostart the programs?

**Comment by agoodfellow123** [comment]
Um, there is a text file called autostart in .config/bspwm directory isn't that what im supposed to use?

**Comment by RAR27** [comment]
I don't think I've ever heard of an autostart file in that directory, though I could be wrong. What I do is I just put all my autostart programs directly in my bspwmrc. You could try to do it like that. Just make sure to have an ampersand at the end. 
Ex. `picom &`

**Comment by agoodfellow123** [comment]
That... did worked yes but it's really confusing to me I used to just have autostart file when I was using debian and it worked completely fine I really can't understand what's happening.

**Comment by RAR27** [comment]
No problem. Right now, are you using just bspwm without a DE? If so, that would explain it. With Debian, maybe the DE you were using had some sort of autostart thing where you place it into a specific file.

**Comment by agoodfellow123** [comment]
No, I'm actually using it with KDE plasma. I really can't find any explanations.

**Comment by RAR27** [comment]
Hm, interesting. Well, glad I could help!

**Comment by RAR27** [comment]
By the way, you may want to close the issue, since it has been solved.

**Comment by agoodfellow123** [comment]
Ah yes my bad, this is the first time i ever created an issue, thank you.

**Comment by RAR27** [comment]
All good 🙂
