### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by lukasino1214** [baskerville/bspwm#1143]
I am using arch and I want install it. I installed everything(gcc make libxcb xcb-util xcb-util-wm xcb-util-keysyms). How I can solve error?
![image](https://user-images.githubusercontent.com/38435841/85433850-5cc65100-b585-11ea-84fd-2c877e3e5f08.png)

**Comment by zSucrilhos** [comment]
Can confirm having the exact same error building it today
 The only version that works is the binary from the core repo.

**Comment by TheGreatMcPain** [comment]
That error comes from GCC 10 which sets `-fno-common` by default.

Until `-fno-common` work here just set `-fcommon` in your CFLAGS.

@lukasino1214 Assuming this is the aur package.  You should be able to add this to the PKGBUILD right before\
`make PREFIX=/usr`.
```
export CFLAGS="${CFLAGS} -fcommon"
```

**Comment by zSucrilhos** [comment]
> That error comes from GCC 10 which sets `-fno-common` by default.
> 
> Until `-fno-common` work here just set `-fcommon` in your CFLAGS.
> 
> @lukasino1214 Assuming this is the aur package. You should be able to add this to the PKGBUILD right before
> `make PREFIX=/usr`.
> 
> ```
> export CFLAGS="${CFLAGS} -fcommon"
> ```

Thanks, this solved the issue.

**Comment by baskerville** [comment]
Fixed in 6c39ab08233d00feb5ad0b5e6b7ba954dc1b578a.
