### ISSUE TITLE
Question about vertical monitors

### ISSUE THREAD

**Issue by marier-nico** [baskerville/bspwm#1149]
Hello!

I have two monitors. One of them is horizontal, and one is vertical, but they both have the same resolution. The issue I'm facing is that on the vertical monitor, only the lower part of it is used and I can't really figure out why. Polybar seems to go to the top of the monitor though, so it's partly working (the bar is broken, but that's fine, I usually put it on my other monitor). Also, when I make a window fullscreen, it does take the full height of the monitor, it's only in tiling mode that it doesn't work. My `bspwmrc` is [here](https://github.com/marier-nico/dotfiles/blob/652387d966648b0c45b865a60df99c5afa517eea/config/bspwm/bspwmrc), so you can look at it if you need to. Any help would be very appreciated! I also added a screenshot below to show what I mean.

![screenshot](https://imgur.com/ScelH2m.png)

**Comment by marier-nico** [comment]
After further digging and trial and error, I've determined that the issue is that my monitor has a weird `top_padding` value set for (as far as I can tell) no special reason. Running the command `bspc config -m <monitor_sel> top_padding 0` works for my use-case, but I'd still like some help in figuring out why its `top_padding` isn't set to 0 by default.

**Comment by jbh** [comment]
I would like to add that I have a vertical monitor, polybar, a top padding for polybar, and I don't have any issues. Well, I have an annoyance in that if the active window is below/above the threshold for the horizontal monitor, I cannot use directional keys to move between monitors. For example, if my active window is at the bottom and it's below the bottom of the horizontal monitor, I cannot use `super + h` to move to the left, to my left monitor.

I've looked at your configuration. It's a bit more complex than [mine](https://github.com/jbh/dotfiles/blob/master/.config/bspwm/bspwmrc), so I'll have to look at it when I'm less tired. I just wanted to add that I don't think it has to do with your top padding.

**Comment by marier-nico** [comment]
Thanks for taking a look @jbh :smile: 

I can confirm I'm also experiencing the inability to move away from my vertical monitor if the window is above the horizontal one. In any case, I think what's causing my issue is probably to do with polybar. Like I mentioned in my other comment, if I add a delay between setting the padding and running polybar, I can clearly see that the padding is added at the same time as polybar starts. I don't think it can be a coincidence either, it's pretty consistent!

But yeah, since you're also confirming that you don't have issues I'll just close this here and open a question with polybar, I think that would make more sense.
