### ISSUE TITLE
Intellij jetbrains-idea breaks bspwm layers

### ISSUE THREAD

**Issue by poleprogger** [baskerville/bspwm#1155]
Hello, :-)

I found a weird and annoying bug which happens when using intellij. The layer system seems to be broken.

* What happens: The layers seem not to work anymore. It is possible to cycle and give focus to other nodes but they STAY always in background. Always the last opened window stays on top. So visually nothing changes but it is possible to select the other nodes and for example move them to another desktop.
* My Setup: arch linux, kde/plasma, bspwm, picom. All up to date. 
* How to trigger: Not really clear. After some hours of using intellij suddenly the layers are broken.
* What i tried: Restart bspwm, restart plasma. Only complete restart of bspwm (kill of process) fixes the issue.

Please let me know if i can provide any useful debug messages, logfiles etc.

Thanks in advance for any help! :-)

**Comment by StasTelnov** [comment]
Try to add 'wmname LG3D' into ~/.config/bspwm/bspwmrc:
https://wiki.archlinux.org/index.php/Bspwm#Problems_with_Java_applications

**Comment by Sbatushe** [comment]
My solutions is a custom script to switch in "java mode" as shown by StasTelnov:
```
#!/bin/sh

#facciamo andare d'accordo java con bspwm
#arg 0: 1 = on, 0 = off

if [ "$1" = 0 ]; then
    wmname bspwm;
    bspc config focus_follows_pointer true;
    notify-send "java-bspwm disattivato";
else
    wmname LG3D;
    bspc config focus_follows_pointer false;
    notify-send "java-bspwm attivato";
fi
```

then add this on _sxhkdrc.config_:

```
#script per le app java
ctrl + alt + j
    /root/.config/bspwm/bspwm-java.sh 1

shift + ctrl + alt + j
    /root/.config/bspwm/bspwm-java.sh 0
```

this could be written in a more optimized way but i don't care because it just works :) .

**Comment by poleprogger** [comment]
Thanks a lot for the help.
