### ISSUE TITLE
BSPWM Logo Proposal (The Snake Square Style)

### ISSUE THREAD

**Issue by bandithijo** [baskerville/bspwm#1157]
Hello 👋
I am BSPWM user from Indonesia 🇮🇩. I have used BSPWM since April 2019.
Thank you very much for creating the Window Manager that can cover all my needs 🤝.

I want to contribute but I don't know C language. I know Ruby a bit, but I am not really good at programming. 😄

I thought 🤔, I should give something to BSPWM because I have used for a year. And today, I get inspiration BSPWM logo for my Neofetch. 

<div align="center">
<img alt="figure_0" src="https://i.postimg.cc/430zPmXK/bspwm-figure-0.png">
</div>

<div align="center">
<img alt="figure_1" src="https://i.postimg.cc/KjStXwkx/bspwm-figure-1.png">
</div>

This logo inspired by Suckless logo and @spcmd that has recommendation logo on Issue #495 and Snake game.

The figure below is BSPWM ascii art, you can modify it as needed based on this basic pattern.

```
  Binary     Space   Partition  Window  Manager

 █████████  ████████ █████████ ██ ██████████████
 ██     ██  ██       ██     ██ ██ ██    ██    ██
 ██     ██  ██       ██     ██ ██ ██ ██ ██ ██ ██
 ██████████ ████████ █████████ ██ ██ ██ ██ ██ ██
 ██      ██       ██ ██        ██ ██ ██ ██ ██ ██
 ██      ██       ██ ██        ██    ██    ██ ██
 ██████████ ████████ ██        ██████████████ ██
```

I don't really expect my recommendation to be accepted . Being able to make this GitHub Issue on the BSPWM repository is more than enough for me 😇.

I am sorry for my bad English and grammar 🙏.

Thank you 😁

Regards, @bandithijo

**Comment by rwilhelm** [comment]
Please make it as suckless as possible...

![image](https://user-images.githubusercontent.com/154026/88491213-c03b0880-cfa1-11ea-98c7-01cbe3ecc5c6.png)

**Comment by rwilhelm** [comment]
Not sure about the "official suckless rules for proper logo design", but I guess it would resemble something like this:
![g165](https://user-images.githubusercontent.com/154026/88492235-82da7900-cfa9-11ea-9b95-2efd3a7f9623.png)

**Comment by emanuele6** [comment]
@bandithijo, hey that's very cool, man.
