### ISSUE TITLE
[Feature request] --on-restart flag for bspc subscribe so it exits when bspwm restarts

### ISSUE THREAD

**Issue by SeerLite** [baskerville/bspwm#1158]
`bspc subscribe` processes will run until either they're killed manually or bspwm exits and the socket is closed (afaik). Usually `subscribe` scripts are started from bspwmrc.

`bspc wm --restart` will reset some stuff (only rules?) from the wm and then re-run bspwmrc. Since the restart doesn't kill these `subscribe` scripts, it means they're gonna run again and you'll end up with multiple lingering `subscribe` processes.

I propose a new flag for `subscribe` (something like `-r, --on-restart`?). This flag would make the `subscribe` process exit when bspwm is restarted.

An alternative I also like for this is a new event for `subcribe` (something like `restart`). This way, running the following:

    bspc subscribe restart

will yield a special output everytime a restart is produced (`Wrestart`?). That way, a script that reads from this `subscribe` process would only have to read for this special line and can stop manually.

And thank you for all the work you put into bspwm!

**Comment by emanuele6** [comment]
Very cool. To achieve this, I was creating a temporary file named `init` in my `~/.config/bspwm/tmp` directory from my `~/.xinitrc` script, checking for its existance in my `bspwmrc` script and then, if it existed, executing some commands and then removing `~/.config/bspwm/tmp/init`.

Now I can just use this in my `bspwmrc` without having to create a file from `~/.xinitrc` and then removing it:

```sh
[ "$1" -eq 0 ] && {

some_command arg1 arg2
other_command &
...

}
```

Awesome!

**Comment by SeerLite** [comment]
Well, that's definitely a way to do it! I'd still like a way for `subscribe` to exit on restarts though.
It fits my workflow of

    edit scripts -> restart -> new scripts are running
without having to go killing them manually.

Still, thanks a lot!

**Comment by emanuele6** [comment]
@SeerLite, if all you want to do with `bspc subscribe restart` is something like this:

```bash
#!/bin/env bash
# node_add_daemon

bspc subscribe restart node_add | while read -ra msg; do
    [[ "${msg[0]}" = restart ]] && break
    : handle node_add somehow
done
```

You can just run `killall bspc` in your `bspwmrc` and then relaunch all your `bspc subscribe` daemons everytime you run `bspc wm -r`.
```bash
#!/bin/sh
# bspwmrc

killall bspc

node_add_daemon &
node_remove_daemon &
```

**Comment by SeerLite** [comment]
Thanks! I mean, yes that's a valid solution for it too. But what if I want only _some_ of the scripts to restart, and not all? (this is just an example, your solution _does_ work for me)

IMO an `--exit-on-restart` is a really nice and clean solution (disclaimer: idk how hard it is to implement). It allows finer control of scripts in general.

**Comment by emanuele6** [comment]
I don't get why you would want to do that.

You said that you wanted to reload these daemons in case you change their source. I get that, it makes sense.

I don't get why you would want to only terminate the daemons which use the `--exit-on-restart` option and not the others.

What's a use case? Can you think of a decent example?

If you really wanted to have that behaviour for some obtuse reason, you could make `bspwmrc` create a file somewhere called `terminate_node_add_daemon` and make `node_add_daemon` check for its existance for example:

```bash
#!/bin/env bash
# node_add_daemon

bspc subscribe restart node_add | while read -ra msg; do
    [[ -f /path/to/terminate_node_add_daemon ]] && {
        rm /path/to/terminate_node_add_daemon
        break
    }
    : else, handle node_add somehow
done
```

Or something else, even if it's not straight-forward how to do, you can always figure out a way. I don't see the point of this option, but maybe you can change my mind with an example.

**Comment by SeerLite** [comment]
I was gonna link you an [example from Liupold's pidswallow](https://github.com/Liupold/pidswallow/blob/02fd8a2e72d11a4ba0a2a32fae4a9b6d35899535/pidswallow#L72) (a custom script) where I used a little hack with `report` to check for restarts. I think it would have been really clean to use a `--exit-on-restart` flag there.

However, it turns out that some hours ago Liupold made the script WM-independent and [changed the implementation](https://github.com/Liupold/pidswallow/blob/dc50307202622683b8665bc9aeb870c7eb7cb5a6/pidswallow#L77) and is now doing [pretty much what you said](https://github.com/Liupold/pidswallow/blame/dc50307202622683b8665bc9aeb870c7eb7cb5a6/README.md#L57). So yeah, I think it's fine to leave it like this (I still think a flag would be cleaner, but eh)

**Comment by emanuele6** [comment]
> I was gonna link you an [example from Liupold's pidswallow](https://github.com/Liupold/pidswallow/blob/02fd8a2e72d11a4ba0a2a32fae4a9b6d35899535/pidswallow#L72) (a custom script) where I used a little hack with `report` to check for restarts. I think it would have been really clean to use a `--exit-on-restart` flag there.

I don't get why Liupold added that. It's basically forcing the user to call `pidswall --loop &` every time in `bspwmrc` instead of letting the user handle the daemon however he/she pleases. Why? I don't get it.

The function would work just as well like so:
```sh
loop() { #*
        bspc subscribe node_add node_remove | while read -r event; do
                [ "${event#node_add}" != "$event" ] && swallow "${event##* }"
                [ "${event#node_remove}" != "$event" ] && vomit "${event##* }"
        done
        return 0
}
```

**Comment by SeerLite** [comment]
> I don't get why Liupold added that. It's basically forcing the user to call pidswall --loop & every time in bspwmrc instead of letting the user handle the daemon however he/she pleases. Why? I don't get it.

I was the one who did it this way ;) It's for the same reason I said above:


> It fits my workflow of
> 
> ```
> edit scripts -> restart -> new scripts are running
> ```
> 
> without having to go killing them manually.

But as I said, they changed it and now it's pretty much the way you're saying.

**Comment by emanuele6** [comment]
> Actually, I was the one who did made it that way ;) It's for the same reason I said above:

@SeerLite, if you want a certain behaviour, you can just implement it that way for yourself!

Adding that to `pidswallow` made it so users of `pidswallow` **HAD** to use `pidswallow --loop &` in their `bspwmrc` without providing any option to have it not exit on restart (which is very weird!).

You could have just used, this:
```sh
#!/bin/sh
# bspwmrc

killall bspc 2> /dev/null

pidswallow --loop &
```
or this if you wanted to only restart `pidswallw`:
```sh
#!/bin/sh
# bspwmrc

pidof -x pidswallow | xargs -r -n1 -I{} kill {}

pidswallow --loop &
```

--------------------------------------------

This allows users to handle the daemon this way:
```sh
#!/bin/sh
# bspwmrc

pidof -x pidswallow || { pidswallow --loop & }
```
or this way:
```sh
#!/bin/sh
# bspwmrc

[ "$1" -eq 0 ] && {
pidswallow --loop &
}
```
or however they pleased.

**Comment by SeerLite** [comment]
> Adding that to `pidswallow` made it so users of `pidswallow` **HAD** to use `pidswallow --loop &` in their `bspwmrc` without providing any option to have it not exit on restart (which is very weird! definitely something I wouldn't expect and that I would confused by).

Now you're just making a big deal out of it. It's not as bad as you make it out to be and it's functionally the same.

Your suggestions are alright though, in fact

> ```shell
> #!/bin/sh
> # bspwmrc
> 
> [ "$1" -eq 0 ] && {
> pidswallow --loop &
> }
> ```

is something I was already going for.

> Can you think of another example? This one **DEFINITELY** didn't change my mind.

Quoting myself:
> However, it turns out that some hours ago Liupold made the script WM-independent, [changing the implementation](https://github.com/Liupold/pidswallow/blob/dc50307202622683b8665bc9aeb870c7eb7cb5a6/pidswallow#L77) and is now doing [pretty much what you said](https://github.com/Liupold/pidswallow/blame/dc50307202622683b8665bc9aeb870c7eb7cb5a6/README.md#L57). **So yeah, I think it's fine to leave it like this** (I still think a flag would be cleaner, but eh)

---

Please don't be so confrontational about all this stuff. It's not like I'm trying to make user experience worse or anything.

**Comment by emanuele6** [comment]
> Please don't be so confrontational about all this stuff. It's not like I'm trying to make user experience worse or anything.

Before the change:
* you could have just used `pidof -x pidswallow | xargs -r -n1 -I{} kill {}; pidswallow --loop &`.
* I could have used `pidof -x pidswallow || { pidswallow --loop & }`
* someone else could have used whatever.

After the change:
How can a I have the behaviour of `pidof -x pidswallow || { pidswallow --loop & }`? I can't without modifying the source of `pidswallow`, can I?
You are forcing the behaviour of `pidof -x pidswallow | xargs -r -n1 -I{} kill {}; pidswallow --loop &` (pre-change) on all the users.

Conclusion: the script is less flexible isn't it?

Do you understand what I'm saying?

**Comment by SeerLite** [comment]
> After the change:
> [...]
> You are forcing the behaviour of `pidof -x pidswallow | xargs -r -n1 -I{} kill {}; pidswallow --loop &` (pre-change) on all the users.

[No.](https://github.com/Liupold/pidswallow/blame/dc50307202622683b8665bc9aeb870c7eb7cb5a6/README.md#L57)

And I've been saying so for the past 3 replies.

I'm done here.

**Comment by emanuele6** [comment]
I understand (understood) that the code has changed since.
What I'm telling you is why I don't think that code snippet is a valid giustification for `--exit-on-restart` being useful, I was explaining why and I was asking if you had another example.

> I don't see the point of this option, but maybe you can change my mind with an example.

> Can you think of another example? This one DEFINITELY didn't change my mind.
