### ISSUE TITLE
[BEHAVIOUR] bspwm should use the desktop id it passes to erc unless told to do otherwise

### ISSUE THREAD

**Issue by emanuele6** [baskerville/bspwm#1163]
The behaviour of an erc can be different with and without `echo "desktop=$desktop"`.

Example 1:
erc:
```sh
#!/bin/sh

eval "$4"

bspc desktop ^2 -r
bspc monitor "${monitor:-focused}" -a "$(date +'%H|%M|%S')"

#echo "desktop=$desktop"
```
rule:
```shell
bspc rule -a '*' -o desktop=^3
```

Let's assume this layout
```json
{"name":"LVDS1","id":10485766,"randrId":66,"wired":true,"stickyCount":0,"windowGap":0,"borderWidth":3,"focusedDesktopId":10485767,"padding":{"top":20,"right":0,"bottom":0,"left":0},"rectangle":{"x":0,"y":0,"width":1366,"height":768}, "desktops":[
{"name":"1","id":10485767,"layout":"tiled","userLayout":"tiled","windowGap":0,"borderWidth":3,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null},
{"name":"2","id":10485768,"layout":"tiled","userLayout":"tiled","windowGap":0,"borderWidth":3,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null},
{"name":"3","id":10485769,"layout":"tiled","userLayout":"tiled","windowGap":0,"borderWidth":3,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null},
{"name":"4","id":10485770,"layout":"tiled","userLayout":"tiled","windowGap":0,"borderWidth":3,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null}]}
```
* I open a window;
* `bspwm passes` desktop=10485769 (in hex) to erc (result of `^3`);
* I rearrange the desktops in erc: ^1=10485767 ^2=10485769 ^3=10485770 ^4=10485771(new id);
* I don't use `echo "desktop=$desktop"` because I assume it should be implied -> window goes to 10485770 (even though `bspwm` passed 10485769 to erc);
* I use `echo "desktop=$desktop"` -> window actually goes to 10485769.

----------------------------
Example 2:
erc:
```sh
#!/bin/sh

class="$2"
eval "$4"

bspc desktop "${desktop:-focused}.!occupied" -n "${class:-(unknown)}"

#echo "desktop=$desktop"
```
rule+commands:
```shell
bspc rule -a '*' -o desktop=Firefox
bluefish &
```

Let's assume this layout
```json
{"name":"LVDS1","id":10485766,"randrId":66,"wired":true,"stickyCount":0,"windowGap":0,"borderWidth":3,"focusedDesktopId":10485769,"padding":{"top":20,"right":0,"bottom":0,"left":0},"rectangle":{"x":0,"y":0,"width":1366,"height":768}, "desktops":[
{"name":"Firefox","id":10485767,"layout":"tiled","userLayout":"tiled","windowGap":0,"borderWidth":3,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null},
{"name":"qutebrowser","id":10485768,"layout":"tiled","userLayout":"tiled","windowGap":0,"borderWidth":3,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null},
{"name":"Gvim","id":10485769,"layout":"tiled","userLayout":"tiled","windowGap":0,"borderWidth":3,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null},
{"name":"TelegramDesktop","id":10485770,"layout":"tiled","userLayout":"tiled","windowGap":0,"borderWidth":3,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null}]}
```
NOTE: the `Firefox` desktop is not occupied and the focused desktop is 10485769(`Gvim`).

* A `bluefish` window gets open;
* `bspwm` passes desktop=10485767 (in hex) to erc (result of `Firefox`);
* since the `Firefox` desktop is not occupied, its name changes to `Bluefish`;
* I don't use `echo "desktop=$desktop"` -> window goes to 10485769 (i.e. the focused desktop because `Firefox` doesn't yield any result; even though `bspwm` passed 10485767 to erc);
* I use `echo "desktop=$desktop"` -> window actually goes to 10485767.

---------------------------
`bspwm` should remember the desktop id it passed to erc and use that as `desk_desc` unless erc print `desktop=[DESKTOP_SEL]`. (this is what should also happen for `monitor` and `node`.)

**Comment by baskerville** [comment]
Could you try the `resolve-csq` branch?

**Comment by emanuele6** [comment]
It seems to have fixed this.
