### ISSUE TITLE
BUG: behaviour of `bspc node NODE_DESC -f NODE_DESC` is incosistent.

### ISSUE THREAD

**Issue by emanuele6** [baskerville/bspwm#1167]
**output of `bspwm -v`**: `0.9.10-2-g5298a91`
**content of `bspwmrc`**:
```
#!/bin/sh
bspc monitor -d 1 2 3 4 5
```
Setup:
* open a tiled window and a floating terminal in desktop `1`;
* leave desktop `2` empty;
* open a window in desktop `3`;
* leave desktop `4` empty;
* open a window in desktop `5`.

----------------------------------------------

The behaviour of `bspc ND1 -f ND2` is usually "if `ND1` doesn't have a result, don't do anything; if `ND1` has a result, focus the result of `ND1#ND2`"

I just notice that if you use a PATH descriptor as `ND1`, the command will always focus `ND2` regardless of the result of `ND1`; also it will somehow use the result of `ND1` as reference even if it doesn't exist.

------------------------------------------------

Run all of these example commands from the floating terminal in desktop `1`. 

Commands:
* `bspc node 'any.!window.leaf' -f any.tiled` -> does nothing: there is no receptacle;
* `bspc node -i; bspc node 'any.!window.leaf' -f any.tiled; bspc node 'any.!window.leaf' -k` -> focuses the tiled window in desktop `^1`: there is at least one receptacle;
* `bspc node @3:/ -f any.tiled` -> focuses the tiled window in desktop `1`: the root node of desktop `3` exists;
* `bspc node @2:/ -f any.tiled` -> focuses the tiled window in desktop `1` even though `@2:/` doesn't exist and `bspc query -N -n @2:/` fails;
* `bspc node @2:second/east/south/parent/west -f any.tiled` -> focuses the tiled window in desktop `1` even though `@2:second/east/south/parent/west` doesn't exist [...];
* `bspc node @2:elephant -f any.tiled` -> focuses the tiled window in desktop `1`: even though `@2:elephant` shouldn't be valid;
* `bspc node @2:/ -f 'next.!local.window'` -> focuses the window on desktop `3` even though `@2:/` doesn't exist [...];
* `bspc node @4:/ -f 'next.!local.window'` -> somehow uses `@4:/` as the reference even though it doesn't exist and focuses the window in desktop `5`.

AFAIK this problem only occurs when using a PATH descriptor as `ND1`.

**Comment by emanuele6** [comment]
> bspc node @4:/ -f 'next.!local.window' -> somehow uses @4:/ as the reference even though it doesn't exist and focuses the window in desktop 5.

This also happens when you use `bspc '@4:/#next.!local.window' -f` is it intended?
note that `@^4:/` doesn't exist (or at least isn't returned by `bspc query -N -n @4:/` which also fails).

**Comment by baskerville** [comment]
> > * `bspc node @4:/ -f 'next.!local.window'` -> somehow uses `@4:/` as the reference even though it doesn't exist and focuses the window in desktop `5`.

`node A -f B` is equivalent to `node B -f` so it must be because there were no windows between the focused desktop and desktkop *5*.

> This also happens when you use `bspc '@4:/#next.!local.window' -f`. Is it intended?

No it isn't. The only reason the `PATH` descriptor is allowed to return the root of an empty desktop if for `node PATH -i` to work in all cases.

**Comment by emanuele6** [comment]
> `node A -f B` is equivalent to `node B -f`

I noticed that `bspc node next.window -f` and `bspc node next.window -f next.window` (run from the same focused windows) will focus the same window, so I was wrong about saying that `bspc node next.window -f next.window` is equivalent to `bspc node next.window#next.window -f`.

But it's true that the command will run only if `A` has a result, e.g. these two are different:
* `bspc node -f next.window`: focus the next window node;
* `bspc node 'any.!window.leaf' -f next.window`: focus the next window node only if there is a receptacle.

So it's more like "if `A` doesn't have a result, don't do anything; if `A` has a result, focus the result of `B`"

---------------------------------------

> * `bspc node @2:/ -f 'next.!local.window'` -> focuses the window on desktop `3` even though `@2:/` doesn't exist [...];
> * `bspc node @4:/ -f 'next.!local.window'` -> somehow uses `@4:/` as the reference even though it doesn't exist and focuses the window in desktop `5`.

I now get the same behaviour from both command for some reason, but I still get different behaviours for `bspc node '@2:/#next.!local.window' -f` and `bspc node '@4:/#next.!local.window' -f`, but you explained the reason why that happens.

I guess that the reason why `@5:elephant` isn't allowed, but `@2:elephant` is, is that when the selector parser sees that desktop **2** is empty, it just returns the "root node" node and stops parsing the rest of the PATH.

Since there's a reason why this is happening, I think the issue can be closed.
