### ISSUE TITLE
Switching focus between windows not working as expected

### ISSUE THREAD

**Issue by cubetastic33** [baskerville/bspwm#1168]
If I open more than one window and then try to cycle between the windows, multiple windows take focus at once. Earlier it used to cycle properly, but after the latest update this issue happens. [Here](https://i.imgur.com/9j63Aoq.mp4)'s a video demonstrating the issue.

The shortcut I was using to cycle through the windows calls `bspc node -f next.local`.

**Comment by g-w1** [comment]
I have this exact same issue. I think the arch linux update on 2020-08-06 09:38 UTC broke it for me.

**Comment by emanuele6** [comment]
Use `bspc node -f next.local.window` instead of `bspc node -f next.local`.

https://github.com/baskerville/bspwm/commit/d87e6c0f773e189a3a62b2d066b982b3a4e2bd56

https://github.com/baskerville/bspwm/issues/1113

**Comment by g-w1** [comment]
This works but it does not cycle through. Once it reaches the end of the cycle it does nothing. It does not start at the beginning as expected.

**Comment by cubetastic33** [comment]
It seems to work properly as well as cycle for me, but what is the purpose of the older command then?

**Comment by emanuele6** [comment]
> This works but it does not cycle through. Once it reaches the end of the cycle it does nothing. It does not start at the beginning as expected.

@g-w1, are you sure?

> what is the purpose of the older command then?

@cubetastic33, of what? `bspc node -f next.local`?

**Comment by cubetastic33** [comment]
@emanuele6 Yes.

**Comment by emanuele6** [comment]
> @emanuele6 Yes.

@cubetastic33, `next` can select any type of node now, that's just a side-effect, previously it could only select leaf nodes which contained a window and that where not hidden.

**Comment by g-w1** [comment]
Interesting. I have a two monitor setup and it only works as a cycle on the left one. On the right it just stops after it gets to the last node.
output of xandr
```Screen 0: minimum 320 x 200, current 3520 x 1328, maximum 16384 x 16384
LVDS-1 connected primary 1600x900+1920+428 (normal left inverted right x axis y axis) 382mm x 215mm
   1600x900      60.01*+  59.99    59.94    59.95    59.82  
   1400x900      59.96    59.88  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    59.97    59.81    59.91  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
VGA-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
```

**Comment by emanuele6** [comment]
> Interesting. I have a two monitor setup and it only works as a cycle on the left one. On the right it just stops after it gets to the last node.

@g-w1, That doesn't happen for me.

--------------------------------
@cubetastic33, isn't the issue solved?

**Comment by g-w1** [comment]
It works. I had to clear the right monitor of all windows first to take affect.

**Comment by jbh** [comment]
@emanuele6 works great for me. Thanks for the explanation as well.

**Comment by emanuele6** [comment]
I thought `bspc node next -f` would skip hidden nodes as it used to do before the update, but it does not: it only used to "skip" them because `next` and `prev` didn't select hidden nodes before the update, not because `node -f` is programmed to do so.

@g-w1, that problem was probably caused by the presence of an hidden node in the desktop you were using that keybind in (I had the same problem), to avoid this problem, use these selectors instead: `next.local.!hidden.window` and `prev.local.!hidden.window` (remember to quote the string or to escape `!` if you are in a shell).

ping @jbh @cubetastic33.
