### ISSUE TITLE
Reordering desktops not working after last bspwm update

### ISSUE THREAD

**Issue by boogy** [baskerville/bspwm#1169]
Hello,

Since the last update to `bspwm 0.9.10-1` on archlinux `Linux 5.7.12-arch1-1` the desktop reordering is not working properly on all monitors.

I have the following shortcut in `sxhkd` to move a desktop to another monitor:
```bash
alt + control + {Left,Down,Up,Right}
  desk=$(bspc query -D -d focused); \
  monitor=$(bspc query -M --monitor {west,south,north,east}); \
  bspc desktop -m {west,south,north,east}; \
  bspc monitor -f {west,south,north,east}; \
  bspc desktop -f $desk; \
  bspwm-reorder-desktops.sh $monitor &
```

The script to reorder the desktops is as follows (scripts copied from:https://gitlab.com/protesilaos/dotfiles)
```bash
_desk_order() {
	while read -r line; do
		printf "%s\\n" "$line"
	done < <(bspc query -D -m "${1}" --names) | sort -g | paste -d ' ' -s
}
bspc monitor -o $(eval _desk_order "${1:-focused}")
```
The script I use to configure the monitors is as follow:
```bash
_desk_order() {
    while read -r line; do
        printf "%s\\n" "$line"
    done < <(bspc query -D -m "${1:-focused}" --names) | sort -g | paste -d ' ' -s
}

PRIMARY_MONITOR=$(xrandr | grep primary | cut -d ' ' -f 1)
OUTPUTS=($(xrandr --listactivemonitors|awk '{print $4}'|sed '/^$/d'))
NB_OF_MONITORS=${#OUTPUTS[@]}

for MONITOR in ${OUTPUTS[@]}; do
    case $NB_OF_MONITORS in
        1)
            bspc monitor $MONITOR -d 1 2 3 4 5 6 7 8 9 10
            ;;
        2)
            if [[ ${MONITOR} == ${PRIMARY_MONITOR} ]]; then
                bspc monitor $MONITOR -d 4 5 6 7 8 10
            else
                bspc monitor $MONITOR -d 1 2 3 9
            fi
            ;;
        *)
            if [[ ${MONITOR} == ${PRIMARY_MONITOR} ]]; then
                bspc monitor $MONITOR -d 1 2 3 4 5 6 7 8 9 10
            else
                bspc monitor $MONITOR -d 1 2 3
            fi
            ;;
    esac
    ## reorder the desktops for each monitor
    bspc monitor $MONITOR -o $(eval _desk_order $MONITOR)
done
```

In this case I'm in a dual monitor setup and I have one monitor (DP1-2) with desktops `1 2 3 9` and the main monitor (HDMI2) with `4 5 6 7 8 0`. When I move a desktop to the HDMI monitor all workspaces get messed up. Even when running the reorder command by hand it doesn't change anything. When I move a desktop from the HDMI2 -> DP1-2 the desktops are reordered properly on DP1-2.

So the reordering is not consistent and doesn't work properly for both screens. And sometimes it's working on the HDMI2 but not anymore on the DP1-2.

Is there something I'm doing wrong, or is there a problem with bspwm since the last version?
The command `bspc monitor -o` seems completely ignored!

**Comment by baskerville** [comment]
> ```shell
> alt + control + {Left,Down,Up,Right}
>   desk=$(bspc query -D -d focused); \
>   monitor=$(bspc query -M --monitor {west,south,north,east}); \
>   bspc desktop -m {west,south,north,east}; \
>   bspc monitor -f {west,south,north,east}; \
>   bspc desktop -f $desk; \
>   bspwm-reorder-desktops.sh $monitor &
> ```

It looks like the author of the above binding hasn't got a clue about how *sxhkd* works.

This is equivalent to (modulo the classic nonparallel sequences mistake):

```
alt + control + {Left,Down,Up,Right}
    bspc desktop -m {west,south,north,east} --follow && \
    bspwm-reorder-desktops.sh
```

**Comment by boogy** [comment]
OMG, thank you so much it works flawlessly.
I should have seen the issue here but I was so nervous that I didn't thought about it all the way.

Anyway, thanks again for the help.
