### ISSUE TITLE
Rules using WM_NAME only works correctly the first time when using Firefox

### ISSUE THREAD

**Issue by rawbeeh** [baskerville/bspwm#1173]
Version: 0.9.10

I'm using the new WM_NAME selector for Firefox window rules and have the following in my bspwmrc:

```
bspc rule -a firefox:Browser:'About Mozilla Firefox' state=floating
bspc rule -a firefox:Navigator:'Mozilla Firefox (Private Browsing)' desktop='^10'
```

The rules work correctly the first time the windows are opened but any subsequent times it fails.

What happens: 
 - Open Firefox. Open Private Window. Private Window moves to desktop 10. Close Window. Open new private window. This time it doesn't follow the rules and opens in the same workspace. 
- The same thing happens when you open the Firefox About Page in Help > About Firefox. The About Window will float the first time but doing so again results in a tiled window opening. 

Quick Edit:

The issue regarding Private Windows seemed to go away though I'm not sure what causes it. It's working as expected for me and I don't know how to reproduce it at the moment. However, the Firefox About Page is consistent with not respecting window rules when opening it a 2nd time onwards.

**Comment by rawbeeh** [comment]
Quick Edit: 

The issue regarding Private Windows seemed to go away though I'm not sure what causes it. However, the Firefox About Page is consistent with not respecting window rules when opening it a 2nd time onwards.

**Comment by emanuele6** [comment]
> The same thing happens when you open the Firefox About Page in Help > About Firefox. The About Window will float the first time but doing so again results in a tiled window opening.

That may be a `firefox` issue (?): if you close and re-open `firefox`, that rule will be applied again only the first time you open the about-window.

This is very weird.

**Comment by emanuele6** [comment]
I patched `bspwm` to make it send a notification containing the value of **WM_NAME** after it gets it before applying rules.

```diff
diff --git a/src/rule.c b/src/rule.c
index 583b238..277a803 100644
--- a/src/rule.c
+++ b/src/rule.c
@@ -295,6 +295,9 @@ void _apply_name(xcb_window_t win, rule_consequence_t *csq)
 {
 	xcb_icccm_get_text_property_reply_t reply;
 	if (xcb_icccm_get_wm_name_reply(dpy, xcb_icccm_get_wm_name(dpy, win), &reply, NULL) == 1) {
+		char notify_name[2000] = { 0 };
+		snprintf(notify_name, sizeof notify_name, "notify-send \"%s\"", reply.name);
+		system(notify_name);
 		snprintf(csq->name, sizeof(csq->name), "%s", reply.name);
 		xcb_icccm_get_text_property_reply_wipe(&reply);
 	}
```

As you can see from [this video I recorder](https://youtu.be/T2MTZDYrkyk), the second time you open the about-window (and any successive time), the initial value of **WM_NAME** of that window is *Firefox* for some reason (not *About Mozilla Firefox*): this is a firefox issue.

> This `external_rules_command` script tells me that the title is the same every time ("About Mozilla Firefox"):

Since the value of **WM_NAME** changes by the time `bspwm` gets to running `external_rules_command`, you can probably solve this problem pretty easily by using an external rule instead of a standard rule: e.g.

```bash
#!/bin/bash

wid="$1"
class="$2"
instance="$3"
#eval "$4"
title="$(xtitle "$wid")"

[[ "$class" = firefox && "$instance" = Browser && "$title" = 'About Mozilla Firefox' ]] \
    && echo 'state=floating'
```

This issue is not `bspwm`'s fauit. @rawbeeh

**Comment by rawbeeh** [comment]
Thanks for that @emanuele6 ! I'll close this issue.
