### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by roelycooly** [baskerville/bspwm#1178]
For some reason when I switch focus from a window from the top of the tree it focuses everything and and unless I switch focus from the window at the bottom of the tree it always selects not just the window I am trying to focus on but the window before it. For example when I alt tab to focus on the next window it does this: (Selects previous node and next node.)
![image](https://user-images.githubusercontent.com/39352111/89975627-17d0a980-dc1b-11ea-9d20-a34e77499091.png)
And then I would have to run the keybind again to focus on what I actually want to focus on. If I am doing something wrong please tell me, but this never happened before when I was using this config just a month ago.

**Comment by emanuele6** [comment]
Duplicate of #1168, #1171, #1172 and #1177 (this is issue #1778).

To understand what is wrong and how to fix your problem: read the [CHANGELOG](https://github.com/baskerville/bspwm/blob/2492695ad47c7ae8c630bdf22328334f57e41c1a/doc/CHANGELOG.md), read the updated [example `sxhkd` configuration](https://github.com/baskerville/bspwm/blob/2492695ad47c7ae8c630bdf22328334f57e41c1a/examples/sxhkdrc#L65) or read the comments on the other (duplicate) issues.

**Comment by roelycooly** [comment]
Thank you so much
