### ISSUE TITLE
bspc node -f next.local focuses all open windows(nodes)

### ISSUE THREAD

**Issue by fiplox** [baskerville/bspwm#1184]
When I cycle between open nodes (windows) with alt + tab (`bspc node -f next.local`) after focusing the last window it does not focus the first one, but all of them. And if I hit a shortcut to quit window it closes all the windows in the current desktop. I suppose it shouldn't do that.

**Comment by rwilhelm** [comment]
See #1182.

**Comment by fiplox** [comment]
Thank you, it worked! Closing the issue.
