### ISSUE TITLE
Combination of splitting preselection ratio and cancel not working 

### ISSUE THREAD

**Issue by das-s** [baskerville/bspwm#1190]
Preselecting a splitting area with both the `~` direction prefix and the `-o` flag produces unexpected results, especially when selecting the `east` direction. 

I'm currently using the following lines in my sxhkdrc:
```
super + alt + l
  bspc node -o 0.2 -p "~"east
```
This does not result in any preselection. In turn, when using `west,south,north` it works as expected. Also, removing either `-o` or `~` from the line makes it work properly.

Can anybody reproduce this?

**Comment by ortango** [comment]
this is because -o is making a preselection, then right after you are toggling it off with -p. (presel made with -o without a direction already will always be east).

if you want to do that it would be better like

    bspc node focused.automatic -o 0.2 -p east || bspc node -p cancel

**Comment by das-s** [comment]
Thanks for the explanation and workaround!
