### ISSUE TITLE
transfer desktop can cause stickyCount to incorrectly increment

### ISSUE THREAD

**Issue by ortango** [baskerville/bspwm#1199]
bspwm version is latest git.

steps to reproduce:

* set a node to sticky on an active desktop.
* bspc desktop -m next

stickycount will now be +1 on that monitor.

it looks to happen in `insert_node()` during `transfer_sticky_nodes()`

______

i just want to add here, but i probably should open another issue.

using desktop reorder fails silently (returns success), leaving an "unexpected" state, when there are sticky nodes on the desktops being reordered (the desktops swaps fail when the stickies are present).

**Comment by ortango** [comment]
just a note:

for a workaround subtracting the sticky windows on the desktop from stickycount before the relevant `transfer_sticky_nodes()` in `transfer_desktop()` seems to "fix" the issue.

**Comment by baskerville** [comment]
> using desktop reorder fails silently (returns success), leaving an "unexpected" state, when there are sticky nodes on the desktops being reordered (the desktops swaps fail when the stickies are present).

Please create another issue for this.
