### ISSUE TITLE
Matlab Dropdown Menus rendered in the center and close immediately

### ISSUE THREAD

**Issue by rahulaggarwal965** [baskerville/bspwm#1204]
**Using bspwm-git (this occurs with bspwm as well)**

When using Matlab and selecting what should be dropdown menus, they instead appear as floating windows windows at the center of the screen.
https://imgur.com/a/I4mYNQc

I have `_JAVA_AWT_WM_NONREPARENTING=1` and I also tried`AWT_TOOLKIT=MTOOLKIT` but they don't seem to help. `wmname LG3D` does nothing too.

The xprop output for the window is
```
_NET_WM_DESKTOP(CARDINAL) = 5
WM_STATE(WM_STATE):
        window state: Normal
        icon window: 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR
WM_HINTS(WM_HINTS):
        Client accepts input or input focus: False
        window id # of group leader: 0x220002f
WM_TRANSIENT_FOR(WINDOW): window id # 0x220002f
_NET_WM_PID(CARDINAL) = 7915
WM_CLIENT_MACHINE(STRING) = "RVA"
WM_PROTOCOLS(ATOM): protocols
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x0, 0x0, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
        program specified location: 2832, 148
        program specified size: 279 by 387
        window gravity: NorthWest
WM_CLASS(STRING) = "sun-awt-X11-XWindowPeer", "MATLAB R2020b - academic use"
WM_CLIENT_LEADER(WINDOW): window id # 0x220002e
_NET_WM_NAME(UTF8_STRING) = "DefaultOverlayManager.JWindow"
WM_NAME(STRING) = "DefaultOverlayManager.JWindow"
```

but setting `bspc rule -a "sun-awt-X11-XWindowPeer" manage=off` did not help.

Additionally, changing `MATLAB_JAVA` to the jdk8-openjdk/jre did not change anything as well. Is there anything else I can do to make matlab menus work?

**Comment by emanuele6** [comment]
> `bspc rule -a "sun-awt-X11-XWindowPeer" manage=off` did not help.

`sun-awt-X11-XWindowPeer` won't match that window, you sould use `*:sun-awt-X11-XWindowPeer` or `MATLAB R2020b - academic use:sun-awt-X11-XWindowPeer`.

---------------------------------------

A similar issue happens with the `Rulers` "context menu" of `ardour`, try using this rule:

    bspc rule -a 'MATLAB R2020b - academic use:sun-awt-X11-XWindowPeer' center=off

**Comment by rahulaggarwal965** [comment]
Thanks for the quick reply! I ended up using `bspc rule -a 'MATLAB R2020b - academic use:sun-awt-X11-XWindowPeer:DefaultOverlayManager.JWindow' manage=off` which got the behavior I wanted, being properly positioned and focused properly.
