### ISSUE TITLE
Floating windows move while I type

### ISSUE THREAD

**Issue by Occhioverde** [baskerville/bspwm#1206]
Good morning.

I am writing here because I am a new bspwm user and I am facing a rather annoying problem.

As you can see from [this video](https://cloud.nexxontech.it/index.php/s/6K7b94QJ3iRSnbk) (I apologize for the almost negative framerate, but I'm using a VM), in fact, every time I try to use a launcher like Albert or Krunner in floating mode, it moves as I type inside the search box.

If it can be useful to understand the cause of the problem, I'll tell you right now that together with bspwm I use KDE Plasma and that this is my configuration:
```
#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		43

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "*":"krunner" state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Albert state=floating manage=off 
```

Thank you in advance for your help.

**Comment by emanuele6** [comment]
Does this also happen if you disable the border?

```bash
bspc rule -a Albert state=floating manage=off border=off
```

**Comment by Occhioverde** [comment]
> Does this also happen if you disable the border?
> 
> ```bash
> bspc rule -a Albert state=floating manage=off border=off
> ```

Disabling border did the trick on both Krunner and Albert.

Thank you very much!
