### ISSUE TITLE
Window Size on second portrait monitor follows first landscape monitor

### ISSUE THREAD

**Issue by Samael0** [baskerville/bspwm#1208]
I am running two monitors with my main being in landscape orientation and the second being in portrait orientation. Every time I spawn a application on my portrait monitor it does not have a size from top to bottom on the monitor. Instead it starts from the same position as the landscape monitor. I have a [reddit post](https://www.reddit.com/r/bspwm/comments/iy58c6/multimonitor_help/?utm_source=share&utm_medium=web2x&context=3) here explaining with pictures of what is going on. I also noticed that if I use a rule with the `state=fullscreen` it really does cover the whole screen. But I would like to use the `state=tiled`

**Comment by emanuele6** [comment]
Could you reproduce the problem in [the last screenshot](https://preview.redd.it/h4u2c0j1huo51.png?width=4000&format=png&auto=webp&s=ae40700619efd5f4ec1c94f25f113224ba02b5ae) and post the json dump of the tree (`bspc wm -d`)?

**Comment by Samael0** [comment]
`{"focusedMonitorId":14680068,"primaryMonitorId":14680068,"clientsCount":2,"monitors":[{"name":"DP-2","id":14680068,"randrId":459,"wired":true,"stickyCount":0,"windowGap":40,"borderWidth":0,"focusedDesktopId":14680070,"padding":{"top":50,"right":0,"bottom":0,"left":0},"rectangle":{"x":0,"y":560,"width":2560,"height":1440},"desktops":[{"name":"Web","id":14680070,"layout":"tiled","userLayout":"tiled","windowGap":40,"borderWidth":0,"focusedNodeId":46137355,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":{"id":46137355,"splitType":"vertical","splitRatio":0.500000,"vacant":false,"hidden":false,"sticky":false,"private":false,"locked":false,"marked":false,"presel":null,"rectangle":{"x":40,"y":650,"width":2520,"height":1350},"constraints":{"min_width":32,"min_height":32},"firstChild":null,"secondChild":null,"client":{"className":"kitty","instanceName":"kitty","borderWidth":0,"state":"tiled","lastState":"tiled","layer":"normal","lastLayer":"normal","urgent":false,"shown":true,"tiledRectangle":{"x":40,"y":650,"width":2480,"height":1310},"floatingRectangle":{"x":670,"y":625,"width":1220,"height":1310}}}},{"name":"Term","id":14680072,"layout":"tiled","userLayout":"tiled","windowGap":40,"borderWidth":0,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null},{"name":"Discord","id":14680073,"layout":"tiled","userLayout":"tiled","windowGap":40,"borderWidth":0,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null},{"name":"Spotify","id":14680074,"layout":"tiled","userLayout":"tiled","windowGap":40,"borderWidth":0,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null}]},{"name":"DP-0","id":14680066,"randrId":448,"wired":true,"stickyCount":0,"windowGap":40,"borderWidth":0,"focusedDesktopId":14680071,"padding":{"top":610,"right":0,"bottom":0,"left":0},"rectangle":{"x":2560,"y":0,"width":1440,"height":2560},"desktops":[{"name":"Code","id":14680071,"layout":"tiled","userLayout":"tiled","windowGap":40,"borderWidth":0,"focusedNodeId":31457281,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":{"id":31457281,"splitType":"horizontal","splitRatio":0.500000,"vacant":false,"hidden":false,"sticky":false,"private":false,"locked":false,"marked":false,"presel":null,"rectangle":{"x":2600,"y":650,"width":1400,"height":1910},"constraints":{"min_width":32,"min_height":32},"firstChild":null,"secondChild":null,"client":{"className":"Code","instanceName":"code","borderWidth":0,"state":"tiled","lastState":"tiled","layer":"normal","lastLayer":"normal","urgent":false,"shown":true,"tiledRectangle":{"x":2600,"y":650,"width":1360,"height":1870},"floatingRectangle":{"x":2560,"y":25,"width":1440,"height":1440}}}},{"name":"Term","id":14680075,"layout":"tiled","userLayout":"tiled","windowGap":40,"borderWidth":0,"focusedNodeId":0,"padding":{"top":0,"right":0,"bottom":0,"left":0},"root":null}]}],"focusHistory":[{"monitorId":14680066,"desktopId":14680071,"nodeId":0},{"monitorId":14680068,"desktopId":14680070,"nodeId":0},{"monitorId":14680066,"desktopId":14680071,"nodeId":0},{"monitorId":14680066,"desktopId":14680071,"nodeId":31457281},{"monitorId":14680068,"desktopId":14680070,"nodeId":0},{"monitorId":14680066,"desktopId":14680071,"nodeId":31457281},{"monitorId":14680068,"desktopId":14680070,"nodeId":46137355}],"stackingList":[31457281,46137355]}
`

**Comment by Samael0** [comment]
I was able to figure out that the problem was caused by polybar instead of bspwm. I have a [closed issue](https://github.com/polybar/polybar/issues/2213) on the polybar repo with my solution.
