### ISSUE TITLE
Screen freezes, keyboard and mouse completely stop working (can't switch tty)

### ISSUE THREAD

**Issue by tonijarjour** [baskerville/bspwm#1210]
https://www.youtube.com/watch?v=HLZXI0v6Y3s

I'm using Arch Linux with up to date nvidia drivers. bspwm version 0.9.10

**Comment by ortango** [comment]
are you sure that bspwm has anything do do with this? regardless there isn't much information here.

can you ssh into the machine when it is locked up?

**Comment by tonijarjour** [comment]
Alright Ill just close this for now (im assuming its a personal problem). If I get any good info Ill reopen.
