### ISSUE TITLE
Socket produces 0x08 for subscribe command

### ISSUE THREAD

**Issue by patrick96** [baskerville/bspwm#1212]
Since commit https://github.com/baskerville/bspwm/commit/7aca1b6c4e550c1a5a5cea5cb20d9dd8d3190999 (which fixed #1207) the bspwm socket produces a single `0x08` (`SUBSCRIBE_MESSAGE`) byte before the actual output.

This has caused a problem with the polybar bspwm module (https://github.com/polybar/polybar/issues/2224) because we expected the socket to directly return the report message.

Is the socket part of bspwm's public API or is it only supposed to be used with `bspc`?

If it is, this looks like a breaking change and will probably break most programs that use the bspwm socket directly.

If it isn't, it will probably still break programs (but that is no longer your problem :wink:).

I think I can probably work around it and still support both variants of the format, but I'd first like to see what you think and whether is was intended to introduce a breaking change to how subscribe commands are received.

**Comment by baskerville** [comment]
I'll revert this commit.

**Comment by patrick96** [comment]
Thanks for the quick response :smiley:
