### ISSUE TITLE
bspc node -f next.local - select more than one node in cycle

### ISSUE THREAD

**Issue by drdeimos** [baskerville/bspwm#1213]
![4878994d8a8c56550e448f1fd3240b6baf7f10a3](https://user-images.githubusercontent.com/3472810/97219693-641f9480-17db-11eb-9d2f-d24c13bda423.png)
I have hotkey for CYCLE_DIR node selection.
Recently more than one window has been selected in this cycle. I couldn't find an option to disable this behavior.
Perhaps the default loop should still be a loop, and such behavior above should be enabled by some kind of modifier?

**Comment by drdeimos** [comment]
Oh, sorry... I found it:
>- The node descriptors `next` and `prev` might now return any node. The previous behavior can be emulated by appending `.!hidden.window`.

BUT, https://semver.org/ -

>MAJOR version when you make incompatible API changes,
>MINOR version when you add functionality in a backwards compatible manner, and
>PATCH version when you make backwards compatible bug fixes.

According to Semver, it looks like this change shouldn't have been in the patch version. Breaks the current functionality. Not critical, but unpleasant.

P.S. Thank you, for your awesome work. I have been using bspwm for over 4-5 years

**Comment by Kranzes** [comment]
Hi im encountering the same issue too, did you manage to fix it? if you did what was the workaround/fix?

**Comment by drdeimos** [comment]
@Kranzes 
just appended new selectors in sxhkd (hotkey daemon) config
```
super + {_,shift + }c
  bspc node -f {next,prev}.local.!hidden.window
```

**Comment by Kranzes** [comment]
that solved it,thanks

**Comment by ortango** [comment]
@drdeimos : the semantic version business has come up here before.

it's been pointed out that 0.x.x shouldn't be expected as stable [ref](https://semver.org/#spec-item-4)

would you close this if you agree that is the case?
