### ISSUE TITLE
'any' Descriptor: documented vs. actual behavior

### ISSUE THREAD

**Issue by borosai** [baskerville/bspwm#1216]
In order to implement simple window hiding/unhiding in bspwm, I have the following key bindings:
super + d
    bspc node -g hidden
super + shift + d
    bspc node any.hidden.local -g hidden=off

To keep things simple, my goal was to unhide all hidden windows on the focused desktop. After reading the man page, I figured 'any' wouldn't work since it says it "selects the first node that matches the given selectors." However, I tried it anyway, and it unhides them all. That's great for me I guess, but I'm not sure if it's supposed to work that way. I tried using 'any' with another flag (marked, I believe), and the command only affected a single marked window.

So the question is: what should I actually expect from my key bindings above?
Also, is there a better/recommended way to handle this action?

**Comment by ortango** [comment]
bspc node any.hidden.local.window -g hidden=off

check the result of `bspc query -N -n .hidden.!window.local`

you will probably see some parent nodes. one of which is the first result of `.hidden.local` causing this.

**Comment by borosai** [comment]
It never occurred to me that non-window nodes could be hidden along with their child node(s), so thank you ortango. I confirmed your notes on my end, so although I now need to decide how I want to approach unhiding multiple windows, at least I understand what's happening and I can work with that.
