### ISSUE TITLE
Problems using a path containing a desktop_sel as a reference node.

### ISSUE THREAD

**Issue by ortango** [baskerville/bspwm#1218]
first off, i should say i'm not sure that this should work the way i think it should, never the less:

using the latest git master build.

using a path with a desktop_sel as a reference does not work *when using a modifier too*. this seems to be a discrepancy, especially considering the last example below - which i think should functionally be the same thing as the first example (the problematic one).

it seems similar to #804

so for nonsense example:
    
    $ bspc query -N -n @focused:/#next.descendant_of.window
    query -n: Invalid descriptor found in '@focused:/#any.descendant_of.window'.
    
    $ bspc query -N @focused:/ -n next.descendant_of.window
    #the above works, but only for queries, you can not do this for a node command.
    
    $ bspc query -N -n @/#next.descendant_of.window
    #this also works, but is not the same really.
    
    $ bspc query -N -n @focused:/#next
    #works. just an example without a modifier.
    
    $ path=$(bspc query -N -n @focused:/)
    $ bspc query -N -n ${path}#next.descendant_of.window
    #getting the actual id for the path and using that works too.

**Comment by baskerville** [comment]
Thanks for the report!
