### ISSUE TITLE
GUI app that requires root acesss

### ISSUE THREAD

**Issue by GamerTechUni** [baskerville/bspwm#1220]
When I use a gui program like gparted, it does not open, because the program requires a root acess prompt for it to open. How can I make it, so it prompts a root acess prompt, so I can open the program.

**Comment by rwilhelm** [comment]
![image](https://user-images.githubusercontent.com/154026/98329192-f273f180-1ff7-11eb-807c-a65e3452e8fe.png)

**Comment by Lythenas** [comment]
This is probably not (directly) a problem with bspwm. But e.g. gnome automatically start an authentication agent. With bspwm you have to do this manually for some applications to work.

If you start gparted in a terminal (without sudo) you should see something like: `No authentication agent found.` You can install any authentication agent you want (e.g. the one from gnome, kde, etc.). And then simply start it in your bspwmrc. E.g. add the line `lxpolkit &` or something similar.

For arch linux you can find more here:

- https://wiki.archlinux.org/index.php/Polkit
- https://bbs.archlinux.org/viewtopic.php?id=175895

**Comment by GamerTechUni** [comment]
Ok thanks, it has been working.
