### ISSUE TITLE
Switching into/out of fullscreen freezes desktop

### ISSUE THREAD

**Issue by PrangerStefan** [baskerville/bspwm#1222]
Switching into or out of fullscreen mode with any kind of window freezes the desktop (almost everytime) only to be resolved by switching to a different desktop and switching back again.  Visually the window seems to be stuck in an intermediate state, e.g. if I fullscreen the only terminal window on a specific desktop the contents of the terminal, i.e. the prompt, moves up as the terminal in fullscreen mode now occupies the space of my `polybar`. Such a terminal will still respond to keystrokes.

I can also report this happening when I fullscreen a video, e.g. on youtube, by either
 - hitting `f`,
 - double-clicking or
 - via `bspc node -t fullscreen`.

I am kind of restricted with my means of reporting, as I cannot really tell what output would be of interest here. `bspc subscribe report` reports the window that I switched to be fullscreen as in fullscreen state: 
```
WmeDP-1:o1:o2:O3:o4:f5:f6:f7:f8:LT:TT:G:MHDMI-1:o9:O0:LT:TT:G
WmeDP-1:o1:o2:O3:o4:f5:f6:f7:f8:LT:TT:G:MHDMI-1:o9:O0:LT:T=:G
```
(Note that this does also happen without my external monitor attached)

I am running `bspwm -v` : `0.9.7-10-g2ffd9c1`

This is closely related to #170, although their problem seemed to be more isolated, I am experiencing that issue with any kind of window.

**Comment by emanuele6** [comment]
> I am running `bspwm -v` : `0.9.7-10-g2ffd9c1`

`0.9.7` is more than 1 year and 9 months old.

The latest release version of `bspwm` is `0.9.10`.

**Comment by emanuele6** [comment]
If I spam `super + t`(`bspc node -t tiled`) and `super + f`(`bspc node -t fullscrren`), I don't have any problem.

Upgrade to `0.9.10` and see if you can reproduce the issue in that version.

**Comment by PrangerStefan** [comment]
Ok, I was convinced that I did upgrade bspwm, but I didn't check whether that actually worked.... sorry. 

Sadly this did not fix the issue. Tested while I am writing this comment as well as with my suckless terminal. Both still freeze when either switching to our out of fullscreen. 

What is the preferable way to trace such issues down?

**Comment by PrangerStefan** [comment]
Ok, I found the culprit. it was `xcompmgr`. I switched to `picom` which seems to fix the issue! 

Thanks for your help!
