### ISSUE TITLE
Zenity not following bspwm rules

### ISSUE THREAD

**Issue by kushraj** [baskerville/bspwm#1224]
**Zenity is not following bspwm rectangle position rule completely**

Setting a rule for zenity ie ```rectangle=widthxheight+x+y```

On launching the window, size is set as mentioned in rule, but its position is always in screen center.
same behavior  on using either of  bspwmrc or external script for setting the rule

**Comment by ortango** [comment]
you can add `center=false` to your rule to keep dialog windows from being centered.

[ref](https://github.com/baskerville/bspwm/blob/1c795c33512c8f0808c25a75c7416053447aee6f/src/rule.c#L228-L230)

**Comment by kushraj** [comment]
Thanks , that worked
