### ISSUE TITLE
Workspace switching fails: Invalid descriptor found in '^2'

### ISSUE THREAD

**Issue by TheChosenPrometheanKing** [baskerville/bspwm#1225]
**System Specs:**
Distro: Arch Linux
Kernel: 5.9.8-arch1-1
Bspwm Version: 0.9.10
Sxhkd version: 0.6.2

**bspwmrc**
```

#!/bin/sh

#     __                               
#    / /_  _________ _      ______ ___ 
#   / __ \/ ___/ __ \ | /| / / __ `__ \
#  / /_/ (__  ) /_/ / |/ |/ / / / / / /
# /_.___/____/ .___/|__/|__/_/ /_/ /_/ 
#           /_/                        

sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

feh --bg-fill ~/.config/wallpaper/forest.jpg &

bspc config top_padding 20

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
```

**Summary of the description:**
It appears that I am locked to a single workspace. I can't switch to other workspaces with Super+1-9, I can't send windows to other workspaces either. It is as if the other workspaces don't exist.
The config files appear to be valid and worked just fine in the past.
I noticed when I run sxhkd via the terminal to observe the log output, I get the following errors when trying to switch to a different workspace or trying to send a window to a different workspace:

![2020-11-16-142614_434x243_scrot](https://user-images.githubusercontent.com/64966609/99258096-f4b42800-280f-11eb-9ed7-38138d89eb6c.png)

Also, 
Running `bspc query --desktops` returns `0x00600004`.
Running `bspc query -D --names` returns `Desktop`

**Why is this a bspwm issue?**
Because sxhkd still seems to work just fine for other shortcuts (e.g spawning new windows, closing or moving them etc).
It only fails when trying to move windows to different workspaces or set the focus to a different workspace which I think is a follow-up issue because of a bug in bspwm.
I did a lot of research, and the only other post I cam across that has the same problem was here: https://www.reddit.com/r/bspwm/comments/h9450y/any_solution_for_workspace_issue/
The proposed solution didn't work for me.

I hope this issue is investigated and addressed quickly as it essentially renders the system useless, since you are forced to a single workspace.

**Comment by ortango** [comment]
it makes sense you are getting those "errors" from sxhkd since as you see there is only a one desktop.

why not run `bspc monitor -d 1 2 3 4 5 6 7 8 9 10` in a terminal and see if there are errors. *if* there is a bug then that would be the bugged command.

side note: the linked bug was absolutely not fixed in the way that post says that makes no sense - ignore that type stuff.

**Comment by TheChosenPrometheanKing** [comment]
@ortango Wow, running `bspc monitor -d 1 2 3 4 5 6 7 8 9 10` actually fixed the issue. Polybar is showing all workspaces again, switching between them and moving windows works again.

Might still be interesting to know why this had to be ran manually and isnt configured correctly out of the box.
