### ISSUE TITLE
Weird question, can bspwmrc be written in anything other than shellscript?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [baskerville/bspwm#1226]
I had an idea to write a bspwmrc in rust.

I made a lib

```rust
use std::env;
use std::io::{Read, Write};
use std::process;
use std::os::unix::net::UnixStream;

const BUFSIZ: usize = 8192 as usize;
const FAILURE_MESSAGE: i32 = 7;
const SOCKET_ENV_VAR: &'static str = "BSPWM_SOCKET";


fn err(message: &str, code: i32) {
    eprintln!("{}", message);
    process::exit(code);
}


pub fn bspc(cmd: Vec<&str>) {
    let mut i = 0;
    let mut buffer = [0; BUFSIZ];

    // We add all the command line arguments to 'buffer', separated by a null
    // character (\0). At the end, 'i' will store the buffer's length, so we
    // can send it (and nothing more) to the socket stream.
    for string in cmd {
        for c in string.chars() {
            buffer[i] = c as u8;
            i += 1;
        }

        buffer[i] = 0;
        i += 1;
    }

    if i == 0 {
        err("No arguments given.", 1);
    }

    // An environment variable can be set by bspwm (or the user) to tell bspc
    // where the socket file is. If the variable is set, use it. If not, use
    // the new scheme.
    let stream_file = env::var(SOCKET_ENV_VAR)
                          .unwrap_or_else(|_|  format!("/tmp/bspwm{}_{}_{}-socket", "", 0, 0));

    let mut stream = {
        let maybe_stream = UnixStream::connect(stream_file);

        if let Err(_) = maybe_stream {
            err("Failed to connect to the socket.", 1);
        }

        maybe_stream.unwrap()
    };

    stream.write(&buffer[..i]).unwrap();
    let size = stream.read(&mut buffer).unwrap();
    drop(stream);

    // Force a null character at the end of the message.
    buffer[size] = 0;

    let (status, offset) = match buffer[0] as i32 {
        FAILURE_MESSAGE => (1, 1),
        _ => (0, 0),
    };

    let message = String::from_utf8_lossy(&buffer[offset..size]);
    print!("{}", message);

    process::exit(status);
}
```

And I call it from a binary

```rust
const GAP: u16 = 20;

fn main() {
    let gap = GAP.to_string();
    let neg_gap = format!("-{}",GAP);

    // These work
    bspc(vec!["config", "window_gap", &gap]);
    bspc(vec!["config", "top_padding", &gap]);
    bspc(vec!["config", "left_padding", &gap]);
    bspc(vec!["config", "right_padding", &gap]);
    bspc(vec!["config", "bottom_padding", &gap]);    

    for side in ["top_monocle_padding", "right_monocle_padding", "bottom_monocle_padding", "left_monocle_padding"].iter() {
        bspc(vec!["config", *side, &neg_gap])
    }

    // This doesn't
    bspc(vec!["config", "border_width", &gap]);

}
```

I can set window gap and padding but am unable to set border_width.

Is it silly to try to make a bspwmrc in a compiled language like rust or am I doing something wrong?

**Comment by Th3Whit3Wolf** [comment]
My code for the lib came from [here](https://github.com/marionauta/bspc), I modified it to use only the std library.

**Comment by Lythenas** [comment]
It's probably not worth writing your bspwmrc in a compiled language. It's probably not going to be easier to write than in a scripting language and speed does not matter because it is just executed once on startup.

I also start other programs and scripts from by bspwmrc (e.g. polybar, picom, dunst, xidlehook, ...) which will probably be slightly harder in Rust than in bash.

However I think it should be possible to just replace your bspwmrc with any executable. You should also be able to use any other scripting language with a shebang at the top of the file. E.g. `#!/bin/fish` if you want to use the fish scripting language or `#!/bin/python` if you want to use python. It think there is also a tool that can execute rust code in script files. You should be able to also use that in a shebang.

**Comment by Th3Whit3Wolf** [comment]
I'm doing it mostly to see if I can and partially to combine a few different scripts that I'd otherwise call from bspwmrc.

I use bspwm inside KDE. Autostart scripts get launched be KDE, so that's not an issue.  

My idea was to combine a few different scripts I've seen (mostly involving layouts) and build them into a compiled bspwmrc. 

That's what I thought too, I am quite perplexed that some of the commands work and some don't. I am not sure what would cause this.
