### ISSUE TITLE
Borders Not Drawn on VS Code with Custom Title Bar

### ISSUE THREAD

**Issue by jacksonSingleton** [baskerville/bspwm#1229]
![2020-11-20-003325_1920x1080_scrot](https://user-images.githubusercontent.com/17009633/99767095-0fb0c180-2ac8-11eb-9d35-a2b73b463dbf.png)
Pretty much the dealio. Native title bar looks awful, I just want my borders with custom. Not sure if there's some bspc rules or anything like that I can do to fix that. I've seen other people post this issue, but as I said, I don't want native title.

**Comment by Ferryistaken** [comment]
This is a vscode problem, go in settings, then search for `title bar style` and change it from `custom` to `native`, then restart vscode. Some applications(like chromium) let you choose between using their title bar and borders and your systems's.
Nice terminal prompt btw

**Comment by alexacallmebaka** [comment]
> This is a vscode problem, go in settings, then search for `title bar style` and change it from `custom` to `native`, then restart vscode. Some applications(like chromium) let you choose between using their title bar and borders and your systems's.
> Nice terminal prompt btw

The problem with this is that if you disable the custom title bar, you get [this ](https://github.com/microsoft/vscode/issues/101314)issue (or at least I did).

**Comment by Ferryistaken** [comment]
oh wow I never got that! I'm using Arch with `code` version `1.51.1`. I also use picom as my compositor

**Comment by alexacallmebaka** [comment]
Okay, weird thing. I tried switching back a couple of days ago, and I was still having the same issue. I decided to give it one more try today, and it's now working just fine. I have made several changes to my system in the time between both tries, and it would be impossible for me to pinpoint what changed caused this but here we are. Nonetheless, switching back to the native title bar gave me the bspwm border back.

**Comment by Ferryistaken** [comment]
The name of the setting is a bit confusing, the "native" title bar actually uses custom borders(it uses bspwm borders), while the "custom" setting uses native borders(native to vscode). I assumed that OP meant native as in vscode native title bar, but I may be wrong

**Comment by alexacallmebaka** [comment]
Ah, I see where the confusion arises. I could be wrong too.

**Comment by Ferryistaken** [comment]
Well until OP doesn't reply or close the issue we'll never know @jacksonSingleton

**Comment by jacksonSingleton** [comment]
I apologize, been working in GitLabs nowadays and missed the notifs! Still having the issue but I don't rock BSPWM borders anymore so not really an issue. I messed around with picom and a bunch of other configs to no avail. Wish I had a more specific answer

**Comment by jacksonSingleton** [comment]
Oh and  @Ferryistaken the native bar is what I was trying to avoid. The unfitting GTK theme is much less preferable than something that fits with the rest of my apps.

**Comment by Lythenas** [comment]
As far as I can tell:

- native = from the system (i.e. bspwm borders)
- custom = from vs code (i.e. the windows looking title bar in the OPs picture)

For me when I set "Window: Title Bar Style" to "native" in VS Code I get the normal bspwm borders as expected (without the icon at the left and minimize etc button on the right).

Note that I'm using the open source build of VS Code on Arch and not the build by Microsoft. But I would expect them to behave the same.

**Comment by jacksonSingleton** [comment]
@Lythenas You mind posting a screenshot of what your build looks like? My native currently has a very different looking bar. I believe I'm using the official Microsoft build

**Comment by Ferryistaken** [comment]
@Lythenas I am using the open source build too and I can confirm that native = bspwm borders while custom = vscode's own borders
![2020-12-07-160602_862x1416_scrot](https://user-images.githubusercontent.com/47927670/101405463-1ef48500-38a6-11eb-8ce7-ad2e3149188b.png)
@jacksonSingleton here is the screenshot

**Comment by Lythenas** [comment]
@Ferryistaken that's pretty much how it looks for me too

**Comment by jacksonSingleton** [comment]
Well it looks like I just might be out of luck. I was hoping to find a balance that would let me use my xrdb colorschemes for the title bar(custom) as well as keeping the BSPWM borders. I'm sure there's some solution, but just not worth the energy over some small aesthetic differences.
