### ISSUE TITLE
focus=off, follow=off, but Mailspring still steals my focus on launch

### ISSUE THREAD

**Issue by Ferryistaken** [baskerville/bspwm#1230]
I would like to make `Mailspring` start at every login, and go to desktop 10, so in my `bspwmrc` I put this line
```bash
bspc rule -a Mailspring desktop=10 follow=off focus=off
```
Mailspring spawns in desktop 10, but still steals my focus and makes me go to desktop 10. I also tried putting them on separate lines like so
```bash
bspc rule -a Mailspring desktop=10
bspc rule -a Mailspring follow=off
bspc rule -a Mailspring focus=off
```

**Comment by SeerLite** [comment]
Maybe it's Mailspring stealing the focus through EWMH requests? If so, you can ignore these with
```shell
bspc config ignore_ewmh_focus true
```

**Comment by Ferryistaken** [comment]
Thanks, this worked, is there a man page/other resource where I can find more info on all this Xorg specific settings?

**Comment by SeerLite** [comment]
It's all in the man page! `man bspwm` and look for the "SETTINGS" section.

**Comment by Ferryistaken** [comment]
Thanks!
