### ISSUE TITLE
Cusor theme works everywhere except the desktop.

### ISSUE THREAD

**Issue by Filip62** [baskerville/bspwm#1231]
Hello.

So I set my cursor-theme in LXAppearence, in `.config/gtk-3.0/settings.ini`, in `/home/filip/.icons/default/index.theme`.

They work everywhere except the desktop. So it does not work when my cursor is not hovering over any window.
The configuration works in Qtile.

Thank you for help.

**Comment by SolitudeSF** [comment]
run `xsetroot -cursor_name left_ptr`

**Comment by Filip62** [comment]
I do that in .xprofile.
Oh, of course I forgot to actually verify that the program is installed and of course it was not.
Thank You.
