### ISSUE TITLE
No XDG_SEAT_PATH defined when sxhkd is managed by systemd

### ISSUE THREAD

**Issue by Arteneko** [baskerville/bspwm#1234]
When running `sxhkd` in the `bspwmrc` configuration file,

```
pkill sxhkd ; sxhkd &
```

everything works as expected (ie `XDG_SEAT_PATH` is defined, among other things).

When running `sxhkd` through a user-bound unit file, by putting the following in the `bspwmrc`,

```
systemctl --user restart sxhkd
```

the daemon starts, but no `XDG_SEAT_PATH` is defined and some other weirdness happens (like reloading bspwm kills every window instead of reparenting them).

I tried and obtained this behaviour using:

- bspwm 0.9.10
- sxhkd 0.6.2
- LightDM 1.30.0
- SDDM 0.19.0-2

I wonder why the parent of the sxhkd process matters in this case, because as far as I understood things, bspwm is the one supposed to handle seats and such, sxhkd being a daemon that should only manage hotkeys.

**Comment by ortango** [comment]
it seems this is not a bspwm issue at all?

>bspwm is the one supposed to handle seats and such

nope. it manages windows.

**Comment by Arteneko** [comment]
Then I wonder which component in this chain would break it when sxhkd changes parent, since this literally is the only change being done.

**Comment by ortango** [comment]
the parent will affect the inherited environment. DISPLAY might not be set (or BSPWM_SOCKET is wrong). you could dump sxhkd's environment and inspect the difference.

as far as i can tell from google `XDG_SEAT_PATH` is specific to the display manager - but i haven't found good documentation.

**Comment by Lythenas** [comment]
When running `systemctl --restart sxhkd` skxhd does not inherit the environment variables from the script where the command is run. sxhkd will only have the environment variables that are specified in the unit files and some that come from systemd directly. This is just how systemd works.

I'm not sure how to fix this issue. Hard coding the values in the unit file might be an option (I'm not sure what the value of XDG_SEAT_PATH is or if it is always the same).

**Comment by Arteneko** [comment]
Makes sense, indeed.

Instead of hardcoding them, I'm thinking about just creating a `.cache/sxhkd.env` EnvironmentFile that will be defined in the `bspwmrc` file just before it starts the systemd unit file.

But that goes out of scope for this issue.

Thanks
