### ISSUE TITLE
Unable to set rules for desktops > 10

### ISSUE THREAD

**Issue by cubetastic33** [baskerville/bspwm#1238]
If I have a rule like `bspc rule -a discord desktop=3`, for example, it works fine. However, if I change it to `bspc rule -a discord desktop=11`, it stops working, even though I do have 11 desktops. Discord simply opens in the focused desktop instead of desktop 11.

**Comment by emanuele6** [comment]
> I do have 11 desktops
> instead of desktop 11

`desktop=11` will send the window to the first desktop named "11" that is found.

If you want to send the window to the 11th desktop, you should use `desktop=^11`

**Comment by cubetastic33** [comment]
Wow, that fixed it. Thanks so much!
