### ISSUE TITLE
WM_NAME rule matching doesn't work.

### ISSUE THREAD

**Issue by PoSayDone** [baskerville/bspwm#1240]
Trying it with bum, which is sets custom name to mpv.
```
_NET_WM_ICON_NAME(UTF8_STRING) = "bum"
_NET_WM_NAME(UTF8_STRING) = "bum"
WM_ICON_NAME(STRING) = "bum"
WM_NAME(STRING) = "bum"
WM_CLASS(STRING) = "gl", "mpv"
```
`bspc rule -a mpv:gl:bum desktop='^6' state=pseudo_tiled`
also tried 
`bspc rule -a *:*:bum desktop='^6' state=pseudo_tiled`

**Comment by ortango** [comment]
this doesn't seem to be a bspwm issue, or a mpv issue. mpv can set the title on time for the rule to catch it. either with `--title=` or lua. bspwm rules work fine with there is a title to match

maybe it is a bum issue or a python-mpv issue. regardless wm_name doesn't seem to be set at mapping when using bum.

**Comment by PoSayDone** [comment]
> this doesn't seem to be a bspwm issue, or a mpv issue. mpv can set the title on time for the rule to catch it. either with `--title=` or lua. bspwm rules work fine with there is a title to match
> 
> maybe it is a bum issue or a python-mpv issue. regardless wm_name doesn't seem to be set at mapping when using bum.
Ok, thanks.
