### ISSUE TITLE
Make window stay focused while it's open

### ISSUE THREAD

**Issue by O1100001** [baskerville/bspwm#1242]
Is there a way to make a rule that makes a window unable to be unfocused?

The only solution I can think of is using wmutils to watch for focus changes and re-focus it, but needless to say that is extremely hacky and a very ugly solution.

I've tried searching but it was as (if not less) helpful than asking my cat, which can't even speak.

**Comment by SeerLite** [comment]
You could add a rule to set `focus=off` on everything else, and set the config option `ignore_ewmh_focus` to true. Also subscribe/monitor for the node to be closed, at which point the rule and config could be reset (everything goes back to normal).

**Comment by O1100001** [comment]
Hi, thanks for the reply.  
I'm not so sure that `focus=off` would completely stop focusing that window. In case I was unclear I wanted it to keep the focus even if I were to try focus another window with my mouse or keybind/command.  
I already have `ignore_ewmh_focus` enabled in my bspwmrc.

If it helps, the window in question is just `st` with a special class, and I am able to modify the script.

**Comment by SeerLite** [comment]
I meant `focus=off` just for new windows taking focus. You'd still be able to focus the other windows by yourself. I thought you only wanted windows to not get focused automatically, not in general.

I have to ask, is there any reason you need to disable the ability to manually focus these other windows? Can't you just like, decide not to focus them?

There is no builtin way to disable manual focusing (AFAIK), but you could probably get it working with some changes.
As a start you'd have to edit your sxhkd bindings (in case you're using sxhkd) and have everything that might focus a different node first check if the node you're not currently focusing this central node (sorry if I'm not explaining myself well haha). Alternatively, you could kill sxhkd and start a new sxhkd instance with all focusing keybindings removed.
After that, you'd want to disable mouse-click focusing by setting `bspc config click_to_focus none` (and then back to `button1` once done).
I'm pretty sure that covers all possible ways you could manually focus in bspwm.

**Comment by O1100001** [comment]
I realized shortly after my reply that I should probably just put `pgrep || exit` in the keybind script and disable/enable hover-to-focus, but forgot to say and close this issue.

> After that, you'd want to disable mouse-click focusing by setting bspc config click_to_focus none (and then back to button1 once done).

This is a good idea.

Thanks for the help!
