### ISSUE TITLE
Skip scratchpad in task switcher

### ISSUE THREAD

**Issue by sagb** [baskerville/bspwm#1256]
My `alttab` window switcher has an issue about scratchpad in bspwm: https://github.com/sagb/alttab/issues/111

I could be wrong, but seems like bspwm scratchpad isn't a distinct feature (like EWMH desktop number -1) but a set of instructions for user to "emulate" it using sticky/floating/hidden EWMH hints?

If so, could I kindly ask you to also include setting for `_NET_WM_STATE_SKIP_TASKBAR` atom in `_NET_WM_STATE` property, so that task switchers would ignore that improvised scratchpad windows, for more consistent user experience?

**Comment by ortango** [comment]
it doesn't seem to me that desktop "-1" is described by ewmh - i don't think that the idea of a scratchpad is either.

should bspwm be the one to handle this attribute? _NET_WM_STATE_SKIP_TASKBAR *should* be set by the program. and unlike other state properties that bspwm does handle already (sticky, layer), this property wouldn't actually have internal bspwm usage.

for a workaround you could use `wmctrl` (xprop can't set that property correctly).

**Comment by sagb** [comment]
Does bspwm have such a feature - "scratchpad"?
For example, i3 _has_ a scratchpad, it has a specific meaning and documented interface/api: https://i3wm.org/docs/userguide.html#_scratchpad

**Comment by sagb** [comment]
Ratpoison, on the contrary, has _no_ scratchpad. Of course, user can "arrange" some setup that may be called "scratchpad" in ratpoisoin, but ratpoison itself has _no_ such a feature.
What about bspwm?

I believe the answer should show who the author of scratchpad, i.e. who has to bother about windows' properties.

**Comment by ortango** [comment]
>Does bspwm have such a feature - "scratchpad"?

no, not specifically.

>user can "arrange" some setup that may be called "scratchpad"

yes, same with bspwm.
