### ISSUE TITLE
Wildcard/regex rule matching

### ISSUE THREAD

**Issue by robinp7720** [baskerville/bspwm#1258]
It would be very convenient to allow rule matching based on wild cards for windows/applications which have a dynamic VM_NAME.

For example, the participants window in zoom is called "Participants (1)". As far I can tell, there's no way to currently create a rule which only targets this Participants window.  Eg: I'd expect "*:*:Participants (*)" to match a zoom window with the name "Participants (1)".

**Comment by dieggsy** [comment]
@robinp7720 sure you can! you can use an external rules script, see: https://github.com/baskerville/bspwm/tree/master/examples/external_rules The rules script can even be in your favorite language (shell, python, chicken scheme, you name it), so you can use whatever wildcard/regex/shell command, etc. features you want.

**Comment by robinp7720** [comment]
> @robinp7720 sure you can! you can use an external rules script, see: https://github.com/baskerville/bspwm/tree/master/examples/external_rules The rules script can even be in your favorite language (shell, python, chicken scheme, you name it), so you can use whatever wildcard/regex/shell command, etc. features you want.

Thanks! I tried that before posting the issue and I made a very trivial mistake. I thought it might make the configuration simpler if you could define regexes directly within the ```bspc rule -a``` command, but after using the externel_rules, I don't see that solution as being very useful.
