### ISSUE TITLE
Rearrange layout

### ISSUE THREAD

**Issue by fxdave** [baskerville/bspwm#1259]
Is there a method to rearrange the layout?
For e.g. rebuild the current workspace layout based on the split ratio.

**Comment by ortango** [comment]
for that specific example i think you can do:

    bspc config split_ratio 0.33
    bspc node @/ -E

that will not move nodes, but it will resize them based on the new split ratio.

**Comment by rauldipeas** [comment]
I'm using `bspc node -f @parent` to select all windows on one side of screen and `sh -c "bspc node -d prev && bspc desktop -f prev && bspc node -f next.local.!hidden.window"` or `sh -c "bspc node -d next && bspc desktop -f next && bspc node -f next.local.!hidden.window"` to move windows do another side of the screen, next I can switch any window with the same commands from position to rearrange it.
