### ISSUE TITLE
Resizing windows with nvidia drivers are incredibly laggy

### ISSUE THREAD

**Issue by zeuph** [baskerville/bspwm#1261]
Hello, after installing my nvidia drivers yesterday bspwm are lagging behind, stuttering and sometimes freezing when resizing windows. Moving windows and moving floating windows is not an issue, it's super smooth. Resizing a floating or tiling window causes lag.

I come from this thread [here](https://bbs.archlinux.org/viewtopic.php?pid=1954960) and thought to see if this will be fixed or if the problem lies elsewhere. A user in that thread posted a video and it looks identical to me. Much like the other users experienced, it's mainly with OpenGL applications. Alacritty, for example, will completely freeze all windows for a few seconds if I have more than 2 alacritty windows are open and resized. 

My apologies if this has been noted before. I did a few searches and couldn't find specifically this so since other people find similar issues I thought to link to that thread. 

I noticed almost all of the lag gone after loads of tinkering. In case someone else has a similar problem:
I moved some of my config from bspwm to .xinitrc which I probably shouldn't have had there to begin with like monitor configuration with xrand, background with feh and so on. I now start most of them from .xinitrc.
I also changed around pointer_motion_interval in bspwmrc to different values ranging from 7 all the way tp 50ms.

Hopefully that'll help someone in the future.

**Comment by hariseldon78** [comment]
I can confirm that raising pointer_motion_interval greatly alleviate the issue.
