### ISSUE TITLE
set float "Android Emulator -*"

### ISSUE THREAD

**Issue by spavlovich001** [baskerville/bspwm#1262]
I run:
$emulator -avd Pixel_2_API_R -netdelay none -netspeed full

$xprop.sh
title: "Android Emulator - Pixel_2_API_R:5554"

I need set "Android Emulator -*" float. How to do this?

**Comment by emanuele6** [comment]
I am not sure I understand, but if you want to make any window that has a title that starts with `Android Emulator - ` floating, you can do that by using a simple external rule:

1. Create a file with this content:
```bash
#!/bin/bash

wid=$1
title=$(xtitle "$wid")

[[ "$title" == 'Android Emulator -'* ]] \
    && echo state=floating
```
2. Make it executable (e.g. with `chmod +x name_of_the_file`)
3. run this command to set that script as the `external_rules_command` (you will probably also want to add this to your `bspwmrc`):
```bash
bspc config external_rules_command /full/path/to/the/script
```

-----
* [`xtitle`](https://github.com/baskerville/xtitle)

**Comment by spavlovich001** [comment]
10x

**Comment by jallbrit** [comment]
@spavlovich001 if your issue is solved then please close the issue.
