### ISSUE TITLE
A way to keep floating window on top across workspaces?

### ISSUE THREAD

**Issue by Arteneko** [baskerville/bspwm#1272]
Hello, I was wondering if there was a way to keep a floating window across workspaces ("pinning" it on top ?) ?

**Comment by SolitudeSF** [comment]
`bspc node -g sticky`, `super + ctrl + y` in default sxhkd config.

**Comment by Arteneko** [comment]
Thanks, I misunderstood the "sticky" mode so I didn't get it was what I was looking for.
