### ISSUE TITLE
Mouse doesn't respond before/until launching a terminal

### ISSUE THREAD

**Issue by aruizdlt** [baskerville/bspwm#1277]
Hello everyone!
I have an issue with my mouse on bspwm v0.9.9 on Ubuntu 20.04.2 LTS. It doesn't respond before/until pressing super + Return and launching my terminal. 

This is my bspwrc configuration:
``` 
#! /bin/sh

bspc monitor DisplayPort-3 -d I
bspc monitor HDMI-A-1 -d II III IV V VI

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/shades/launch.sh &
pgrep -x compton > /dev/null || compton &
pgrep -x dunst > /dev/null || dunst &
feh --bg-fill /home/user/Images/photo.jpg

bspc config border_width         2
bspc config focused_border_color "#ffffff"
bspc config window_gap           7
bspc config -m HDMI-A-1 top_padding     27
bspc config -m HDMI-A-1 bottom_padding   2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^3' follow=on
```

I had this problem before adding compton and dunst so I don't know what to do to fix it.
Any ideas?
Thanks you!

**Comment by angrypanda1** [comment]
yup same lol but i just never thought anything of it

**Comment by jallbrit** [comment]
> It doesn't respond before/until pressing super + Return and launching my terminal.

Can you explain what you mean by "doesn't respond"? You launch `bspwm`, and then what do you do to see this behavior? Do you open a window and your mouse won't click on it or something? Or is your cursor just not appearing on your screen until you launch an application (e.g. terminal)? Or something else?

**Comment by angrypanda1** [comment]
exactly what you said. When i open an application, for example arandr, i can't see or move the cursor around. However, when i launch the terminal, the cursor appears, and everything works perfectly as expected. it's not really a big deal of a bug, but it is a bit annoying. feel free to put this at low priority lol

**Comment by aruizdlt** [comment]
In my case @jallbrit when I login into `bspwm` the cursor appears always in the same place (near to bottom right corner of my left screen) but I've noticed that It's probably only a render issue because if I move my mouse to the right screen, even if I don't see that transition, and then launch a terminal, the terminal and the cursor appears in the right screen. When I said cursor It's not the X cursor.

**Comment by dimitris-triantafyllidis** [comment]
What about `xsetroot -cursor_name left_ptr &` in `bspwmrc`?

In my case the cursor was invisible before launching apps, but the mouse seemed to otherwise work. I used the above command to have a consistent cursor shape and it also fixed this issue.
