### ISSUE TITLE
Can't cycle desktops

### ISSUE THREAD

**Issue by sambazley** [baskerville/bspwm#1278]
`bspc desktop -f DisplayPort-1:focused#next.local` with fb35765 returns `desktop -f: Invalid modifier found in 'DisplayPort-1:focused#next.local'.`

**Comment by ortango** [comment]
this is my fault for not testing more. i thought this was a simple problem to solve.

colon != null and `next.local` ends up getting passed to `monitor_from_desc` and failing.

i wonder if the fix for this is simple though?

``` diff
diff -ruN a/query.c b/query.c
--- a/query.c	2021-03-24 18:29:24.427620712 -0400
+++ b/query.c	2021-03-24 18:30:45.373307036 -0400
@@ -711,6 +711,7 @@
 		coordinates_t tmp = {mon, mon->desk, NULL};
 		if ((ret = desktop_from_desc(desc, &tmp, ref)) == SELECTOR_OK) {
 			desc = hash + 1;
+			colon = strrchr(desc, ':');
 		} else {
 			free(desc_copy);
 			return ret;
```

**Comment by sambazley** [comment]
Whoops, accidentally clicked the close button.

Just checked out the code and reached the same conclusion. Submitted pull request #1282.
