### ISSUE TITLE
borderless_singleton not working

### ISSUE THREAD

**Issue by CoinBR** [baskerville/bspwm#1280]
![2021-04-08_09-55](https://user-images.githubusercontent.com/7809913/114030153-a0f2bb80-9850-11eb-8369-a1d81f0f6c77.png)

Hello there, I'm new to bspwm.

This is a 3 screens setup, and I got borders even if I have only window open (for instance, the terminal on the screenshot)

By the way, is something like **gapless_singleton** planned? It would me amazing!

**Comment by ortango** [comment]
>This is a 3 screens setup

that's the issue.

config description:

>Remove borders of the only window on the __only monitor__
>`bool the_only_window = !m->prev && !m->next && d->root->client;`

**Comment by CoinBR** [comment]
Oh, I see...

I just set the border very thin, and stop caring about it.

The gaps still a problem tough. Will try to make a workaround to that

Thanks for the reply!
