### ISSUE TITLE
Frozen windows on intel integrated GPU (Arch)

### ISSUE THREAD

**Issue by chris-aeviator** [baskerville/bspwm#1285]
I realized that since a year or so BSPWM seems to have issues on intel integrated graphics (X1 Carbon 6thG) on arch. Electron based apps as well as GPU enhanced tools like Alacritty do not play well with BSPWM.  After a while I will get the described applications to "tear" when swichting e.g. from Firefox to an Electron app. The image of the firefox window is kind of frozen onto the electron window, and only killing the electron window will release the space again. What's the smartest way of debugging this?

I can confirm not having these issues at all on Gnome, also the issue only started appearing somewhere within the last 12-24 Months (after an update). This turns bspwm completely unusable, since the issue pops up every some minutes and I constantly have to restart applications.

```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 225c
	Flags: bus master, fast devsel, latency 0, IRQ 138
	Memory at 2ffa000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 2fa0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at e000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by SeerLite** [comment]
Are you running a compositor along with bspwm?

**Comment by chris-aeviator** [comment]
@SeerLite I have found `compton` in my autorun.sh file, but can confirm it's not running. If I start it manually it fails to start anyways.

**Comment by emanuele6** [comment]
You probably have archlinux's `extra/xf86-video-intel` package installed.

 That driver is always the cause of many problems.
 
If you have it unistall it, reboot and see if that fixes your problems:
 ```bash
 # pacman -Rs xf86-video-intel
 ```

**Comment by chris-aeviator** [comment]
Thanks for the hint - I uninstalled it and rebooted. Will close the issue if it runs stable for tomorrow.

**Comment by emanuele6** [comment]
You have not followed up yet. Was the problem fixed or were you still experiencing?

**Comment by munnik** [comment]
I _think_ I have the same problem on Debian Bullseye. I run https://vscodium.com/ on one desktop and Firefox on another desktop. Whenever I switch back to the desktop running codium the application window is not drawn and it appears that the previous desktop is still focused. Only polybar indicates that the desktop with codium is currently focused. If I press F11 switch to fullscreen and back or super + m to alternate between monocle and tiled layout the application is drawn again and I can use it. I have the same issue with the https://signal.org/ desktop app but the https://slack.com/ desktop app is working without these issues.

**Comment by chris-aeviator** [comment]
@munnik that's exactly what I would describe my issue like. I can only see in polybar that I've switched to the "frozen" application. However it seems that uninstalling `xf86-video-intel` has worked so far. I will have a full working day today on this machine to re-evaluate.

**Comment by chris-aeviator** [comment]
I can confirm removing the intel driver seems to have solved my issue. Anyhow since @munnik has a similar issue I'd like to keep it open to check if there is a software side/ different issue to this. @munnik can you check if you have the driver installed also?

**Comment by munnik** [comment]
After some struggles getting X running without the `xserver-xorg-video-intel` package I can also confirm that it is working fine now. Thanks for the help!
