### ISSUE TITLE
Class/Instance names truncated to 32 characters.

### ISSUE THREAD

**Issue by pnelson** [baskerville/bspwm#129]
Chromium extensions have a longer identifier. I can workaround by truncating my rules but I feel that extending it a bit may be the better option long term.

Example for GMail extension:

crx_pjkljhegncpnkpknbcohdijeoej
crx_pjkljhegncpnkpknbcohdijeoejaedia

**Comment by senft** [comment]
This is still happening to me in `0.9-138-g4b538bc`

xprop:

    _MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x3d, 0x0, 0x20, 0x3, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
    XdndAware(ATOM) = BITMAP
    _NET_WM_DESKTOP(CARDINAL) = 2
    _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
    _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x1, 0x0, 0x0
    _NET_WM_STATE(ATOM) = 
    WM_HINTS(WM_HINTS):
    		Client accepts input or input focus: False
    		Initial state is Normal State.
    
    _NET_WM_PID(CARDINAL) = 9323
    WM_CLIENT_MACHINE(STRING) = "das-eck"
    WM_PROTOCOLS(ATOM): protocols  WM_TAKE_FOCUS, WM_DELETE_WINDOW
    WM_CLASS(STRING) = "sun-awt-X11-XFramePeer", "jetbrains-idea-ce"
    WM_CLIENT_LEADER(WINDOW): window id # 0x3200008
    _NET_WM_ICON_NAME(UTF8_STRING) = "simonstrator-pubsub - [~/Code/Java/Uni/simonstrator-pubsub/simonstrator-pubsub] - MonitoringSource.java - IntelliJ IDEA 15.0.3"
    WM_ICON_NAME(STRING) = "simonstrator-pubsub - [~/Code/Java/Uni/simonstrator-pubsub/simonstrator-pubsub] - MonitoringSource.java - IntelliJ IDEA 15.0.3"
    _NET_WM_NAME(UTF8_STRING) = "simonstrator-pubsub - [~/Code/Java/Uni/simonstrator-pubsub/simonstrator-pubsub] - MonitoringSource.java - IntelliJ IDEA 15.0.3"
    WM_NAME(STRING) = "simonstrator-pubsub - [~/Code/Java/Uni/simonstrator-pubsub/simonstrator-pubsub] - MonitoringSource.java - IntelliJ IDEA 15.0.3"
    WM_NORMAL_HINTS(WM_SIZE_HINTS):
	    	user specified location: 965, 24
    		program specified location: 965, 24
	    	program specified size: 943 by 515
    		window gravity: NorthWest

bspc query -T -d focused:

    {"id":52428861,
    ...
    "client":{"className":"jetbrains-idea-c",
    "instanceName":"sun-awt-X11-XFramePeer",
    ...
    }}}

**Comment by baskerville** [comment]
No, it isn't.

This is more likely related to #372 (but the NULL byte is missing at the end this time).

You can check that by running [xlsw](https://github.com/baskerville/xlsw) while the program is running.

**Comment by senft** [comment]
Alright thanks. Sorry for posting in the wrong issue.
