### ISSUE TITLE
[Feature request] Window Decorations.

### ISSUE THREAD

**Issue by AadityaThapaAce** [baskerville/bspwm#1293]
It would be nice to add a window decorations like on i3 or awesome with the ability to turn it off and on since some people would not like it.

**Comment by beyond9thousand** [comment]
@zjeffer 
![image](https://user-images.githubusercontent.com/77363063/179100518-68081b17-0c90-454f-9b76-8ce84cf617bb.png)

**Comment by beyond9thousand** [comment]
> Looks like OP deleted his GitHub account. 
> 
> @beyond9thousand I think you should open a new issue if you want this feature.

Fair enough, I think i will!
