### ISSUE TITLE
Error opening 'box'

### ISSUE THREAD

**Issue by GiancarloAparicio** [baskerville/bspwm#1294]
When I try to open a file manager (any) in bspwm it takes about a minute and the whole desktop changes.
That is, it goes from image 1 to image 2.

## Image 1
![image](https://user-images.githubusercontent.com/61440825/118820601-09837e00-b87c-11eb-9c6d-0e8a58006728.png)

## Image2
![image](https://user-images.githubusercontent.com/61440825/118820464-e658ce80-b87b-11eb-88c9-01528d6e7e39.png)

Also, once this happens, the file manager opens normally, the system features are:
![image](https://user-images.githubusercontent.com/61440825/118821140-92021e80-b87c-11eb-8308-de445038e736.png)

bspwm: 0.9.10-17-g7012d99

**Comment by zjeffer** [comment]
Judging by the fact that you have desktop shortcuts, the cause seems to be that you're mixing MATE's desktop environment with bspwm. Does the problem perist if you only run bspwm, without the MATE desktop?

**Comment by GiancarloAparicio** [comment]
@zjeffer If that is in my xinitrc

```
sxhkd &
exec bspwm
```
What seems strange to me, is that it only happens when I use a 'box' file manager, I have tried with all the gnome apps and they work without this error

**Comment by GiancarloAparicio** [comment]
@zjeffer Uhmm apparently it is an error with linux mint, it seems that the error does not have a specific origin, because when closing session with 'kill -9 -1' the error sometimes appears and other times it works normal (although it still takes 1min in open the box for the first time)

![image](https://user-images.githubusercontent.com/61440825/119077874-bebc5000-b9ba-11eb-931b-8255c1a95578.png)
