### ISSUE TITLE
Adopt and manage windows/applications that were started before BSPWM

### ISSUE THREAD

**Issue by Alexander-Shukaev** [baskerville/bspwm#1301]
I've noticed that when some applications (their windows) are started before BSPWM, they are not being adopted/managed by BSPWM.  Is there any special option or command to achieve this?

**Comment by zjeffer** [comment]
How and when are you starting those applications? I always start my applications after `exec bspwm` in `~/.xinitrc`

**Comment by maetthew** [comment]
I start bspwm from `.xinitrc` and then I put whatever I need autostarted with bspwm in the `bspwmrc`. Like @zjeffer asks, how and where are you starting those applications?

**Comment by Alexander-Shukaev** [comment]
I am aware of this way of setting things up.  I personally dislike this, as applications (and their start) in general have nothing to do with BSPWM, it's just yet another window manager, which is by no means supposed to manage how my applications start and when.  Hence, I have a different setup, the details of which are irrelevant here.  I understand that starting GUI applications after BSPWM is already running will result in their windows being managed by BSPWM.  My question was, how to adopt/manage those, which were started before BSPWM is started.  I want to understand where there is any command and/or option to signal BSPWM to adopt/managed such windows/applications.

**Comment by emanuele6** [comment]
You can make `bspwm` manage unmanaged windows by unmapping and remapping them (`$wid` is the id of the unmanaged window).
using `xdo`:
```bash
xdo hide "$wid" ; xdo show "$wid"
```
using `xdotool`:
```bash
xdotool windowunmap "$wid" windowmap "$wid"
```

To do using the mouse, you can use:
```bash
xdotool selectwindow windowunmap windowmap
```

This can also be useful if you want to reload rules on an already-managed window.

**Comment by SeerLite** [comment]
Also try just adding
```
bspc wm --adopt-orphans
```
in your bspwmrc.

I'm not sure if it's only for windows that have been managed by a previous bspwm session or windows in general. If it doesn't work then just use the fix @emanuele6 gave above

**Comment by Alexander-Shukaev** [comment]
@emanuele6, you made my day, thanks!  This is exactly what I was looking for.  The next tricky part was to collect window IDs for all the windows/applications that can be meaningfully managed by BSPWM.  For instance, there are roughly 200 existing windows IDs right after the start of DE on my system already (i.e. lots of them are some sort of panel widgets or otherwise special applications that are not supposed to be displayed and/or managed by WM), though I need only a handful of true user applications to have their windows managed by BSPWM.  The following command pipeline did the trick in a generic way:

```shell
xdotool search --all --onlyvisible --maxdepth 1 '' | exclude $(xdotool search --all --onlyvisible --class Bspwm)
```
