### ISSUE TITLE
[Feature request] a node command to swap children

### ISSUE THREAD

**Issue by ortango** [baskerville/bspwm#1308]
this would be equivalent to `bspc node "${t}#@1" -s "${t}#@2"`, but it would be chain-able (on node $t).

the point would be to have a complimentary command to `--type` making (non-recursive) node rotation possible with one `bspc` command. like `bspc node @/1 -y vertical -I`

i've been using non recursive `flip_tree()` for this (without the ratio invert), and calling it `-I`, `--invert`.

but it's kind of a redundant feature. i'm not sure that anyone else would find it useful.

**Comment by emanuele6** [comment]
`node NODE -s @brother` does that, I guess

**Comment by emanuele6** [comment]
Oh, no, nevermind

**Comment by ortango** [comment]
yea, and useful purely for the chaining aspect.
100% superfluous and didn't seem like anyone else is interested. It's easy enough [to add](https://github.com/baskerville/bspwm/compare/master...ortango:bspwm:reverse_pol) in for anyone who comes across this issue.
