### ISSUE TITLE
How to disable picom's transparency when using monocle mode

### ISSUE THREAD

**Issue by salahmak** [baskerville/bspwm#1313]
HI, I've been using Bspwm for a long time, and when using monocle mode with terminals, it becomes hard to read bcs of the transparency effect, so I'm trying to find a way to disable the transparency effect when on monocle mode using picom.

example:
![image](https://user-images.githubusercontent.com/49586511/125638486-85d3487d-44bc-4397-91af-f47e859a53ad.png)

Thanks in advance

**Comment by 3nt3** [comment]
probably ask this in the [picom repo](https://github.com/yshui/picom)

**Comment by salahmak** [comment]
opened issue on picom's repo: https://github.com/yshui/picom/issues/675
