### ISSUE TITLE
bspwm becoming unresponsive to input

### ISSUE THREAD

**Issue by Alumniminium** [baskerville/bspwm#1318]
I'm having the same issue as in #683, #1146   multiple times a day... any leads? I don't notice any high CPU usage on X or my Terminal and I don't use lemonbar either. Polybar on the other hand keeps updating values

**Comment by Alumniminium** [comment]
the last two times I successfully restored bspwm to a working state by... killing Geary. Seems to be related to geary or something it does while its idle.

**Comment by zjeffer** [comment]
Nevermind, looks like our issue is different than #1146 and #683, because the bspwm process doesn't actually stop/crash, but freezes instead.

For reference, today I also managed to recover from the freeze after killing a [polybar script](https://github.com/polybar/polybar-scripts/blob/master/polybar-scripts/player-mpris-tail/player-mpris-tail.py) (which was still running, even after killing polybar)

**Comment by zjeffer** [comment]
Killing the same script fixed it again. I forgot to do a gdb backtrace and `lsof` on the process but I'll do that next time.

@Alumniminium Do you also use this script by any chance?

**Comment by zjeffer** [comment]
Yesterday it froze again. These were the contents of the /proc/<script-process-id>/fd/ folder:

```
total 0
dr-x------ 2 zjeffer zjeffer  0 Nov 15 22:29 .
dr-xr-xr-x 9 zjeffer zjeffer  0 Nov 15 22:24 ..
lr-x------ 1 zjeffer zjeffer 64 Nov 15 22:29 0 -> pipe:[29118]
l-wx------ 1 zjeffer zjeffer 64 Nov 15 22:29 1 -> pipe:[29119]
lrwx------ 1 zjeffer zjeffer 64 Nov 15 22:29 10 -> socket:[34356]
lr-x------ 1 zjeffer zjeffer 64 Nov 15 22:29 16 -> /proc/stat
l-wx------ 1 zjeffer zjeffer 64 Nov 15 22:29 2 -> pipe:[29119]
lrwx------ 1 zjeffer zjeffer 64 Nov 15 22:29 3 -> socket:[29122]
lrwx------ 1 zjeffer zjeffer 64 Nov 15 22:29 4 -> anon_inode:[eventfd]
lrwx------ 1 zjeffer zjeffer 64 Nov 15 22:29 5 -> socket:[29123]
lrwx------ 1 zjeffer zjeffer 64 Nov 15 22:29 6 -> socket:[29124]
```

`cat`-ting the first pipe (`0`) unfroze `bspwm`. How can I figure out why that happens? What does the number mean inside the square brackets: `pipe:[<number>]`?

**Comment by ortango** [comment]
>cat-ting the first pipe (0) unfroze bspwm. How can I figure out why that happens?

what process was this from?

>What does the number mean inside the square brackets: pipe:[<number>]?

it is the fifo's id. you can use it to match the other side of the pipe.

**Comment by zjeffer** [comment]
> what process was this from?

The polybar `player-mpris-tail` script mentioned above

**Comment by Alumniminium** [comment]
for me it was a script i wrote myself reading out the cpu usage.
