### ISSUE TITLE
"Warp" command?

### ISSUE THREAD

**Issue by 2ver** [baskerville/bspwm#1320]
Hi, is there any kind of "warping" command similar to yabai? I've used awesome, i3, herbstluftwm, dwm, spectrwm, leftwm, and bspwm but I haven't found something quite like that function. 

I thought that the reason it wasn't here in bspwm was because you could use the preselections to achieve something similar but that hasn't been my experience. Let's say I have a terminal window open with my editor inside it and another window with a man page or something on the left of that. I find myself doing something like this quite often and I usually want to spawn something like a file manager or another instance of the editor *from the editor*. If I do this, that new window will go underneath the terminal with the editor when I usually want it to go the left side and be split with the man page window. I can't simply preselect on the left side because I have to spawn the file manager or whatever from the editor window which doesn't respect the preselection on the other window. 

After ~9 months of using other window managers, I still find myself missing that warp functionality of yabai. Is there a recommended workflow for this kind of thing in bspwm?

Thanks.

**Comment by emanuele6** [comment]
I have no idea of what "warp" does in `yabai`, you should have explained it.

Anyhow, from what i read [here](https://github.com/koekeishiya/yabai/blob/8efc57cbd0f499b2498e4fe174984f00bcdef7df/doc/yabai.asciidoc):

```
--warp <WINDOW_SEL>
  Re-insert the selected window, splitting the given window.
```

It sounds like it does exactly what the "node -n" command does in `bspwm`:

```
 -n, --to-node NODE_SEL [--follow]
     Send the selected node on the given node. If --follow is
     passed, the focused node will stay focused.
```

Your example makes no sense to me.

**Comment by 2ver** [comment]
I figured it was a pretty terrible example as soon as I posted it and I thought I might make a screen recording if no could understand it. Fortunately, you have! Though the `--follow` option appears to change nothing, the base behaviour of `-n` is exactly what I was looking for. Thank you!
