### ISSUE TITLE
subscribe before event

### ISSUE THREAD

**Issue by addy419** [baskerville/bspwm#1324]
I want to run a script (or command) before node_add to preselect the position of the window to be spawned. Is it possible to do this?

**Comment by emanuele6** [comment]
> I want to run a script (or command) before node_add

`external_rules_command` will be run before `node_add`.

You can set `external_rules_command` with `bspc config`.

For some examples, see here: https://github.com/baskerville/bspwm/issues/1302#issuecomment-860170568

**Comment by addy419** [comment]
@emanuele6 Thank you, this works. One more question, how to balance windows before spawing them?
For ex, I have 3 windows on right side (like master stack) and I spawn a new window and then balance it but it creates glitches because the window spawns and then resizes. Can I spawn the window directly balanced (and not spawn it then rebalance)

**Comment by emanuele6** [comment]
if you want a master/stack-like layout just use `bspc automatic_scheme spiral`

**Comment by addy419** [comment]
I was actually trying to create a 2 column grid layout, something like:
|--------|--------|
|--------|--------|
|--------|--------|
