### ISSUE TITLE
Automatic layout: Grid

### ISSUE THREAD

**Issue by addy419** [baskerville/bspwm#1325]
I want to create a automatic layout, a two column grid. Since bspwm is a binary tree, This is what I have come with

                                                   a
                                              /         \
                                            1            2
                                             \             \
                                              4              3
                                                \              \
                                                  6               5

children of root (1 and 2) are vertically split with 50 split, whereas all the children are 100% width (either all left or all right). Subtree of 1 and 2 are equal sized. New nodes are added to the shortest subtree of either 1 or 2. So the result is something like (with initial_polarity second_child)

+----------+---------+
| ----1 ----|----2 ---|
+----------+---------+
|---- 4 ----| ----3----|
+----------+---------+
| ----6 ----|----5----|
+----------+---------+

How do I go about this in bspwm?

**Comment by emanuele6** [comment]
> Since bspwm is a binary tree

`bspwm` uses **FULL** binary trees. That is not a **FULL** binary tree.

You are misunderstanding how binaray space partitioning works if you think that is the tree you want to achieve for that layout.

**Comment by addy419** [comment]
@emanuele6 I'm sorry, I missed that bspwm uses full binary tree. Considering each node has 2 children, how do I go about doing this?

**Comment by emanuele6** [comment]
> I missed that bspwm uses full binary tree.

You need to understand that binary space partitioning only makes sense in full binary trees.
Only leaf nodes can be windows so, even if we ignore that the tree you have drawn is not a full tree, there would only be 2 windows: 5 and 6.

 Anyway, I think the automatic layout you have in mind is pretty easy to implement:

 ```bash
#!/bin/bash
# external rules script

wid=$1 class=$2 instance=$3
eval "$4"

find_actual_root_node ()
{
    (( $# <= 1 )) || return 2
    local nid root ret
    nid=$(bspc query -N -n "${1-@/}") || return
    if bspc query -N -n "$nid"'#@1#any.descendant_of.!fullscreen.!floating.window#'"$nid"'#@2#any.descendant_of.!fullscreen.!floating.window' > /dev/null
        then printf '%s\n' "$nid"
    elif root=$(find_actual_root_node "$nid#@1" || find_actual_root_node "$nid#@2")
        then printf '%s\n' "$root"
        else return 1
    fi
}

if [[ -z $node && -z $desktop && -z $monitor ]] && root=$(find_actual_root_node); then
    if
        bspc query -N -n "$root.vertical" > /dev/null && {
            mapfile -t first_child_wins  < <(bspc query -N "$root#@1" -n '.descendant_of.!fullscreen.!floating.window')
            mapfile -t second_child_wins < <(bspc query -N "$root#@2" -n '.descendant_of.!fullscreen.!floating.window')
            target=$(bspc query -N "$root" -n "@$(( ${#first_child_wins[@]} > ${#second_child_wins[@]} ? 2 : 1 ))")
        }
    then
        : "$target"
    else
        : "$root"
    fi
    printf 'node=%s\n' "$_"
fi
```

```bash
#!/bin/sh
# script to run in the background

find_actual_root_node ()
{
    [ "$#" -le 1 ] || return 2
    local nid root ret
    nid=$(bspc query -N -n "${1-@/}") || return
    if bspc query -N -n "$nid"'#@1#any.descendant_of.!fullscreen.!floating.window#'"$nid"'#@2#any.descendant_of.!fullscreen.!floating.window' > /dev/null
        then printf '%s\n' "$nid"
    elif root=$(find_actual_root_node "$nid#@1" || find_actual_root_node "$nid#@2")
        then printf '%s\n' "$root"
        else return 1
    fi
}

bspc subscribe node_add | while read -r _ _ did _ nid; do
    if root=$(find_actual_root_node "@$did:/") && first_child=$(bspc query -N "$root" -n '@1'); then
        bspc node "$nid#$first_child.ancestor_of" -B \
            || bspc node "$nid#$first_child.!ancestor_of#@brother" -B
    fi
done
```

You might want to consider converting `find_actual_root_node` into a separate program to avoid code duplication.

------------------------

If you have questions about these scripts, please prefer asking them on [IRC or matrix](https://github.com/baskerville/bspwm#community).

**Comment by addy419** [comment]
I still have a few questions but I understand this is not the right place. I'll close this and continue it on IRC or matrix. Thank you for the tremendous help :)

**Comment by emanuele6** [comment]
@addy419 if you have problems connecting to `#bspwm`, you can ask here...
