### ISSUE TITLE
Urgent window notification

### ISSUE THREAD

**Issue by SamyadeepSaha** [baskerville/bspwm#1329]
I do not use any status bar. Is there any way I can pop up notification for urgent window? Example notify-send you have a urgent window on desktop number something.

**Comment by ortango** [comment]
read the manual. you can subscribe to events. eg:

    #!/bin/sh
    bspc subscribe node_flag | while read _ _ d n f s; do
        [ "$f" = urgent ] && [ "$s" = on ] &&
            notify-send "Urgent window on $(bspc query -D -d $d --names)" "$(xtitle $n)"
    done

also, this is not much of an issue; it seems like you just don't want to read the docs. i think you should ask questions like this in a more appropriate place, not on an issue tracker.

**Comment by SamyadeepSaha** [comment]
I am sorry to bother you. But there is not enough documentation for subscribe and node_flag argument of bspc. Can you tell the output format of "bspc subscribe node_flag". It prints nothing on my terminal. Thank you for your time.

**Comment by emanuele6** [comment]
I am quoting the manual page:
> ```
> node_flag <monitor_id> <desktop_id> <node_id> hidden|sticky|private|locked|marked|urgent on|of
>     One of the flags of a node changed.
> ```

> It prints nothing on my terminal. 

It will print something every time *one of the flag of a node changes*.
