### ISSUE TITLE
bspc actions to desktops and windows return 'Failed to connect to the socket.'

### ISSUE THREAD

**Issue by sirakai-pc** [baskerville/bspwm#1339]
I don't understand what caused this, I really tried everything, from reinstalling your last bspwm version, I tried also compiling and running it from the github repo, I tried changing execution order of sxhkd-bspc-polybar in the config.
Firstly it didn't work with sddm, then I tried replacing it with lxde, now it runs but any bspc related command to move windows etc. doesn't work.
```
$ bspc desktop --focus 'III'
Failed to connect to the socket.
```
Here's my bspwmrc file:
```
#!/bin/sh

export VIRSH_DEFAULT_CONNECT_URI=qemu:///system 
setxkbmap it &
picom &
# feh --bg-fill --randomize $HOME/Pictures/wallpapers/* &
feh --bg-scale $HOME/Pictures/wallpapers/photo_2021-10-19_11-45-45.jpg &
# /etc/runit/sv/macchanger/run &
$HOME/.bin/rfkill-block-bluetooth &

# FIRST keybinding server (simple x hotkeys daemon I guess)
pgrep -x sxhkd > /dev/null || sxhkd &

# THEN the bspwm monitor
bspc monitor eDP1 -d I II III IV V VI VII VIII IX X & 

# FINALLY polybar
$HOME/.config/polybar/launch.sh &

#connman-gtk &
cmst &
xfce4-clipman &
# nordvpn connect $COUNTRY 

bspc config border_width        1
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mpv vlc state=floating
#bspc rule -a Screenkey manage=off

```
### **bspwm version:**
0.9.10

**Comment by zjeffer** [comment]
* How are you launching bspwm? 
* Do you have a socket called `bspwm_0_0-socket` in `/tmp`?
* Can you try again with a very minimal `bspwmrc`?

**Comment by sirakai-pc** [comment]
The problem isn't from bspwm itself. It seems that most of the files in /tmp directory cannot be created, even mkinitpcio ones...
It's not a permission problem. It's something bigger..
Closing this as it's not bspwm related.

**Comment by zjeffer** [comment]
Is your /tmp directory full, maybe?

**Comment by sirakai-pc** [comment]
No, unfortunately not, my drive is empty, how could it be full?Now the system is unbootable, already tried to chroot and mkinitpcio+grub-mkconfig but nothing has changed.After choosing the entry in grub, it hangs infinitely.The only way to "boot" the system is via chroot...Guess I'll have to backup everything and reinstall the os.20:55, 7 December 2021, zjeffer ***@***.***>:
Is your /tmp directory full, maybe?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile
