### ISSUE TITLE
bspc rule: How to add rule with window name

### ISSUE THREAD

**Issue by Achileas** [baskerville/bspwm#1356]
How do I add rule base on WM_NAME (window name), not WM_CLASS which looks like this below:

`bspc rule -a jetbrains-idea-ce:jetbrains-idea-ce state=floating` or
`bspc rule -a jetbrains-idea-ce state=floating`

JetBrains IDE's have a window name "win0" on the splash screen. but the splash screen takes the whole screen and focus from other windows example terminal or browser

Thanks in advance

**Comment by Randoragon** [comment]
This can be accomplished quite easily, see `external_rules_command` in bspwm(1).
A simple example is included in [bspwm/examples/external_rules](https://github.com/baskerville/bspwm/tree/master/examples/external_rules)
Here's my external rules script which floats xev windows based on the window name:
```sh
#!/bin/sh

wid="$1"
class="$2"
instance="$3"
consequences="$4"
title="$(xdotool getwindowname "$wid")"

# Float xev window
[ "$title" = "Event Tester" ] && echo 'state=floating'
```

**Comment by Achileas** [comment]
Thank you!
