### ISSUE TITLE
New terminal window is opening as float after a ruled tdrop window interaction

### ISSUE THREAD

**Issue by dbvasconcelos** [baskerville/bspwm#1360]
This behavior is annoying me and i cant figure how to solve it:

I have a tdrop mapping on shhkd (im using kitty as $TERMINAL):

```
super + Return
	$TERMINAL

super + shift + Return
	tdrop -ma -w "50%" -h "50%" -x "25%" -y "25%" -n scratchpad $TERMINAL --class scratchpad
```

I made a bspwm rule so it appears floating and sticky:

```
bspc rule -a scratchpad state=floating sticky=true
```

It works and the window behaves as expected, the issue is that after interacting with the scratchpad, the first normal terminal (and only the first)  window i spawn appears as floating, and i expect it to appear as tiled.

I gave the scratchpad example but its the same thing for any tdrop mapping i have.

**Comment by Darukutsu** [comment]
I have similar problem. Opening tdrop will ignore all rules but other terminals (non tdrop class, still kitty) open with rule in consideration (floating and centered.

sxhkdrc:
```
# terminal emulator
super + Return
kitty

# tdrop (square mid)
F12
tdrop -ma kitty --class tdrop
```
bspwmrc:
```bspc rule -a tdrop state=floating center=on```

When I do something like this:
```	tdrop --class tdrop -ma -h 50% -w 45% kitty --class tdrop
```
other terminals will open in tiling, tdrop in floating but still ignores `center=on` and instead it appears in top left corner

**Comment by ortango** [comment]
i'd suggest consulting tdrop's source.

it already will make a rule for use with the options you are running. plus, unless you specify `-x '' -y ''` xoff & yoff will be set and the window will always be moved by tdrop - but only if `-m` is not set.

if you remove the `-m` option and override the tdrop rule creation by setting `-l ''` tdrop will still break centering because of the resize - unless you unset w and h too.

**Comment by Darukutsu** [comment]
> i'd suggest consulting tdrop's source.

Thanks for help now everything works perfectly.
in bspwmrc:
```
bspc rule -a "*" rectangle=900x550+0+0 center=on follow=on
```

in sxhkdrc:
```
# tdrop (square mid)
F12
	tdrop -P 'bspc node -t floating -l above' kitty
```
Since all new windows open in tiling mode by default they, preserve setting set by rule in floating state. There is small visual clutter but it doesn't matter anyway.

**Comment by dbvasconcelos** [comment]
Since a workaround was provided i will close the issue. Thanks!
