### ISSUE TITLE
Strange behaviour on different external monitor swap

### ISSUE THREAD

**Issue by ghost** [baskerville/bspwm#137]
I am not sure if this is problem with bspwm or fbpanel, but I decided to submit it here for now.

My bspwm monitor/desktop configuration is as following:

```
bspc desktop ^1 -n 1
bspc monitor LVDS1 -d 1 2 3 4
bspc monitor VGA1 -d 5 6 7 8
bspc config top_padding 14
```

I am on a laptop and I have 2 different display monitors which I plugin in and out on same port. When I start with monitor A plugged in, my configuration is fine. Now I unplug Monitor A and plug in Monitor B. Bspwm creates desktop 9 (named `Desktop4` for Monitor B). Now if I unplug Monitor B and plug in Monitor A back, it creates another new desktop for Monitor A while moving all the previously created desktops to LVDS1 monitor.

Is there any way to avoid this? I would like to achieve one of the two possible behavious:
1. Attach desktops to Port, so no matter what monitor I plugin to VGA1 port, the desktops will belong to that monitor.
2. If desktops belong to a specific monitor so if a monitor is replugged in, it will switch desktops to that monitor.

Is there any possible workaround for this?

**Comment by alecive** [comment]
Hey @baskerville , I don't know if you changed something in between that I was not aware of, but as of now the command you suggested seems not to be working. I have updated and compiled `bspwm` to the latest commit, as you can see here:

```
(~/code/bspwm/bspwm) (master) 
[alecive@malakim]$ git log -1
commit ccddf1231d5a63e59e99b143aeedd20ba364090c
Author: Bastien Dejean <nihilhill@gmail.com>
Date:   Thu Sep 22 22:30:38 2016 +0200

    Add node modifier: active
```
But the command is not recognized: 
```
(~/code/bspwm/bspwm) (master) 
[alecive@malakim]$ bspc config persistent_monitors true
config: Unknown setting: 'persistent_monitors'.
```

**Comment by baskerville** [comment]
It was removed in aca232b23ca181caf992b1da144cfd187ef72535 and is now the default behavior.

**Comment by alecive** [comment]
Ok thank you as usual @baskerville . So maybe this is not what I was looking for. My problem is that I have this configuration:
```
bspc monitor eDP1 -d 1 2 3
bspc monitor HDMI1 -d 4 5 6
```

when I disconnect the `HDMI1` monitor, all the workspaces are pushed to the only monitor left, that is `eDP1` (which is perfectly fine). Now, if I reconnect `HDMI1` back, `eDP1` still has the same 6 desktops as before while for `HDMI1` a 7th is created anew. I would like the previous configuration to come back automatically. Isn't it the same issue that @ghost had?
