### ISSUE TITLE
Feature: hiding borders

### ISSUE THREAD

**Issue by Ploppz** [baskerville/bspwm#138]
I would like to only display borders for the selected window - thus hiding other borders, for example by setting an alpha channel: bspc config normal_border_color '#00rrggbb'. (substitute rrggbb with an actual hex colour of course)
Instead of transparency, maybe just a setting to disable the border (substitute the colour by some "off" switch).

**Comment by rainerborene** [comment]
I can confirm this bug. `border=off` have no effect.

**Comment by rainerborene** [comment]
@baskerville off topic question. is it possible to match `WM_CLASS` and `WM_NAME` on the same rule? I want Steam Friends window to be floating not all steam windows.

**Comment by baskerville** [comment]
@rainerborene You need to create a separate issue.

**Comment by half-cambodian-hacker-man** [comment]
`border=off` still has no effect.

**Comment by neeasade** [comment]
You can set arbitrary wid widths with: `bspc config -n <wid> border_width <wid>`, so you can eg `bspc config -n $(bspc query -N -n) border_width 0`. I will sometimes use this to have differing widths on focused vs unfocused windows: https://0x0.st/zr_j.png
