### ISSUE TITLE
initial_polarity doesn't respect monitor selector

### ISSUE THREAD

**Issue by BrotifyPacha** [baskerville/bspwm#1383]
Steps to repoduce:

- `bspc config -m next initial_polarity second_child`
- `bspc config -m focused initial_polarity first_child`
- `bspc config -m next initial_polarity` - echoes `first_child`, as i didn't change `next` monitor's `initial_polarity`, i expected that it would echo `second_child`

Thanks in advance

**Comment by emanuele6** [comment]
It's not a bug. `intial_polarity` is a "Global Setting", it can only be set globally.

You can't just set any setting per-monitor, per-desktop, and/or per-node.

You can read the manual page to read the list of all the settings and you will see the are divided in four categories: "Global Settings", "Monitor and Desktop Settings", "Desktop Settings", "Node Settings".

There actually very few setting that are not global-only; only 6:

>        Monitor and Desktop Settings
>            top_padding, right_padding, bottom_padding, left_padding
>                Padding space added at the sides of the monitor or desktop.
>     
>        Desktop Settings
>            window_gap
>                Size of the gap that separates windows.
>     
>        Node Settings
>            border_width
>                Window border width.

You can use `-[ndm] SELECTOR` only with these six settings. If you specify a selector for a global setting, that is just ignored.

Setting `initial_polarity` per-monitor is not supported.

**Comment by BrotifyPacha** [comment]
Oh, okay, thanks for clarification.
