### ISSUE TITLE
Using plank (dock app) properly with bspwm

### ISSUE THREAD

**Issue by beyond9thousand** [baskerville/bspwm#1391]
# The Problem
After installing it for the first time and adding it to my bsp rc, I noticed that plank would actually go behind all windows. This only fixes itself if I restart the wm in that session. Meaning on every new login, I would have to restart the wm in order for plank to start working correctly once again.

# Expected behavior
Plank spawns above all other windows when the mouse is lowered to the bottom edge of the screen, and disappears when it is taken away. Plank is also not under focus at all times / when switching to a different workspace.

# Tested workaround
Adding the bspc rule 
`bspc rule -a Plank manage=on border=off locked=on focus=off follow=off`
This solves the issue of plank not staying on top after the first login. But simultaneously it also adds a different problem. Plank is now on focus whenever I am on an 'empty' desktop. This branches off into a tertiary problem where I can no longer use jgmenu since plank is always on focus. I have demonstrated my problem below

https://user-images.githubusercontent.com/77363063/170856932-d0259194-b6c4-4862-a15f-4bb8b4302ea0.mp4

# End Goal
To be able to use plank and jgmenu in the same setup without either of them interfering with each other or bspwm prohibiting their functionality in any way. This only works without the bspc rule and **only after restarting the wm in that session.** Demonstrated below

https://user-images.githubusercontent.com/77363063/170857607-e58c0d19-77cb-4d71-83fa-98bc05bb18f1.mp4

**Comment by beyond9thousand** [comment]
#390

**Comment by beyond9thousand** [comment]
https://github.com/baskerville/bspwm/issues/390

**Comment by JFOZ1010** [comment]
@beyond9thousand Exactly bro, me pasa eso tal cual, the docks get stuck behind tiled windows and i dont know what i have to do.

**Comment by beyond9thousand** [comment]
Fixed it by running this script in the background

https://github.com/beyond9thousand/dotfiles/blob/master/.config/bspwm/hooks/b9k-stacking.sh
