### ISSUE TITLE
[Feature Request] Any chance to have different single monocle configs for different monitors?

### ISSUE THREAD

**Issue by DavidHeiss** [baskerville/bspwm#1409]
Hey, I am trying to have different “single_monocle” settings per monitor. I know that it's possible with for example window gap.
Is the problem that it is a global setting?

```bash
bspc config -m HDMI-0 single_monocle true
bspc config -m DP-0 single_monocle true
bspc config -m DP-2 single_monocle false
```
![image](https://user-images.githubusercontent.com/43972734/184213808-a6f92792-a5b8-4434-8a45-f92645383fba.png)

**Comment by opalmay** [comment]
Hi see my pull request
