### ISSUE TITLE
cant compile bspwm on fedora xcb_event.h no such file or directory

### ISSUE THREAD

**Issue by fislysandi** [baskerville/bspwm#1419]
so i cant compile bspwm on fedora,

doesnt taht mean it this wm doesnt support fedora?

**Comment by fislysandi** [comment]
ok i progressed a little and installed the package now this is the issue

xinerama.h no such file or directory.

if somebody responds please include dependencies in the wiki tab.

**Comment by zjeffer** [comment]
You need to supply more information. What is the full error message? 

It sounds like you haven't installed the necessary dependencies (https://github.com/baskerville/bspwm/wiki#from-source). Have you installed `xcb-util`?

**Comment by zjeffer** [comment]
> ok i progressed a little and installed the package now this is the issue 

which package did you install?

**Comment by fislysandi** [comment]
im just missing dependecies and need to install them rn im stuck at xcb_iccm

**Comment by fislysandi** [comment]
i just dont know the equvivelent packages that are for fedora bspwm exists in fedora repos

but compiling it yourself i think is a better solution.

**Comment by fislysandi** [comment]
@zjeffer i installed rust-xcb+xinerammadevel and xcb-util, now im digging what is iccm .

**Comment by zjeffer** [comment]
Looks like the fedora package is quite old, so it is indeed better to compile from source.

**Comment by zjeffer** [comment]
> @zjeffer i installed rust-xcb+xinerammadevel and xcb-util, now im digging what is iccm .

Try `libxcb` and `libxcb-devel`

**Comment by fislysandi** [comment]
well it says its complete
![vmware_VK58unPYRn](https://user-images.githubusercontent.com/45166203/192166414-b6d69d77-865c-4f61-a7b5-8ec6f575759c.png)

**Comment by fislysandi** [comment]
i already firgered out myself how to put bspwm in sddm options so i just need to find these damn packages.

**Comment by zjeffer** [comment]
Try `xcb-util-wm-devel`.

**Comment by fislysandi** [comment]
well thats weird i look packages from this site pkgs.com

**Comment by fislysandi** [comment]
ok now the issue is that xcb_keysyms

**Comment by fislysandi** [comment]
we are making progress.

**Comment by zjeffer** [comment]
xcb-util-keysyms

**Comment by fislysandi** [comment]
well installed it but it still complains if doesnt exist
![vmware_VP8svwg0Wj](https://user-images.githubusercontent.com/45166203/192166575-e3c0c91b-fff9-474b-a4f0-9259aaa1f518.png)

**Comment by zjeffer** [comment]
What about xcb-util-keysyms-devel?

**Comment by fislysandi** [comment]
hey that was not installed

**Comment by fislysandi** [comment]
now it compiled successfully lets try sxhkd
![vmware_d0DDwl2cou](https://user-images.githubusercontent.com/45166203/192166618-181d4222-3ae6-4a8b-a361-0dfe23f9d08c.png)

**Comment by fislysandi** [comment]
shxkd compled

**Comment by fislysandi** [comment]
ok after this issue can you add the deps to the wiki of bspwm?

**Comment by zjeffer** [comment]
I'm not a maintainer but I think I can add them. Can you list the exact packages you had to install?

**Comment by fislysandi** [comment]
ok second..

**Comment by fislysandi** [comment]
https://fedora.pkgs.org/36/fedora-aarch64/rust-xcb+xinerama-devel-0.10.1-3.fc36.noarch.rpm.html
https://packages.fedoraproject.org/pkgs/xcb-util/xcb-util/
xcb-util-keysyms-devel,xcb-util-wm-devel,xcb-util

these.

**Comment by fislysandi** [comment]
man this feels like for the first im participating in FOSS project.

**Comment by zjeffer** [comment]
I don't think you need `rust-xcb+xinerama-devel`, as this project doesn't use rust as far as I know. You probably also don't need the devel versions.

I believe the packages are the exact same as the Arch Linux dependencies: `libxcb xcb-util xcb-util-wm xcb-util-keysyms`. Would you agree?

**Comment by fislysandi** [comment]
yea? sure.

**Comment by zjeffer** [comment]
Updated the wiki: https://github.com/baskerville/bspwm/wiki

You can close the issue now.

**Comment by fislysandi** [comment]
ok issue closed!
