### ISSUE TITLE
`bspc subscribe report` doesn't work properly

### ISSUE THREAD

**Issue by andreykaere** [baskerville/bspwm#1437]
Command `bspc subscribe report` doesn't print anything when command `bspc node <node> -d <desktop>` is run for `<node>`, that is hidden. However it works perfectly fine for visible nodes, as expected.

**Comment by emanuele6** [comment]
Oh, yeah. And that matters, because the desktop in which the node is located could become free, and the target desktop could become occupied.

**Comment by andreykaere** [comment]
Yes, exactly my point here! :)
