### ISSUE TITLE
Launch google-chrome

### ISSUE THREAD

**Issue by Breizil29** [baskerville/bspwm#1449]
Hi,
I can't launch "google-chrome" with a command, it follows the rules of "bspwmrc" but "sxhkdrc" won't launch it.
I know "xprop". Here's my order :
[gui apps]
alt+g; {e,f,w,g}
     {\
     $EDITOR, \
     $FILEMNGR, \
     google-chrome-stable, \
     geany\
    
     }
I've found "google-chrome-stable"

**Comment by emanuele6** [comment]
I don't know if what i am seeing is your actual config since you have not formatted it correctly, but you need a space or tab at the start, and `\` at the end of every like on your hotkey excluding the `alt + g ; {e,f,w,g}` line.

for example:
```bash
alt + g ; {e,f,w,g}
 {$EDITOR,\
  $FILEMNGR,\
  google-chrome-stable,\
  geany\
 }
```
 
> it follows the rules of "bspwmrc" but "sxhkdrc" won't launch it.

I don't understand what this means.

**Comment by Breizil29** [comment]
It's solved, I wrote it in the first message:
I found "google-chrome-stable"

**Comment by emanuele6** [comment]
If it's "solved" why don't you close it?

**Comment by Breizil29** [comment]
because I had not seen that we could do it
