### ISSUE TITLE
empty split 

### ISSUE THREAD

**Issue by icf20** [baskerville/bspwm#1470]
i have no idea how i get this empty split

![imagen](https://github.com/baskerville/bspwm/assets/17784575/5201f91c-7082-4f75-a435-ffd6a612c52f)

![imagen](https://github.com/baskerville/bspwm/assets/17784575/a03619f5-5d3e-4997-88de-d5c6480b696b)

`xwininfo: Window id: 0x400005`  any ideas?

**Comment by Neurognostic** [comment]
Looks like a [receptacle](https://github.com/baskerville/bspwm/blob/master/doc/bspwm.1.asciidoc#receptacles).

**Comment by icf20** [comment]
note that this did not happen to me again so far i have zero idea what caused this
