### ISSUE TITLE
Single window have border

### ISSUE THREAD

**Issue by og900aero** [baskerville/bspwm#1473]
In the case of Bspwm, I see that it is possible to specify how thick the border should be and what color it should be:

bspc config border_width 4
bspc config focused_border_color '#c93648'

But can it be set that if only 1 window is open, the size of the border and the color can be set separately? Or it's best if I can set no border have when only one window opened in workspace.

**Comment by Neurognostic** [comment]
You could do that with a `bspc subscribe node_add` event loop that checks how many windows on the focused workspace there are and sets the `bspc config` options based on these conditions. Then also `bspc subscribe desktop_focus` to check how many windows are open on the desktop you switched to and set `bspc config` options accordingly. 

Alternatively, you could do something similar with the `external_rules` script.

**Comment by og900aero** [comment]
> If you only want to configure that windows have no border when there is only one visible tiled window, you can set:
> 
> ```
> bspc config borderless_singleton true
> ```
> 
> If you are using bspwm `0.9.10` instead of compiling `bspwm` from the `master` branch of this repository, you cannot use `borderless_singleton`, but you can use:
> 
> ```
> bspc config borderless_monocle true
> bspc config single_monocle true
> ```
> 
> This will also make tiled nodes not have a border in desktops that are using the `monocle` layout, but maybe you don't care about that.

bspc config borderless_monocle true
bspc config single_monocle true

Working fine, thx!
