### ISSUE TITLE
inconsistent focus when opening with qutebrowser

### ISSUE THREAD

**Issue by Combowombo** [baskerville/bspwm#1477]
I don't know if this is an issue with bspwm or with qtwebengine. Usually, when I open something in the terminal, say with mpv or zathura, the focus does not automatically switch to those windows, which is what i'm used to. However, when I open a file or a link in the terminal with qutebrowser, the focus switches to the qutebrowser window. This inconsistency is throwing off my keyboard driven muscle memory. Any ideas on how to fix this?

**Comment by ortango** [comment]
>Usually, when I open something in the terminal, say with mpv or zathura, the focus does not automatically switch to those windows

bspwm should be focusing new (local) windows by default, unless zathura or mpv is opening the file in an existing instance.

If qutebrowser is focusing an existing window when a url is opened it would be because qutebrowser is requesting focus.

For details you can check the bspwm docs for `ignore_ewmh_focus` and qutebrowser's docs for `--target`.

**Comment by Combowombo** [comment]
here are my results:

I tried:
bspc config ignore_ewmh_focus	true

This did not work

adding the following setting in qutebrowser achieved the non-focus behavior i was looking for exept it only did it if there was already an instance of qutebrowser running:
c.new_instance_open_target = 'tab-silent'

finally, setting rule for qutebrowser to not focus did the trick:
bspc rule -a qutebrowser focus=off follow=off

Thanks for your suggestions!

**Comment by ortango** [comment]
Cool.

It may be worth mentioning that the `follow`ing part of this is not inconsistent with other windows. All local windows are followed when created.

And the ignore_ewmh config would work. Not sure why it would not. It will not allow bspwm to focus any window that requests focus on it's own.

**Comment by Combowombo** [comment]
Gotcha. I haven't really used other windows except pqiv or zathura launched from the terminal. But glad I was able to make the adjustment. Thanks for your input!
