### ISSUE TITLE
Document split_dir

### ISSUE THREAD

**Issue by milkmiruku** [baskerville/bspwm#169]
It would be handy (especially on non-widescreen monitors) if one could alter the default automatic split direction.

**Comment by mxmilkb** [comment]
N.b. because I've just re-set this up, an `external_rules` with this works;
```
if [ $(bspc query -N -d|wc -l) == "1" ]; then echo "split_dir=south"; fi
```

**Comment by mxmilkiib** [comment]
The above only works for new nodes on a one node desktop, so doesn't apply when a node is moved onto a desktop.

I'm moving to a wm with an automatic layout  for now, but if anyone has a script to achieve this in bspwm, please post or link it below.
