### ISSUE TITLE
Reorganize the tree

### ISSUE THREAD

**Issue by wernight** [baskerville/bspwm#171]
I found myself often with a tree that doesn't look like what I want (for example two large horizontal wide windows on an already wide screen instead of two vertical ones).

However to change the tree structure I found it really difficult:
 1. Mod + Ctrl + h/j/k/l - Set where you want the child
 2. Mod + Enter - Create a new window there
 3. Drag & drop to that new terminal
 4. Close the terminal opened at step 2

Is there a simpler way? Something along like drag & drop on edges?

**Comment by sac2171** [comment]
Is this something still being planned?

**Comment by baskerville** [comment]
It is, but I don't have too much time to work on *bspwm* right now.

**Comment by baskerville** [comment]
It is now possible (as of eb07d2f) to preselect internal nodes.

**Comment by Alkeryn** [comment]
sory for unburying but with good use of the node roatate fonction anko problem is solved in 3 step

What you can't solve with rotate however is whe you have 4 nodes on default shape and you want them to take a grid layout
