### ISSUE TITLE
Add scratchpad functionality

### ISSUE THREAD

**Issue by mrabault** [baskerville/bspwm#179]
Would you consider adding a scratchpad (like i3's) to bspwm ? Currently, you have to use [this kind of hack](https://wiki.archlinux.org/index.php/Bspwm#Scratchpad), and I think it would be a great addition to bspwm. I do realize that you perhaps think that it's not necessary for bspwm to provide this functionality, though.

Thanks in advance for your attention

**Comment by Swoorup** [comment]
+1 for this

**Comment by roosemberth** [comment]
+1

**Comment by roosemberth** [comment]
Any news on this? :+1:

**Comment by neeasade** [comment]
people interested in this may want to take a look to [tdrop](https://github.com/noctuid/tdrop)

**Comment by baskerville** [comment]
Fixed by 331cc9e.
