### ISSUE TITLE
Enable/Disable monitors

### ISSUE THREAD

**Issue by Lindenk** [baskerville/bspwm#182]
Hello,

So I have an HDMI splitter hooked to a TV and my computer and am using xrandr to turn it on/off when needed. Of course, when it's off, xrandr still treats the monitor as connected, just not being used. Bspwm though forces me to give it a desktop and acts like a monitor when moving desktops/windows between monitors. Because I usually have the TV off, this is a bit annoying.

I would like to request a command to add and remove connected monitors from bspwm. The desktops on the monitor could either be moved to the next monitor or destroyed (both options would be nice if possible).

**Comment by nikolaishields** [comment]
This was super helpful to find!
Thanks @baskerville
