### ISSUE TITLE
Subscribe to different events

### ISSUE THREAD

**Issue by nfnty** [baskerville/bspwm#188]
Would love to have the possibility to subscribe to different events such as new window, close window, change window, change desktop, change monitor, window modification(tiled, floating, resize) etc. If this could be bound to different domains, such as a specific monitor or desktop that would be awesome.

I'm currently writing a python script to modify windows on the fly whenever they change having to do quite a bit of ugly hacking involving calling `bspc query --tree --desktop focused` every 0.1 seconds in order to update the window layout (consumes about 1M cycles each call) and then regexing it to find if the windows are tiled or not and what class and name they have. Luckily I can at least lazily use `bspc control --subscribe` so that the desktops don't reset every time I change, but that is also far from perfect.

E.g.
`bspc control --subscribe --close` # outputs a line with wid every time a window closes
`bspc control --subscribe --floating` # outputs a line with wid every time a window changes to floating
`bspc control --subscribe --floating --desktop 1` # outputs a line with wid every time a window changes to floating on desktop 1

**Comment by baskerville** [comment]
I could add a bit mask for subscribers that tells what type of events there're interested in.

Maybe the following hierarchy would be suitable:
```
          all
         /    \
        /      \
   report    event
            /  |  \
           /   |   \
          /    |    \
    monitor desktop window
           /   |       |  \
          /    |       |   \
         /     |       |    \
       add   rename  close   fullscreen

```
*report* being the default.

*fullscreen* events, for example, would be sent to subscribers as:
```
fullscreen on|off WINDOW_ID DESKTOP_NAME MONITOR_NAME
```

**Comment by jvvv** [comment]
+1 for the bit mask concept. I think this would be easy to work with.

**Comment by baskerville** [comment]
My initial implementation for this is 9dd581f.

Example: `bspc control --subscribe desktop window_fullscreen` will listen to all the desktop events and to the *fullscreen* window event.

To those who requested the feature: what events do you need?

**Comment by Lindenk** [comment]
The events that I would most likely use:

Add/Remove window/desktop/(monitor would be nice too if possible)  
Desktop move  
Window/Desktop/Monitor focused  
Window/Desktop removed

**Comment by nfnty** [comment]
Basically all possible events; resize, pseudo_tile, floating, sticky etc.  Would be great to have something like `bspc control --subscribe window all` which subscribes to all window events.

JSON output would be much easier and efficient to work with. Example:

Monitor: HDMI1
Desktop: 1
Window ID: 0x1000009
pseudo_tile: off
```
{
    "HDMI1": {
        "1": {
            "0x1000009": {
                "pseudo_tile": false
            }
        }
    }
}
```

**Comment by baskerville** [comment]
There's already an event name (*window*) that encapsulates all the window events.

I guess I could provide a *resize* events that only fires at the end of a resize transaction (that is, not after every `pointer -t X Y` messages).

Please note that there can't be more than 32 events.

Regarding JSON: I'm not against the idea but I need some evidences to support those claims.

**Comment by nfnty** [comment]
That would be perfect.

Evidence for what claims? Serializing JSON is very cheap with Jansson. Deserializing JSON is less error prone and much higher performance than regexp.

**Comment by Chrysostomus** [comment]
This is probably partially of topic, but with the current implementation, what events I need to subscribe to in order to get notification when window moves to another workspace? Or when number of windows in workspace changes? I use subscribtion to automatically switch between monocle and tiled mode depending on the number of windows on workspace. If I subscribe to all events, the script interferes with with manually choosing between modes. If I use bspc control --subscribe window instead, the script won't react to windows being moved to different workspaces.

**Comment by baskerville** [comment]
@Chrysostomus see the *EVENTS* section of the manual and the *leaf_monocle* setting.

**Comment by Chrysostomus** [comment]
Thanks

**Comment by baskerville** [comment]
Done.
