### ISSUE TITLE
Emacs locking up.

### ISSUE THREAD

**Issue by blitzaxt** [baskerville/bspwm#189]
When using bspwm Emacs locks up when launched as the graphical version.  Launching Emacs in xfce4 does not cause any issues.  I cannot reproduce it on a separate install of bspwm on a different computer.

Both computer run arch linux fully up to date.
I am suspecting I have messed a config line up somewhere or I am missing something.
Graphics card does not seem to be the issue I tried both an AMD and NVIDIA card and it did not change anything.

Please let me know if more information or logs are needed I just don't know where to go from here.

Thanks, Jon

**Comment by jjzmajic** [comment]
@blitzaxt ok, I'm encountering the exact same issue, and can't find any mention of the solution online. I can't seem to find any Arch IRC logs either.

Any help?

**Comment by jjzmajic** [comment]
`(setq frame-resize-pixelwise t)`
