### ISSUE TITLE
Insert second window on right instead of left 

### ISSUE THREAD

**Issue by lyeoh** [baskerville/bspwm#193]
By default, opening a second window in automatic splitting mode gives
```
_________      _________
|a      |  ->  |b  |a  |
|   F   |      | F |   |
|_______|      |___|___|
```
where `a` and `b` label the windows and `F` labels the focused window.

I prefer
```
_________      _________
|a      |  ->  |a  |b  |
|   F   |      |   | F |
|_______|      |___|___|
```
since the original window `a` typically contains some left-aligned, unwrapped text. Then this behaviour leaves the text alone for easy reference.

This can definitely be implemented by some clever scripting of preselections or private windows, but I think it may be simplest at the source where we need only swap 2 characters in tree.c.

I personally found it annoying enough to sort through the source and recompile bspwm. If anyone else feels the same, it might be worth a config option for those only slightly annoyed.

**Comment by Lindenk** [comment]
I wouldn't mind a config option. If you've already fixed it, you could probably just submit a pull request.

**Comment by baskerville** [comment]
As of c13c678: `bspc config initial_polarity second_child`.

**Comment by lyeoh** [comment]
Cheers, baskerville. Works great.
