### ISSUE TITLE
Option to obey resize hints for tiled windows

### ISSUE THREAD

**Issue by flannelhead** [baskerville/bspwm#194]
It would be nice to have an option to have bspwm obey resize hints for tiled windows, too. There's a particular use case for it: for example, I'm using a transparent terminal, but Vim's background is not transparent. In the picture below you can see that there's an overlapping transparent slice in the bottom of the terminal window, because URxvt's grid doesn't fill the whole frame.

![2015-01-08-150627_1366x768_scrot](https://cloud.githubusercontent.com/assets/5001906/5662931/57c6936a-9748-11e4-9363-3e6dfe71f95e.png)
E: to clarify, I would only like bspwm to resize the window to get rid of that small transparent slice.

This option is clearly a very minor tweak, and it needn't be enabled by default. If you think this would be a good idea, I'm willing to look into the code myself and submit a PR (if I'm able to learn XCB well enough).

**Comment by rr-** [comment]
+1, I just stumbled into this when trying out `gvim`.

**Comment by neeasade** [comment]
Here's a possible alternate solution -https://www.reddit.com/r/vim/comments/4clr3d/bleeding_bottom_and_right_edges_of_vim_how_to_fix/d1jcfox

**Comment by baskerville** [comment]
`bspc config honor_size_hints true`.
