### ISSUE TITLE
Feature request: Option to disable centering of pseudo-tiled windows

### ISSUE THREAD

**Issue by cju** [baskerville/bspwm#196]
Hi,

is there a chance for an option that lets you choose if pseudo-tiled windows will be centered or not? Instead of centering, I'd like to have it sticked to the upper-left corner of its window space when sending it into the pseudo-tiled state.
All the other pseudo-tiled behaviour should stay the same, I'd just like to disable the centering.

Would that be possible?

**Comment by baskerville** [comment]
Why would you want that?

**Comment by cju** [comment]
Well, I'd simply find it much more intuitive/logical in terms of the frame-idea. I just can't get used to the fact that the pseudo-tiled windows are centered, though I use bspwm for over a year now.

For example, if you have to windows side-by-side and you'd like to send the right one into the pseudo-tiled state, it'd nicely keep fitting to the left one.
Then, one could create more flexible arrangements that way, because you could place for example floating windows into the frame of a pseudo-tiled window more easily if it isn't centered, but nested to a corner.
(I'm not sure if I'm expressing myself clearly enough, please ask if you don't get my point, it's likely to be my fault.)

If this doesn't cost way too much effort for you, I'd really appricieate such an option.

**Comment by baskerville** [comment]
As of 1167e06: `bspc config center_pseudo_tiled false`.

**Comment by cju** [comment]
Works like a charm, thank you very very much!
