### ISSUE TITLE
No rules are correctly working after migrating config files from one machine to another.

### ISSUE THREAD

**Issue by z1lt0id** [baskerville/bspwm#200]
So I migrated my bspwm files from my home machine to my work computer.  Installed all the appropriate packages and compiled all the latest git releases and I've noticed that my rules are no longer working.  

My bswmpc is at the following link
http://pastebin.com/5Nx0Yef9

**Comment by rychipman** [comment]
Are the rules the only things not working? Are your config settings working as expected?

**Comment by z1lt0id** [comment]
The configuration settings are working, just not the rules.  I suspect it
is something to do with this specific install.   As I've tried my config
files on other machines and it works fine.
