### ISSUE TITLE
resize_* incredibly slow when composition manager running

### ISSUE THREAD

**Issue by untitaker** [baskerville/bspwm#202]
I tried resizing either urxvt and Firefox, and the movement gets extremely jerky, with the "windows border trails" known from MS Windows.

All of those issues disappear when killing off compton.

**Comment by Stebalien** [comment]
Try messing with sxhkd's `-f` flag (it sets the motion event frequency). I use `100`.

**Comment by boreq** [comment]
Thank you for the question and the answer, I had exactly the same problem with the same programs for a very long time but I ignored it. Changing the `-f` flag indeed seems to improve things.

**Comment by neeasade** [comment]
I found that setting sxhkd's shell to something like dash helped the speed of this noticeably.

**Comment by baskerville** [comment]
The current version of *sxhkd* [just writes](https://github.com/baskerville/sxhkd/commit/07595089fee6aac5953af8acb2f2e98682fa03d5) the motion events as messages on *bspwm*'s socket, so there's no shell involved.

**Comment by neeasade** [comment]
Ah. I was referencing an old experience with sxhkd on a netbook thinking it would still be relevant.
