### ISSUE TITLE
Check for XCB_ICCCM_SIZE_HINT_P_ASPECT flag?

### ISSUE THREAD

**Issue by EvanPurkhiser** [baskerville/bspwm#206]
Would be nifty if when resizing a window the `XCB_ICCCM_SIZE_HINT_P_ASPECT` flag was taken into account so that windows are locked into an aspect ratio.

The linux version of [mpv](http://mpv.io/) adds this size hint flag.

For reference, AwesomeWM also appears to [implement this](https://github.com/awesomeWM/awesome/blob/dea5a23eac7e54c60df5771caa0ee28b3f1fc8e8/objects/client.c#L646-L680).

Would be great to see this on bspwm!

**Comment by EvanPurkhiser** [comment]
Any thoughts on this @baskerville? :-)

**Comment by baskerville** [comment]
I will get to it eventually.

**Comment by baskerville** [comment]
Size hints are supported as of 12edac8.
