### ISSUE TITLE
Bug with floating chromium

### ISSUE THREAD

**Issue by darkleo** [baskerville/bspwm#208]
It's a very strange issue but, at least on my machine, it's completely reproducible.

Steps, from an empty desktop:
- Open Chromium
- Open the Developer Tools (right click, inspect (any) element)
- Detach the Developer Tools (I send `bspc window -t floating` through shxkd)

Unexpected Behavior:
- bspwm terminates, X terminates.

Notes:
It only happens when there is only *one* chromium window and *one* Developer Tools open. If anything else (another chromium another DevTools, a terminal, ..) is on the screen, everything works as expected.

I really don't know what to say more. I tried to get a coredump backtrace but... bspwm just terminates, so gdb doesn't say anything more than "[Inferior 1 (process 5109) exited normally]". Likewise, there isn't anything in the X output, as is just see bspwm terminates "normally".

I'm running archlinux, using the bspwm-git package on the AUR (https://aur.archlinux.org/packages/bspwm-git/).
Sorry not to be able to show any other technical trace, if I can do or experiment anything useful please let me know.

**Comment by baskerville** [comment]
I'm unable to reproduce. But maybe I'm not performing the third step properly: I'm undocking the developer tools window and toggling its floating state.

**Comment by baskerville** [comment]
As of 5c1f76f, you should get a precise error message that starts with *The server closed the connection*.

**Comment by darkleo** [comment]
Here is the precise error message:
> The server closed the connection: socket, pipe or stream error.

And the complete debug output, if that can help to reproduce:
> update monitors
add monitor LVDS1 (0x42)
add desktop Desktop1
update motion recorder size: 1366x768
window show A00001
enable motion recorder
window show A00000
enter notify A00001 0 0
enable motion recorder
window show A00000
map request E00003
window show E00003
unmap notify 1000003
destroy notify 1000003
map request 1200001
manage 1200001
insert node 1200001
arrange LVDS1 new
stack 1200001
focus node 1200001
enable motion recorder
window show A00000
window show 1200001
enter notify A00001 0 3
enable motion recorder
window show A00000
configure request 1000022
configure request 1200001
client message 1200001 342
motion notify
motion notify
motion notify
motion notify
motion notify
motion notify
motion notify
motion notify
motion notify
motion notify
disable motion recorder
window hide A00000
enter notify 1200001 0 4
enter notify 1200001 1 2
configure request 1200001
client message 1200001 342
unmap notify 1200042
enter notify 1200001 0 4
unmap notify 1200042
destroy notify 1200042
configure request 1200043
map request 1200043
manage 1200043
insert node 1200043
arrange LVDS1 new
stack 1200043
focus node 1200043
enable motion recorder
window show A00000
window show 1200043
enter notify A00001 0 3
enable motion recorder
window show A00000
arrange LVDS1 new
floating 1200043: true
update vacant state
stack 1200043
arrange LVDS1 new
remove monitor LVDS1 (0x42)
remove desktop new

**Comment by baskerville** [comment]
Is this happening with an empty `bspwmrc`?

**Comment by darkleo** [comment]
Unfortunately, yes.

If I remove my bspwmrc, I get
> Couldn't execute the configuration file.
The server closed the connection: socket, pipe or stream error.

Obviously, it is also happening when the file is empty.

The output is also a bit cleaner
> update monitors
add monitor LVDS1 (0x42)
add desktop Desktop1
update motion recorder size: 1366x768
update monitors
add monitor LVDS1 (0x42)
add desktop Desktop1
update motion recorder size: 1366x768
unmap notify C00003
destroy notify C00003
map request E00001
manage E00001
insert node E00001
arrange LVDS1 Desktop1
stack E00001
focus node E00001
window show E00001
configure request C00022
arrange LVDS1 Desktop1
configure request E00001
client message E00001 317
grab pointer 1
configure request E00001
client message E00001 317
configure request E00001
client message E00001 317
unmap notify E0004A
unmap notify E0004A
destroy notify E0004A
configure request E0004B
map request E0004B
manage E0004B
insert node E0004B
arrange LVDS1 Desktop1
stack E0004B
focus node E0004B
window show E0004B
arrange LVDS1 Desktop1
floating E0004B: true
update vacant state
stack E0004B
arrange LVDS1 Desktop1
remove monitor LVDS1 (0x42)
remove desktop Desktop1

For what it can help, chromium is the current up to date stable version: 40.0.2216.111 (64-bit)

**Comment by MehLON** [comment]
This also happens with dwm, I suspect it's an issue with chromium
