### ISSUE TITLE
Wine Photoshop Bug

### ISSUE THREAD

**Issue by rainerborene** [baskerville/bspwm#209]
Photoshop on Wine runs smoothly on i3 but not on bspwm.
https://www.dropbox.com/s/4uqk164j0x42ee5/photoshop_bug-2015-02-10_20.17.05.mkv?dl=0

Download the video to your local machine because the preview quality is crap.

**Comment by rainerborene** [comment]
@baskerville I could send you a pull request but I have no clue where to start from.

**Comment by baskerville** [comment]
If you want to contribute, have a look at `doc/CONTRIBUTING.md`.

Are you running *compton*?

**Comment by rainerborene** [comment]
Not running compton.

**Comment by baskerville** [comment]
Could you try running *compton* to see if it makes a difference?

**Comment by rainerborene** [comment]
It doesn't make any difference. If I add the following rule some of the issues are gone but as you can see the window became unmanageable.

`bspc rule -a Wine manage=off`

Using `center=off` fixes the "context menu" centering issue.

**Comment by baskerville** [comment]
Is this still happening?

What's the output of `xev -root`?
