### ISSUE TITLE
bscp window next.local selected by default

### ISSUE THREAD

**Issue by Lindenk** [baskerville/bspwm#212]
The commands `bspc window next -f` and `bspc window prev -f` only select windows on the current desktop rather than all windows. They seem to act like `bspc window next.local -f` and `bspc window prev.local -f` should instead.

**Comment by neeasade** [comment]
@baskerville is this behavior intended as with the focus behavior on multihead commented on in https://github.com/baskerville/bspwm/issues/460 ?

@Lindenk you might try the following from the example bindings:
``` sh
# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on
```
