### ISSUE TITLE
Floating windows don't retain size and position when cycling between float and tile mode

### ISSUE THREAD

**Issue by eamrhein** [baskerville/bspwm#213]
I notice this often when i have multiple terminals open. When I cycle a terminal between float and tiling mode the window doesnt retain the size I set for it previously. I am not sure if there is some bspwmrc configuriation that can fix this, but I didnt see anything in the documentation. 

If this is not a feature, may I suggest adding it in future builds.

**Comment by baskerville** [comment]
I can't reproduce.

Could you provide more details?

**Comment by eamrhein** [comment]
I've isolated it to xfce4-terminal. it works correctly with urxvt.

**Comment by baskerville** [comment]
I can reproduce and I think the problem must come from the fact that I'm not taking into consideration the resize increments specified by the the size hints of the window.

**Comment by baskerville** [comment]
Is this still happening?

**Comment by neeasade** [comment]
Can't reproduce with xfce4-terminal 0.6.3 -- works with `honor_size_hints` set to either `true` or `false`, though.
