### ISSUE TITLE
Slow performance bspwm + termite combination

### ISSUE THREAD

**Issue by PaBLoX-CL** [baskerville/bspwm#216]
I have been using bspwm for a couple of days, and I started finding a weird issue with termite. When I resize the windows (regardless of the gap), the movement of the windows get choppy and the borders starts to tear a lot... I found that this doesn't happen with `st` for example (or it's too little, almost unnoticeable). Sometimes even I finish moving the windows, and the windows still move to "catch" the cursor.

I don't use any compositor, but I tried to see what happened with compton default backend, which is almost the same. Running with the opengl backend (`compton --backend glx`) seems to work better, but there are still noticeable artifacts, like the borders get wide while they catch with the cursor.

I have a fairly new laptop, i7-4770HQ CPU @ 2.20GHz quad core, and an Intel Iris Pro and 8gb ram, so I don't believe the problem is there :/

**Comment by ryneeverett** [comment]
I've been using bspwm + termite for a few weeks now and haven't had issue.

**Comment by ryneeverett** [comment]
Of course, the issue may have emerged in the past couple months as I've updated neither.

**Comment by angelic-sedition** [comment]
I haven't updated since termite broke ranger image preview compatibility, but even without a compositor, I have never had any problems. If it's a problem with termite, it would have to be in a fairly recent commit.

**Comment by PaBLoX-CL** [comment]
Okay... some updates. The problem happens with any terminal emulator, and any app actually. For some reason beyond my knowledge, with some applications is more noticeable. I read [this](https://bbs.archlinux.org/viewtopic.php?pid=1506012#p1506012) comment from the arch linux thread:

> … I believe it is because bspwm tries to resize (and therefore redraw) a window being rezised each time it receives an updated mouse position. Meaning if your mouse has a high refresh rate (many new mice have a refresh rate of 1000hz!) then as long as you are moving the mouse that is how many times it will attempt to redraw and resize the window each second. So I think the -f option limits how many times per second bspwm will resize and redraw the window regardless of how often your mouse updates.

In fact, after killing and running `sxhkd -f 35`, starts working fine (just starting `sxhkd` again, didn't solve the issue, and with `-f 50` it still looked choppy).

Well, the thing is that I'm finding this actually could be a bug on `bspwm/sxkhd` because for example yesterday suddenly after turning on the leaptop, it started to worked fine again (yes, I did try the windows ™ solution, I rebooted thrice yesterday when trying to troubleshoot the issue), it did actually worked flawlessly for the whole afternoon.

Now today, after using the laptop for a while it started to happen again, the only thing I did was suspend the laptop (closed the lid). Now after running `sxhkd -f 35`, suspending and waking the system didn't reproduce the strange behaviour.

Is there any way I can debug sxkhd/bspwm and see what is happening?

@ryneeverett I envy you :(, I just can't stop having problems with my workflow xD.

**Comment by ryneeverett** [comment]
If it helps I'm also on arch and my specific versions are `bspwm-git 967-1` and `sxhkd-git 130-1`, though I have no idea what the version numbers correspond to. Since we're both on arch though that probably eliminates any other dependencies as potential culprits.

**Comment by Alzarath** [comment]
Would it be possible to give the option for bspwm to only draw the outline as it's resized, then redraw the window when it's released?

**Comment by PaBLoX-CL** [comment]
Now it's working fine. I dunno what was happening, but I'll close since, it doesn't apply anymore. yay!
