### ISSUE TITLE
Can't focus windows by direction after reload

### ISSUE THREAD

**Issue by mbennehar** [baskerville/bspwm#217]
Hello there, I'm using bspwm with the loop example so what I've done is that I placed wm in a directory included in path, made the modifications to bspwmrc and sxhkdrc and .zprofile and everything is working as it should be. One issue though is when I use ctrl+super+escape command I can't focus windows by directions. pressing super + i,j,k,l doesn't seem to work.

**Comment by NicolasCARPi** [comment]
I can't reproduce this bug. Can you try with latest git version ?

**Comment by baskerville** [comment]
Fixed by 6fb0469.
