### ISSUE TITLE
Request: --subscribe: get desktop layout info per monitor

### ISSUE THREAD

**Issue by Ploppz** [baskerville/bspwm#218]
Hi. I'm interested in displaying the layout of the focused desktop per monitor; that is display the layout (tiled/monocle) in the bar/panel, individually for each monitor.
Right now, it gives a more global information:
```
WMHDMI-0:o17:O22:f23:f10:f7:mDVI-0:o2:F3:f15:f20:Ltiled
```
what I'd want is:
```
WMHDMI-0:o17:O22:f23:f10:f7:Lmonocle:mDVI-0:o2:F3:f15:f20:Ltiled
```

Thanks.

**Comment by baskerville** [comment]
It's already the case in the Git version.

I should probably make a release though.
