### ISSUE TITLE
bspwm ignores ' bspc rule -a "*" ' - rules

### ISSUE THREAD

**Issue by blendi-93** [baskerville/bspwm#219]
i type 

    bspc rule -a "*" -o split_dir=up
    bspc rule -l

lists
 
   * => split_dir=up

spawn a term (term spawns left has normal)

    bspc rule -l

dont display the rule anymore

using current git-verison

**Comment by baskerville** [comment]
If you specify `-o`, the rule will auto-destroy after being used once.

Furthermore, the rule works as expected here.

**Comment by blendi-93** [comment]
ok found the error.
dmenu_run triggers the rule... sry

**Comment by blendi-93** [comment]
adding -d ( Force docking without asking the window manager. This is needed if the window manager isn't EWMH compliant.) to bar, fixed it.
