### ISSUE TITLE
Documentation for bspc monitor after bspc config.

### ISSUE THREAD

**Issue by pnelson** [baskerville/bspwm#220]
I ran into this while upgrading and I see that `bspc monitor -d ...` must now be called after the last `bspc config` line in `bspwmrc`. As per your comment in the following thread, this is expected behavior. https://github.com/baskerville/bspwm/issues/186#issuecomment-65119960

I wasn't sure how you'd like to communicate that but I think it should be documented under `Commands > Monitor > -d, --reset-desktops`.

**Comment by baskerville** [comment]
Feel free to make a pull request.
