### ISSUE TITLE
[featurerequest] --balance for a range of windows

### ISSUE THREAD

**Issue by blendi-93** [baskerville/bspwm#227]
for example 4 windows open:
![showing 4 windows before and after ballance](http://i.imgur.com/Us4YCN4.png)

bspc window --balance 2 3 4 would balance them (1 2 3 4 ~ window id or selector)

**Comment by neeasade** [comment]
when you say balance, you mean align to your window split ratio?

**Comment by blendi-93** [comment]
i mean, all selectd windows (2 3 4) shuld have the same height/width desktop 900px height all selected windows = 300px heigh

finaly got my own script do this.

**Comment by Chrysostomus** [comment]
@blendi-93 I'm curious, how did you solve this issue? I'm having a similar puzzle to solve currently. My current best solution is to bspc node @brother -B when the biggest window is focused, but it is not entirely ideal.
