### ISSUE TITLE
cursor jumps to middle of window

### ISSUE THREAD

**Issue by agauniyal** [baskerville/bspwm#230]
Whenever I try to click some kind of native (gtk , not some inside-browser) button , my cursor jumps from its original position to middle of that window. I have no idea about what is causing this bug , but I guess it started since the last update of bspwm on arch.

I have tried switching off my touchpad , then using only touchpad -no mouse , but this problem persists and is very very annoying.

**Comment by baskerville** [comment]
I can't reproduce.

Have you tried with an empty *bspwmrc*?

**Comment by agauniyal** [comment]
@baskerville It was indeed something wrong with my bspwmrc , sorry for the trouble :smile:
