### ISSUE TITLE
High cpu usage after opening dialog window of Java programs.

### ISSUE THREAD

**Issue by thinusbaun** [baskerville/bspwm#231]
Hi.
I am using IntelliJ Idea and other Java programs and I have found something strange. When I open any dialog window of Java application and move my mouse(which changes focus from dialog window to other window) to this opened dialog window, cpu usage spikes for a few seconds and dialog is not responsible. After few seconds cpu usage is again low and i can use dialog window. I have tried git version with default config and my config. I also have tried Oracle Java 8 and OpenJDK8.

For reproducing you can download for example [Graph Searching JAR](http://www.aispace.org/downloads.shtml) and play with it a little.

**Comment by Stebalien** [comment]
I can reproduce this bug.

**Comment by NicolasCARPi** [comment]
I can reproduce it also with ImageJ software.

**Comment by Keats** [comment]
Happens to me on pycharm as well

**Comment by zeroDivisible** [comment]
This can be reproduced and as texegesis written [on reddit](https://www.reddit.com/r/bspwm/comments/267srd/problem_with_intellij_bspwm/cl6649w):

```
but there was one more issue with java apps, bspwm that I think setting the WM name to LG3D in the correct places was intended to fix, and what happens is bspwm tries to set focus to window, but the app tries to grab focus, and you can get into a neverending loop of 'give/grab' with focus that makes the java app suck 100% cpu; this happens in visualvm, jmeter, and intellij, basically any awt app you can type into.
```

**Comment by baskerville** [comment]
Thanks, I now have an idea on how to fix this.

**Comment by zeroDivisible** [comment]
No worries - happy if the above provides some more context.

**Comment by baskerville** [comment]
Should be fixed by 36f740f.

**Comment by zeroDivisible** [comment]
@baskerville It is - at least IntelliJ Idea works perfectly.

You're awesome :)

**Comment by zeroDivisible** [comment]
BTW, I think this issue can be closed.

**Comment by NicolasCARPi** [comment]
Hello, I can confirm that the bug was squashed, good job :)

**Comment by baskerville** [comment]
Could someone test the *icccm-input-focus* branch?

**Comment by baskerville** [comment]
@zeroDivisible Can you test the *icccm-input-focus* branch?

**Comment by zeroDivisible** [comment]
@baskerville will do, will try to do so today, in next 2-3h

**Comment by zeroDivisible** [comment]
@baskerville unless I made a mistake when testing, things are looking good on that branch. IntelliJ Idea is behaving as expected for me.

**Comment by baskerville** [comment]
Thanks.
