### ISSUE TITLE
Windowhints related to taskbar/pager as well as above/below are not implemented?

### ISSUE THREAD

**Issue by bklaase** [baskerville/bspwm#233]
When I manipulate windows to have window hints to:
- not list them in pagers/taskbars
- keep them above others (when they are all floating)
- keep them below others (when they are all floating)

these seem not to be implemented in bspwm. The same actions do trigger the desired effect in other tiling, or traditional WM's (tested in: awesome, openbox, pekwm). 

Am I missing a setting? If not, would it be difficult to implement?

**Comment by baskerville** [comment]
Just to clarify: you're requesting the implementation of `_NET_WM_STATE_{ABOVE,BELOW}`, is that right?

**Comment by bklaase** [comment]
Forgive my somewhat vague description and thank you for replying; yes, I was referring to those.
The bullet saying: "not list them in pagers/taskbars", refers to ```_NET_WM_STATE_SKIP_{TASKBAR,PAGER}```

Would these require a lot of effort?

**Comment by bklaase** [comment]
As an afterthought:
If ```_NET_WM_STATE_SKIP_TASKBAR``` is set, I think it would make sense to skip te window with:
```bspc window -f {next,prev}```

**Comment by baskerville** [comment]
`_NET_WM_STATE_{ABOVE,BELOW}` are now supported.
