### ISSUE TITLE
transparent borders

### ISSUE THREAD

**Issue by ScriptorNY** [baskerville/bspwm#236]
Hello,

I have been searching for quite a long time how to have transparent frames in my windows, unfortunately I didn't find anything.

So my question is, what have I missed ?

P.S: What do the monocle options mean ?

Thank you very much in advance :)

**Comment by ikn** [comment]
Why not set border width to 0 and add padding?  (Or did you mean translucent?)

**Comment by baskerville** [comment]
[*compton*](https://github.com/chjj/compton) has a `--frame-opacity` option.

**Comment by ScriptorNY** [comment]
Thank you very much :)

**Comment by mxmilkb** [comment]
`compton` doesn't have an separate options for active and inactive frame opacities. Could there be some way to script this for bspwm?
