### ISSUE TITLE
Segfault when laptop lid is closed

### ISSUE THREAD

**Issue by jhyeon** [baskerville/bspwm#237]
If I close the lid of my ThinkPad X220 when the following conditions are met, bspwm crashes:
- xfsettingsd from xfce4 is running
- bspc config remove_unplugged_monitors true
- bspc config remove_disabled_monitors true

Debugging info:

(gdb) r
Starting program: bspwm 
update monitors
add monitor LVDS1 (0x41)
add desktop Desktop1
update motion recorder size: 1366x768
update monitors
update monitor LVDS1 (0x41)
update motion recorder size: 1366x768
update monitors
update monitor LVDS1 (0x41)
update motion recorder size: 1366x768
update monitors
update monitor LVDS1 (0x41)
update motion recorder size: 1366x768
add desktop L2
add desktop L3
add desktop L4
add desktop L5
add desktop L6
update monitors
merge LVDS1 into (null)

Program received signal SIGSEGV, Segmentation fault.
0x0000000000406dd7 in insert_desktop (m=0x0, d=0x625cb0) at desktop.c:136
136		if (m->desk == NULL) {
(gdb) l
131		d->floating = false;
132	}
133	
134	void insert_desktop(monitor_t *m, desktop_t *d)
135	{
136		if (m->desk == NULL) {
137			m->desk = d;
138			m->desk_head = d;
139			m->desk_tail = d;
140		} else {
(gdb) where
#0  0x0000000000406dd7 in insert_desktop (m=0x0, d=0x625cb0) at desktop.c:136
#1  0x0000000000406ba0 in transfer_desktop (ms=0x625c30, md=0x0, d=0x625cb0) at desktop.c:87
#2  0x0000000000405b61 in merge_monitors (ms=0x625c30, md=0x0) at monitor.c:198
#3  0x000000000040689d in update_monitors () at monitor.c:422
#4  0x000000000040ba15 in handle_event (evt=0x625860) at events.c:71
#5  0x0000000000404252 in main (argc=1, argv=0x7fffffffda18) at bspwm.c:181
(gdb) q

**Comment by baskerville** [comment]
Should be fixed by f3ca2aa.

**Comment by jhyeon** [comment]
It works.  Thanks a lot!
