### ISSUE TITLE
[feature request] fullscreen window at back of desktop z-index?

### ISSUE THREAD

**Issue by aerobit** [baskerville/bspwm#240]
Could support for gluing a window to the desktop background be added? I find myself wanting a terminal rather than an image. Allowing fullscreen windows to go under floating windows ( or a new type?? ) would work too, though.

**Comment by EvanPurkhiser** [comment]
Maybe this could be done with `wmctrl` if bspwm can be told to orphan a window?

**Comment by baskerville** [comment]
@EvanPurkhiser windows can already be unmanaged with the `manage=off` rule consequence.

@aerobit do you want the window to be focusable?

**Comment by aerobit** [comment]
Yeah, I'm looking for focusability without bringing it to the front. I tried using `xdo lower` but it won't put it permanently at the bottom.

**Comment by aerobit** [comment]
After some thought, this could be solved by implementing `_NET_WM_STATE_{ABOVE,BELOW}`, as requested in https://github.com/baskerville/bspwm/issues/233

The implementation would have to let ABOVE and BELOW apply to fullscreen windows too.

**Comment by baskerville** [comment]
It is now possible: just send the window in the *above* layer.
