### ISSUE TITLE
How to set manual split as default

### ISSUE THREAD

**Issue by norwack** [baskerville/bspwm#241]
How would i set it to default so if i have 3 terminals open, and whatever i open (terminal, browser, etc) is opened so it has the same size as the other 3 windows?

For the life of me i can't seem to figure this part out..

**Comment by ikn** [comment]
If you're talking about a specific setup (ie. exactly 3 windows which have a specific class open in a specific layout), I'm not sure.  If you mean you just want any new window to split the largest existing window, I'm using a custom script with `bspc config external_rules_command`: https://github.com/ikn/config-stuff/blob/master/.local/share/bspwm/adjust-new-window (`$BSPWM_SCRIPTS_DIR` points to the directory containing that script).
