### ISSUE TITLE
bspc window -f left has illogical behaviour

### ISSUE THREAD

**Issue by Ploppz** [baskerville/bspwm#242]
I have 4 windows tiled in a desktop, pretty symmetrically. When the top-right window is focused, and I press `ctrl + h` which maps to `bspc window -f left`, the focus is moved to the window which is located at the *bottom left*. I can create 4 windows at any time, tiled like [this](http://a.pomf.se/bevppe.png), and it has this behaviour. Expected behaviour is to move focus to the *top left* window.

`bspc query -T`:
```
HDMI-0 1920x1080+0+0 15,0,0,0 *
	[.....]
	22 3 5 0,0,0,0 T - *
		V m 0.528721
			H m 0.500000
				m Termite termite 0x3600005 3 642x386+636+344 R --------
				m Termite termite 0x2200005 3 642x386+636+344 U --------
			H m 0.556604
				a Termite termite 0x3C00005 3 890x772+760+201 R f------- *
				H m 0.556604
					m Termite termite 0x3400005 3 642x386+636+344 R --------
					m Termite termite 0x2400005 3 1043x836+800+226 U --------
	[.....]
```
That floating termite window is the window in which I write `bspc query -T`

Thanks.

**Comment by ikn** [comment]
Maybe you have `bspc config focus_by_distance` set to `false` - it should be `true` for your desired behaviour.

**Comment by Ploppz** [comment]
Yes that certainly fixed it.. didn't know that option existed even though I haven't had that problem before. Thanks!
