### ISSUE TITLE
Make examples easier understandable

### ISSUE THREAD

**Issue by pickfire** [baskerville/bspwm#244]
Hi, I think you should add comments to make the examples easier understandable.

**Comment by svenstaro** [comment]
Reading the examples, I concur. They could also be simplified quite a bit.

**Comment by baskerville** [comment]
@svenstaro: sure.

**Comment by pickfire** [comment]
Yeah, maybe it should uses more simple keys such as:
```
h    left
j    down
k    up
l    down
-    vertical split
|    horizontal split
H    move left
J    move down
K    move up
L    move right
r    resize
```

**Comment by Krak-n** [comment]
@baskerville 

I dabbled a bit with the folder for the example panel, and have a rough change: [Here](https://github.com/Krak-n/bspwm/tree/panel_readme/examples/panel)

Are you opposed to having a README in each example sub-folder? The README would contain a bit of information on how to implement each example. This change would remove the need for those extra "sxhkd" & "bspwmrc"  files that are floating around in each of the example sub-folders.

**Comment by pickfire** [comment]
I think adding README to every subfolders is not needed and adding comments to **examples** is what needed as when users try to see the default keys, they will first have a look at *~/.config/sxhkd/sxhkdrc* which is the copy of **examples**, so adding coment to the **examples** will let them understand the key easily rather then no comments for:
```
super + {o,i}
        bspc control --record-history off; \
        bspc window {older,newer} -f; \
        bspc control --record-history on
```

**Comment by Krak-n** [comment]
I fully understand that, and if you look at my [dotfiles](https://github.com/Krak-n/dotfiles), I'm slowly mulling over that too. Basically what I did was remove anything I didn't use, and slowly add it back while commenting it.

I still don't understand some commands. :(

**Comment by baskerville** [comment]
@Krak-n
A basic knowledge of the *Unix* ecosystem is required when using *bspwm*.
I won't merge anything that breaks this principle.
Comments that paraphrase the manual or state the obvious aren't welcome.

**Comment by Krak-n** [comment]
@baskerville understood. Does the PR I made for sxhkdrc break this rule?

**Comment by baskerville** [comment]
@Krak-n 
Yes, it does.

**Comment by pickfire** [comment]
> A basic knowledge of the Unix ecosystem is required when using bspwm.
> I won't merge anything that breaks this principle.
> Comments that paraphrase the manual or state the obvious aren't welcome.

What is the principle that you say? Unix philosophy?

**Comment by baskerville** [comment]
Fixed.
