### ISSUE TITLE
Install latest from Git or Stable recommended?

### ISSUE THREAD

**Issue by addisonamiri** [baskerville/bspwm#248]
As this is still pre-1.0 do you recommend users to install the git version or the last stable build. I'm curious as the last stable build in the Arch Package Repo was a few months ago and I see a lot of fixes since then but at the same time it doesn't make sense to update the version number for every bug fix in beta software. I also have the same question for sxhkd and your other utilities that are commonly used in bspwm setups.

**Comment by Krak-n** [comment]
The real question is what do YOU feel comfortable using?

If things break, do you feel comfortable troubleshooting them?

Yes - Use the git version

No - Use the "Stable" version

**Comment by baskerville** [comment]
@Krak-n said it all.
