### ISSUE TITLE
Left click events ignored on certain applications

### ISSUE THREAD

**Issue by inorichi** [baskerville/bspwm#254]
In some applications like Steam and Bomi the left click is ignored most of the time (in Bomi, play/pause, etc..., doesn't work, but dragging the volume bar and time bar works fine, the buttons work if I click them with the control key though).

At first, I thought it was related to #232, but I don't use that option, and it happens whether it's enabled or not.

I don't know if it's an issue of Bomi/Steam or bspwm.

I'm using the latest git version of bspwm and sxhkd.

Edit: It seems Bomi works with the mouse up event, and when releasing the button, somehow the focus on that key is lost and nothing happens. But if I move the mouse before releasing it a bit, it works.

**Comment by baskerville** [comment]
Should be fixed by 2b2ed4e.
