### ISSUE TITLE
Feature request: Multiple configs

### ISSUE THREAD

**Issue by svenstaro** [baskerville/bspwm#255]
Just as sxhkd allows for multiple configs to be loaded sequentially, I think it would be useful to have this in bspwm as well. The reason is that if you have one generic config, you can still have system-specific config overwrite the generic defaults without an external templating solution. This would ease shared bspwm configuration for different setups (such as laptop with dynamic screens, desktop with static screens, etc) quite a bit.

**Comment by Stebalien** [comment]
The bspwm config is just a shell script. Can't you just run/source your additional configuration scripts from your main one?

**Comment by svenstaro** [comment]
Oh frankly I had no idea it was just a shell script. That would solve the problem then, I guess.

**Comment by svenstaro** [comment]
Now that you mention it: I just spotted the shebang and now I feel stupid. Sorry, this feature obviously isn't required. I also realize now that it's required for sxhkd exactly because it's not just a shell script!
