### ISSUE TITLE
Disappearing prelelection because of launching kupfer

### ISSUE THREAD

**Issue by coditoter** [baskerville/bspwm#258]
I use a simple config - bspwm, sxhkd + kupfer. I send a preselect message, then I run kupfer to launch an app and ... auto mode is used, because the window(f.e. firefox) loses the focus. 
Is there any way to force the preselection to work despite losing the focus?
I've spent plenty of hours reading the doc ... and no solution's been found.

**Comment by ikn** [comment]
The issue isn't another window being focused, it's a new window appearing that bspwm starts managing.  When this happens, the preselection is used to determine where to place the window, apparently even if it's floating.

So maybe it makes sense only to remove the preselection if the new window is tiled or pseudo-tiled; otherwise, perhaps a rule called 'ignore_preselect' could be added?

**Comment by coditoter** [comment]
@ikn 
Yes, you're right ... however I doubt if it's scriptable using available UI, without changing source code:
"So maybe it makes sense only to remove the preselection if the new window is tiled or pseudo-tiled; "

**Comment by supplantr** [comment]
Preselections should be honored by any managed window, floating or not. Floating windows still receive a node in the layout tree.
It sounds like an issue with kupfer. It probably doesn't set the [override redirect flag](http://tronche.com/gui/x/xlib/window/attributes/override-redirect.html), which is what dmenu does. This would signify to the window manager to ignore the given window. Have you tried adding a rule to unmanage kupfer's window? i.e. ``bspc rule -a kupfer manage=off``

**Comment by coditoter** [comment]
@supplantr 
I added and ...  the preselection doesn't get lost after kupfer. However, input ( I mean chosing an app using my mouse, f.e.) is impossible.

**Comment by supplantr** [comment]
It seems kupfer doesn't steal input focus the way dmenu does, meaning it won't receive input unless it's the focused window (which it can't be if it's unmanaged). As a workaround, you could use `bspc window last --presel DIR` to preselect the previously focused window after opening kupfer.

**Comment by coditoter** [comment]
@supplantr 
Really thanks ... it works. Simple but not so simple. So the problem's workarounded.
