### ISSUE TITLE
Arbitrary splits without new windows?

### ISSUE THREAD

**Issue by addisonamiri** [baskerville/bspwm#259]
Is there any way to split a window before a new window appears? For instance a tree would go from

```
window1
```

to

```
      vsplit
     /      \
window1    empty
```

And the next window I launch would take the empty spot in the tree. I haven't looked at the code but I'm assuming the tree structure is based off of windows so it might be a bit cumbersome to switch to be off of spots or places for windows (occupied or not) but if there was a way I could do this that'd be cool. So far All I can think of is setting `right_padding` to half my screen and configuring my launcher to check it and change it when launching a new window but that would resize the current window twice.

I think this a pretty simple example but it would allow static layouts for certain desktops that could be defined in a user's `bspwmrc`. I'm no fan of static layouts but they do come in handy for things like IM.

Also I'm pretty sure I remember seeing someone mention this previously but I couldn't find the issue so if it's been discussed I'm sorry.

**Comment by Almehdi** [comment]
You mean like in sxhkdrc...

```
## Cut the window at...
super + ctrl + {a,s,w,d}
    bspc window -p {left,down,up,right}
```

**Comment by addisonamiri** [comment]
This does preselection but what I was more hoping for was making the split happen before the new window is created. A use case could be having a terminal not take up the whole screen. You could launch your terminal and run `bspc window -P left` and the terminal would shrink in size (based on your split ratio) and the next window created would take up the empty space. I'd like BSPWM to function like there's a window there but it's just empty space.

**Comment by addisonamiri** [comment]
Is anyone else interested in this? I found out that herbstluftwm treats splits like this and I find it personally desirable. I think a `bspc config` option would be the best way to implement this (if it was implemented). If there's no one else that thinks this is useful I'll close this in a few days though. No need to pollute the open issues.

**Comment by lamarpavel** [comment]
>Is anyone else interested in this?

Yes, I wanted to have invisible pseudo windows that allow splits without opening actual new windows for some time. Initially to allow more convenient space partitioning that allows me to see part of the conky UI on my desktop. Now I would use invisible pseudo windows to create a free area on my desktop that I can place floating windows in without overlapping tiled windows.

**Comment by addisonamiri** [comment]
@lamarpavel you can achieve this along one full side of the screen by toggling padding. Setting the bottom right corner would require this feature though.

**Comment by neeasade** [comment]
I know this isn't a perfect solution, but you can launch an invisible window using urxvt (give it a custom title and make a bspc rule to hide its borders) 

The how to is here(not mine): http://thedarnedestthing.com/bspwm%20gym 
under the heading 'pseudo frame'

**Comment by lamarpavel** [comment]
@neeasade I thought of something similar, but with that solution there is still a problem with selection. There is one more window to select than you expect when cycling, which gets confusing quickly and breaks workflow. If we could set a window to be non-selectable it might work, but a solution integrated into bspwm would of couse be much preferable.

**Comment by baskerville** [comment]
@lamarpavel You might want to use pseudo-tiled windows.

@addisonamiri I could insert *receptacle* nodes. But your use case probably requires to insert each window in a precise receptacle. And since those leaves don't hold any window, there's no way to reference them as insertion point unless I generalize the *window* command and introduce a node selector notation.

**Comment by luizfl** [comment]
That's the behaviour on stumpwm and ratpoison IIRC.

**Comment by notyetawizard** [comment]
Ah, the null/receptacle nodes sound like just what I'm looking for too; I have a few cases where I'd like to reserve a space for something that pops in and out of existence so that the other windows on the screen don't move on those events. Padding and floating windows work, but this sounds much better!

I'm glad to see things are already headed in this direction :)

**Comment by roosemberth** [comment]
:+1: for this feature

**Comment by Chrysostomus** [comment]
Cool feature! How does one delete these receptacles once they are created?

**Comment by cju** [comment]
Afaics receptacles can be found via ```bspc query -N -n .leaf.!window.local```.

To kill them all at once, you could use things like a for loop or something like that…

PS: You're absolutely right, this feature is really smooth, thanks a lot @baskerville! :+1:

**Comment by Chrysostomus** [comment]
Optimally I would like to have a keybinding that could undo them and close windows seamlessly. Or have external rule that replaces receptacle with the new window. 

Thanks, I'll experiment with this :)

**Comment by cju** [comment]
Tested, works: ```for i in $(bspc query -N -n .leaf.!window.local); do bspc node $i -k; done```

One line to kill 'em all. :smile:

**Comment by Chrysostomus** [comment]
Okay, I have managed the following:

```
super + alt + space
  {smartsplit ; bspc node -i,\
  for i in $(bspc query -N -n .leaf.!window.local); do bspc node $i -k; done}
```
This binding alternates between splitting the focused window with a receptacle and killing all receptacles.

I also found that I can fill the space left by receptacle by transplanting a window into it:

    bspc node -n $(bspc query -N -n .leaf.\!window.local)

However, I cannot yet get the same behavior with an external rule. What I have tried is the following:

```
receptacle=$(bspc query -N -n ".leaf.!window.local")
if [ -n "$receptacle" ] > /dev/null ; then
    echo "node=$receptacle"
fi
```
This comes close, as the new window is transplanted into the receptacle, but the receptacle is not filled, but instead halved. Any ideas how to get the new window to entirely replace the receptacle?

**Comment by baskerville** [comment]
`query -N -n .leaf.!window.local` might return multiple results.

A receptacle will only be *filled* if it isn't preselected.

**Comment by Chrysostomus** [comment]
Yeah, I noticed and added an awk pipe to only print the first result. Would be great to be able to use biggest.leaf.!window.local. but that would defeat the purpose of unselectable node I guess.

Thanks for the tip! Is there a way not to transplant without preselecting in a external rule?

**Comment by baskerville** [comment]
The term *transplantation* can only be used for existing nodes. If you want `NODE_SEL` to be the insertion point for the upcoming window of an external rule, you can express your intentions with `echo "node=NODE_SEL"`.

**Comment by Chrysostomus** [comment]
Thanks! 

I noticed that my script was also echoing split dir. Removing that made it work.

**Comment by MarcosCosmos** [comment]
Are receptacles still available? I can't seem to find a way to get them working (bspc node -i seems to be invalid syntax and I can't find any mention of them in the manpage or on the wiki..)
