### ISSUE TITLE
bspc config -m focused window_gap returns default value

### ISSUE THREAD

**Issue by addisonamiri** [baskerville/bspwm#260]
In my bspwmrc I have window_gap set to 12 and I get 12 from the monitor's output even when I've changed it. These steps should reproduce it:

```
bpsc config window_gap 12
bspc monitor -d 1 2 ...
bspc config -m focused window_gap 14
bspc config -m focused window_gap   # returns 12
```

**Comment by baskerville** [comment]
The *window_gap* setting is local to a desktop.

`bspc config -m focused window_gap 14` sets the window gap for all the desktops of the focused monitor, while `bspc config -m focused window_gap` retrieves the window gap used when creating new desktops (because you didn't specify a desktop).

**Comment by addisonamiri** [comment]
I figured it was something like this. That's why I thought of writing some documentation. Thanks.
