### ISSUE TITLE
A more informative readme?

### ISSUE THREAD

**Issue by addisonamiri** [baskerville/bspwm#262]
Would you be open to someone rewriting the main project README.md to not just be the bspc manpage? I think it'd be good for people looking at the project for the first time. I was also considering making readme's for the each of the folders in examples and one for the example folder itself explaining what they are and how to use them. I think a bit of better introductory documentation would help people who are considering it for the first time (and I also think better descriptions of what's going on in each of the examples would help people trying to modify them for their own configs). I don't mind writing a few of them myself. Just wondering if you'd accept the pull request before I write it ;)

**Comment by baskerville** [comment]
Yes: that's a good idea.

**Comment by Krak-n** [comment]
@addisonamiri 
I just uploaded a branch I was working on  locally regarding this:

https://github.com/Krak-n/bspwm/tree/panel_readme/examples/panel

If you want to copy that branch and start one to give each of the examples readme files, go ahead!

**Comment by baskerville** [comment]
I've just pushed a `README.md`.

**Comment by vyp** [comment]
@baskerville I did like man page being generated by github though. Would you oppose having a symbolic link named `bspwm.1.asciidoc` in the `doc` directory that points to `bspwm.1.txt` for this purpose?

**Comment by baskerville** [comment]
@vyp Fixed.

**Comment by vyp** [comment]
@baskerville Thank you!

**Comment by baskerville** [comment]
No one seems to be interested. I'm therefore closing this issue.
