### ISSUE TITLE
Rules for positioning and sizing floating windows

### ISSUE THREAD

**Issue by rr-** [baskerville/bspwm#263]
I'd like to have rules that make Pidgin stay in the top left workspace corner and music player in the top right workspace corner. Right now I feel like this is impossible unless I wrap Pidgin and music player in a shell script that does `xdotool search --sync` and then moves the windows to desired position. It's clunky and doesn't look too good (a solution like this won't prevent the window from briefly rendering itself in unwanted size).

Having `rule -a class_name command="xdotool windowmove {} 100 200"` would be sufficient, but I'm all for more elegant options, especially if they take care of multi monitor geometries.

i3 has better control in this regard, for example I can do `for_window [title="(?i)buddy list"] floating enable move position 100 100`.

**Comment by blendi-93** [comment]
hi u could use external rules, for example:

add this into ur bspwmrc

    bspc config external_rules_command /path/to/external/rules

and this into ur external_rules file

    #! /bin/sh
    
    wid=$1
    class=$2
    instance=$3
    title=$(xtitle "$wid")
    
    if [ "$instance" = Pidgin ] ; then
    	case "$title" in
    		buddy_list|Buddy-Liste)
    			echo "floating = on"
    			xdotool windowmove $wid 0 0
    			;;
    	esac
    	echo $title >> /tmp/windows
    fi

**Comment by Chrysostomus** [comment]
Does anybody with more experience with scripting/external rules know if there is a good way to place floating windows based on number/position of floating windows in the desktop?
I'm looking for smart window placement like in awesome wm or recent xfce4, but just moving new floaters a few pixels aside would suffice, so that floating terminals don't overlap completely with each other. (I'm trying look into it myself, but progress is slow due to limited experience and available time)

**Comment by blendi-93** [comment]
u could count floating windows of current desktop with 

   bspc query -T | grep " f"| wc -l

and if u add this to the external rule:

    #! /bin/sh
    
    wid=$1
    class=$2
    instance=$3
    title=$(xtitle "$wid")
    
    #place floating windows
    floats=$(bspc query -T -w | grep " f"| wc -l)
    xdotool windowmove --sync $wid $(( 10 + 10 * floats )) $(( 20 + 20 * floats ))
    
    if [ "$instance" = Pidgin ] ; then
    	case "$title" in
    		buddy_list|Buddy-Liste)
    			echo "floating = on"
    			xdotool windowmove --sync $wid 0 0
    			;;
    	esac
    	echo $title >> /tmp/windows
    fi

all new floating windows are created top left and ahifted depending of current open floating windows

**Comment by Chrysostomus** [comment]
Thanks! This is exactly what I was looking for!

**Comment by blendi-93** [comment]
so u would close this issue pls ;)
