### ISSUE TITLE
Handle _NET_SYSTEM_TRAY_OPCODE

### ISSUE THREAD

**Issue by rr-** [baskerville/bspwm#264]
It would be cool if `bspc control --subscribe all` would tell us about tray events, so that we could implement icons in third party taskbars.

Use case: some programs use tray icon as the only channel to receive user attention.
Example: Pidgin. When receiving a message on an inactive workspace, it doesn't make its window urgent or anything... it just changes tray icon.

**Comment by Airblader** [comment]
Just an FYI, pidgin does have a setting to trigger the urgent flag.

**Comment by rr-** [comment]
@Airblader I searched for it and didn't find anything, at least not in its GUI preferences dialog.

**Comment by Airblader** [comment]
@rr- It's a little hidden, but it's there. See https://awesome.naquadah.org/wiki/IM_tips#Pidgin

**Comment by rr-** [comment]
You're right, I missed it. Thanks.
This probably should be closed unless someone else comes up with more use cases.
