### ISSUE TITLE
Selecting a monitor with ^<n> seems broken

### ISSUE THREAD

**Issue by svenstaro** [baskerville/bspwm#265]
This should illustrate the problem:

    $ bspc query -M         
    VGA-0
    VGA-1

    $ bspc query -M -m VGA-0
    VGA-0

    $ bspc query -M -m ^0
    

    $ bspc query -M -m ^1
    
I expect ^0 and ^1 to return some screen but it doesn't return anything.

**Comment by baskerville** [comment]
Some shells (e.g. *zsh*) treat *^* as a special character, furthermore, the *^n* notation starts at *1*.

So, instead of `^0` and `^1`, you should write `\^1` and `\^2`.
