### ISSUE TITLE
maim and bspwm

### ISSUE THREAD

**Issue by r8b7xy** [baskerville/bspwm#266]
I don't know if this is bspwm bug but:
When I try to run `maim -s` and mouse is over any window and I select it maim gives an error:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  25  
  Current serial number in output stream:  25  
```
Problem doesn't appear when mouse is over lemonbar and then I select the window I'd like to print (bspwm@arch).
[video](https://youtu.be/FJWQyNgK4Jo)

**Comment by Eryla** [comment]
I don't think its related to maim, I can reproduce this with just xprop.
```
xprop
_NET_WM_PID(CARDINAL) = 909
_NET_WM_NAME(UTF8_STRING) = "bspwm"
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0xe00000
```

I can reproduce it 100% by opening a new window or changing desktop without focusing anything.

I use 
```
~button1
        bspc pointer -g focus
```
in sxhkd.

And it doesn't focus windows if they happen to be on the same location while changing desktop.
(Works if I move the cursor out of the window and back again to "focus" it_)

**Comment by rr-** [comment]
Are you using newest HEAD? Does this have to do with #232 ?

**Comment by r8b7xy** [comment]
Thanks! It indeed works as expected with latest github pull.
