### ISSUE TITLE
bspwm and mpv - flickering

### ISSUE THREAD

**Issue by r8b7xy** [baskerville/bspwm#268]
When the mouse pointer is over the mpv I can't change the desktop. When I'm trying to switch from desktop 1 to 2 for example screen starts to flick. I've experience this issue after upgrading bspwm from pacman to latest git version. It may be related to https://github.com/baskerville/bspwm/commit/56895ab9ab074877d5af92aa1367699d1b351a38
```
LVDS1 1280x800+0+0 20,0,0,0 *
	1 3 15 0,0,0,0 M -
		V m 0.500000
			m mpv gl 0x1C00002 3 640x360+320+220 R --------
			m qutebrowser qutebrowser 0x1A00005 3 1250x750+15+35 R -------- *
	2 3 15 0,0,0,0 M - *
		m URxvt urxvt 0x180000A 3 404x244+435+275 R -------- *
	3 3 15 0,0,0,0 M -
	4 3 15 0,0,0,0 M -
		m URxvt urxvt 0xE0000A 3 404x244+435+275 R -------- *
	5 3 15 0,0,0,0 T -
```
EDIT:
I've experienced this bug with other windows as well.
Moving the mouse cursor over the lemonbar fix the issue.

**Comment by rr-** [comment]
I'm using mpv and lemonbar as well and on two separate machines and I don't experience this issue. I use compton on both machines to get vsync. One machine uses Nvidia, and the other one uses ATI graphic card.

**Comment by rr-** [comment]
Edit: I experience similar behavior but I'm unable to determine what are the circumstances that trigger it.

**Comment by reportados123** [comment]
I experience the same thing after updating to the latest git version, relating to the new implementation of focus_follows_pointer. If I disable focus_follows_pointer, everything works fine. If I were to turn it on, and try to switch desktops, I get an endless flickering between the two desktops.

I think it's reproducible by doing this: Open terminal (urxvt), cd to a video directory, open a video file with mpv, move your mouse over the mpv window to focus it, and then try switching desktops.

**Comment by reportados123** [comment]
I just tested with the new commit. Everything works fine again. I think this issue can be closed if the others don't experience it as well.
