### ISSUE TITLE
focus_follows_pointer doesn't focus empty monitors on a multimonitor setup

### ISSUE THREAD

**Issue by trollhase** [baskerville/bspwm#269]
**Problem:**
focus_follows_pointer doesn't focus empty monitors on a multimonitor setup anymore.

**How to produce the bug:**
1. connect second monitor
2. open a window on one monitor
3. try to open a window on the empty monitor

**Bug exists since:**
commit 56895ab9ab074877d5af92aa1367699d1b351a38

**Comment by baskerville** [comment]
I was aware of the problem but I thought I had fixed it with 8821c69527f67c46c3562a5834693f4103f220e7.

**Comment by trollhase** [comment]
I checked with the newest commit before i posted and also checked just now.
It still doesn't recognize my mouse moving to the second empty monitor.
I even opened up a bspc control --subscribe, but it doesn't print anything if i just move my mouse to the empty monitor.

Any way i can debug this here and send you information?

**Comment by baskerville** [comment]
The output of *bspwm* compiled with `make clean debug` might help.

**Comment by trollhase** [comment]
Here is the output: http://sprunge.us/HKMa

I started bspwm with my config. (also sxhkd to open anything)
moved my mouse over to the second monitor and opened several urxvt windows which showed up on the first monitor.

**Comment by baskerville** [comment]
What seems strange is that there's not a single *motion notify* message in your log and no *leave notify* either.

What's the output of `sleep 3; xwininfo -root -events` (you have to move your mouse pointer on the root window within 3 seconds)?

**Comment by trollhase** [comment]
http://sprunge.us/BEAP

**Comment by baskerville** [comment]
Can you also provide a valid version of the first output?

**Comment by trollhase** [comment]
The other output were fine only the xwininfo had been made with the old commit. Sry again :(

**Comment by baskerville** [comment]
Can you compile this:
```C
#include <stdio.h>
#include <xcb/xcb.h>

int main(void)
{
	xcb_connection_t *dpy = xcb_connect(NULL, NULL);
	const xcb_setup_t *setup = xcb_get_setup(dpy);
	xcb_screen_iterator_t iter = xcb_setup_roots_iterator(setup);
	for(int i = 0, len = xcb_setup_roots_length(setup); i < len; i++) {
		xcb_screen_t *screen = iter.data;
		printf("root %i: 0x%X\n", i, screen->root);
		xcb_screen_next(&iter);
	}
	xcb_disconnect(dpy);
	return 0;
}
```
And post its output when both of your monitors are plugged?

**Comment by trollhase** [comment]
http://sprunge.us/NUJb

**Comment by rr-** [comment]
What if you try to get information via Xinerama?

    #!/usr/bin/python3
    import ctypes
    import ctypes.util
    
    class XineramaScreenInfo(ctypes.Structure):
        _fields_ = [
            ('screen_number', ctypes.c_int),
            ('x', ctypes.c_short),
            ('y', ctypes.c_short),
            ('width', ctypes.c_short),
            ('height', ctypes.c_short),
        ]
    
    xlib = ctypes.cdll.LoadLibrary(ctypes.util.find_library('X11'))
    xlib.XOpenDisplay.argtypes = [ctypes.c_char_p]
    xlib.XOpenDisplay.restype = ctypes.POINTER(ctypes.c_void_p)
    d = xlib.XOpenDisplay(b'')
    if not d:
        raise Exception('Could not open display')
    
    xinerama = ctypes.cdll.LoadLibrary(ctypes.util.find_library('Xinerama'))
    if not xinerama.XineramaIsActive(d):
        raise Exception('Xinerama is not active')
    
    number = ctypes.c_int()
    xinerama.XineramaQueryScreens.restype = ctypes.POINTER(XineramaScreenInfo)
    infos = xinerama.XineramaQueryScreens(d, ctypes.byref(number))
    infos = ctypes.cast(infos, ctypes.POINTER(XineramaScreenInfo * number.value)).contents
    
    print([(i.x, i.y, i.width, i.height) for i in infos])

**Comment by trollhase** [comment]
http://sprunge.us/YNQf

**Comment by trollhase** [comment]
I just played around some more with moving windows etc. while having bspc control --subscribe open and it doesn't print anything if I move the only window from one monitor to the other monitor **although** the debug output shows *focus monitor* lines. I don't know if that's correlated or not.

Output:

**Comment by baskerville** [comment]
Can you reproduce with this `.xinitrc`:
```sh
sxhkd &
exec bspwm
```

**Comment by trollhase** [comment]
Well my current .xinitrc:
```bash
#!/bin/bash

~/.config/scripts/prepare_monitors.sh

sxhkd -c ~/.config/sxhkd/sxhkdrc &
~/bspwm-debug/bspwm -c ~/.config/bspwm/bspwmrc 2>&1 >~/bspwm-debug.log
```

prepare_monitors.sh is a xrandr script, which is necessary else both monitors would show the same screen area:
```bash
#!/bin/bash

INTERN="LVDS1"
EXTERN="VGA1"

xrandr --output $INTERN --auto

if [ -n "$(xrandr -q | grep $EXTERN' connected')" ]; then
    xrandr --output $EXTERN --auto --right-of $INTERN
else
    xrandr --output $EXTERN --off
fi
```

nothing else is run. everything after you told me to use *make clean debug* has been tested with this .xinitrc

**Comment by trollhase** [comment]
Here are my configs, maybe they're the reason?
bspwmrc: http://sprunge.us/MZfP
sxhkdrc: http://sprunge.us/dehY

**Comment by baskerville** [comment]
Try with this *bspwmrc*:
```
#! /bin/sh
bspc config focus_follows_pointer true
```

**Comment by trollhase** [comment]
Nope. same problem.

Opened a terminal on LVDS1 and tried to open a terminal on VGA1 which showed up on LVDS1.

bspwm output: http://sprunge.us/GCeb

**Comment by baskerville** [comment]
This should be fixed as of 639763c.

**Comment by rr-** [comment]
Does this mean #232 is back? :sob:

**Comment by trollhase** [comment]
Awesome it works again. :+1:  sorry the new method didn't work out yet.
