### ISSUE TITLE
focus_follows_pointer doesn't work with termite

### ISSUE THREAD

**Issue by Stebalien** [baskerville/bspwm#270]
As of 8821c69527f67c46c3562a5834693f4103f220e7

I'm getting enter/leave notify events but no motion notify events:
```
leave notify 240009F 0 0
enter notify 2600005 0 0
leave notify 2600005 0 3
enter notify 1400005 0 3
leave notify 1400005 1 0
```

**Comment by baskerville** [comment]
It seems that *X.org* and its despicable design interferes.

And forces me to grab the pointer.

This should be *fixed* as of dfc03b5.

**Comment by neeasade** [comment]
hi, I was having this issue, it appears fixed now.

**Comment by Stebalien** [comment]
Fixed. Thanks!
