### ISSUE TITLE
weird behaviour after killing bspwm

### ISSUE THREAD

**Issue by r8b7xy** [baskerville/bspwm#272]
After every bspwm upadte I used to restart bspwm with 'pkill bspwm' command. After https://github.com/baskerville/bspwm/commit/8821c69527f67c46c3562a5834693f4103f220e7 when I perform 'pkill bspwm' all urxvt instances are spawning in top left corner with fixed size and I can't focus them.

**Comment by baskerville** [comment]
Please check your spelling.

The proper way to quit *bspwm* is to use the *quit* message. You can also cleanly restore the state of *bspwm* through the *restore* message, cf. *examples/loop*.

**Comment by r8b7xy** [comment]
```bspc quit``` command gave me the same result.
I apologise for linguistic errors. I'm still improving my english.

**Comment by r8b7xy** [comment]
I thought that problem was gone but it still occurs. I made screencast [here](https://youtu.be/3jsS5VWQ8qg).
I restart bspwm with ```bspc quit``` as you recommended.
