### ISSUE TITLE
Is it possible to WINDOW_SEL second biggest window?

### ISSUE THREAD

**Issue by Chrysostomus** [baskerville/bspwm#273]
I'd like to create an external rule that would transplant new windows in the second biggest window of the desktop. How would one go about doing that?

**Comment by ikn** [comment]
You could always preselect the biggest window, then use 'biggest.automatic'.

**Comment by blendi-93** [comment]
u can use this script.
for eample, this would focus the second biggest window:

    bspc window -f $(./list_windows_by_size.sh 2)

or to use this in ur external rules.

	echo window=$(~/list_windows_by_size.sh 2)

pls install [jshon](https://github.com/keenerd/jshon) to use the script.

https://gist.github.com/blendi-93/b2038896ac29037353af

**Comment by baskerville** [comment]
I've got a one-liner using [jq](https://stedolan.github.io/jq/):
```shell
bspc query -T -d | jq '[..|objects|select(.client != null)|.client.tiledRectangle as $r|[.id, $r.width * $r.height]|sort_by(.1)]|.[1][0]'
```

**Comment by blendi-93** [comment]
this gives me "null"

    ~%: bjects|select(.client != null)|.client.tiledRectangle as $r|[.id, $r.width * $r.height]|sort_by(.1)]|.[1][0]'
    null

**Comment by baskerville** [comment]
It should work as of eb07d2f.

**Comment by blendi-93** [comment]
y, works with it and destroyed my sxhkd config + panel script :D.

**Comment by baskerville** [comment]
This [guide](https://github.com/baskerville/bspwm/wiki/Upcoming-Changes-in-0.9.1) might be helpful.

**Comment by baskerville** [comment]
@Chrysostomus The original version of my one-liner was broken and I've updated my comment with a working version.

**Comment by Chrysostomus** [comment]
The two options suggested. The one-liner gives me just null, but that might be because my bspwm version is not entirely up to date. The jshon option works, but it has one flaw from my point of view: the window number provided by it is not window id used by other programs. My external rule uses wattr to choose split direction, and passing the given value to wattr does not work. I need some way of converting this value to window id (like bspc query -N -n focused.automatic would provide).

**Comment by Chrysostomus** [comment]
... 
bwid=$(bspc query -W -w $(list_windows_by_size.sh 2))
So that's how it is done...

**Comment by baskerville** [comment]
Or just `bwid=$(printf '0x%x' BASE_TEN_BWID)`.

**Comment by Chrysostomus** [comment]
Thanks. What is BASE_TEN_BWID?

**Comment by baskerville** [comment]
The relevant window ID in base 10.

**Comment by Chrysostomus** [comment]
Many thanks =)
