### ISSUE TITLE
Gaps and borders fail to change size.

### ISSUE THREAD

**Issue by shiftypenguin** [baskerville/bspwm#274]
The commands documented in the example bspwmrc to change the window gap and border width fail to change either respectivly. The commands I tried are "bspc config border_width 7" and "bspc config window_gap 50". I don't know if it makes a difference, but I installed bspwm from the Arch User Repository and the default arch repos. The error occured in both versions. 

EDIT: The version I'm running right now is 0.9

EDIT2: Guy on reddit said it might be helpful to inform you that when running bspwm from a terminal, no error messages displayed when replicating this behavior.

**Comment by shiftypenguin** [comment]
Alright, I dun goofed. The file didn't have execute perissions. Regardless, I think you might add somewhere in your manpage the these settings apply to only new (or refreshed) desktops. That would have been nice to know.

**Comment by zzggbb** [comment]
If you apply a MONITOR_SEL, you can get the `window_gap` to refresh instantly. For example,

    bspc config -m ^1 window_gap 10

**Comment by addisonamiri** [comment]
Am I correct in saying that this doesn't work for `border_width` for existing windows? Is there a way to change the `border_width` for all open windows and all new windows?

**Comment by neeasade** [comment]
@addisonamiri Yes, you can reset/refresh a desktop after changing the bspwm setting to do changes on the fly. 

I do this in my bspwmrc (which I abuse with enviroment vairables) [here](https://github.com/neeasade/dotfiles/blob/3589326052485ba3e08c3aeb7fe04b699f27dd3e/bspwm/.config/bspwm/bspwmrc#L78)

it looks like: https://u.teknik.io/ogaw7k.webm
