### ISSUE TITLE
Feature request: Per window border color

### ISSUE THREAD

**Issue by wsinnema** [baskerville/bspwm#275]
At the moment, when I enter `bspc config -w focused normal_border_color white`, all windows change color. It would be nice to be able to have different window with different border colors, and possibly being able to set them using rules (or at least external rules).

**Comment by baskerville** [comment]
What is the use case?

**Comment by neeasade** [comment]
@wsinnema There is a project called [wmutils](https://github.com/wmutils/core) compromised of many tools for manipulating x windows, many of which work with bspwm - including the `chwb` utility which can be used to change border colors of individual windows.

**Comment by wsinnema** [comment]
Thanks, I didn't know about `chwb` but that's even better.

**Comment by thejmazz** [comment]
For what it is worth, for whoever lands here from Google, I got it going like [this](https://github.com/thejmazz/dottos/blob/2ec6d4368e6117d7f30bf0606d7e6f4ce053e086/.config/bspwm/subscribe/node_focus.sh):

```bash
#!/bin/bash

# needs jq and chwb

bspc subscribe node_focus | while read -r action monitor_id desktop_id node_id; do
    # echo Action: $action
    # echo Monitor: $monitor_id
    # echo Desktop: $desktop_id
    # echo node_id $node_id

    className=$(bspc query -T -n $node_id | jq -r '.client.className')

    case "$className" in
        Postman)
            # Sometimes flashes
            chwb -c 0x464646 $node_id
            # Flashes less?
            # bspc config focused_border_color "#464646"
            ;;
        *)
            # Reset to default focused_border_color
            # Not required if using chwb approach
            # bspc config focused_border_color "#dfdfdf"
        esac
done
```

My use case is getting borders to match the color of that window's "banner,", e.g. yellow for a popped-out Google Keep, and `#464646` for Postman:

![screenshot from 2018-05-27 13-28-35](https://user-images.githubusercontent.com/1270998/40589347-c3c3fd20-61b9-11e8-822f-8ba0300f33c9.png)


However, there is sometimes flashing with this solution (briefly shows `focused_border_color` before `chwb` kicks in). Perhaps bspwm's handling of border colors could be disabled and it would be up to the user to handle `node_focus` events (including changing border of unfocused window...). Or a new rule key/value pair could be implemented, Something like `border_color=0x464646`.
