### ISSUE TITLE
Floating not always on top?

### ISSUE THREAD

**Issue by steelcowboy** [baskerville/bspwm#276]
From what I've read and been told, floating windows should always be on the top. I have a rule to make the Google Hangout panels always floating, yet when I hit the minimize button they end up minimizing like they should, but then when I hover over to bring them back up they open *under* my tiled windows. Is this a bug or is there something I can do to make sure they always stay on top?

**Comment by baskerville** [comment]
*bspwm* doesn't handle minimization.

**Comment by steelcowboy** [comment]
So why is the window sometimes correctly maximizing over the tiled and sometimes disappearing under the tiled windows?
