### ISSUE TITLE
Feature request. Full screening 'window areas'

### ISSUE THREAD

**Issue by sac2171** [baskerville/bspwm#277]
I've upgraded to a 4k monitor, and would love the ability to take sections of the screen as a grouping. For example, If I have
 b | 1
_    _
a |  2

And would like to 'fullscreen' 2, so that it takes up the space of both one and two. being able to take other actions on smaller groupings of windows (besides from the whole desktop) would also be useful.

**Comment by neeasade** [comment]
@sac2171 you might take a look into http://www.herbstluftwm.org/ for that kinda thing

**Comment by baskerville** [comment]
@sac2171 It would be possible if layouts were node based and not desktop based.
