### ISSUE TITLE
Feature Request: bspc query --history --subscribe option

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#280]
I would like to be able to have a script react to window focus changes without looping the output of the `bspc query --history` command. A subscribe would be good for this use case, akin to the '--subscribe' option from bspc control.

**Comment by baskerville** [comment]
As of dccb5e7, `bspc control --subscribe {monitor,desktop,window}` receives focus events.

**Comment by neeasade** [comment]
I was gonna add onto this that I would like to retain the ability to query parameters for history, like per monitor/desktop, but I can keep track of last focused monitor/desktop with this new option, so that solves that, thank you. 

Thanks for bspwm, it rocks.
