### ISSUE TITLE
[bug] bspc control --subscribe output behind by one window event

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#284]
After start, if I open and close a terminal a few times this problem become apparent - the desktop will show occupied status after closing the terminal and free status after opening the terminal. 

(This is with bspwm-git via aur)

bspc control --subscribe in relation to bspc control --subscribe window:
```
WM1:F1/00:f1/01:f1/10:f1/11:LT:m2:F2/00:f2/01:f2/10:f2/11:LT:m3:O3/00:f3/01:f3/10:f3/11:LT
WM1:O1/00:f1/01:f1/10:f1/11:LT:m2:F2/00:f2/01:f2/10:f2/11:LT:m3:O3/00:f3/01:f3/10:f3/11:LT
```

```
window_focus 0x1E00003
window_manage 0x2000003
window_focus 0x2000003
window_unmanage 0x2000003
```

focus is on monitor 1 desktop 1/00 - after `window_manage` status is M1:F1/00(free desktop), after `window_unmanage` status is M1:O1/00(occupied desktop)

**Comment by Sprocklem** [comment]
I also am experiencing a one line lag since this last commit, but noticed it when changing desktops: the output of `bspc control --subscribe` would captalize the destop I was one before the current one, instead of the current one.

**Comment by baskerville** [comment]
@Sprocklem by *this last commit* do you mean 09c603a85eccf5203a995b186454a0a203d4ae1a?

**Comment by Sprocklem** [comment]
I do. I just reverted to 2dc91676f593cc3799b67524c995e1cbbe866717 to verify, and everything is working correctly there.
