### ISSUE TITLE
When launched with slim, BSPWM fails to create socket

### ISSUE THREAD

**Issue by Derpford** [baskerville/bspwm#285]
When launching via Simple Log-In Manager, bspwm appears to not create a socket. I can't use bspc to do anything, unless I manually launch bspwm outside of SLiM.

**Comment by baskerville** [comment]
Is there a way for you to capture the output of `bspwm-session`?

**Comment by Derpford** [comment]
I can pipe the output from it to a file. Working on it now.

*--Chris Scott*

**Comment by fredlebel** [comment]
I have noticed that sometimes I have to manually delete the socket file `/tmp/bspwm:0.0-socket` in cases where the shutdown wasn't clean.  Otherwise bspwm fails to launch.

**Comment by Derpford** [comment]
Looking in /tmp/, there's no bspwm socket file.

*--Chris Scott*

**Comment by jvvv** [comment]
Is BSPWM_SOCKET set in the shell environment?
<code>$ readlink -f $BSPWM_SOCKET</code>

**Comment by Derpford** [comment]
It appears that it's not set; using readlink returns an error, and echoing
$BSPWM_SOCKET gives me a blank line.

*--Chris Scott*

**Comment by baskerville** [comment]
@fredlebel it's *fixed* as of 645ad38. Is the abnormal shutdown caused by *bspwm* crashing? If so, you should submit a backtrace.

@Derpford As of 2b5cf37, *bspwm-session* doesn't exist anymore. The desktop file just launches *bspwm*. You'll have to start *sxhkd* yourself.

**Comment by Derpford** [comment]
@baskerville I am launching sxhkd, and sxhkd is not broken (I can launch
programs via dmenu with mod4+space) but bspwm-reliant binds do not work (I
can't cycle between xterms or close windows).

**Comment by jvvv** [comment]
What do the slim.conf and your .xinitrc/.xsession files look like. I'm thinking that bspwm is not running if there is no socket file. That would explain why sxhkd is working but no bspc isn't.
