### ISSUE TITLE
Unable to change between desktops

### ISSUE THREAD

**Issue by whyfoo** [baskerville/bspwm#286]
For some reason, switching between desktops stopped working like 3-4 days ago. 
I use Super + [1-9] for switching between desktops, but it doesn't work. Super + L for locking does work. 

I checked everything, super is still super, number keys are still numer keys. 
I even rolled back my backedup configs, but I still have the issue.

Any ideas?

**Comment by lainofthewired** [comment]
Well, I downgraded to older version of bspwm and sxhkd and used the example configs, but the problem persists, so this might not be a problem with bspwm after all

**Comment by neeasade** [comment]
I took a look in your dotfiles and see that in your bspwmrc you are naming desktops `web dev sch msc`, whilst your sxhkd expects desktops to be named 1-9(your desktop focus command is bspc desktiop -f ^{1-9}) - might not be the issue since it was working before, but seems a little weird to me that it would work in the first place.

**Comment by lainofthewired** [comment]
Well, I also tried changing my desktop names to that, but with no result.

**Comment by vyp** [comment]
Similar to what @neeasade said, your `monitor -d` line in your bspwmrc only has four names, whereas your sxhkd I think might be expecting 10 (1-9 and 0), so try making 6 more names for the rest of the 6 desktops, or just do `1-4` in your sxhkdrc to make them both the same number, and see if that works.

I don't think it's the names though because I use names instead of numbers for `monitor -d`, but I also use `1-9` in sxhkdrc.

**Comment by whyfoo** [comment]
Been there, done that. No change.

**Comment by vyp** [comment]
:(

Well I can't spot anything else out of the ordinary in your sxhkdrc. fwiw I'm on 0.9 from the official arch repos (where this bug does not happen for me), I presume you've already tried that too though. and also my xorg-server version is 1.17.2-4 (also just official arch package).

I guess the next thing would be to try and reproduce this on another machine if you have one available. But don't think I can help any further though, sorry. (unless I happen to get this bug some time in the future that is)

**Comment by moookino** [comment]
Hi, i have same problem, instead of super + 1-9, dekstops switching works with super + shift + 1-9, but cannot move desktops with super + shift + 1-9, some other keys stop working too, for example 
'''
super + {grave,Tab}
	bspc {window,desktop} -f last
'''
super + Tab - works fine, super + grave not working

**Comment by rcr1000** [comment]
I am having the same problem. @moookino's solution does not work for me however.

**Comment by rcr1000** [comment]
I was able to fix the problem I was having with it. Maybe this can help others.

When I copied bspwmrc into my .config/ I accidentally renamed it to a misspelled version of the filename. Make sure you didn't do something similar.

**Comment by whyfoo** [comment]
Nope, this is not the case for me.

**Comment by moookino** [comment]
Finally get sxhkd to work, start it with .xinitrc like this: #set shell that sxhkd uses to execute commands:
export SXHKD_SHELL=/usr/bin/bash

#start bspwm and sxhkd
sxhkd -f 100 -c /home/$USER/.config/sxhkd/sxhkdrc &

**Comment by whyfoo** [comment]
@mookino Yup, this was the issue, I had my shell set to fish.

**Comment by whyfoo** [comment]
@mookino Yup, this was the issue, I had my shell set to fish.

**Comment by whyfoo** [comment]
@mookino Yup, this was the issue, I had my shell set to fish.

**Comment by whyfoo** [comment]
@mookino Yup, this was the issue, I had my shell set to fish.

**Comment by whyfoo** [comment]
@mookino Yup, this was the issue, I had my shell set to fish.

**Comment by whyfoo** [comment]
@mookino Yup, this was the issue, I had my shell set to fish.
