### ISSUE TITLE
[bug] bspc config -m focused window_gap displays incorrect value.

### ISSUE THREAD

**Issue by rye761** [baskerville/bspwm#287]
Take a look at the following terminal output.

```
~  > bspc config -m focused window_gap
14 <-- default value
~  > bspc config -m focused window_gap 10
~  > bspc config -m focused window_gap
14 <--should be 10
```

It doesn't seem to change the value that is retrieved, even after setting that exact value. Only happened when I affected the monitor. If I did the desktop only, then it was fine. Window also gives correct value.

**Comment by baskerville** [comment]
There's no *window_gap* setting stored at the monitor level.

`bspc config -m focused window_gap 10` has the effect of changing the window gap setting of every desktop of the focused monitor.

**Comment by rye761** [comment]
I see that now. I feel that from a UX point of view this is kind of confusing the way it returns an inaccurate value. I'd be willing to fix, but I'm not sure if it would be more appropriate to return some kind of average, multiple values, or simply an error code.

**Comment by baskerville** [comment]
No matter what we do, the *GET* and *SET* cases should be symmetrical.

I'm tempted by the idea of just returning an error.

@Stebalien what are your thoughts on that?

**Comment by baskerville** [comment]
Returning an error is the best option: everything else is confusing.

@rye761 feel free to make a pull request.
