### ISSUE TITLE
Subscribe event when window focus is changed

### ISSUE THREAD

**Issue by daGrevis** [baskerville/bspwm#289]
Right now, when I subscribe to bspwm events like this:

     bspc control --subscribe

...and change focus to other window in the same desktop, I don't get the status update.

Is there a way to get notification for that? I tried to pass `all` to the command like this:

    bspc control --subscribe all

...but that didn't help.

Can this be added to subscribe command?

**Comment by baskerville** [comment]
The focus events are emitted as of dccb5e7.

The first command won't receive those events, because the default mask is *report*.

The second command works as expected for me.

**Comment by daGrevis** [comment]
Thanks! I'll try it at home, but I guess it should work and it didn't work for me because I wasn't using the upstream version of bspwm.

**Comment by daGrevis** [comment]
It works, case closed.

Just `bspc control --subscribe all`.
