### ISSUE TITLE
Can we have an activate_on_focus flag?

### ISSUE THREAD

**Issue by dhaines** [baskerville/bspwm#290]
It would be incredibly useful to be able to send a _NET_ACTIVE_WINDOW message to on change of focus. Is there any chance we could have an 'activate_on_focus' flag that, when enabled, would cause bspwm to automatically send such a message?

**Comment by neeasade** [comment]
If I understand correctly, you want a message when window focus changes? like `bspc control --subscribe window` or no?

**Comment by dhaines** [comment]
No. I appear to be unversed in the terminology. Here's what I'm trying to accomplish:

Certain programs (foremost in my mind rxvt-unicode with the pointerBlank resource set to true) exhibit different behavior between being merely "focused" and being the "active" window. In the rxvt example, if the client isn't activated, it will not blank the pointer, even if it has focus, until such time as the mouse is moved. I have found it possible to actually activate the focused rxvt by means of 'xdotool windowactivate $(xdotool getactivewindow)'; however, this cannot be easily shoved into sxhkd in such a way that it works no matter whether a window is being deleted, created, etc..

It would be super awesome if there were a flag that could be set that would cause the "activation" of the focused client on the change of focus so that ugly xdotool hacks could be avoided. It is my understanding that xdotool sends a _NET_ACTIVE_WINDOW event to bspwm, though I could be wrong about that.

Does that make more sense?

**Comment by baskerville** [comment]
The *_NET_ACTIVE_WINDOW* is set by the *wm* and is a single value.

**Comment by dhaines** [comment]
Makes sense.

So, having poked around, I think what I'm looking for is a call to xcb_ewmh_set_active_window() if the putative activate_on_focus flag is set. Does that make sense?

**Comment by baskerville** [comment]
No it doesn't make sense because *_NET_ACTIVE_WINDOW* is already set by *bspwm* and is the ID of the focused window.

There's at most `num_desktops - 1` active windows and one focused window.
