### ISSUE TITLE
BSPWM not recognizing Spotify

### ISSUE THREAD

**Issue by Brett99** [baskerville/bspwm#291]
I'm trying to make a rule for Spotify, but it's not working.  When I run 'bspc query -T', Spotify appears to have no name. Here's the output of bspc query -T:
```
HDMI3 1920x1080+0+0 50,0,0,0 *
	1 5 50 0,0,0,0 T - *
		V a 0.500000
			a Google-chrome Google-chrome 0x2000001 5 875x920+990+105 L --------
			H m 0.500000
				a URxvt urxvt 0x1200009 5 484x292+713+389 R -------- *
				V m 0.500000
					m URxvt urxvt 0xE00009 5 484x292+713+389 R --------
					m URxvt urxvt 0x1000009 5 484x292+713+389 R --------
	2 5 50 0,0,0,0 T -
		V m 0.500000
			m XFontSel xfontsel 0x1C0002A 5 574x181+668+444 R f------- *
			m   0x1600001 5 1810x920+55+105 R --------
	3 5 50 0,0,0,0 T -
	4 5 50 0,0,0,0 T -
	5 5 50 0,0,0,0 T -
```

Spotify is the line below XFontSel. It doesn't have a name, so I can't make a rule pertaining to it.

**Comment by Brett99** [comment]
I was able to make a rule that works with Spotify by using ```bspc rule -a "" fullscreen=on```. Spotify's name is an empty string. Is this a BSPWM or Spotify issue?

**Comment by Brett99** [comment]
I think this is a BSPWM issue and not a Spotify issue because Spotify's name is recognized by xprop.

**Comment by baskerville** [comment]
What's the output of *xprop*?

**Comment by Brett99** [comment]
```
_NET_WM_ICON(CARDINAL) = 
WM_CLASS(STRING) = "spotify", "Spotify"
WM_NAME(STRING) = "Spotify"
_NET_WM_NAME(UTF8_STRING) = "Spotify"
XdndProxy(WINDOW): window id # 0x1400002
_NET_WM_DESKTOP(CARDINAL) = 4
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		window gravity: Static
_NET_WM_PID(CARDINAL) = 5221
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "Server"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

**Comment by baskerville** [comment]
What's the output of [xlsw](https://github.com/baskerville/xlsw)?

**Comment by Brett99** [comment]
```0x0400001  ui-  NA           NA
0x0C00001  -io  Xautolock/xautolock  xautolock
0x0800003  u--  NA           xcompmgr
0x0E00001  u--  Google-chrome/google-chrome  google-chrome
0x0E00003  u--  Google-chrome/google-chrome  google-chrome
0x0E0001F  u--  Google-chrome/google-chrome  google-chrome
0x0E00022  u--  Google-chrome/google-chrome  google-chrome
0x1400001  u--  NA           NA
0x1600009  u--  URxvt/urxvt  brett@Server:~
0x1000075  u--  Google-chrome  Some glyphs don't work, some are tiny... don't know what to do. · Issue #889 · powerline/powerline - Google Chrome
0x2000001  u--  Spotify/spotify  Green Day - 21 Guns
0x100007B  u--  Google-chrome  How can I bind something to moving the scroll wheel left/right? · Issue #61 · baskerville/sxhkd - Google Chrome
0x1000001  ---  Google-chrome  baskerville/xlsw - Google Chrome
0x1800009  ---  URxvt/urxvt  brett@Server:~/Downloads/xlsw-master
0x1200004  u--  NA           NA
0x0E00030  u-o  NA           NA
0x1000046  ui-  NA           Chromium clipboard
0x0E0021E  u--  Google-chrome/google-chrome  google-chrome
0x1000078  u-o  NA           NA
0x100007C  u-o  NA           NA
0x1E00001  u--  Spotify/spotify  spotify
0x2A00001  u--  NA           NA
0x1000057  u-o  NA           NA
0x0400000  ui-  NA           bspwm
```

**Comment by baskerville** [comment]
*Spotify* sets its WM_CLASS too late. This property should exist when the map request is received.

**Comment by Froziph** [comment]
I get that Spotify should be the ones to fix this. But it worked before i updated bspwm (just did that today, haven't had time to create new configs before now). When it worked before, shouldn't it be fixable from bspwm's site? Any way to have a rule saying Spotify should spawn on a specific desktop? Some workaround?

**Comment by D630** [comment]
@Froziph A workaround for spotify is to get the _NET_WM_PID via xprop and then to grep the command name. An example for `external_rules_command`:

```sh
#!/bin/sh

id="${1?}" \
instance="$3" \
class="$2";

case "$class" in
    (foo)
        bar;;
    ("")
        unset -v _NET_WM_PID;
        . /dev/fd/0 2>/dev/null <<IN
        : \"\${$(
            xprop \
                -id "$id" \
                -notype \
                -f _NET_WM_PID 32c '=$0' \
                _NET_WM_PID;
        )}\";
IN
        case "$(ps -p "${_NET_WM_PID:?}" -o comm= 2>/dev/null)" in
            (spotify)
                echo desktop=^5;;
        esac;;
esac;
```

**Comment by navdeepio** [comment]
@D630 I'm facing the same problem, can you explain how to use your solution?

**Comment by D630** [comment]
Hey. I have come up with a much simpler solution in the meantime. Have a look at https://github.com/D630/bin/blob/master/bspwm-rules, https://github.com/D630/etc-bspwm/blob/master/etc/bspwm/bspwmrc, and https://github.com/baskerville/xdo

**Comment by navdeepio** [comment]
Thanks a ton @D630

**Comment by deadlysyn** [comment]
For posterity, this seems to be less spotify specific and more about electron apps in general? I have the same problem with slack from aur. Either way, @d630 's solution is a big help. :+1:

**Comment by exynil** [comment]
```
#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

main() {
	case "$class" in
		firefox)
			if [ "$instance" = "Toolkit" ]; then
				echo "state=floating sticky=on"
			fi
			;;
		Spotify)
			echo "desktop=3"
			;;
		"")
			wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))

			class=${wm_class[-1]}

			[[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}

			[[ -n "$class" ]]; main
			;;
	esac
}

main
```

**Comment by maniac-en** [comment]
Hey, @exynil @d630 Even I'm facing the same issue of not able to add a rule for spotify! You both have mentioned a bash script to handle the issue but I'm actually unaware of how to actually implement your solution.

Do I simply call the script in `bspwmrc` or do I need to do something else about it?

**Comment by exynil** [comment]
Hi @maniac-en, Sorry for my English.

You need to use external rules in `bspwmrc`

`bspc config external_rules_command "$ HOME / bin / bspwm-external-rules"`


You can look at my [dotfiles](https://github.com/exynil/dotfiles)

**Comment by maniac-en** [comment]
Hey @exynil Thanks for your reply!
I tried your solution, it _almost_ works for me as I wanted to put my spotify on `desktop 5` but it doesn't take me there! Here's what I'm using from your script: [spotify.sh](https://gist.github.com/maniac-en/c0100f7f7887515cb51bf0b9a35f4b33)

Do you know what might be the issue?

**Comment by exynil** [comment]
@maniac-en 
Your code works for me. There is a delay in the script `sleep 0.5`. I did it because my window class data appears after some time.
You may have a very fast or slow system. Try increasing this delay number, for example, to a second and see if it helps.

In fact, this is not a very good way (to rely on latency), but it turns out that data on the window class appears in the system some time after the program starts. I haven't found another way to quickly get the window class data yet.

P.s. I have a poor level of English, I hope I didn't make any mistakes.

**Comment by exynil** [comment]
@maniac-en 
What do you mean by "almost works"? Spotify expands to full screen, but just doesn't go to 5 workspace? Can you show me your last `bspwmrc` and `spotify.sh` (external-rules)

**Comment by maniac-en** [comment]
Your English is completely fine, don't worry about that!
I get how you're fetching the class based on delay! But the thing is other rules for `spotify` are working in my case except going to `Desktop 5`.

I say almost because out of all the rules I supplied in [spotify.sh](https://gist.github.com/maniac-en/c0100f7f7887515cb51bf0b9a35f4b33) , going to `Desktop 5` is not working!

I tried changing the delay to 1, 1.5, 2, and even removing it, but no luck!

Here's my [bspwmrc](https://gist.github.com/maniac-en/295bbb068ab086d7448af71925f125d6) which has the external rule for spotify!

**Comment by exynil** [comment]
@maniac-en 
I think I understand what your mistake is.
Your desktop names are referred to as:

`bspc monitor -d I II III IV V VI VII VIII IX X`

when creating rules, you should rely on these names.

`echo "state=fullscreen desktop=V follow=on"`

Hope this helps you!

**Comment by maniac-en** [comment]
@exynil 
Oh ya that was it! Everything works now.
I just shifted to using `BSPWM` and therefore I was using the config provided in `/usr/share/doc/bspwm/examples/bspwmrc`.

Thankyou so much for help!

**Comment by exynil** [comment]
@maniac-en You’re welcome

**Comment by lyonelz96** [comment]
Alright so spotify has been a mother to work with the bspwm rules but I managed to find a workaround. 

1. Fixing spotify going to the right workspace on startup:

At the top of my bspwmrc I launch polybar then I have a few programs I want to start one of them being spotify:
`spotify &`

Then I put this command:
`wmctrl -r Spotify -t 6`

This pretty says "Take spotify and put it in the 6th workspace (Starting the count from 0, so really the 7th workspace)

You can replace the 6 with whatever workspace you want spotify to go to.

2. Fixing the spotify rule

I just used @d630 script he posted in 2016 and put this on my bspwmrc.
`bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"`

And now my spotify goes to its assigned workspace at startup and if for whatever reason I close it during the session, if I reopen it it's going to to the assigned workspace.

Phew...

**Comment by DashCruft** [comment]
I can fully confirm @lyonelz96 's solution and @d630 's script still work till this day.

Even better, @d630 's script lack focus and follow so when you open the window, it doesn't switch workspaces.

To add that feature, simply add `follow=on` and `focus=on` after `echo desktop=^5`
So it looks like this: 

```sh
echo desktop=^5 follow=on focus=on;;
```
Instead of 

```sh
echo desktop=^5;;
```

**Comment by BlueInt32** [comment]
A little note to anyone struggling to make @d630's script work: do not forget to add execution permissions to the bspwm-rules file. I have been stuck on this for like an hour... :smirk:

**Comment by vaygr** [comment]
My problem with external rules is that on every window launch the script is going to be executed, which seems much heavier on resources. I ended up writing a devilspie2 rule after taking a look at https://github.com/dasJ/spotifywm/issues/8:

```lua
-- Move spotify to the designated desktop
local spotify_desktop = 5

if (get_application_name() == "Untitled window" and get_window_name() == "Untitled window") then
  if get_process_name() == "spotify" then set_window_workspace(spotify_desktop) end
end
```

**Comment by PolGZ** [comment]
Neither of the two solutions offered by @d630 nor @exynil seem to work for me. Even copy-pasting their scripts/config files.

I have `bspc config external_rules_command "$HOME/.config/bspwm/scripts/external_rules.sh"` on my bspwmrc and the `external_rules.sh` script has execute permissions. Any idea what should I test?

Debian stable + spotify flatpak

**Comment by exynil** [comment]
Hello @PolGZ . I checked my solution is still working. If you still haven't solved the problem. Send me your bspwmrc and bspwmrc_extarnal_rules.sh file.

**Comment by bo1929** [comment]
They have finally fixed this. The latest version of the Spotify client now sets everything on time.
