### ISSUE TITLE
2 monitors, changing layout with xrandr

### ISSUE THREAD

**Issue by Ploppz** [baskerville/bspwm#292]
I'm experimenting with xrandr + laptop + monitor.
Initially, I placed the monitor left of the laptop: `xrandr --output HDMI1 --left-of LVDS1`. My laptop screen has 4 virtual desktops and the monitor has 1.
Something strange happened when I ran the same command again but with `--right-of` instead. When I now cycle through the desktops using `bspc desktop -f {prev,next}`, it does so on both monitors, even though `HDMI1` only has one desktop. Furthermore, all the windows I had open before this, are scattered around both the 4 'fake' virtual desktops of my external monitors (which in fact only had 1) and the 4 virtual desktops of the laptop monitor. After doing something I can't really remember - but probably just switching between monitors and doing some unrelated simple operations- firefox suddenly just changed monitor. All in all the behaviour is rather erratic and hard to pinpoint.

I hope someone can get anything out of this strange behaviour.

**Comment by baskerville** [comment]
It's very confusing, indeed. If you manage to reach this incoherent state again, maybe you could post the output of `bspc wm -d`?
