### ISSUE TITLE
Ordering of monitors in --subscibe

### ISSUE THREAD

**Issue by Ploppz** [baskerville/bspwm#293]
When calling `bspc control --subscribe`, the way in which the monitors appear has a certain ordering that is not dependent on the layout.

I'm using the output of this command as a basis to keep track of which monitor is in focus in order to change the colour of the corresponding part of `bar` (lemonbar) shown on each monitor, and to write monitor-specific information. I then pass this information to `bar`. I have for example an array `desktops` which is indexed by monitor number (where monitor appears in `bspc control --subscribe`), and contains desktop infomation for each monitor. Then I write something like `%{S0} ... desktops[0] ... %{S1} ... desktops[1] ... ` to `bar`.

However, `bar` has a ordering of monitors from left to right and top to bottom in the layout. I would like bspwm to have the same ordering. Is this possible?

**Comment by baskerville** [comment]
See `monitor --swap`.
