### ISSUE TITLE
Mouse jumps to center when clicking on different monitor

### ISSUE THREAD

**Issue by justbuchanan** [baskerville/bspwm#296]
I have the `pointer_follows_monitor` config set to `true` in my bspwmrc so that when I use keyboard shortcuts to focus a window on a different monitor, the mouse jumps to the center of that monitor.

My issue is that sometimes the mouse jumps to the center when I've used the mouse to click on a window in a different monitor.  It seems to only happen when I click on a google chrome window, so I wonder if it has something to do with chrome's multi-process model.

I'd be glad to take a look at fixing this and sending a PR if you can give me a starting point of where to look for the issue.  Thanks!

**Comment by neeasade** [comment]
Are floating windows involved in this in some way? for example if you float a window and drag it to another monitor the window is still tied to the first monitor, and a focus on it would also be a focus on the initial monitor, causing the cursor to jump all the way across.

**Comment by baskerville** [comment]
@justbuchanan Diffs for normal/chrome windows of `xev -root` and `bspc subscribe monitor desktop node` might be helpful.
