### ISSUE TITLE
Ability to target motion recorder

### ISSUE THREAD

**Issue by rr-** [baskerville/bspwm#299]
Suggestion from #298 to use `xdo lower` works nicely, but it disables interaction with panel. To regain this interaction, one needs to do `xdo lower` for motion recorder as well. Right now the only way to obtain motion recorder's window ID is to use `xwininfo`'s picker (this can't be used in scripts), or with ` $(( $(xdotool search --pid $(pidof bspwm)) + 2 ))` (specifically +2 for first monitor, +3 for second monitor and so on) that might break at any time.

It would be beneficial for scripts etc. to be able to match motion recorder by class name.

**Comment by baskerville** [comment]
The motion recorder is an internal implementation detail and shouldn't be dealt with.
