### ISSUE TITLE
Ruld, Rulc, bspwm_rules

### ISSUE THREAD

**Issue by esn89** [baskerville/bspwm#300]
Hi there, I haven't used bspwm in about 8 months and I guessed a lot has changed, namely the rules.

I migrated old dotfiles over and majority of it seem to work, except my rules and external rules.
I noticed now, the [rulc](http://ix.io/lGg/#n-LINENO), [ruld](http://ix.io/lGh/#n-LINENO), [rule_command](http://ix.io/lGi/#n-LINENO) and [bspwm_rules](http://ix.io/lGj/#n-LINENO)
are no longer in the main repo of Baskerville.

How can I get my old external_rules file, and the rules in my bspwmrc working again?
Here is my [.xinitrc](http://ix.io/lGk/#n-LINENO) for reference

**Comment by baskerville** [comment]
The built-in *rule* command was reinstated and *rule_command* was replaced with *external_rules_command* (see the manual and `examples/external_rules`).

**Comment by esn89** [comment]
So, to clarify: 
I don't need the rulc, and ruld command in my xinitrc, not the scripts themselves. 

For my external rules, do I leave them as is? At the moment, I don't see a file named "external_rules_command". 

Do I now put all the rules in the bspwmrc? And also. Which rule command should be in the xinitrc?
