### ISSUE TITLE
Compton fades in when fullscreening a video and fades out when unfullscreening a video

### ISSUE THREAD

**Issue by reportados123** [baskerville/bspwm#303]
Hi, after the new recent changes to bspwm, compton has started to fade in when you fullscreen a video, for example on youtube, and fade out when you exit the fullscreen when watching a video.

Before the changes, I would watch a video on youtube, fullscreen it, and no fading in would occur by compton. Likewise, I would exit fullscreen when watching a video on youtube, and no fading out would occur.

Also, the fading in and out would be quite lengthy, about 1 second. It's not the same speed as if you would switch desktops.

Interestingly enough, this only occurs on firefox (not chromium, which I've tested) and using the html5 player on youtube. If I were to use flash, this would not occur. I've tested this on facebook videos as well, and the fading in and out occurs. I believe this problem only occurs when an html5 video is involved.

To reproduce:
1. Open firefox
2. Go to youtube and watch a video (make sure the video is html5)
3. Click fullscreen
4. Fading in should occur (also should be quite lengthy than usual)
5. Press ESC
6. Fading out should occur (also should be quite lengthy than usual)

I'm on Arch Linux x86_64, with packages up to date as of today.
Firefox is version 42.0-1
bspwm is git version, locally compiled and installed (up to commit f08e7073a21cc42531acfad194d9478292c01ef8, which is the latest as of today)

This is my .compton.conf
http://ix.io/lTy

EDIT: I also tested firefox in safe mode and the problem still occurs. Not only that, but if I were to fullscreen firefox itself by pressing super + f, which is set to do bspc window -t fullscreen, and watch a video, the fading in and out would NOT occur. Therefore, this problem only occurs when firefox is tiled or floating.

**Comment by baskerville** [comment]
Could you identify the problematic commit (via `git bisect`)?

**Comment by reportados123** [comment]
Sorry for the false alarm, it appears it isn't bspwm's fault. The new update to firefox 42 added a stupid feature that made fullscreening html5 videos fade in and out with ridiculously long default transition durations. The setting in `about:config` is called `full-screen-api.transition-duration.enter` and `full-screen.api.transition-duration.leave`

I jumped to conclusions thinking it was bspwm's fault when I updated my packages, I didn't think it would be firefox's fault until now.

**Comment by vyp** [comment]
@reportados123 One good way I think to potentially rule out the window manager is to try and test it out on another window manager if possible (such as i3 or something). So if it happens in both, then it's probably an application specific issue. Either way I don't blame you for jumping to the conclusion that it might be compton/window manager related, because I don't think it's normal for applications to mess with window effects (transitions/fading) anyway.
