### ISSUE TITLE
floating and fullscreen rules have no effect after 6fb0469

### ISSUE THREAD

**Issue by blendi-93** [baskerville/bspwm#306]
hi,
in the current version (some) rules have no effect.

    bspc rule -a "*" floating=on

launch anything (urxvt in my case).
  => urxvt launches, but in tiled mode.

**Comment by baskerville** [comment]
The syntax changed (see the manual) `floating=on` is now `state=floating`.

**Comment by blendi-93** [comment]
ok, sry for steeling ur time.

and thx for ur great wm.
