### ISSUE TITLE
Pointer resize no longer working for tiled windows.

### ISSUE THREAD

**Issue by kstolp** [baskerville/bspwm#307]
I have the following sxhkd keybindings:
```
~button1
	bspc pointer --grab focus

super + button{1-3}
	; bspc pointer --grab {move,resize_side,resize_corner}

super + @button{1-3}
	bspc pointer --ungrab
```
When I try to resize tiled windows, the commands get sent to bspc, but nothing happens. I am still able to resize windows by using the ```bspc window --edge``` command. I can also use the mouse to resize pseudo-tiled windows. I just seems to not be working with tiled windows.

Using f17cee7afdb710576f15d75b66e940bd26e9a4db

**Comment by baskerville** [comment]
Fixed by 92bbc49.
Thanks for reporting.
