### ISSUE TITLE
Some windows no longer receiving focus properly

### ISSUE THREAD

**Issue by rosslovas** [baskerville/bspwm#309]
The two applications I noticed it with are `baka-mplayer` and `keepassx2`, which I think both use Qt5 so that may have something to do with it.

If I go to a field in either of these applications that takes keyboard input and start typing it works just fine, but then if I click away e.g. into my browser address bar, and then back into the input field and start typing again, the text is entered in my browser address bar despite the browser not being in focus. I haven't been able to find any way to properly get the focus back into the input field so that I can type in it again.

I isolated the problem to having been caused by this commit 36f740f98b660af90389469b4fdf83011845f37c and found that adding classnames for these programs to ICCCM_FOCUS_EXCEPTIONS fixes it, but I feel like that might not be such a good long term solution, especially if it is a Qt5 thing.

**Comment by baskerville** [comment]
Could you try the *icccm-input-focus* branch?

**Comment by rosslovas** [comment]
Played around in that branch for 5 minutes and everything appears to work fine, that seems to have fixed it.

**Comment by baskerville** [comment]
Thanks for reporting.
