### ISSUE TITLE
`window -t` still behaves as toggle

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#310]
While window states are real states now, and the man page sets that `bspc window -t` is supposed to *set* the state, it still behaves as a toggle. This by itself isn’t so inconvenient, if it were not for the fact that `=on|off` are no longer accepted. So it seems one cannot easily set a window to floating regardless of whether it already floats (as a workaround, scripts would have to manually check the state via `bspc query`).

Maybe one could do either one of the following:
1. Make `window -t` really set the target state, and do nothing if the target state is already set.
2. Leave it as a toggle, but continue to allow `=on|off` on states.

**Comment by baskerville** [comment]
I could do *1.* but users will certainly complain about not being able to *toggle* the *state* anymore.

If I do *2.*, then it might induce the ill-founded conception that states are booleans.

What I could do is to provide a boolean setting called `auto_state`: when set it would interpret consecutive identical `--state` messages as a will to switch to the previous state.

**Comment by eigengrau** [comment]
> What I could do is to provide a boolean setting called auto_state: when set it would interpret consecutive identical --state messages as a will to switch to the previous state.

Hmm, this seems to go in a different direction, but might be useful nonetheless. It would still be nice to have an interface which applies some state to a window and does nothing in case the window is already in that state.

> If I do 2., then it might induce the ill-founded conception that states are booleans.

Maybe an additional switch for `bspc window` for additional convencience? Semantically, it would `--do-nothing-if-already-this-state`. Or, since the man-page currently says that `-t` *sets* the state: Maybe one could have two versions of the switch. The old `-t`, or `--toggle-state`; and something like `--set-state`, where the latter will do nothing in case the state is already set.

The reason this came up for me is that I have an sxhkd binding which will get a geometry from slop, and will then float the currently focused window with the given geometry. If the window was already floated, it would just apply the geometry. Currently, I have to `bspc query` if the window is already floated, and then not fire `-t floating`, because otherwise, the floated window will return to tiling instead of being resized.

**Comment by baskerville** [comment]
I decided to go with *1.*: it will help users realize that something changed.

**Comment by blendi-93** [comment]
mby somone else find this usefull (little script to get to toggle back):
paste this into  `~/.config/bspwm/toggle_state.sh`

    #!/bin/bash
    state_new=$1
    state_old=$(bspc query -T -d| grep "\*"| tail -1| rev| cut -c 9| rev)
    #-=tabbed; f=floating; F=fullscreen
    if [[ $state_old == $state_new ]]; then
    	#echo "echo old == new => back to tiled"
    	bspc window -t tiled
    else
    	case $state_new in
    		"F")
    			#echo "want a fullscreen window"
    			bspc window -t fullscreen
    			;;
    		"f")
    			#echo "want a floating window"
    			bspc window -t floating
    			;;
    		*)
    			#echo "setting window tiled"
    			bspc window -t tiled
    			;;
    	esac
    fi

and edit ur `~/.config/sxhkd/sxhkdrc`
so it contains for example:

    super + {s,f}
    	~/.config/bspwm/toggle_state.sh {f,F}

**Comment by baskerville** [comment]
I've got a slightly more compact solution:
```
super + {s,f}
	state={floating,fullscreen}; \
	bspc query -W -w "focused.$\{state\}" && state=tiled; \
	bspc window -t "$state"
```
