### ISSUE TITLE
Active desktop not correctly indicated anymore after restarting bspwm

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#311]
After upgrading from f08e707 to 54d9215, I’ve noticed that reloading bspwm (via `query -{T,H,S}` and `restore`) will now make lemonbar show the wrong desktop as active. I. e., say we have: `1 2 [3] 4`. Now, after saving and restoring state, lemonbar, wmctrl, etc. will indicate that desktop 1 is active, but bspwm still shows the windows from desktop 3, and cycling through desktops will yield odd results. Only after all desktops have been cycled through, the indicated active desktop will be in sync with the actual active desktop again.

**Comment by eigengrau** [comment]
This doesn’t only seem to affect the relative ordering of desktops. Some parts of bspwm seem to believe that desktop 1 is active, while others believe desktop 3 is focused. Specifically, when desktop 1 and 3 have different window gaps set, bspwm will continue showing the windows from desktop 3, but the window gap settings from desktop 1 will be applied to any new windows.

**Comment by baskerville** [comment]
First let me say that if you're upgrading *bspwm* and the `query -T` format changed (and that's the case), then you can't use the *loop* method to restart *bspwm*.

Can you identify the problematic commit with `git bisect`?

**Comment by eigengrau** [comment]
> First let me say that if you're upgrading bspwm and the query -T format changed (and that's the case), then you can't use the loop method to restart bspwm.

Yea, sorry, I was unclear on this. I did completely log out after upgrading. The loop problem only manifested after that.

> Can you identify the problematic commit with git bisect?
The issue first appears in f28f334.

**Comment by eigengrau** [comment]
Since the behavior is a bit awkward to describe, here’s a [video](https://ptpb.pw/Gk49.mkv).

**Comment by baskerville** [comment]
Could you do the following:

1. Before restarting: `bspc query -T > tree_a`.
2. After restarting: `bspc query -T > tree_b`.
3. `diff -u tree_a tree_b`

And post the output of step *3*?

**Comment by baskerville** [comment]
Should be fixed by e8ee82c.

**Comment by eigengrau** [comment]
Ah, you were took quick for me…

```
--- before	2015-11-12 14:14:09.034641940 +0100
+++ after	2015-11-12 14:14:17.872289348 +0100
@@ -1,10 +1,10 @@
 DVI-1 1920x1080+0+0 24,0,0,0 *
-	web 2 24 0,0,0,0 T
+	web 2 24 0,0,0,0 T *
 		m XTerm xterm 0x1E00022 2 484x316+716+380 R- -- ---- *
 	msg 2 24 0,0,0,0 T
 	emacs 2 24 0,0,0,0 T
-	I 2 42 0,0,0,0 T *
+	I 2 42 0,0,0,0 T
 		m Termite termite 0x2000003 2 770x890+573+93 R- -- ---- *
 	II 2 42 0,0,0,0 T
 	III 2 42 0,0,0,0 T
 	IV 2 42 0,0,0,0 T
```

I’ll give e8ee82c a shot.

**Comment by eigengrau** [comment]
That did it! Thanks! 😸
