### ISSUE TITLE
border_width on floating windows

### ISSUE THREAD

**Issue by Swoorup** [baskerville/bspwm#312]
Is there a way to have different `border_width` for normal tiled windows and floating windows. The reason is that I would like floating windows to not have any borders whereas tiled windows to have borders supported.

**Comment by baskerville** [comment]
Yes:
```shell
#! /bin/sh

BORDER_WIDTH=$(bspc config border_width)
FLOATING_BORDER_WIDTH=0

bspc control --subscribe window_state | while read msg monitor desktop wid state value ; do
	if [ $state = "floating" ] ; then
		if [ $value = "on" ] ; then
			bspc config -w $wid border_width $FLOATING_BORDER_WIDTH
		else
			bspc config -w $wid border_width $BORDER_WIDTH 
		fi
	fi
done
```

**Comment by Swoorup** [comment]
Are you sure that works? I am using version 0.9 from archlinux community repo. I get no changes. Curiously I tried the following. Doesn't look right. 

I also tried the latest git version. But bspwm is simply not starting. I am using xorg server 1.18

```bash
bspc control --subscribe window_state | while read msg monitor desktop wid state value ; do
echo $msg
done

Output:
WmeDP1:OI:fII:fIII:fIV:fV:LT:MVGA1:ODesktop2:LT
WMeDP1:OI:fII:fIII:fIV:fV:LT:mVGA1:ODesktop2:LT
WmeDP1:OI:fII:fIII:fIV:fV:LT:MVGA1:ODesktop2:LT
WMeDP1:OI:fII:fIII:fIV:fV:LT:mVGA1:ODesktop2:LT
WmeDP1:OI:fII:fIII:fIV:fV:LT:MVGA1:ODesktop2:LT
```

**Comment by baskerville** [comment]
It works as of d98c3d1.

**Comment by chuckdries** [comment]
Hey guys,
This doesn't seem to work anymore as the command syntax has changed and control is no longer a domain. Can anyone point me to the updated subscribe command I need? I'm having a lot of trouble figuring out which event to subscribe to.
