### ISSUE TITLE
Example config broken

### ISSUE THREAD

**Issue by Lesik** [baskerville/bspwm#314]
Hey,

I'm writing my own config for `lemonbar` to work with `bspwm`, trying to look into code of others as little as possible. But the parsing of `bspc control --subscribe` was too complicated for me, I had to look into the [example parser](https://github.com/baskerville/bspwm/blob/master/examples/panel/panel_bar).

If I understand the code correctly, for each `$item` the `$wm_infos` is being overwritten **before** it is anyhow `echo`-ed or `printf`-ed. So that means any output before the last `$item` is being overwritten, the only one that is left is the last `$item` – the only thing you see on the panel is the last workspace.

I presume this is not the wanted behaviour (you want to see more than just the last workspace on the panel, right?). The `$wm_infos` has to be concatinated, for example like this:
```
wm_infos+="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
```

It's just 9 lines that need to be changed so I was too lazy for a pull request, I'd be happy if you could fix this for future readers/viewers/self-coders. :)

**Comment by baskerville** [comment]
It isn't overwritten: each of the 9 lines is a concatenation.

In the shell, the concatenation of variables `a` and `b` is `"$a $b"`.

**Comment by Lesik** [comment]
Ah yes, of course. I didn't notice the `${wm_infos}` concatenation. My bad.
