### ISSUE TITLE
update bspwm/examples/sxhkdrc

### ISSUE THREAD

**Issue by dicktyr** [baskerville/bspwm#315]
assuming recent code changes broke the example config

I was puzzled by the pointer bindings
(to move/resize windows with the mouse)

	super + button{1-3}
		; bspc pointer -g {move,resize_side,resize_corner}
	
	super + @button{1-3}
		bspc pointer -u

which stopped working after an update
but this works for me

	super + button{1-3}
	    bspc pointer -g {move,resize_side,resize_corner}
	
	super + !button{1-3}
	    bspc pointer -t %i %i
	
	super + @button{1-3}
	    bspc pointer -u

**Comment by baskerville** [comment]
The current bindings work fine here.

Your build of *sxhkd* is outdated.

**Comment by dicktyr** [comment]
I'm sorry
I mistakenly assumed that both the Void repository
(bspwm and sxhkd were out of sync)
and Arch documentation were up to date
