### ISSUE TITLE
Add a way to get window state on demand

### ISSUE THREAD

**Issue by trollhase** [baskerville/bspwm#320]
Ive just now updated my bspwm installation and updated my configurations just to find that there is no more way to simply toggle floating due to the new window state system.
As I often use the ability to switch windows between tiled and floating window states.

May it be too much to request a possibility to get the current window state apart from subscribing to events?

**Comment by baskerville** [comment]
Have you tried this:
```
super + {p,s,f}
	state={pseudo_tiled,floating,fullscreen}; \
	bspc query -W -w "focused.$\{state\}" && state=tiled; \
	bspc window -t "$state"
```
?

**Comment by trollhase** [comment]
Perfect. Sorry for bothering, I didn't think of the query command..
