### ISSUE TITLE
Quirks with new WINDOW_SEL

### ISSUE THREAD

**Issue by Chrysostomus** [baskerville/bspwm#323]
The new provided functions are great, but the options with ! seem to have quirks. For example:
bspc query -W -w biggest.tiled.!automatic
yields error: zsh: event not found: automatic

This happens from command line with bash and zsh. Not with dash though. Also, they seem to work in bash scripts.

Why do they fail in interactive mode of bah an zsh? This makes testing scripts somewhat harder.

**Comment by baskerville** [comment]
Because *!* is a special character for most shells in interactive mode.

You can use `'biggest.tiled.!automatic'` or `biggest.tiled.\!automatic` instead.

**Comment by Chrysostomus** [comment]
Cool. Thanks!
