### ISSUE TITLE
Keeping old fullscreen keybind

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#326]
If I were trying to keep the old fullscreen behavior in place how would I do so? like have the window remember if it was tiled or floating before it was made fullscreen? would be nice if I could just toggle fullscreen to 'off' - when another window gets focus in the same desktop fullscreen window changes state to what it was previously. 

Side note for others you can keep the 'toggle' feel if you want in your sxhkd with:
``` bash
super + s
    bspc query -W -w focused.tiled && state=floating || state=tiled; \
    bspc window -t $state
```

**Comment by neeasade** [comment]
Ah! you can totally do this, because a window is considered both fullscreen and tiled || floating at the same time. 

``` bash
◾ bspc window -t fullscreen
◾ bspc query -W -w focused.tiling
0x1800003
◾ bspc query -W -w focused.fullscreen
0x1800003
```

hm, the following should work but does not:
``` bash
super + f
    if bspc query -W -w focused.fullscreen; then \
        bspc query -W -w focused.floating && state=floating || state=tiled; \
        bspc window -t $state; \
    else \
        bspc window -t fullscreen; \
    fi
```

I believe I have a bug, when going to fullscreen from a floating window (it is still read as tiling window):
``` bash
◾ bspc query -W -w focused.tiling
0x1800003
◾ bspc query -W -w focused.fullscreen
0x1800003
◾ bspc query -W -w focused.floating
! 
```

**Comment by baskerville** [comment]
No, `.tiling` isn't a valid modifier and will be rejected as of 98e30c5.

The correct binding is:
```
super + f
	state=fullscreen; \
	bspc query -W -w "focused.$state" && state=$(bspc query -T -w | jshon -e client -e lastState -u); \
	bspc window -t "$state"
```

**Comment by neeasade** [comment]
ah crap, I had even corrected that earlier. still exploring the json information as well. thank you.
