### ISSUE TITLE
Triggering "Urgent" state

### ISSUE THREAD

**Issue by bcspragu** [baskerville/bspwm#327]
Is there a way, using `bspc` to set the state of a desktop to 'urgent'? Or should this be done at the X level?

**Comment by blendi-93** [comment]
from the manpage.

    WINDOW FLAGS
           locked
               Ignores the window --close message.
    
           sticky
               Stays in the focused desktop of its monitor.
    
           private
               Tries to keep the same tiling position/size.
    
           urgent
               Has its urgency hint set. This flag is set externally.

**Comment by baskerville** [comment]
A desktop is considered *urgent* when it holds at least one urgent window.
