### ISSUE TITLE
Use last_{state,layer} more consistently

### ISSUE THREAD

**Issue by d125q** [baskerville/bspwm#328]
What was the rationale behind [this commit](https://github.com/baskerville/bspwm/commit/15dda1659e911c40036cf3e22e3d8b902ba030c6)?  Also, why doesn't [`set_layer`](https://github.com/baskerville/bspwm/blob/master/window.c#L390) remember the last layer?  In my opinion this is very inconsistent.

As to why it is inconsistent: a toggle is a toggle between the current and the previous state.  Not predetermined states/layers.

**Comment by baskerville** [comment]
The commit is based on some user feedback received in #310.

I'm letting the user choose what *toggling* means in the world of states.

The best implementation of the toggling concept would probably require an history of states, not just the last state.

`last_layer` is only used by `set_fullscreen`.

**Comment by d125q** [comment]
Thanks a lot for getting back to me.  I saw #310, but I still think that EWMH handling was fine as it was.  That issue specific to `bspc window -t`, not to EWMH.

I noticed that `last_layer` is only used in `set_fullscreen`, but it should still be updated in `set_layer`.  Else `set_fullscreen` doesn't work well (i.e. the last layer _will_ be incorrect).

I also think that [`manage_window`](https://github.com/baskerville/bspwm/blob/master/window.c#L66) should remember the initial state and layer as the last ones, e.g. have something like:
```c
	// ...
	if (f != NULL && f->client != NULL && csq->state != NULL && *(csq->state) == STATE_FLOATING) {
		c->layer = f->client->layer;
	}

	if (csq->layer != NULL) {
		c->layer = *(csq->layer);
	}

	c->last_layer = c->layer;
	set_state(m, d, n, csq->state != NULL ? *(csq->state) : c->state);
	c->last_state = c->state;
	// ...
```

**Comment by reportados123** [comment]
I agree that manage_window should remember the initial state and layer because I have a couple of rules to set certain programs to open as floating, but when I toggle their states, for example, from floating to fullscreen, it goes fullscreen to tiled. I looked at bspc query and noticed that the lastState was set as tiled even though the initial state was floating.

**Comment by d125q** [comment]
@baskerville I thought about this some more and I would like to share a few thoughts.  My original issue was rather unfounded (although I think it would be wise to rename `last_layer` to something like more descriptive like `layer_before_fullscreen` or something), and I apologize for that.

A few points that I still think are valid are:

1. `manage_window` remembering the initial state (layer would not be necessary);
2. Remember the state-before-fullscreen for fullscreen windows just like the layer is remembered.  That way a user can have a floating Firefox window, fullscreen it, and have it go back to floating (rather than tiling) when fullscreen is off.

What do you think?

**Comment by baskerville** [comment]
Agreed.

I will fix 1. and 2. ASAP.
