### ISSUE TITLE
xfce4-panel covers fullscreen window

### ISSUE THREAD

**Issue by jhyeon** [baskerville/bspwm#331]
After updating bspwm to commit 0d98547 (from a previous commit a few months old), a fullscreen window (of the mpv player for instance) appears not above xfce4 panels but below them.  This was not the case with the previous commit.

**Comment by baskerville** [comment]
Cf. https://github.com/baskerville/bspwm/issues/301#issuecomment-152870406.

**Comment by jhyeon** [comment]
Thanks for the tip!  Now the fullscreen window appears above the panels.  However, I have another issue that I did not have before: the panels are below every window.  Is there a way to put the panels below the fullscreen window but above the tiled (and floating) windows?

**Comment by baskerville** [comment]
Doesn't your panel reside in a padding space?

**Comment by jhyeon** [comment]
One panel does.  The other is in the auto-hide/show mode which is difficult to use if the other windows cover it.

**Comment by baskerville** [comment]
You could listen to the *window_state* event and call `xdo above|below` accordingly.
