### ISSUE TITLE
Reload bspwm

### ISSUE THREAD

**Issue by Fnux** [baskerville/bspwm#332]
Hi !

Is there a way to reload the bspwm's config ?
Actually I have to use `bspc quit` and `startx`.

**Comment by baskerville** [comment]
The config is an executable, generally a shell script.

So, to reload your config, just run `/path/to/your/config`.

**Comment by valsoray17** [comment]
What if the config also starts other bins like sxhkd or compton. In this case someone might end up with several instances of those programs.

**Comment by neeasade** [comment]
that would be on you to modify your config to check if processes are running and launch them if not running, or handle them in another script, etc..

**Comment by valsoray17** [comment]
I thought that was the way, but had some doubts. Thanks for confirmation.

**Comment by Coder-Takshil** [comment]
> that would be on you to modify your config to check if processes are running and launch them if not running, or handle them in another script, etc..

Uh how would u do that anyway?

**Comment by neeasade** [comment]
@Coder-Takshil eg 

```
if ! pgrep firefox; then
  setsid nohup firefox &
fi
```
