### ISSUE TITLE
Monocle layout and focus when node is removed

### ISSUE THREAD

**Issue by d125q** [baskerville/bspwm#333]
Consider the following scenario, done exactly in this order on a desktop with monocle layout (all clients are tiled and on normal layer; I will use Firefox and HexChat as examples):

1. Open Firefox;
2. Open HexChat (it is now focused);
3. Go back to Firefox;
4. Open a dialog in Firefox (i.e. ctrl + s to save something);
5. Close the dialog;
6. The focus goes not to Firefox, but to HexChat.

Is the focus history somehow malfunctioning?  I cannot tell.

**Comment by baskerville** [comment]
I can't reproduce.

I might be useful to post the content of your *bspwmrc*.

Is there any inconsistency in the output of `bspc control --subscribe monitor desktop window`?

**Comment by d125q** [comment]
Sorry, false alarm.  I had set `bspc control --record-history off` in my command for switching between windows.  Man, I suck.  Sorry again.
