### ISSUE TITLE
Possible regression from 0.9

### ISSUE THREAD

**Issue by NicolasCARPi** [baskerville/bspwm#335]
Hello,

I was trying to setup some rules in ~/.config/bspwm/bspwmrc and it didn't work with latest from git. I tried with the repo version (0.9) and it worked.

So I'm wondering if there is not a regression somewhere, or maybe the syntax changed ?

You can try with this rule : 
`bspc desktop 3 -t floating=on`
With git version : it does nothing
With 0.9 it works as expected.

Can you reproduce this ?

Thanks for the great wm ;)
Regards,
~Nico

**Comment by baskerville** [comment]
There's no `desktop -t` anymore. The new event system is powerful enough to allow this feature to be externalized : https://github.com/baskerville/bspwm/issues/325#issuecomment-160435323.

**Comment by NicolasCARPi** [comment]
Ah ok, thank you. Please make sure it is indicated in the documentation for the future release :)

Cheers.
