### ISSUE TITLE
Create monitor for specified rectangle

### ISSUE THREAD

**Issue by arkrost** [baskerville/bspwm#337]
Hi!

Is it possible to add support for creating monitors. As I understand monitor is simply rectangle that contains desktops. Moreover there is a method `make_monitor(xcb_rectangle)`. So it is needed cli to add or remove monitor.

The use case is very simple. I want to separate my screen in two monitors. Use one of them actively. The other one would be used for notification purposes. I expect complex layout on monitor with notifications so I don't want to mess with sticky windows.

**Comment by baskerville** [comment]
You can already create fake monitors by loading an hand-written state via `restore -T`.

Here's an example of JSON state that contains three fake monitors:

```json
{
	"monitors":
	[
		{
			"name": "ALPHA",
			"rectangle": {"width": 1920, "height": 720, "x": 0, "y": 0},
			"desktops": [{"name": "I"}, {"name": "II"}, {"name": "III"}, {"name": "IV"}]
		},
		{
			"name": "BETA",
			"rectangle": {"width": 1560, "height": 360, "x": 0, "y": 720},
			"desktops": [{"name": "V"}, {"name": "VI"}, {"name": "VII"}]
		},
		{
			"name": "GAMMA",
			"rectangle": {"width": 360, "height": 360, "x": 1560, "y": 720},
			"desktops": [{"name": "VIII"}, {"name": "IX"}, {"name": "X"}]
		}
	]
}
```

Please note that a monitor must contain at least one desktop.

**Comment by arkrost** [comment]
Yes, it is not that usable. I wish there were 2 more commands for `bspc` (`add_monitor(rect)` and `remove_monitor`). IMO, it would be way better than writing state by hand.

**Comment by neeasade** [comment]
Wow, I had not considered using restore -T in that way, good to know. What @arkrost is looking for may be related to https://github.com/baskerville/bspwm/issues/277 (full screen/define window 'areas') for the same purpose?

**Comment by baskerville** [comment]
@arkrost added as `wm -{a,r}`.
