### ISSUE TITLE
[featurerequest] option to use preselection border again

### ISSUE THREAD

**Issue by blendi-93** [baskerville/bspwm#340]
i dont like the new areas and would prefer to keep the border color to indicate preselection ratio and dir.

**Comment by baskerville** [comment]
I'm not sure if you've noticed, but you can preselect internal nodes (`node @parent -p east`). It makes the border based feedback rendering approach useless.

I would recommend, though, to make the preselection feedbacks semi-transparent.

This can be achieved with the following *compton* rule:
```
opacity-rule = [ "63:class_g = 'Bspwm' && class_i = 'presel_feedback'" ];
```
where *63* is the opacity percentage.

**Comment by blendi-93** [comment]
y i could use compton but the lack of compositting was one major reason for a minmal vm.

**Comment by jamietanna** [comment]
I'd like to :+1: this; I've just upgraded to the latest version, and although I appreciate the new feature, I'd also love to be able to only use borders - could this be possibly done via a config variable/compile-time change? I realise using Compton is viable, but it'd be nice not to have to install it to get the old functionality back

**Comment by Chrysostomus** [comment]
This preselecting internal nodes seems visually interesting, but what does it actually do? I haven't been able to transplant new windows into this presel. It mainly seems to just prevent focusing windows under it. What is it for?

**Comment by baskerville** [comment]
Preselection was previously limited to leaves and now it isn't.

The transplantation will fail between a node and its immediate ancestor though.

Here's an example use case of generalized preselection:
```
+----------------------+                                +-----------------------+
|         |            |                                |       |       |       |
|         |     b      |         node @/ -p west        |       |       |       |
|         |            |                                |       |       |       |
|    a    |------------|           -------->            | > c < |   a   |   b   |
|         |            |                                |       |       |       |
|         |   > c <    |           node -n @/           |       |       |       |
|         |            |           node @/ -B           |       |       |       |
+----------------------+                                +-----------------------+

       STATE X                                                  STATE Y
```

**Comment by Chrysostomus** [comment]
Thanks for the explanation!

**Comment by neeasade** [comment]
holy shit this is awesome. very hype for keybind experimentation possiblities

**Comment by D3faIt** [comment]
> I'm not sure if you've noticed, but you can preselect internal nodes (`node @parent -p east`). It makes the border based feedback rendering approach useless.
> 
> I would recommend, though, to make the preselection feedbacks semi-transparent.
> 
> This can be achieved with the following _compton_ rule:
> 
> ```
> opacity-rule = [ "63:class_g = 'Bspwm' && class_i = 'presel_feedback'" ];
> ```
> 
> where _63_ is the opacity percentage.

Using compton is a workaround AND this does **not** answer the question being asked here.

Are there still no way of configuring preselect borders?

**Comment by Megalodonix** [comment]
@Aadniz 
Hey did you manage to find a solution? ik this is old but I've been googling for hours
