### ISSUE TITLE
bspwm rule desktop move does not work for urxvt

### ISSUE THREAD

**Issue by reportados123** [baskerville/bspwm#342]
I have a rule set as

    bspc rule -a ncmpcpp desktop=^8

but it does not work if you try spawning a urxvt window via

    urxvt -name ncmpcpp -e ncmpcpp

Before the generalization of windows to nodes, it was working. My rule for steam does work though, which is 

    bspc rule -a Steam state=floating desktop=^9

EDIT: It appears that the rules only work on the latter WM_CLASS. For example, if I create a urxvt window with the name ncmpcpp, it'll have the WM_CLASS of "ncmpcpp" and "URxvt". If I create a rule for "ncmpcpp", it won't work. If I create a rule for "URxvt", it will work. You don't even need to create a name. You can even test it with the default WM_CLASS of "urxvt". Creating a rule for "urxvt" will not apply the rules to it, but a rule for "URxvt" will.

**Comment by baskerville** [comment]
`bspc rule -a *:ncmpcpp desktop=^8`

**Comment by reportados123** [comment]
Thanks, it works!
