### ISSUE TITLE
Option to ignore fullscreen requests?

### ISSUE THREAD

**Issue by quuz** [baskerville/bspwm#343]
After a Youtube video or a slideshow presentation go fullscreen, 
`bspc node -t tiled`
will set the fullscreen window into the tile. Is it possible to bypass this step and prevent all windows from going fullscreen?

**Comment by lamarpavel** [comment]
Have you tried setting a rule for the name of the particular window? If the window would be named `flash`, this should work:

`bspc rule -a flash fullscreen=off`

**Comment by baskerville** [comment]
@lamarpavel the rule syntax changed as of eb07d2f.

**Comment by lamarpavel** [comment]
Oh. Well, that would have been a nice surprise on the next update. Sorry for the noise.

**Comment by Dasith-Gunawardhana** [comment]
To clarify, only fullscreen requests from the program (chrome, libreoffice, etc.) would be ignored. It should be possible to manually change the state with bspc.

**Comment by Dasith-Gunawardhana** [comment]
I've achieved the desired behavior by making a slight modification to events.c:
```c
if (state == ewmh->_NET_WM_STATE_FULLSCREEN && IS_FULLSCREEN(n->client) == false) {
		if (action == XCB_EWMH_WM_STATE_ADD) {
			set_state(m, d, n, STATE_FULLSCREEN);
			arrange(m, d);
			set_state(m, d, n, n->client->last_state);
		} else if (action == XCB_EWMH_WM_STATE_REMOVE) {
			if (n->client->state == STATE_FULLSCREEN) {
				set_state(m, d, n, n->client->last_state);
			}
		} else if (action == XCB_EWMH_WM_STATE_TOGGLE) {
			set_state(m, d, n, IS_FULLSCREEN(n->client) ? n->client->last_state : STATE_FULLSCREEN);
		}
		arrange(m, d);
```

Is it possible to achieve this using external rules? As far as I can tell there is no way to differentiate between requests from the application and requests from bspc using rules.

**Comment by neeasade** [comment]
Here is a way to do it in the current scheme (perhaps not the right way/in the nature of this request, but.):

daemon script:
``` sh
#!/bin/sh
# depends on: xprop
# prevent certain window classes from being fullscreen in bspwm.
# note: doesn't exact match (greps WM_CLASS for defined names)

# define WM_CLASS blockers here.
blockers='chromium libreoffice'

bspc subscribe node_state | while read msg; do
	# only care about fullscreens
	echo $msg | grep -q "fullscreen on" || continue

	# if lock is on, we're not preventing.
	[ -f /tmp/bspcblock ] && continue

	# get info
	wid=$(echo $msg | cut -d ' ' -f 4)
	class=$(xprop -id $wid | grep "WM_CLASS" | sed 's/^[^=]*=//g')

	# check all the blockers, tile if encountered anywhere in WM_CLASS line.
	IFS=' '
	for check in $blockers; do
		echo $class | grep -q $check && bspc node $wid -t ~fullscreen
	done
done
```

bspc wrapper function:
``` sh
bspc()
{
    _bspc="/usr/local/bin/bspc"
    if echo $@ | grep -q " fullscreen"; then
        touch /tmp/bspcblock
        $_bspc node -t fullscreen
        # give the script time to react
        sleep 0.5
        rm /tmp/bspcblock
    else
        $_bspc $@
    fi
}
```

webm showing functionality: https://u.teknik.io/AaReH.webm
