### ISSUE TITLE
Cancelling all preselection nodes on desktop does not work.

### ISSUE THREAD

**Issue by reportados123** [baskerville/bspwm#344]
The example in sxhkd for cancelling the preselection nodes does not work for the desktop. However, it does work on the focused node.

    # cancel the preselection for the focused node or desktop
    super + ctrl + {_,shift + }space
	    bspc node @{_,/} -p cancel

If you try create 2 new windows, and then have a preselection node on both, and try to press super + ctrl + shift + space, it will not cancel any of the preselection nodes. However, if you press super + ctrl + space, it will cancel the focused preselection node.

**Comment by ttzhou** [comment]
I find that having
```
bspc node {@, @/} -p cancel
```
does the trick. However, I wonder why the `@` does not get detected outside. Perhaps something to do with `sxhkd` (I am using latest git pull)?

**Comment by neeasade** [comment]
Confirmed here as well.

**Comment by baskerville** [comment]
My bad: `node @/ -p cancel` cancels the preselection of the root of the focused desktop.

The correct command is `bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel`.
