### ISSUE TITLE
Desktop selector modifiers don't work in node path selectors

### ISSUE THREAD

**Issue by blendi-93** [baskerville/bspwm#347]
`bspc node -f @next:/` > all nodes on next desktop focused.
`bspc desktop -f next` > next desktop selected.
`bspc node -f @next.occupied:/` > exitcode 1 nothing selected.

so `@next.occupied:/` doesnt work.

**Comment by baskerville** [comment]
Thanks for reporting.

**Comment by blendi-93** [comment]
thanks for the new shiny features.
