### ISSUE TITLE
Example scripts for panel out-of-date

### ISSUE THREAD

**Issue by yzoug** [baskerville/bspwm#348]
The file examples/panel/panel doesn't work for me as is, needed to change the line regarding FIFO by "bspc control --subscribe > "$PANEL_FIFO" &"

**Comment by baskerville** [comment]
The panel script isn't outdated but your copy of *bspwm* is.

**Comment by yzoug** [comment]
My bad! The Arch package isn't at the last version and I didn't check the version here, thanks for the quick reply!

**Comment by d125q** [comment]
@yzoug The Arch package is a *stable* version, the Git version is obviously a development version.
