### ISSUE TITLE
`swap_nodes` through different desktops does not do everything correctly?

### ISSUE THREAD

**Issue by d125q** [baskerville/bspwm#351]
I have `xtitle` running and outputting the currently focused window's title.

Assume I did the following:

1. Open Firefox on desktop 1;
2. Open URxvt on desktop 2;

Focus Firefox (`xtitle` will output Firefox's title).  Now, swap Firefox from desktop 1 with the URxvt from desktop 2.  `xtitle` won't output URxvt's title.

**Comment by baskerville** [comment]
I can't reproduce.

**Comment by neeasade** [comment]
@d125q  Could you do this with a `bspc subscribe all` or `bspc subscribe window` and post the output?

**Comment by d125q** [comment]
I am sorry; this no longer seems to be happening with the latest version from Git.  I was running the version just prior to the "generalization" of window commands to node commands.
