### ISSUE TITLE
Mousing over preselection causes desktop change

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#353]
Under certain conditions, when mousing over the new preselection area, bspwm appears to switch to the last focused desktop. This doesn’t seem to happen when the preselected window is focused before touching its preselection area.

In the [video](https://ptpb.pw/j5jF.mkv), you see that when window B is focused on desktop IV, coming from desktop III and touching the preselection area switches the focus back to desktop III.

**Comment by cju** [comment]
I can confirm this behaviour exactly as you described it.

**Comment by baskerville** [comment]
Thanks for reporting!
