### ISSUE TITLE
Re-add sticky, urgent border indicators?

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#354]
Since there wasn’t any comment on why sticky, urgent, etc. indicators are gone: Did they just fall aside for the sake of simplicity while making the changes for the node domain, or was there a conceptual issue with them? If the former, I’d find it convenient if they were re-added in some form or other at some point.

If you are concerned about making a decision between indicators in case multiple states apply (urgent + sticky), maybe there could be some sort of control socket event emitted when a window goes urgent? I presume sticky, etc., could already be implemented on the user side by subscribing to focus changes and calling `chwb`, if need be.

**Comment by cju** [comment]
> If you are concerned about making a decision between indicators in case multiple states apply (urgent + sticky), maybe there could be some sort of control socket event emitted when a window goes urgent?

Or just mix the colors…

**Comment by baskerville** [comment]
There are two issues:

- Rendering a set of flags as one color would mean, as @cju noted, mixing the colors (but we need *2^n - 1* colors to render *n* flags).
- Flags are now applicable to non-leaf nodes: those nodes aren't associated with a window, so there's no window border to draw to.

Consequently, I've added the information regarding the state and flags of the focused node of the focused desktop of a given monitor to the *report* event.

It is possible to emulate the previous behavior regarding the urgent flag, because it only applies to leaves:

```
#! /bin/bash

bspc subscribe node_flag | while read -a msg; do
	[ "${msg[4]}" = "urgent" -a "${msg[5]}" = "on" ] && chwb -c 0xff5555 "${msg[3]}"
done
```

**Comment by neeasade** [comment]
>   [ "${msg[4]}" = "urgent" -a "${msg[5]}" = "on" ] && chwb -c 0xff5555 "${msg[3]}"

Side note for others - that chwb command is from [wmutils](https://github.com/wmutils).

**Comment by eigengrau** [comment]
> It is possible to emulate the previous behavior regarding the urgent flag, because it only applies to leaves

This will work nicely for the urgent flag (though sadly compton will apply transparency to borders set by chwb, I will have to look into that). I wonder if there’s a simple way to emulate sticky, though. Since the border set by chbw is lost after focusing the respective window, one would have to also monitor focus events etc. to re-apply the sticky border all the time. Maybe there’s a more elegant solution.

**Comment by baskerville** [comment]
So the answer to the question is *no*.

**Comment by rnhmjoj** [comment]
Any chance you'll ever reconsider? It's pretty ugly having two processes running (bspc and sh) just to set the borders.
