### ISSUE TITLE
Nothing seems to happen using -C and -R

### ISSUE THREAD

**Issue by svenstaro** [baskerville/bspwm#355]
So I followed the migration guide and now have this:

```
super + {comma,period}
    bspc node -C {backward,forward}

super + ctrl + {comma,period}
    bspc node -R {270,90}
```

Typing those in does not result in errors and I think the syntax is correct. However, it doesn't actually do anything on my tiling desktop. I would except to cycle the leaves and rotate the tree. Maybe this is a bug due to the recent node changes?

**Comment by cju** [comment]
Take a look at https://github.com/baskerville/bspwm/wiki/Upcoming-Changes-in-0.9.1#message-translation-guide

In short: You now also have to use a selector.

**Comment by svenstaro** [comment]
The manual doesn't seem to reflect that yet or am I parsing it wrong?

With the selector it works. I thought it was optional as it was before.

**Comment by baskerville** [comment]
You're parsing it wrong: the default selector is the focused node, and if the focused node is a leaf, `-C` and `-R` have no effects.

**Comment by baskerville** [comment]
I'm guessing that you probably want to select the root of the focused desktop: `@/`.

**Comment by PaBLoX-CL** [comment]
Sorry, I don't understand how it could be done... I used to run:

    bspc desktop --flip horizontal

But now, 

    bspc node --flip horizontal

Does nothing, but also doesn't give any error.
