### ISSUE TITLE
New preselection rectangle treated as own node/window?

### ISSUE THREAD

**Issue by cju** [baskerville/bspwm#356]
Hi,

I wonder why the new preselection rectangle is obviously treated as some sort of own node/window, because it gets its own shadow from the compositor (compton, if that matters).

Is this really intended behaviour? And if so, how can one adress this type of "sub node/window"?

My intention would be to exclude it from getting shadows, but therefore, I'd need a window class or something like that…

**Comment by baskerville** [comment]
Yes, the preselection feedback is a window created by *bspwm*. Can you suggest another approach?

If you're using *compton*, you can disable shadows with:
```
shadow-exclude = [ "class_g = 'Bspwm' && class_i = 'presel_feedback'" ];
```

**Comment by cju** [comment]
Thank you very much for your quick answer (and for all your work, of course :+1:  ), works perfectly!
