### ISSUE TITLE
What does ~ do?

### ISSUE THREAD

**Issue by svenstaro** [baskerville/bspwm#357]
The manual shows an option [~] for -t and it also appears in the migration guide and the source code reads like it would be an option to toggle between node states. However, using ~ (for instance bspc node -t ~floating) doesn't seem to do anything for me. When leaving it away it correctly switches the node to the desired state.

So, what does the ~ do and how do I use it?

**Comment by d125q** [comment]
It toggles, rather than sets the state (so you can go, for example, tiled to floating to tiled just by using `~floating` twice).  Note that you should enclose it within single quotes, i.e. `bspc node -t '~floating'` in order to prevent tilde expansion from messing things up.

**Comment by baskerville** [comment]
I've added some explanations regarding *~* in c7364e0.
