### ISSUE TITLE
Less hacky way to put the bar below everything else?

### ISSUE THREAD

**Issue by svenstaro** [baskerville/bspwm#358]
So in https://github.com/baskerville/bspwm/blob/44c5084/examples/panel/panel you have what I assume is a hack to put the desktop atop the bar so that when you fullscreen a window the bar won't be rendered above it. It seems fairly hacky to do it the way it is. Why isn't it possible to make a rule do that?

**Comment by baskerville** [comment]
Because rules are applied to managed windows.

**Comment by svenstaro** [comment]
Oh well I guess that's that then.
