### ISSUE TITLE
Per-instance rules should override class catch-all

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#362]
After adapting my rules definitions to the new 0.9.1 syntax, I’ve noticed that you cannot create instance-specific rules anymore when you already have a rule for the class. Or rather, you can create these, but they will never apply. E.g., my old rules corresponded to these:

```
bspc rule -a emacs:erc  desktop=msg
bspc rule -a emacs      desktop=dev
```

However, when i create an Emacs window with instance name «erc», it will only pop-up on the «emacs» desktop as of late. Ideally, instance-specific rules should override any catch-all rule.

**Comment by baskerville** [comment]
It should work if you create the rules in the following order:
```
bspc rule -a emacs      desktop=dev
bspc rule -a emacs:erc  desktop=msg
```

**Comment by eigengrau** [comment]
Ah, right, this works. Thanks!
