### ISSUE TITLE
Shifting focus directionally while multiple nodes active crashes bspwm

### ISSUE THREAD

**Issue by lytedev** [baskerville/bspwm#363]
Hopefully the title is pretty self-explanatory. I'm admittedly not familiar with the current system. I just migrated up from way back when `node`s were `window`s, so maybe I'm doing something dumb.

To reproduce:
* Select multiple nodes
* Change focus directionally

To definitely exactly reproduce:
* Have these in your sxhkdrc:
```
super + {_,shift + }{h,j,k,l}
  bspc node -{f,s} {west,south,north,east}
super + {p,b,comma,period}
  bspc node -f @{parent,brother,first,second}
super + Return
  urxvt
super + ctrl + {h,j,k,l}
  bspc node -p {west,south,north,east}
```
* Press these keystrokes after freshly launching bspwm:
```
Super + Enter (spawn terminal)
Super + Ctrl + J (preselect south)
Super + Enter (spawn terminal)
Super + P (focus parent node [selecting both terminals])
Super + J (shift focus south)
Crash to TTY (assuming your setup is like mine)
```

I'd love to help get this fixed in any way I can!

**Comment by baskerville** [comment]
Thanks for reporting!

**Comment by lytedev** [comment]
'Preciate it very much, man! Thanks for being super quick!

For what it's worth, bspwm changed the way I work. So thanks a million, man.

You take donations or anything?

**Comment by baskerville** [comment]
Thanks, you can send donations, via PayPal, to the email address given on my [profile](https://github.com/baskerville/).
