### ISSUE TITLE
[suggestion] stacking mode

### ISSUE THREAD

**Issue by minhpara** [baskerville/bspwm#364]
There is only one thing I miss when I migrate from xmonad to bspwm. When the number of window > 3,4,5... the smallest one is not enough to work with; So, its appearance on screen becomes useless. 

If bspwm offer stacking windows, it will be the best wm :)

Thank all of you!

**Comment by vyp** [comment]
But it does...?

**Comment by baskerville** [comment]
@minhpara `bspc node -t '~floating'`?
