### ISSUE TITLE
Ignore padding when in Monocle

### ISSUE THREAD

**Issue by Dissonant-Tech** [baskerville/bspwm#365]
A `bspc config` option that would allow monocle to ignore all padding would be very useful.

If I have any free time I'll try to look through the code and do a PR but maybe someone who knows it better could quickly add this setting?

**Comment by neeasade** [comment]
`bspc config gapless_monocle [true|false]`

**Comment by Dissonant-Tech** [comment]
Already in my `bspwmrc`, it only ignores the `window_gap` setting, not `{top,left,right,bottom}_padding` settings

**Comment by neeasade** [comment]
sure you're not talking about `borderless_monocle`? (the one I initially mentioned to you in irc)

**Comment by Dissonant-Tech** [comment]
`borderless_monocle` and `gapless_monocle` only ignore `border_width` and `window_gap` respectively. 

What I'm looking for is an option that will make windows(nodes) ignore `top_padding` when in monocle. I would like for the panel to still be visible when I'm not in monocle, but hidden when I'm not, this way windows in monocle take up the entire screen (including covering the panel).

I've looked at the code and so far it seems like getting this option to work would involve changing [arrange() in tree.c](https://github.com/baskerville/bspwm/blob/master/tree.c#L42) to ignore padding when in monocle. I'm still trying to get it working, though it might just be some other file I should be looking into.
