### ISSUE TITLE
bspwm for placement, kwin for decoration?

### ISSUE THREAD

**Issue by dncohen** [baskerville/bspwm#369]
This is a question more than an issue.  I wonder whether this is already possible but I'm not sure how.

I'd like to use bspwm and kde at the same time.  So that bspwm is placing windows, while kde is decorating them.

My goal is to use bspwm within qubes.  For those who don't know, qubes manages multiple virtual machines, and makes it clear to the user which VM is hosting an application by customizing the window title, and border colors.  I want to rely on the existing code to do that decoration, but I also want bspwm to place windows and sxhkd for shortcuts.

**Comment by baskerville** [comment]
I don't know.
