### ISSUE TITLE
Rules not working with the latest branch of bspwm

### ISSUE THREAD

**Issue by esn89** [baskerville/bspwm#373]
I have updated to the latest bspwm and although I have changed the settings within sxhkdrc (which works), I am having troubles getting the rules in bspwm to work.

Here is what I have in my bspwmrc:

https://paste.debian.net/361895/
I understand that for rule -a:  "rule -a: it is now possible to specify the class name and instance name (e.g.: rule -a Foo:bar)"   It mentions that is only "possible" so I did not do it.

Are there lines that have changed there as well?

**Comment by DanteFireX** [comment]
Link is broken.
But classname alone should be alright. Maybe the className changed. I had to change urxvt to URxvt. With `bspc query -T -d DESKTOP_SEL` you could confirm that the names are alright.

**Comment by baskerville** [comment]
It's important to:
- Understand the difference between class and instance names.
- Read the manual.
