### ISSUE TITLE
Some Node Commands Not Working

### ISSUE THREAD

**Issue by bubylou** [baskerville/bspwm#374]
The following node commands, which were previously desktop commands, no longer work "--rotate, --flip, --balance, --equalize, --circulate". Below is a section from my sxhkdrc which neither of the commands works anymore after they were changed to node commands. They also don't work if they the commands are run directly from a terminal.

I am using the latest git versions of bspwm and sxhkd which are running on Debian Jessie.

```
alt + {_,shift + }r
    bspc node -R {90,-90}

alt + {_,shift + }e
    bspc node -C {forward,backward}
```

**Comment by cju** [comment]
See https://github.com/baskerville/bspwm/issues/355

**Comment by bubylou** [comment]
Thank you. That explains it.
