### ISSUE TITLE
Black borders on SDL2 windows

### ISSUE THREAD

**Issue by autrimpo** [baskerville/bspwm#375]
Applications that use SDL2 have black borders that don't change color as they should (focused, unfocused, sticky...). SDL adds a `_MOTIF_WM_HINTS` atom to its windows, so my first thought was that the default colors get overriden by this. However after some experimenting I found that the black border stays there even if the window doesn't have the Motif atom. (See also eXeC64/imv#6.)

So I would appreciate your view on what might be causing this and if it's a SDL bug or bspwm bug so it could be reported and fixed where it's supposed to.

**Comment by baskerville** [comment]
I can't reproduce.

I've used the example given [here](https://wiki.libsdl.org/SDL_RenderPresent).

(I've compiled with `gcc $(sdl2-config --cflags --libs) ...`.)

The border of the window I get by running the resulting executable reacts normally.

`sd2-config --version` yields `2.0.4` and `bspwm -v` yields `0.9-126-gb1d9653`.

**Comment by autrimpo** [comment]
Using SDL version `2.0.4` and bspwm `0.9` (binary package in Arch) I can reproduce it using the example code you linked.
I will try compiling the git version and see if I can still reproduce it.

**Comment by autrimpo** [comment]
Using the git version the border indeed works as it should so I guess we can close this.
