### ISSUE TITLE
Mouse stuck on random window

### ISSUE THREAD

**Issue by kevinvdburgt** [baskerville/bspwm#378]
I have a very strange issue uning my mouse on BSPWM, at random times my mouse focus got stock on a random window. Scrolling/selecting on another window/monitor keeps scrolling in the same window where it is stuck on. Even by switch the focus with keyboard keeps the mouse actions stuck.

On thing i mentioned, whenever it happens `xprop` cannot find the cursor. Sometimes it fixes it self but other times i have to restart my machine to get it fixed.

**Comment by baskerville** [comment]
Is this still happening?

**Comment by kevinvdburgt** [comment]
Sorry for late answer, didnt saw the notification.

For some reason this isnt happening anymore, also i am not sure if it is a software problem. I've used a K70RGB keyboard and a M65RGB mouse which causes a lot of issues on linux, since switching the hardware it looks like all issues i had are solved.

If it happens again with new hardware i'll make a new issue.
