### ISSUE TITLE
bspwm few seconds delay

### ISSUE THREAD

**Issue by valsoray17** [baskerville/bspwm#379]
I'm experiencing strange bspwm behavior (maybe sxhkd) at startup after login. For some reason there is ~3 seconds delay after bspwm starts. During this time I cannot open a terminal via super+Enter. I'm using the configs for both bspwm and sxhkd from examples.

If you can tell me how to debug this I'll try it out.

Thanks.

**Comment by neeasade** [comment]
can you post your .xinitrc? it's possible you have a long running command there before sxhkd is launched.

**Comment by valsoray17** [comment]
I don't use .xinitrc, instead it's the bspwm.desktop from the contrib.

**Comment by neeasade** [comment]
where do you launch sxhkd? .xprofile? would be nice to see that instead then if so, for same reasoning.

**Comment by valsoray17** [comment]
It's bspwmrc and it's standard from the repository:

> #!/bin/sh
> 
> sxhkd &
> 
> bspc config border_width         2
> bspc config window_gap          12
> 
> bspc config split_ratio          0.52
> bspc config borderless_monocle   true
> bspc config gapless_monocle      true
> bspc config focus_by_distance    true
> bspc config history_aware_focus  true
> 
> bspc monitor -d I II III IV V VI VII VIII IX X
> 
> bspc rule -a Gimp desktop=^8 state=floating follow=on
> bspc rule -a Chromium desktop=^2
> bspc rule -a mplayer2 state=floating
> bspc rule -a Kupfer.py focus=on
> bspc rule -a Screenkey manage=off

**Comment by ttzhou** [comment]
Try moving the sxhkd call to the bottom.

Also, do you use a login manager?

**Comment by valsoray17** [comment]
I've tried that, but the behavior is the same - when I first start bspwm it always unresponsive for few seconds. Subsequent starts (without rebooting) are ok.

Yes, I'm using login manager, which just invokes bspwm.desktop.

**Comment by neeasade** [comment]
another possible tip would be to fork off all your bspc commands (add '&' the the end of the calls) if the lag time is due to execution(not likely, but still)

**Comment by baskerville** [comment]
I don't see any precise indications on how to reproduce this.
