### ISSUE TITLE
Question regarding the removal of --toggle-visibility

### ISSUE THREAD

**Issue by lordzweigar** [baskerville/bspwm#381]
It appears that this bspc feature was removed, but it is still in the code.

https://github.com/baskerville/bspwm/blob/dcc13f7e5634bb8ffc781216a52c0343ba90a171/window.c#L597

Is there any reason for this? I found this quite a useful feature.

**Comment by baskerville** [comment]
The addition of a  node visibility flag is planned.

**Comment by neeasade** [comment]
ref: https://github.com/baskerville/bspwm/blob/master/doc/TODO.md

side note: `zoom` idea sounds pretty cool - I'm assuming that means only show windows under a node that you 'zoom' too.
