### ISSUE TITLE
bspc pointer -g has no effect

### ISSUE THREAD

**Issue by TheZoq2** [baskerville/bspwm#382]
In my sxhkdrc I have the following lines which I assume should allow me to drag windows around using the mouse. 

```
super + button{1-3}
	bspc pointer -g {move,resize_side,resize_corner}

super + @button{1-3}
	bspc pointer -u
```

However, holding super while clicking the mouse and moving it around does not do anything to the window. It does however prevent the window from receiving click events which to me indicates that sxhkd actually captures the events.

I have also tried running sxhkd with a minimal rc file that only mouse commands with some debug output and that works.

I have also tried running `bspc pointer -g move` and similar commands without sxhkd and they don't have any effect.

My bspwmrc can be found [here](https://github.com/TheZoq2/dotfiles/blob/master/.config/bspwm/bspwmrc). It's a mess but none of the python scripts do anything directly related to bspwm except for dynamically creating workspaces.

**Comment by TheZoq2** [comment]
Sorry about this, sxhkd froze on me while in this tab and when I killed it this issue was posted.

**Comment by ttzhou** [comment]
Did you try updating to latest? I had similar issue that was fixed by update.

**Comment by TheZoq2** [comment]
I have the latest version from the arch repositiories so it should be fairly recent but I can try updating to the very latest version when I have time.

I have also had this issue since I started using bspwm about a year ago

**Comment by bzub** [comment]
I lost mouse resizing also when I switched to bspwm-git on Arch (from AUR).  I don't know why v0.9 would break for you, but below is what my sxhkdrc looks like and fixed the problem.

```
# focus
~button1
        bspc pointer -g focus

# start move/resize
super + button{1-3}
        bspc pointer -g {move,resize_side,resize_corner}

super + !button{1-3}
    bspc pointer --track %i %i

# end move/resize
super + @button{1-3}
        bspc pointer -u
```

**Comment by TheZoq2** [comment]
I don't think 0.9 broke it for me, I have had the issue since I started using BSPWM sevral months ago but never got around to reporting it
