### ISSUE TITLE
Screen order doesn't follow workspace assignment

### ISSUE THREAD

**Issue by DanTheDane** [baskerville/bspwm#385]
I'm using BSPWM in a 3- screen setup, with the following xrandr:
`xrandr --output DP1 --mode 1920x1200 --pos 3840x0 --rotate normal --primary --output DP2-2 --mode 1920x1200 --pos 1920x0 --rotate normal --right-of DP1  --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --left-of DP1`
So in the order:
eDP1 | DP1 | DP2-2

I'm then configuring workspace placement with following:
`bspc monitor DP1 -d 1 2 3 4;
bspc monitor DP2-2 -d 5 6 7 8;
bspc monitor eDP1 -d 9;
`
This is also reflected in the lemonbar switcher, however the actual layout doesn't respect this, it follows the order of the screen instead of the assignment, which means that in effect they're:
eDP1 = 1
DP1 = 2 3 4 5
DP2-2 = 6 7 8 9

**Comment by baskerville** [comment]
See `monitor  --swap`.

**Comment by AlexTes** [comment]
I'm currently using swap after a lot of searching, trying to find an order option / rule. Does that mean there's no way to tell the config about an order for the monitors?

Sounds like a fun challenge for a PR :]
