### ISSUE TITLE
bspwm and xmodmap not getting along

### ISSUE THREAD

**Issue by JC0nde** [baskerville/bspwm#386]
Hi,
I'm trying to swap the `Ctrl` and `Caps` keys but can't get my `xmodmap` command through my `.xinitrc`.

I've found [this thread](https://www.reddit.com/r/unixporn/comments/3ad5ck/bspwm_and_xmodmap_not_getting_along/) but no automate solution is found.

Once `bspwm` is executed `xmodmap` works but when loaded with `.xinitrc`it fails messing all the key mapping :-P

**Comment by baskerville** [comment]
`sxhkd -m -1`?

**Comment by JC0nde** [comment]
Well, I found a solution last night which works nicely:
adding this to `.xinitrc`

`(sleep 2s  && /usr/bin/setxkbmap -option "ctrl:swapcaps") &  # switches CAPSLOCK and Ctrl` 

I knew there was a way of doing it through sxhkd but I didn't know how! :P  
Can't test it now, but as there seems to be many ways to reach the goal, I mark the issue as closed.
Thank you for all that great stuff!
