### ISSUE TITLE
Monitors not setting to numbers in bspwmrc?

### ISSUE THREAD

**Issue by Custodia** [baskerville/bspwm#387]
I have the following monitor setup
```
DVI - DP0 - DP2
|
HDMI
```

And my monitors/desktops in bspwmrc are setup like this:

```
bspc monitor DisplayPort-0 -d I II III
bspc monitor DVI-0 -d IV V VI
bspc monitor DisplayPort-2 -d VII VIII IX
bspc monitor HDMI-0 -d X
```

super + 1-3 is correctly switching desktops on DP0 however for some reason keys for DVI and DP2 are switched.

**Comment by baskerville** [comment]
`sxhkd -m -1`?

**Comment by baskerville** [comment]
Relevant key bindings?

**Comment by Custodia** [comment]
They are currently the defaults from [examples/sxhkdrc](https://github.com/baskerville/bspwm/blob/master/examples/sxhkdrc)

**Comment by baskerville** [comment]
`bspc monitor DVI-0 -s DisplayPort-2`?

**Comment by Custodia** [comment]
```
bspc monitor DVI-0 -s DisplayPort-2
```

Running that made DVI-0 be 4-6 as I want it but now DisplayPort-2 is at 8-10

**Comment by Custodia** [comment]
Where should I add these lines to make this a permanent change?

.xinitrc after:

```
sxhkd &
exec bspwm
```

?

**Comment by baskerville** [comment]
Add those lines to your `bspwmrc`.
