### ISSUE TITLE
Docks get stuck behind tiled windows

### ISSUE THREAD

**Issue by Chrysostomus** [baskerville/bspwm#390]
This bug has been around quite some time. I thought it would have been overcome when the layers got introduced, but alas, it is not. 

If I have any dock in my autostart, it will get stuck behind tiled windows. I have tried setting rule
```
bspc rule -a plank layer=above manage=on
```
but it did no good. The command
```
xdotool search --name Plank windowraise 
```
raises it back, and autohide works properly after that. It also works if I manually start the dock. Raising it with _xdo_ works too.

Same thing happens with all other autohiding docks I have tried as well.

Any tips or workarounds?

Edit: I got it wrong, autostarting or manually running makes no difference. It just gets stuck behind anything newer than itself

**Comment by baskerville** [comment]
First, please define precisely the goal: you want the _dock_ to be above everything except fullscreen windows, is that correct?

**Comment by Chrysostomus** [comment]
Yes, or at least above tiled windows.

**Comment by Chrysostomus** [comment]
To be more exact, I wish dock to hide when focused window overlaps it, and unhide when there is no overlapping focused window or if mouse cursor enters its space. It does this when it is topmost window.

**Comment by Chrysostomus** [comment]
Two workarounds have come to mind:
Add
```
 xdotool search --name Plank windowraise 
```
To 
1) external rule script
Or
2) xdotool behave window edge bottom

Number 1 is probably better. However, both of these are unoptimal, because I don't know which dock user might be running, if any. Running the xdotool commands for all docks, or even one nonexistent, is wasteful. 

So if I was looking fix for my own use, I'd probably have one, but it is poorly suited for my end users (I maintain the manjaro bspwm edition).

**Comment by baskerville** [comment]
A dock window should have the _NET_WM_WINDOW_TYPE_DOCK atom.

So, in your external rules script, you can check if `xwinfo -t ID | grep dock` and store the IDs of the dock windows in `DOCK_IDS`.

Then you might want to listen to the *node_state* and *node_layer* events and `xdo raise $(cat DOCK_IDS)` each time you receive an event.

**Comment by Chrysostomus** [comment]
Hmmm... Would ID be the window id of the new window?

**Comment by baskerville** [comment]
Yes, *ID* is the first argument passed to `external_rules_command`.

**Comment by Chrysostomus** [comment]
Thanks. I'll give it a try, but I think it is unlikely to work with plank, since all plank window ids give  N/A output from xwinfo -t. This probable means it does not properly set _NET_WM_WINDOW_TYPE_DOCK atom. But thats planks problem, I'll try it with different docks.

I just tried having 
`xdotool search --class Plank windowraise &`
`xdotool search --class Dockbarx windowraise &`
`xdotool search --class Docky windowraise &`
`xdotool search --class Wbar windowraise &`

in the external rule. Feels hacky, but works, and does not cause a noticeable delay in window opening. I could add pkgrep to see if those probrams are running, but that is probably just more processes for this.

**Comment by Chrysostomus** [comment]
Okay, Dockbarx does not seem to be setting the atom either, but it obeys the rule in bspwmrc

`bspc rule -a dockbarx layer=above`

This would suggest there is something wrong with either plank or the normal rule I set for it.

**Comment by Chrysostomus** [comment]
Yep, tested it now, I had to use Plank instead of plank. With
`bspc rule -a plank layer=above manage=on border=off`
it works as intended, no external rule necessary. 

Thanks for the help!

**Comment by beyond9thousand** [comment]
> Yep, tested it now, I had to use Plank instead of plank. With `bspc rule -a Plank layer=above manage=on border=off` it works as intended, no external rule necessary.
> 
> Thanks for the help!

@Chrysostomus this only works, but partially. It introduces a new problem where Plank comes to focus whenever the desktop is empty

**Comment by beyond9thousand** [comment]
https://github.com/baskerville/bspwm/issues/1391
