### ISSUE TITLE
Transplanting a new window into preselected root node?

### ISSUE THREAD

**Issue by Chrysostomus** [baskerville/bspwm#395]
Is it possible transplant new window into the root node if root node is preselected? 

I tried following external rule:

```shell
#! /bin/sh
#External rule that transplants new window into the root node if there is presel
root_id=$(bspc query -N -n $(bspc query -T -n @/ | cut -d : -f 2 | cut -d , -f 1))
no_root_presel()
{
	bspc query -T -n @/ | cut -d : -f 10 | grep -q null
}

if ! no_root_presel ; then
	echo "node=$root_id"
fi
```

At first I tried it with just 
`echo "node=@/"`
Then I tried with $root_id being just 
`$(bspc query -T -n @/ | cut -d : -f 2 | cut -d , -f 1)`
before arriving at the current form. None of these seem to work.

**Comment by baskerville** [comment]
The following works as expected here:
```shell
#! /bin/sh

if bspc query -N -n "@/.!automatic" > /dev/null ; then
	echo "node=@/"
fi
```
Make sure to redirect unwanted outputs to `/dev/null`.

**Comment by Chrysostomus** [comment]
Works perfectly!

Thanks!
