### ISSUE TITLE
Need  desktop id when CRUD, rather than using desktop name

### ISSUE THREAD

**Issue by eva7sk** [baskerville/bspwm#397]
First, I don't know if i did it in right way,
when i added a desktop to the first monitor, and added another desktop with same name to the second monitor and moved it to first monitor
so now they are the same name in the same monitor
then open a window, so that one desktop is empty, one is not
and tried to use this script i wrote:

---------------------------------------------------------
sxhkdrc:
super + {1-9}
    /etc/xdg/bspwm/desktop_ctrl.sh {1-9}

desktop_ctrl.sh:
#! /bin/bash
tid=$1

TOP_PADDING=30
DMENU_OPACITY=0.75
SEL_COLOR=#555555
export DMENU_OPACITY SEL_COLOR

categroy="| WORK MEDIA MOVIE MUSIC PICTURE CONVERT DATA DOCUMENT COPY DOWNLOAD WEB NEWS TOOL TUTORIAL SEARCH TRANSLATE OTHER SYSTEM PACKAGE CONFIG BACKUP VIRTUALBOX DEVELOPMENT COMPILE TEMP TEST MM XXX"
#$(bspc query -D -m)

chk_tag(){
	tchk="no"
	taglist=$(bspc query -D)
	while read ele
	do
		if [ "$ele" = "$tag" ] ; then
			notify-send "Already Exist ...."
			#zenity --info --text=$tchk
			return 1
		fi
		#zenity --info --text=$ele
	done < <(echo "$taglist")
	#zenity --info --text=$tchk
	#zenity --info --text=$1
	return 0
}
add_tag(){
	tmp=$(bspc query -D)" "$categroy
	tag=$(printf "%s\n" $tmp | dmenu -i -o $DMENU_OPACITY -fn 'Monospace-11:normal' -h $TOP_PADDING -nb '#000000' -sb $SEL_COLOR -p 'ADD:' -y $TOP_PADDING)
	#zenity --info --text=$tag
	
	chk_tag $tag
	#zenity --info --text=$?
	if [ $? = 0 ] ; then
		bspc monitor -a $tag
	fi
}
ren_tag(){
	tmp=$(bspc query -D)" "$categroy
	tag=$(printf "%s\n" $tmp | dmenu -i -o $DMENU_OPACITY -fn 'Monospace-11:normal' -h $TOP_PADDING -nb '#000000' -sb $SEL_COLOR -p 'REN:' -y $TOP_PADDING)
	
	chk_tag $tag
	if [ $? = 0 ] ; then
		bspc desktop -n $tag
	fi
}
del_tag(){
	if [ $(bspc query -W -d | wc -l) -eq 0 ] ; then
		tmp=$(printf "Yes\nNo" | dmenu -i -o $DMENU_OPACITY -fn 'Monospace-11:normal' -h $TOP_PADDING -nb '#000000' -sb $SEL_COLOR -p 'DEL:' -y $TOP_PADDING)
		sel=$(echo $tmp | tr '[:upper:]' '[:lower:]')
		#notify-send $sel
		if [ "$sel" = "yes" ] ; then
			bspc desktop -r $(bspc query -D -d)
		else
			echo ""
			#notify-send "Canceled"
		fi
	else
		echo ""
		#notify-send "Not Empty"
	fi
}

if [ "$tid" = "add" ] ; then
	add_tag
	exit
elif [ "$tid" = "ren" ] ; then
	ren_tag
	exit
elif [ "$tid" = "del" ] ; then
	del_tag
	exit
fi

if [ $tid -gt $(bspc query -D -m | wc -l) ] ; then
	#bspc monitor -a $(kdialog --inputbox "ADD:")
	#monitor_rec=$(bspc query -M -m)
	add_tag
	exit
else
	if [ $(bspc query -D -d focused) != $(bspc query -D -d $(bspc query -M -m):^$tid) ] ; then
		bspc desktop -f $(bspc query -M -m):^$tid
	else
		if [ $(bspc query -W -d | wc -l) != 0 ] ; then
			#bspc desktop -n $(kdialog --inputbox "REN:" $(bspc query -D -d))
			#desktop_rec=$(bspc query --desktops --desktop focused)
			ren_tag
		else
			del_tag
		fi
	fi
	exit
fi

---------------------------------------------------------
and then, the logic of this script goes wrong, alway try to use the first desktop
so, i simply disabled adding the same desktop,
that's the reason why
notify-send "Already Exist ...."
in this script.
but i still want add the same desktops with the same name and focus/delete desktops without any limit.

**Comment by kmARC** [comment]
It would be still beneficial if one could query the entities' name, too. Now `bspc` query only prints IDs.

**Comment by neeasade** [comment]
You can still query json and filter for name if you wish

**Comment by kmARC** [comment]
Yeah I found this, too. However, as I'm writing a bash script it'd be easier If I would not need to parse json.

**Comment by Stebalien** [comment]
@kmARC try jshon:

```bash
bspc query -T -m | jshon -e "desktops" -a -e "name" -u -p -e id | while {
    read -r name
    read -r id
}; do
    if [[ "$name" == "Some Name" ]]; do
        # something with $id
    fi
done

**Comment by baskerville** [comment]
Indeed, there's *jq* and *jshon*.

And this issue is closed.

**Comment by NamPNQ** [comment]
My implement: https://github.com/NamPNQ/dotfiles/blob/master/wm/.config/lemonbar/lemonbarrc#L4-L9
