### ISSUE TITLE
Is it possible to get window class and type in external_rule?

### ISSUE THREAD

**Issue by eva7sk** [baskerville/bspwm#398]
I want to rule all floating dialog to under mouse
Like New File/New Folder, Permission Dialog etc....
Thank you for your advice

**Comment by eva7sk** [comment]
I changed title too much.... and sorry for my english.

**Comment by Chrysostomus** [comment]
I would use external rule to check if the new window is floating, then output id of the floating window to another scripts that uses xdotool and/or xdo/wmutils to move the window under the cursor.

something like 
```
#!/bin/sh
wid=$1
bspc query -T -n $wid | grep - q '"state":"floating"' && window-placer $wid
```

best way to get mouse position is 
`eval $(xdotool getmouselocation --shell)`

The rest depends a bit on how would you like to place that window relative to cursor? I'm guessing on the center, but not outside the desktop?

**Comment by Chrysostomus** [comment]
Here are some example scripts that may or may not be useful on building your own:
https://github.com/Chrysostomus/bspwm-scripts/blob/master/bin/window-placer
https://github.com/Chrysostomus/rootmenu/blob/master/bin/dboxmenu

**Comment by Chrysostomus** [comment]
Here is an example script that places window centered around cursor, but still fully within the desktop.  Could be improved to use less different tools. Right now it uses xdotool, xdo and wmutils.

**Comment by Chrysostomus** [comment]
This one uses just xdotool and wmutils. If you know your resolution and have only 1 monitor, you can hard code it and drop wmutils too.
