### ISSUE TITLE
About Split

### ISSUE THREAD

**Issue by eva7sk** [baskerville/bspwm#400]
If one parent node has more than two child node,
And use parent shortcutkey to heighlight the hole parent node
then use split shortcutkey to split that node?
Use mouse drag/resize that group
it will be more free and comfortable

**Comment by neeasade** [comment]
> Is it possible one parent node has more than two child node?

No, but you can have a child node be a parent.

eg not 
```
          +-------+
          |       |
          | p     |
          |       |
    +-----+---+---+----------+
    |         |              |
    |         |              |
+---+--+   +--+----+   +-----+--+
|      |   |       |   |        |
|  n   |   |  n    |   |  n     |
|      |   |       |   |        |
+------+   +-------+   +--------+

```

but
```
          +-------+
          |       |
          | p     |
          |       |
    +-----+---+----
    |         |
    |         |
+---+--+   +--+----+
|      |   |       |
|  n   |   |  p    |
|      |   |       |
+------+   +-+-----+----+
             |          |
             |          |
        +----+--+     +-+-----+
        |       |     |       |
        |   n   |     |   n   |
        |       |     |       |
        +-------+     +-------+

```

**Comment by eva7sk** [comment]
@neeasade 
sorry, I changed the title after saw your comment,
i use issue like site very very few(only about three~five times), i do know if change title is wrong concept

**Comment by stephen304** [comment]
Is what you want to do like this?:
```
+-----------------------+  +-----------------------+  +-----------------------+
|           |           |  |           |     |     |  |                       |
|           |     2     |  |           |  2  |     |  |           5           |
|           |     ^     |  |           |  ^  |     |  |                       |
|     1     |-----------|  |     1     |-----|  4  |  |-----------|-----------|
|           |           |  |     ^     |     |  ^  |  |           |  2  |     |
|           |     3     |  |           |  3  |     |  |     1     |-----|  4  |
|           |     ^     |  |           |  ^  |     |  |           |  3  |     |
+-----------------------+  +-----------------------+  +-----------------------+

             X                         Y                          Z 
```

```
             a                          a                          d
            / \                        /^\                        / \
           1   b         --->         1   c         --->         a   5
              /^\                        / \                    / \
             2   3                      b   4                  1   c
                                       / \                        / \
                                      2   3                      b   4
                                                                / \
                                                               2   3
```

I want to be able to select a node instead of only a leaf, so I can insert a new node into the middle of the tree (and even the root) instead of just on the end. This would allow much more flexibility for altering layouts after the fact, such as splitting a container of 2 windows horizontally to make it as if it was split horizontally before vertically (X->Y) or even to split the whole tree so you can dedicate half your screen to something even after creating a tree of windows (Y->Z).

It seems to me this would solve what @eva7sk wants, by allowing you to split a node containing 2 children in the opposite direction as the existing children after the fact.

**Comment by neeasade** [comment]
@stephen304 this is possible in current, it's just he preselection window doesn't popup if you're not preselecting a leaf -- but all nodes (desktop, groups of leafs too) can be preselected

**Comment by stephen304** [comment]
@neeasade Really? I never got it to work before and the readme only shows splitting from a leaf. Currently it seems to me the only way to select a node before splitting is to focus the window. I wasn't aware of any method for focusing a parent node since it's not a window (you can't really click on the parent node).

How is this done?

**Comment by neeasade** [comment]
the path notation is meant to be used for this kind of thing (actions relative to a node position, which can be that nodes parent up to the desktop)

**Comment by stephen304** [comment]
Path notation? The bspc man page doesn't seem to mention that at all...

**Comment by neeasade** [comment]
```
NODE_SEL := (DIR|CYCLE_DIR|PATH|last|older|newer|focused|biggest|<node_id>)[.[!]focused][.[!]automatic][.[!]local][.[!]leaf][.[!]window][.[!]STATE][.[!]FLAG][.[!]LAYER][.[!]same_class]

           STATE := tiled|pseudo_tiled|floating|fullscreen

           FLAG := urgent|sticky|private|locked

           LAYER := below|normal|above

           PATH := @[DESKTOP_SEL:][[/]JUMP](/JUMP)*

           JUMP := first|1|second|2|brother|parent|DIR
```

I'm referring to the `PATH := @[DESKTOP_SEL:][[/]JUMP](/JUMP)*`

**Comment by neeasade** [comment]
ah, sorry -- this is only relevant as of 0.9.1 and up.

**Comment by stephen304** [comment]
Ah brilliant! Just have to convert my old bindings now.
