### ISSUE TITLE
Man page uses both DESK_SEL and DESKTOP_SEL interchangeably

### ISSUE THREAD

**Issue by AntonTell** [baskerville/bspwm#404]
The docs use both `DESK_SEL` and `DESKTOP_SEL` to describe the same type of selector. `DESK_SEL` is only used twice, and the definition uses `DESKTOP_SEL`, so the two occurences of `DESK_SEL` should be changed to `DESKTOP_SEL`.

---

Here are the two occurances:

           PATH := @[DESK_SEL:][[/]JUMP](/JUMP)*
--
       Path Jumps
           The initial node is the focused node (or the root if the path starts with /) of the focused desktop (or the selected desktop if
           the path has a DESK_SEL prefix).

**Comment by baskerville** [comment]
Fixed by ed76b1f.

Thanks for reporting.
