### ISSUE TITLE
Change default monitor ordering

### ISSUE THREAD

**Issue by mkoskar** [baskerville/bspwm#405]
I believe that default ordering of monitors (as returned by RANDR / XINERAMA) is generally not useful because it doesn't reflect physical ordering but IIRC first is always primary monitor and then ordering follows CRTC in ascending order. 

In `bspwm` it concerns `^<n>` and `CYCLE_DIR`'s `prev` and `next` which then use above described un-natural ordering.

I suggest to redefine ordering used by `^<n>`, `prev` and `next` to top-left ordering i.e., monitor with index 1 would be topmost left, and so on.

**Comment by mkoskar** [comment]
Thanks for taking look at this. I've tested and it doesn't seem quite there yet.

According to my testing primary monitor is always first, I'm not sure if that is intended but I think it shouldn't be, because there is `primary` selector which can be used for it.

Looking at source it seems that following should be removed (and probably other bits of `bool update_monitors(void)` accommodated with sorting in mind):
```
 	if (!running && pri_mon != NULL && mon_head != pri_mon) {
		swap_monitors(mon_head, pri_mon);
	}
```

**Comment by baskerville** [comment]
Forgot about that bit, sorry.

Fixed by 87a89ff.

**Comment by mkoskar** [comment]
No problem, I've retested and it works now. Thanks!

As a sidenote, looking at `monitor_cmp` function I was wondering why not just compare top-left coordinates of monitors (`r1.{x,y}` vs. `r2.{x,y}`)? I see you incorporate `height` and `width` there such that overlapping monitors are "equal".

**Comment by baskerville** [comment]
If you only compare the corners, then this monitor setup:
```
           +---------+
+---------+|         |
|         ||    B    |
|    A    ||         |
|         ||         |
+---------++---------+
```
would yield the following output for `bspc query -M`:
```
B
A
```

**Comment by mkoskar** [comment]
Yes I know, I would find such strict ordering more "correct" though, maybe it's less practical in the above scenario I admit. I think it's more common to have screens with different resolutions aligned to the top edge. Nevertheless, it works for me ;).

**Comment by neeasade** [comment]
>  I think it's more common to have screens with different resolutions aligned to the top edge.

perhaps, but I've been keeping my screens like so, and the ordering as of last commit is appreciated from a consistency point of view.

```
                                           +-----------+
                                           |           |
                                           |           |
                     +---------------------+           +-----------------------+
                     |                    ||           ||                      |
                     |                    ||           ||                      |
                     |                    ||           ||                      |
                     |                    ||           ||                      |
                     |                    ||           ||                      |
                     +---------------------+           +-----------------------+
                                           |           |
                                           |           |
                                           +-----------+

```

**Comment by mkoskar** [comment]
@neeasade right, point taken ;)
