### ISSUE TITLE
Pointer doesn't start on focused/primary monitor

### ISSUE THREAD

**Issue by mkoskar** [baskerville/bspwm#407]
Having following configuration:
```
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
```

And `bspc query -M` returns:
```
LVDS1
HDMI3
HDMI2
```

`HDMI3` is `primary` and is the one with focus on start (e.g., spawing terminal opens it there and then mouse jumps there because of `pointer_follows_focus`) but pointer is located on ~~in the center of~~ `LVDS1` initially. It's a bit confusing.

**EDIT:** See strikeout above; pointer seems to be placed arbitrarily although always in the same place NOT in the center, could be maybe explained by lower resolution of LVDS1 and higher of HDMI2 & 3.

**Comment by baskerville** [comment]
Maybe it would make more sense to initially focus the monitor that contains the pointer?

**Comment by mkoskar** [comment]
I actually like that `primary` is focused on start, it makes sense to me because I set primary deliberately to the center monitor and also other things obey it, like tray and status bar. Also I would expect that pointer would be centered in monitor, which is not the case now (for my setup) it seems.

**Comment by mkoskar** [comment]
Tested -> Works. Thanks!
