### ISSUE TITLE
Mouse at edge of window in monocle layout causes unwanted switching of focused window

### ISSUE THREAD

**Issue by vanzomerenc** [baskerville/bspwm#408]
Sometimes, when there are multiple windows on a desktop with monocle layout, the top window will become unfocused and end up below another window. This only happens for certain windows, such as gtk3-icon-browser, and can be triggered by moving the mouse slowly on the edge of the window.

I am using the following bspwmrc:

    #! /bin/bash
    
    # general configuration
    bspc config focus_follows_pointer true
    
    # window placement
    bspc config top_padding 28
    bspc config left_padding 58
    bspc config right_padding 0
    bspc config bottom_padding 0
    
    # borders
    bspc config focused_border_color \#AD3300
    
    # desktops
    bspc monitor --reset-desktops Desktop{1,2,3,4,5,6,7,8,9}

**Comment by eigengrau** [comment]
I’ve also noticed this, but only with a few selected clients. One client that seems to consistently do this is for me is evince (GTK3).

**Comment by sg3des** [comment]
Similar problem, it appeared after upgrade bspwm, i have problems with chromium...

**Comment by neeasade** [comment]
So, what appears to be happening here is the pointer is going through the border of GTK3 windows. If you have `focus_follows_pointer` set, the pointer goes through GTK3 window border to window beneath it and that's why you get the switching. I tested this using large window borders with gedit(GTK3) and leafpad(GTK2), and only gedit had the problem.

**Comment by neeasade** [comment]
So, GTK3 manages window decorations from the client side - I'm assuming that bspwm is still having the borders there but they aren't part of the window necassarily. My initial thought was to try and have gtk css that made it's client-side borders match your bspwm borders, but then you wouldn't get your focus colors -- then I tried to have gtk manage it's own borders (with a width matching bspwm borders, be transparent, and set a _negative_ `border_width` value on the gtk window in an attempt to go into the window. There were 2 problems with that approach:

- I couldn't get GTK3 borders to be transparent (though I have them set as they should be and am running compositor)
- BSPWM doesn't support setting negative border_width in the fashion mentioned above (which is expected)

Here is the `~/.config/gtk-3.0/gtk.css` file I was using to attempt the transparent border style

``` css
.window-frame, .window-frame:backdrop {
	border-style: solid;
	border-width: 20px;
	border-color: rgba(0, 0, 0, 0);

	background-image: none;
	background-color: rgba(0, 0, 0, 0);

	box-shadow: none;
	margin: 0;
	border-radius: 0;
}
```

**Comment by sg3des** [comment]
I do not know, we are talking about the same problem...
simple example: 
you have bind on hotkey open terminal, and setting preselect...
1) open terminal -> now your focus is on this window/node - it`s ok! 
2) set preselect on one of side for this window/node, move your mouse cursor on preselect area, 
3) and again open terminal...
your new terminal window not receive focus, even if you click on this window, focus will be only if you move out the mouse cursor and re-hover on this terminal window.

second example with drag and drop:
1) open text editor(i`m use xfce mousepad)
2) open file manager(i have xfce thunar)
3) drag any text file from file manger to text editor...
text editor not recieve focus, and even highlight the text you can! BUT all the action will be made to file manager!

**Comment by neeasade** [comment]
@sg3des - You are describing a different issue from OP here. I was able to reproduce and have opened https://github.com/baskerville/bspwm/issues/461

**Comment by neeasade** [comment]
@sg3des - You are describing a different issue from OP here. I was able to reproduce and have opened https://github.com/baskerville/bspwm/issues/461

**Comment by neeasade** [comment]
@sg3des - You are describing a different issue from OP here. I was able to reproduce and have opened https://github.com/baskerville/bspwm/issues/461

**Comment by neeasade** [comment]
@sg3des - You are describing a different issue from OP here. I was able to reproduce and have opened https://github.com/baskerville/bspwm/issues/461

**Comment by neeasade** [comment]
@sg3des - You are describing a different issue from OP here. I was able to reproduce and have opened https://github.com/baskerville/bspwm/issues/461

**Comment by sg3des** [comment]
@neeasade - year, thx, my problem is solved! ^^

**Comment by neeasade** [comment]
This issue can be resolved by removing gtk3 client-side decorations with https://github.com/PCMan/gtk3-nocsd.

Here's a webm demonstrating the issue: https://u.teknik.io/P3Hni.webm

and webm demonstrating fix after installing the above: https://u.teknik.io/SNzQ4.webm

The window switching when my mouse is off the border is me doing `bspc node -f next.local`.
