### ISSUE TITLE
node cycle, will not cycle

### ISSUE THREAD

**Issue by thrisp** [baskerville/bspwm#409]
I just reinstalled & reinstalled bspwm from git.

bspwm -version                                                                                 
0.9-138-g4b538bc

sxhkd -version
0.5.5-17-g3f68c38

I use this, but it will not work, trying various things all night:

```
super + {grave, Tab}
	bspc node -C {forward,backward}
```

Funnily, it did work for a second or two I thought I had it it working then crashed bspwm.

Let me know how I can troubleshoot this deeper -- I cannot cycle nodes in monocle as I previously did.

**Comment by thrisp** [comment]
@/

still not certain what that means but you need to do: 
```

super + {grave, Tab}
	bspc node @/ -C {forward,backward}
```

**Comment by cjk** [comment]
Yep, it took me hours to find that syntax tidbit.
I should really file a PR to improve docs / FAQ here, but the problem is to first *understand* what this actually means.

**Comment by neeasade** [comment]
the @/ indicates you are selecting a desktop node, as opposed to a window node -- it is a convenient shortcut for the current desktop -- this is made pretty clear in the docs where it says that a node can be a PATH, and a PATH is defined as:

```
PATH := @[DESKTOP_SEL:][[/]JUMP](/JUMP)*

JUMP := first|1|second|2|brother|parent|DIR
```

The DESKTOP_SEL notation is what clarifies this syntax is for desktop nodes.
