### ISSUE TITLE
on dual head, desktop size is misrepresented in graphical pagers

### ISSUE THREAD

**Issue by milkmiruku** [baskerville/bspwm#410]
Graphical pagers display desktops with the size of the root window, rather than the bspwm desktop size.

If I'm interpreting the issue correctly, this would be a request for _NET_DESKTOP_GEOMETRY and/or _NET_DESKTOP_VIEWPORT support.

![2016-03-07-155343_2560x1024_scrot](https://cloud.githubusercontent.com/assets/108225/13574676/1b6c4e7c-e47d-11e5-9ee9-32db231b2f3c.png)

**Comment by baskerville** [comment]
What's the pager used in the screenshot?

**Comment by milkmiruku** [comment]
xfce4-panel pager (GUI item name is "Workspace Switcher"), though I have the same issue with the gnome-panel pager, the lxpanel pager, the fbpanel pager, xde-pager and fbpager (fluxbox).

(fwiw, fbpager is has broken window representations - all floating/pseudo-tiled windows are represented as located at 0x0 in their desktop, and full screen apps on my second monitor appear on the left side of the [double width] desktop representations, unlike the last 4 second monitor desktops in the screenshot)

netwmpager, ipager and bbpager (blackbox) represent the right desktop ratio, but the mini windows are squished to half the width, so the same problem but at a different level - i guess these pagers have a hardcoded ratio - the last ipager release was 2005 and RandR 1.2 with it's multihead features came in 2007.

**Comment by baskerville** [comment]
Is there a window manager that works as expected with those pagers?

By looking at [the description of *_NET_NUMBER_OF_DESKTOPS* in the spec](https://specifications.freedesktop.org/wm-spec/wm-spec-1.4.html#idm139915845050096), I'm guessing that *_NET_DESKTOP_VIEWPORT* and *_NET_WORKAREA* are the relevant properties…

**Comment by baskerville** [comment]
In fact they aren't: 

- *_NET_DESKTOP_VIEWPORT* must be *(0, 0)* because *bspwm* don't support *large desktops*.
- *_NET_WORKAREA* isn't set by *i3-wm* and isn't used by *fbpanel*.

I'm afraid you might have to write the pager yourself.
