### ISSUE TITLE
desktop -r last.local resp. desktop -m focused -r last do nothing

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#411]
I’m attempting to remove the last focused desktop on the current monitor. I’ve tried both `desktop -r last.local` and `desktop -m focused -r last`, but neither of these have any effect. Any pointers? (This is with 4b538bc).

**Comment by baskerville** [comment]
You can't remove:

- A non-empty desktop.
- The sole desktop of a monitor.

**Comment by baskerville** [comment]
In addition, please note that the syntax of `desktop -r last.local` is invalid, the correct form is `desktop last.local -r`. And `desktop -m focused` means sending the focused desktop to the focused monitor: it has no effects.

**Comment by eigengrau** [comment]
> In addition, please note that the syntax of desktop -r last.local is invalid, the correct form is desktop last.local -r

Yikes, that’s what was tripping me up. Thank you kindly for the pointer!
