### ISSUE TITLE
window_gap key does not work

### ISSUE THREAD

**Issue by drdeimos** [baskerville/bspwm#412]
I'm set key window_gap, but it has no effect.
Example, i'm try command bspc config window_gap 50.

Try set:
```drdeimos@UbuSSD ~ :( $ bspc config window_gap 0```
Get current gap
```
drdeimos@UbuSSD ~ $ bspc wm -d | jq '.monitors[0].desktops[].windowGap'
6
6
6
6
6
6
6
```
Build from commit 4b538bca86c7dbd60b40b30aa795376ce6f63ece
```$bspwm -v
0.9-138-g4b538b```

**Comment by neeasade** [comment]
after changing the window_gap, reset/reload the desktop with `bspc monitor <monitor> -d <desktop>`

**Comment by drdeimos** [comment]
Thank you. I'm initialize monitor before set windows gap.
But earlier this trick worked
