### ISSUE TITLE
Syntax changes result in non-functional commands

### ISSUE THREAD

**Issue by ThurnisH41ey** [baskerville/bspwm#415]
Using bspwm 0.9.1-1, today's update from the Arch repos. The following commands exit without error but do not do anything:
```
bspc node -C forward
bspc node -C backward
bspc node -F vertical
bspc node -F horizontal
```
Before the update, these commands would cycle the desktop forwards or backwards, and flip the desktop vertically or horizontally. Now they do nothing. I'm testing with 3 urxvt's open in tiling mode.

**Comment by ttzhou** [comment]
try `bspc node @/ -C forward`

**Comment by Eisfreak7** [comment]
I have a similar problem. Most of the bspc commands in my `sxhkdrc` stopped working.
Apparently there have been some prettry breaking changes in the last update, are they documented somewhere?
It seems like the `window` commands have been replaced by `node`, but neither `bspc node --focus right` nor `bspc node @/ --focus right` focuses the window to the right.

**Comment by baskerville** [comment]
@ThurnisH41ey @Eisfreak7 
See [`doc/CHANGELOG.md`](https://github.com/baskerville/bspwm/blob/master/doc/CHANGELOG.md) and, _of course_, the manual.

**Comment by Eisfreak7** [comment]
Ah thank you, I should of course have seen that
