### ISSUE TITLE
Fullscreen appearing below lemonbar

### ISSUE THREAD

**Issue by ThurnisH41ey** [baskerville/bspwm#416]
Running
`bspc node -t ~fullscreen`
correctly toggles fullscreen, but when a window gets fullscreened, it appears underneath my lemonbar. Before the 0.9.1-1 update it would appear above every window, which is the sensical behavior.

**Comment by ttzhou** [comment]
there are now stacking layers, so likely lemonbar is set to be on a stacking layer that is above the fullscreen mode.

i think the example docs show a way around this.

**Comment by baskerville** [comment]
The example panel shows how to handle this.

The new concepts originate from #298.
