### ISSUE TITLE
Monitors are switched?

### ISSUE THREAD

**Issue by dasith-gunawardhana** [baskerville/bspwm#417]
My bspwmrc is configured like this:
```shell
bspc monitor LVDS1 -d I II III IV V
bspc monitor HDMI1 -d VI VII VIII IX X
```

And my _sxhkdrc_ like this:
```
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'
```

When I press super + 1, 2, 3, 4, or 5, it goes to the monitor HDMI1, not LVDS1. And when I press super + 6, 7, 8, 9, or 0 it goes to LVDS1. This was working correctly until recently.

**Comment by ttzhou** [comment]
which one is your primary monitor, using `xrandr` output?

**Comment by dasith-gunawardhana** [comment]
LVDS1

**Comment by ttzhou** [comment]
try `bspc monitor LVDS1 --reset-desktops I II III IV V` and similarly for `HDM1`

**Comment by dasith-gunawardhana** [comment]
Tried both in current session and after adding it to the bspwmrc, same problem.

**Comment by faiden** [comment]
bspc desktop -f '^1'
bspc desktop -f 'V'

these two are now the same but number "1" should be "I" as this is how I setup my bspwmrc

bspc monitor Monitor1 -d I II III IV
bspc monitor Monitor2 -d V VI VII VII

however bspc query -M gives output

Monitor2
Monitor1

I had to solve it with:

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
            bspc {desktop -f,node -d} '{I,II,III,IV,V,VI,VII}'

**Comment by baskerville** [comment]
@dasith-gunawardhana @faiden Please format code excerpts using code blocks.

@dasith-gunawardhana What's the output of `bspc wm -d | jq '.monitors[]|{name, rectangle}'`?

**Comment by dasith-gunawardhana** [comment]
```
{
  "name": "HDMI1",
  "rectangle": {
    "x": 0,
    "y": 0,
    "width": 1920,
    "height": 1080
  }
}
{
  "name": "LVDS1",
  "rectangle": {
    "x": 0,
    "y": 1080,
    "width": 1366,
    "height": 768
  }
}
```

**Comment by baskerville** [comment]
Well, the ordering looks fine to me.

I'm afraid you'll have to resort to sorcery: `bspc monitor '^1' -s '^2'`.
