### ISSUE TITLE
Alternative to auto_alternate

### ISSUE THREAD

**Issue by Eisfreak7** [baskerville/bspwm#418]
I see in the changelog that the `auto_alternate` configuration was removed.
Is there a new way to archive the same functionality or is this just no longer supported?
I tried prepending `~` to the deskto_sel, but that doesn't appear to work and I can't find anything about it in the manual either.

A few unrelated questions to the new vesion (they don't quite belong here but don't deserve an own issue):  
The changelog mentions "The monitors are sorted, by default, according to the natural visual hierarchy". What does that mean? I noticed that my monitors now are sorted the opposite way they were before by default. What is the "natural visual hierachy"? My primary monitor is configured through xrandr as `--right of` the other one, is that where the info comes from? Is this configurable or should I just manually add a `monitor --swap` command?  
Also, before the update preselections where shown by simply changing the border color. Now half of the window is completely colored. Is this intendet? The only thing I could find in the manual and changelog is a way to change this color.

**Comment by baskerville** [comment]
- The commit message of 4fbd961 gives possible bindings.
- The new (default) monitor order was discussed in #405.
- This is intended, e.g.: `bspc node @parent -p south`. The new feedback can render a preselection of a node that is the ancestor of multiple windows.

**Comment by Eisfreak7** [comment]
- The scriptability of bspwm is amazing, thanks
- Okay that seems reasonalbe, I'll just have to adjust or rename my monitors
- I think its a bit ugly compared to how it was before, but I can live with that

Thank you for your quick help
