### ISSUE TITLE
rotate balance flip

### ISSUE THREAD

**Issue by faiden** [baskerville/bspwm#419]
I have tried the commands:
```
bspc node -R 90
bspc node -B
bspc node -F horizontal|vertical
```
They do not seem to work or am I doing something odd? I simply want my desktop windows/nodes to change location in a rotating order.

**Comment by neeasade** [comment]
you need to specify the root node/desktop with `@/`, eg `bspc node @/ -R 90`

**Comment by faiden** [comment]
A simple as that tyvm
