### ISSUE TITLE
bspwm-0.9.1 on archlinux : bspc issue

### ISSUE THREAD

**Issue by Fnux** [baskerville/bspwm#421]
It looks like there is something wrong with the `bspwm-0.9.1-1` package on archlinux. bspc returns `unknown command` for almost everything, I had to revert to the `bspwm 0.9-2` package. Did you change something ?

PS : someone who tried to install bspwm told me that it was the same from sources.

**Comment by faiden** [comment]
Take a look at 
[https://github.com/baskerville/bspwm/blob/master/doc/CHANGELOG.md](url)
A lot of the commands has changed

**Comment by tmathmeyer** [comment]
I'm not sure that this should be totally invalid. There seem to be many commands that are not discussed in the changelog or anywhere else I can find. Specifically the commands:
 - focus_by_distance
 - normal_frame_opacity
 - focused_frame_opacity
 - urgent_border_color

don't seem to show up in either changelog.md or in the manual, which alone makes this issue not invalid. 

More importantly though, what has become of specifically the focus_by_distance option? In commit 57b12d8f47ea0c3219fd4b310f8b02d2a85eb74d, you remove it, however it rather significantly changes the way that mouse selection works. 
I also didn't find anything about the frame opacity options in the changelog, commit descriptions, or the manual.

**Comment by neeasade** [comment]
focus_by_distance is present in bspwm 0.9.1[1], therefore removal should
not be reflected in changelog for 0.9.1.

{normal, focused}_frame_opacity were not present in bspwm 0.9[2], therefore
removal didn't occur between 0.9 and 0.9.1 (so no need to note in changelog
to 0.9.1)

urgent_border_color is documented as being removed in the changelog.


focus_by_distance is now default behavior/always on, is why it was
removed(as said in your linked commit), and shouldn't affect pointer
selection. Make an issue to elaborate?

Frames were removed in 0.8.8, implying frame related settings should be
deleted[3].

[1] https://github.com/baskerville/bspwm/blob/0.9.1/doc/bspwm.1.asciidoc
[2] https://github.com/baskerville/bspwm/blob/0.9/doc/bspwm.1.txt
[3]
https://github.com/baskerville/bspwm/commit/e0b6cd3cd42863addcc9a719ea6fe2e44883c72d

The changelog is a recent addition to the repo, and my impression was that
it is meant as a guide between versions, not to serve as a history for all
changes.


Thanks,
Nathan

**Comment by baskerville** [comment]
That sums it up pretty well.

The current *DIR* implementation is based on  [right-window](https://github.com/ntrrgc/right-window).
