### ISSUE TITLE
bspwm 0.9.1-1 and 0.9.1-2 break sxhkd commands

### ISSUE THREAD

**Issue by corkybeta** [baskerville/bspwm#422]
I'm using Arch and both 0.9.1-1 and 0.9.1-2 break Super+hjkl and Super+Shift+hjkl. sxhkd displays these as "unknown command". Downgrading sxhkd daemon makes no difference, but downgrading bspwm to 0.9-2 fixes the issue.

**Comment by neeasade** [comment]
Have a look at [doc/changelog](https://github.com/baskerville/bspwm/blob/master/doc/CHANGELOG.md)

**Comment by cju** [comment]
You probably may want to read https://github.com/baskerville/bspwm/wiki/Upcoming-Changes-in-0.9.1 …

**Comment by corkybeta** [comment]
Ok, so the syntax for all bspc commands are broken. Should I manually rewrite my config then? Or have you provided a new one I can adapt?

**Comment by neeasade** [comment]
the examples in this repo have been updated to reflect syntax changes, and there is a table at the bottom of the wiki linked with examples of old vs new.
