### ISSUE TITLE
Panel in background on multihead

### ISSUE THREAD

**Issue by Eisfreak7** [baskerville/bspwm#424]
I have 2 monitors and tried to adapt your example script to keep the panel behind fullscreen windows to my setup.
However, since the bar has one wid per monitor, the example script doesn't work.
This is my solution:
```
sleep 1s
bspid="$(xdo id -N Bspwm -n root | sort | head -n 1)"
IPS="\n"
xdo id -a "bar" | while read wid; do
	xdo above -t "$bspid" "$wid"
done
```
Perhaps it would be a good idea to modify the example script so the next one doesn't have to do this.

Also, is something similar doable with xdotool? I don't really care about the new windowstack feature, I just want the panel behind fullscreen windows. I'd prefer if I didn't need install and keep up-to-date another tool just for this task if it is possible without it.
Edit: I tried it with `xdotool windowraise`, but that apparently doesn't do what I want. I'm not too familiar with X.

**Comment by baskerville** [comment]
Having a true multi-monitor panel example would require to put a bar on each monitor…

AFAIK *xdotool* can't do relative stacking.

**Comment by alecive** [comment]
I agree. This should definitely go into the tutorial! It took me a good half an hour to get this.
