### ISSUE TITLE
Update config issues

### ISSUE THREAD

**Issue by struckoff** [baskerville/bspwm#426]
After update, I got some odd chanches, like window became node (WHY ?), or control option not exists anymore. 

I kinda handled this, but I lost toggle fullscreen/float options. And, more important, Im not able to rotate desktop anymore. I had binding on  ````desktop -R 90````, it worked perfect. So I moved it to  ````node -R 90```` and got nothing. 

PS  ````bspc node @north -R +270```` kinda works, but not like I needed to.

**Comment by cju** [comment]
Of course it doesn't since you're trying to rotate a single node…

Take a look at https://github.com/baskerville/bspwm/issues/419, for exapmle.

**Comment by neeasade** [comment]
https://github.com/baskerville/bspwm/blob/master/doc/CHANGELOG.md

> like window became node (WHY ?)

personally I think this allows for more flexibilty - a 'node' can be a window, desktop, grouping of windows... this allows for better preselection targetting and manuvers in the WM.

**Comment by struckoff** [comment]
Ok ````bspc node @/ -R 90```` works well

but there is still question about statements

**Comment by ttzhou** [comment]
can you be more specific about what you want in regards to "statements"?

also, in general, answers to most of your issues are in the man pages. in particular, there is a different approach to toggling floating and other non-tiling states.
