### ISSUE TITLE
zsh compinit dont like contrib/zsh_completion ownership

### ISSUE THREAD

**Issue by blendi-93** [baskerville/bspwm#427]
using zsh with grmls zsh config.

reproduce:

    git clone "https://github.com/baskerville/bspwm.git"
    cd bspwm
    make
    sudo make install
    su #enter root password

result:

    zsh compinit: insecure files, run compaudit for list.
    Ignore insecure files and continue [y] or abort compinit [n]?...

fix:
add `chown root:root "$(DESTDIR)$(ZSHCPL)"/_bspc` after line 47 in Makefile.

**Comment by baskerville** [comment]
I don't see any *bspwm* issue here.

ZSH suggests something that might provide more details regarding the actual issue though.
