### ISSUE TITLE
Spawn new windows as floating

### ISSUE THREAD

**Issue by fbt** [baskerville/bspwm#428]
There used to be a flag you could set for a desktop to spawn all new windows as floating. Now it's gone. Is there another way to do this? I really, really liked that feature.

**Comment by fbt** [comment]
nvm figured it out with the help of the IRC channel.

**Comment by fbt** [comment]
Nope, I was too hasty.

**Comment by baskerville** [comment]
```
#! /bin/bash

FLOATING_DESKTOP_ID=$(bspc query -D -d '^9')

bspc subscribe node_manage | while read -a msg ; do
    desk_id=${msg[2]}
    wid=${msg[3]}
    [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
```

**Comment by fbt** [comment]
Hmm. Interesting. So the internal mechanism is truly gone huh? Thx, I'll probably write a daemon doing such things.

**Comment by Alkeryn** [comment]
Is it possible to make a shortcut to switch floating / tilling mode
such as windows open in tilling, and by doing said shortcut they now open in tilling until the shortcut is pressed again ?
Also sorry for the up

**Comment by Crysikrend** [comment]
I think @emugel has a good idea for a feature. While I haven't contributed at all I too want this feature and I might have a play to see if I can make a more accessible method of doing this?

**Comment by baskerville** [comment]
This question was already asked in #550.

**Comment by reaper8055** [comment]
> bspc subscribe _node_manage_ | while read -a msg ; do

_node_manage_ throws '**invalid argument**'
I guess, it's changed to '_node_', and hence the updated script would be
 **bspc subscribe node | while read -a msg ; do**

Kindly, correct me if I am wrong.

**Comment by Crysikrend** [comment]
I have a script which I call execute the program I want to float:
```sh
#!/bin/bash
# Open a command in float mode
bspc rule -a \* -o state=floating && $@
```
I'd use it like so: `bspwmfloat urxvt -e ncmpcpp` which opens a terminal with my music player in a floating window. I do this with firefox as well as various other terminal commands. I hope this helps someone!

**Comment by boliwiz** [comment]
I've spend all day trying to make sxhkd launching floating terminal.
I already have "super + Return" for launching alacritty (my terminal). I want it always launch tiled unless I press shift. i added your line of code to my sxhkdrc file and it finally worked. Thank you. 

`super + {_,shift +}Return`
`{alacritty, bspc rule -a \* -o state=floating && alacritty}`

I hope this helps someone too!

**Comment by emanuele6** [comment]
> ```shell
> #! /bin/bash
> 
> FLOATING_DESKTOP_ID=$(bspc query -D -d '^9')
> 
> bspc subscribe node_manage | while read -a msg ; do
>     desk_id=${msg[2]}
>     wid=${msg[3]}
>     [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
> done
> ```

This should be compatible with modern versions of BSPWM (0.9.9):
```shell
#! /bin/bash

FLOATING_DESKTOP_ID=$(bspc query -D -d '^9')

bspc subscribe node_add | while read -a msg; do
    desk_id="${msg[2]}"
    wid="${msg[4]}"
    [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
```

**Comment by xelaushi** [comment]
For anyone that wants to start all windows as floating, I modified the much earlier solution from baskerville to make it work on current versions of *bspwm*:
```bash
#!/bin/bash

bspc subscribe node_add | while read -a msg ; do
    node_id=${msg[4]}
    bspc node "$node_id" -t floating
done
```
You just need to put it into your `bspwmrc` to have it always running, e.g.
```bash
#!/bin/bash

# ... configuration ...

bspc subscribe node_add | while read -a msg ; do
    node_id=${msg[4]}
    bspc node "$node_id" -t floating
done &

# ... more configuration ...
```
