### ISSUE TITLE
Moving a node into a presel split region

### ISSUE THREAD

**Issue by hillna** [baskerville/bspwm#429]
Before 0.9.1 I was able to move a window into a presel region with the following syntax:
`bspc window -w {left.manual,down.manual,up.manual,right.manual}`

I have not been able to find an example for this for 0.9.1. 

Am I able to move an existing node into a presel region?

**Comment by baskerville** [comment]
```
bspc node -n {west,south,north,east}.!automatic
```

In addition, the example `sxhkdrc` provides the following binding:
```
super + y
	bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused
```
