### ISSUE TITLE
bspc node -f east returns success when focus unchanged

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#434]
To move focus on multihead I started using something along the lines of:

```
bspc node -f $DIR || bspc monitor -f $DIR
```

However, after upgrading, this is no longer working when the next monitor’s desktop is empty, as the first command returns success even though focus remains unchanged.

I *think* this was working, either before upgrading from eb209d8 today, or before upgrading from 4b538bc a few days ago. Or maybe I never tried moving focus to an empty desktop (only have multihead since a week or so), though that’s the more unlikely option.

**Comment by neeasade** [comment]
Also having this issue.

**Comment by eigengrau** [comment]
When using `bspc query -N -n east` when there is in fact nothing to the east now seems to report the currently focused node, so I presume this is the reason why the focus command succeeds.

**Comment by eigengrau** [comment]
Thank you kindly!
