### ISSUE TITLE
Node modifier regressions

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#435]
I’ve noticed that, on bfffe8b, selector modifiers produce unexpected results.

After focusing a non-floated window:
```
$ bspc query -N -n focused         
0x01C00003
```

Oddly, adding the floating modifier not only still lists the unfloated window, but lists additional nodes as well.
```
$ bspc query -N -n focused.floating
0x00E0000F
0x02000022
0x01C00003
```

```
$ bspc query -N -n focused.floating.leaf 
0x00E0000F
0x02000022
0x01C00003
```

**Comment by baskerville** [comment]
Fixed by 3e60b44.
