### ISSUE TITLE
Monitor-selector not recognized in bspc desktop, bspc query

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#436]
Unless I’m misreading the man page, it should be okay to prefix a desktop selector with a monitor selector. However, when attempting to use this (bfffe8b), an error is reported:

```
$ bspc desktop next:Somedesktop -r
desktop: Invalid descriptor found in 'next:Somedesktop'
$ bspc query -D -d next:Somedesktop
query -d: Invalid descriptor found in 'next:Somedesktop'.
```

**Comment by baskerville** [comment]
You're misreading the manual: the `MONITOR_SEL:` prefix is only valid for `focused` and `^<n>`.

**Comment by eigengrau** [comment]
Oh, thanks. Indeed, I’ve misread the parentheses. And I guess it didn’t make much sense seeing that desktops are assumed to be named quasi-uniquely. I plead beginning-of-DST induced tiredness.
