### ISSUE TITLE
moving a desktop and focusing it seems to be broken

### ISSUE THREAD

**Issue by insanum** [baskerville/bspwm#437]
With the latest version of bspwm this command is broken:
```
bspc desktop <DESK_SEL> -m focused -f
```
This command used to work. It would move the specified desktop to the currently focused monitor and then focus it. Now what happens is the specific desktop does get moved but it is never focused. Maybe I'm missing something with the various recent syntax changes.

**Comment by baskerville** [comment]
Fixed by 3e60b44.
