### ISSUE TITLE
Not work rotate

### ISSUE THREAD

**Issue by ithamsteri** [baskerville/bspwm#438]
Before I used command `bspc desktop -R 90` for rotate nodes in current desktop. Now in current version bspwm I use `bspc node -R 90`, but I get empty message in stdout and not rotate nodes in current desktop.

Bspwm version: `0.9.1-10-g3e60b44`
Commit: 3e60b44c29af9bf3147b85aba7bf562d66728899

**Comment by neeasade** [comment]
you need to specify the root node/desktop with a node selector like `@/`, eg `bspc node @/ -R 90`

**Comment by ithamsteri** [comment]
@neeasade Thanks! This work. I thought that the selector is optional. Need more understandable documentation. ;)

**Comment by neeasade** [comment]
I believe it is marked as such because a `node` isn't restricted to being a desktop -- the path notation helps indicate that.

**Comment by baskerville** [comment]
@ithamsteri The selector *is* optional and defaults to the focused node.
