### ISSUE TITLE
Presel fills the window :: borders only option

### ISSUE THREAD

**Issue by mariolima** [baskerville/bspwm#439]
I just upgraded to 0.9.1 but now _presel_ fills the window with a color. I wonder if there is a way to disable that and revert it to the old way where only the borders are _preseled_. This feature can be anoying at times when I'm waiting for a processes that is going to create a window to finish its job, I can't see half the information on screen when the window is _Preseled_.

**Comment by blendi-93** [comment]
alrdy asked:
https://github.com/baskerville/bspwm/issues/340
https://github.com/baskerville/bspwm/issues/420

>  baskerville commented on 23 Dec 2015
>
>I'm not sure if you've noticed, but you can preselect internal nodes (node @parent -p east). >It makes the border based feedback rendering approach useless.
>
>I would recommend, though, to make the preselection feedbacks semi-transparent.

>This can be achieved with the following compton rule:
>
>opacity-rule = [ "63:class_g = 'Bspwm' && class_i = 'presel_feedback'" ];
>
>where 63 is the opacity percentage.

**Comment by catzybluphish** [comment]
@baskerville Is the `&& class_i = 'presel_feedback'` part required? I've ommitted it and the transparency still works.
