### ISSUE TITLE
Multiple bspc commands not doing anything

### ISSUE THREAD

**Issue by Nycrea** [baskerville/bspwm#440]
After updating I noticed most of my sxhkdrc had to be rewritten. After doing so and looking through the updated manual pages for bspc, I noticed that node -B and node -R 90 don't do anything, even though they are listed in the manual.

**Comment by blendi-93** [comment]
node -B and node -R 90 used for nodes now.

if u use ``bspc node -R 90`` u only rotate the current selectd/focused node

if u want to rotate ur windows on current desktop u have to use:
    bspc node @focused:/ -R 90

or if u want to balance ur windows use:
    bspc node @focused:/ -B

**Comment by Nycrea** [comment]
Thank you, it is indeed working as inteded now.
