### ISSUE TITLE
  bspc node -t not working correctly

### ISSUE THREAD

**Issue by JSpeedie** [baskerville/bspwm#441]
the default "super + s" (and "super + f", and I'm assuming any other attempt you make at toggling a windows state with bspc node -t) to toggle between tiling/floating and tiling/fullscreen no longer work correctly. Toggles **to** the specified state correctly, but does not revert to the previous state like it used to/claims to in the docs. This means once you make a window fullscreen or floating, the only way to get it back to tiling is to manually type in a command (like bspc node -t tiling) or make another bind used specifically for making the selected window ("node") tiling. I don't want another bind for that; it's absurd. Not sure if this is intentional or just something forgotten in the shift from bspc window to bspc node, but it'd be cool to see this resolved.

Side note: --toggle-visibility was removed in an update somewhere along the line (I don't really pay attention to the updates of this repo (or any for that matter), but I'm assuming it was in the same update that removed bspc window).
**Warning:** mini rant. I'm just wondering why so much had to be changed and you couldn't have just kept some of the commands for legacy support. I just did a fresh install and like half of my stuff didn't work because of all these changes. I got some really strange "bugs" because of some of them. For example, my workspace output (the workspace stuff on my bar) had the divider I use (to show where a set of desktops ends for one monitor and begins for another) showing when I was in some desktops, but I switched to like the 3rd desktop on my one monitor, and it disappeared. Turns out the output for bspc wm --get-status is not quite the same as bspc control --get-status was. Other issues I had was that I couldn't close any windows because of the command syntax change. None of my binds worked. I understand that "node" makes more sense as a name, but why get rid of bspc window? You could have just never updated anything for bspc window to try to persuade people to switch to using bspc node, but why remove "window" completely? I don't get it. And --toggle-visibility. I don't understand where this went either. I don't use it often, but when I want to and it's not there, it really sucks. I'm sure other people really miss it too. I may be missing the fact that perhaps you added better ways of achieving the functionality of --toggle-visibility through some new commands you added or something, but yet again this makes me wonder why you removed it at all and didn't just keep it for legacy support. I don't get why anything was removed tbh. I'd really like to know why you decided to not have any form of legacy support. /rant.

**Comment by ikn** [comment]
You can toggle by prefixing the state with `~`, but since the state has more than 2 possible values, toggling must be implemented using history.  This means that if a window starts floating, and you toggle it using `~floating`, its state won't change because there's no 'previous' state to toggle to.  For this reason, I use the following _sxhkd_ binding for toggling the focused window between floating/tiled states:

```
super + f                                                                       
    if [ -z "$(bspc query -N -n focused.floating)" ]; then \                    
        bspc node focused -t floating; \                                        
    else \                                                                      
        bspc node focused -t tiled; \                                           
    fi
```

**Comment by JSpeedie** [comment]
That's so absurd though. The docs claim that -t will toggle to the previous state. I spawn my window in and it's tiling, I make it floating, but it won't go back to tiling. We shouldn't have to write some multiline if statement for something that isn't working like the docs claim it should :/

**Comment by neeasade** [comment]
>The docs claim that -t will toggle to the previous state.

The docs say that `-t` sets the state of the window, with the optional `~` parameter to set to last state. Under node: 

```
           -t, --state [~](tiled|pseudo_tiled|floating|fullscreen)
               Set the state of the selected window. If ~ is present and the current state matches the given state, then the argument is
               interpreted as the last state.
```

**Comment by JSpeedie** [comment]
Hm I didn't notice that. Still though, this worked before whatever update changed it and I'm just slightly annoyed by that.

Nonetheless, I'll try ~. Thanks!

**Comment by baskerville** [comment]
*bspwm* uses semantic versioning: [“Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.”](http://semver.org/#spec-item-4)

What's absurd is the amount of disrespect I receive from people who don't even bother to read the docs.

**Comment by ikn** [comment]
Oh, I didn't even realise that.  Maybe consider putting a notice about the major version 0 thing at the top of the readme or something?

**Comment by JSpeedie** [comment]
I'm sorry I didn't read the docs as thoroughly as I should have and I'm sorry if I came off disrespectful. But I had absolutely no intention of sounding - in any way - disrespectful, although I will admit that my second comment was without-thought. With that being said, I stand by what I said. Having another key bind that is used exclusively for making a selected window tiled is absurd. And in my eyes, so is having 5 lines of code for something that was easy to achieve in 1 line previously. Luckily, neither of these are needed as pointed out by @ikn and @neeasade. Regardless, I apologize for coming off arrogant, but it's really just me being salty about some extra work being added to my Friday that I wasn't expecting. 

P.S. I'd still like to know what happened to --toggle-visibility :S
