### ISSUE TITLE
bspc "Unknown command" everytime

### ISSUE THREAD

**Issue by Celes-Eternal** [baskerville/bspwm#442]
Hello,

When i run bspc, i always just have "Unknow command", even with commands from the default config.
In fact i was able to modify gaps, that's all.
I don't really know where i must look to resolve this.
Any ideas?

Thanks

Ps : I'm on Gentoo / amd64 no multilib

**Comment by Stebalien** [comment]
Which config are you using and which version of bspwm?

**Comment by Celes-Eternal** [comment]
Default config from this git. Version 0.9.1.
I don't know if this can help, but now i even can change the focus (I only focus the last window open).

**Comment by neeasade** [comment]
the default config and commands have changed -- ie the default config from 0.9 is not compatible with 0.9.1. bspc now fails verbosely, letting you know that the 'old' commands are now unknown (if that is your issue)

**Comment by Celes-Eternal** [comment]
I don't see the message (recent update?), but seems you're right, a lot of command are back. I have still have some problem, but no more "unknown command".
Thanks
