### ISSUE TITLE
Unknown domain or command: 'pointer'.

### ISSUE THREAD

**Issue by Makpoc** [baskerville/bspwm#446]
Hi,
I'm sure I'm missing something but after I upgraded to 0.9.1 (archlinux - aur package. bspwm -v yelds 0.9.1.12-g12edac8). Unfortunatelly after changing most of the configurations I'm stuck with something that does not seem to be changed. I have the following two mappings in my sxhkdrc file:
```
~button1
    bspc pointer -g focus
 
 super + button{1-3}
    bspc pointer -g {move,resize_side,resize_corner}
```
but neither of them works. When trying to run any of the commands manually it says that pointer is an unknown domain or command. Did this change in any of the updates between 0.9 and 0.9.1+?

I have set click_to_focus to true, but it does not help in any way.

Edit:
Maybe it has something to do with this commit: https://github.com/baskerville/bspwm/commit/12edac86fa3be32f799bedca4c8f5c0287a735b0 , but what is the alternative?

**Comment by baskerville** [comment]
The solution is simple: remove those lines from your `sxhkdrc`.
