### ISSUE TITLE
CTRL/ALT + mouse click are not registered by the application

### ISSUE THREAD

**Issue by Makpoc** [baskerville/bspwm#447]
Hello,
After the upgrade to 0.9.1 and after fixing my pointer problem ( #446 , thanks for that ) I noticed that when trying to use CTRL + button 1 the action is not registered. First I noticed it in Intellij (ctrl + button1 is _open definition_). When pressing the CTRL key the method inder coursor is highlighed as if the click will open it, but clicking on it does nothing.

I noticed the same problem in Firefox with both CTRL and ALT. The links are not opened at all.

**Comment by baskerville** [comment]
Should be fixed by 0042db1.

**Comment by Makpoc** [comment]
Thank you again. I will update and confirm soon.

**Comment by Makpoc** [comment]
I can confirm that it's fixed with 0.9.1-25-g73e402e. Thank you for the fast response and fix!
