### ISSUE TITLE
issue with mouse input to windows

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#451]
0.9.1-25-g73e402e

on a tiling desktop, with focus follows pointer:
- open up a terminal (I'm using a [st fork](https://github.com/neeasade/shit))
- move cursor to where next window will spawn
- play something with mpv from terminal
- mpv window is focused because it's under cursor
- without moving the cursor, click/scroll over mpv window -- they won't reach the window

after you move the cursor at all, click/scrolling works.

**Comment by baskerville** [comment]
Fixed by 2b2ed4eb56c728c24f7e8c5a6b1d08ab0e2aea9c.
