### ISSUE TITLE
setting flags on desktops by ID?

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#453]
side note nice issue sweep :+1: 

I can't `bspc node $(bspc query -D -d) -g hidden=on` but I can `bspc node @/ -g hidden=on`

**Comment by baskerville** [comment]
`DESK_SEL` isn't a node selector, but `@[DESK_SEL:]/` is.

Here's an example for toggling the hidden flag of the root of each desktop:
```
for id in $(bspc query -D); do bspc node @${id}:/ -g hidden; done
```
