### ISSUE TITLE
Disappearing Desktops

### ISSUE THREAD

**Issue by djsissom** [baskerville/bspwm#455]
This is similar to issue #140, which was resolved at the time, but now seems to have regressed.

I have three main monitors, with a forth connection (HDMI-0) going to an AV receiver/TV that gets turned on and off.  The TV mirrors the center monitor.  When I start BSPWM without the TV on, then turn it on and activate it with `xrandr --output HDMI-0 --auto --same-as DVI-I-1`, all unoccupied desktops on the middle monitor are destroyed.  Likewise, if I start BSPWM with the TV on and then turn it off, the middle monitor unoccupied desktops are destroyed.

I think this is similar to the issue I had in #140 which was fixed with the `bspc config persistent_monitors` and `bspc config merge_overlapping_monitors` options set to true.  I upgraded my arch linux bspwm package a few days ago from 0.9-2 to 0.9.1-2, which introduced the regression.  I have now switched back over to the latest git version 0.9.1-37-g0cfe1f3 and the problem persists.

I noticed the new option `bspc config remove_unplugged_monitors` that should have replaced persistent_monitors, and have both it and `bspc config remove_disabled_monitors` set to false.  I still have `bspc config merge_overlapping_monitors` set to true.

Running `bspc query -M` gives 
`0x00800003
0x00800001
0x00800005`
when first starting up BSPWM, but then something like
`0x00800003
0x0080001A
0x00800005`
after activating the TV.

Thanks in advance.

**Comment by djsissom** [comment]
To add to this, once the TV is activated with `xrandr`, every time the TV is physically turned on or off, all the desktops that are unoccupied at that time are destroyed, not just the first time the TV is activated.

**Comment by neeasade** [comment]
if remove_unplugged_monitors is set to true, desktops on monitors that are
unplugged get merged into still open monitors -- maybe try setting those?
the overlapping monitor option would be for monitors whose dimensions
overlap, not mirrored monitors (if that was your impression)

On Wed, Apr 27, 2016 at 9:55 AM, djsissom <notifications@github.com> wrote:

> To add to this, once the TV is activated with xrandr, every time the TV
> is physically turned on or off, all the desktops that are unoccupied at
> that time are destroyed, not just the first time the TV is activated.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/baskerville/bspwm/issues/455#issuecomment-215109803>
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by djsissom** [comment]
No change with setting `remove_unplugged_monitors` and `remove_disabled_monitors` to either true or false.  Empty desktops still disappear.

Setting `merge_overlapping_monitors` to false produces strange results, where there are two sets of desktops that are both visible on the middle monitor and mirrored TV.  So, e.g., opening a window on monitor 1, desktop 1, will show up on both displays.  Switching to monitor 2, desktop 1 and opening a window will cause that window to show up on top of the window opened on monitor 1, desktop 1 (again visible on both screens).  Now with monitor 2 still selected and switching to monitor 2, desktop 2, the second created window disappears and the original window from monitor 1, desktop 1 is still visible.  Anyway, long story short, `merge_overlapping_monitors` seems necessary for my use case.
