### ISSUE TITLE
Clicking with extra mouse buttons

### ISSUE THREAD

**Issue by djsissom** [baskerville/bspwm#456]
Changing the way pointer actions are handled no longer allows (I think) for extra mouse buttons to register click events.  With the old setup, I had a thumb button mapped to select and close a window with
```
button10
    bspc pointer --grab focus; bspc node --close
```

Now that only buttons 1-3 have pre-defined actions, the `pointer --grab focus` doesn't do anything and the currently active window is closed instead of the one under the pointer.

Would it be possible to either add the old pointer behavior back or add a separate command to select the node under the cursor?

Thanks!

**Comment by gavsiu** [comment]
I just wanted to make sure you're having the same issue I am so I don't create a duplicate ticket.

I came from the official Arch repo for bspwm and decided to reinstall from github. I can no longer click to focus windows. That's basically what's happening isn't it?

**Comment by djsissom** [comment]
Not quite, but hopefully yours is an easy fix.  Before a recent commit, you would define the mouse events in your sxhkdrc.  So you would have a mouse button mapped to `bspc pointer --grab focus`, for example.  Now the pointer behaviour is more built in, but you have to enable the options in your bspwmrc.  You'll want to set `bspc config click_to_focus` to true and probably set `bspc config pointer_modifier` to whatever mod key you want to use for dragging/resizing.

My problem is that, now that the pointer behaviour is more built in and don't have `bspc pointer` commands, I can no longer assign clicking events to mouse buttons other than left-, middle-, or right-clicking.  So all my extra fancy mouse buttons are no longer usefully programmable through sxhkdrc.
