### ISSUE TITLE
Can no longer switch between nodes while drag-and-dropping items

### ISSUE THREAD

**Issue by d125q** [baskerville/bspwm#458]
Previously, I could switch between nodes (most notably clients) while drag-and-dropping things such as files from a file manager (Nautilus) or tabs from a web browser (Firefox).  With the recent batch of commits I can no longer do that, which is somewhat of an inconvenience.

**Comment by baskerville** [comment]
What are the steps to reproduce?

**Comment by d125q** [comment]
Open Nautilus on one desktop, and some other program, i.e., Firefox on another.  Begin dragging a file from Nautilus, and try to switch to Nautilus' desktop by whatever means.  You won't be able to anymore (previously it worked just fine).

**Comment by baskerville** [comment]
I've tried with *Thunar* and *Firefox*:

- I can drag from *Thunar* to something else while changing the focus.
- But I can't do the same with *Firefox*.

In both cases, *bspwm* isn't involved.

What happens is that *Firefox* grabs the keyboard (while grabbing the pointer) in synchronous mode, and *Thunar* in asynchronous mode.

**Comment by d125q** [comment]
Everything used to work fine previously.  Could it be a sxhkd issue?

**Comment by baskerville** [comment]
So, *Nautilus* is immutable?

More seriously, if *everything used to work fine*, what's the culprit commit?

**Comment by sg3des** [comment]
I already wrote about this problem:

drag file(text document) from Thunar to Mousepad: focus remain on Thunar... 
Thunar -> SublimeText, Thunar -> terminal  - same

drag selected text from Mousepad to another window Mousepad - focus aslo remain on prev window...

**Comment by d125q** [comment]
The issue is indeed caused by Nautilus.  Dolphin works fine.

**Comment by sg3des** [comment]
What? you are not right! i have this bug everywhere - mousepad, thunar, firefox. 
Because of this issue, I was compelled rollback to my older forked version!

**Comment by neeasade** [comment]
@sg3des the issue you mentioned is separate. It is a focus issue vs
inability to drag and drop at all.

On Tue, May 10, 2016 at 8:43 AM, Valeriy Bdtaev <notifications@github.com>
wrote:

> What? you are not right! i have this bug everywhere - mousepad, thunar,
> firefox.
> Because of this issue, I was compelled rollback to my older forked version!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/baskerville/bspwm/issues/458#issuecomment-218160988>
>



-- 
Nathan Isom
Computer Science
Kansas State University
