### ISSUE TITLE
Fish Completion

### ISSUE THREAD

**Issue by addisonamiri** [baskerville/bspwm#459]
Is there anyone experienced in writing fish shell completions that could write one for BSPWM? I was going to take a whack at it but the syntax looks a bit weirder than what I'm used to.

**Comment by neeasade** [comment]
Perhaps take a look at https://github.com/mbrubeck/compleat ?

On Tue, Apr 19, 2016 at 1:52 AM, Addison Amiri <notifications@github.com>
wrote:

> Is there anyone experienced in writing fish shell completions that could
> write one for BSPWM? I was just looking at the syntax and it seems like a
> doozy.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/baskerville/bspwm/issues/459>
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by neeasade** [comment]
This appears to work for me, tested briefly with vanilla fish shell.

Disclaimer: Primarily a bash/zsh user.

``` fish
function __fish_bspc_needs_command
  set cmd (commandline -opc)
  if [ (count $cmd) -eq 1 -a $cmd[1] = 'bspc' ]
    return 0
  end
  return 1
end

function __fish_bspc_using_command
  set cmd (commandline -opc)
  if [ (count $cmd) -gt 1 ]
    if [ $argv[1] = $cmd[2] ]
      return 0
    end
  end
  return 1
end

complete -f -c bspc -n '__fish_bspc_needs_command' -a 'node desktop monitor
query rule restore wm subscribe config quit'
complete -f -c bspc -n '__fish_bspc_using_command config' -a
'external_rules_command status_prefix normal_border_color
active_border_color focused_border_color presel_feedback_color border_width
window_gap top_padding right_padding bottom_padding left_padding
split_ratio initial_polarity borderless_monocle gapless_monocle
single_monocle pointer_modifier pointer_action1 pointer_action2
pointer_action3 click_to_focus focus_follows_pointer pointer_follows_focus
pointer_follows_monitor ignore_ewmh_focus center_pseudo_tiled
honor_size_hints remove_disabled_monitors remove_unplugged_monitors
merge_overlapping_monitors'

# vim: set ft=fish:
```

On Fri, May 6, 2016 at 8:57 AM, Nathan Isom <nathanisom27@gmail.com> wrote:

> Perhaps take a look at https://github.com/mbrubeck/compleat ?
>
> On Tue, Apr 19, 2016 at 1:52 AM, Addison Amiri <notifications@github.com>
> wrote:
>
>> Is there anyone experienced in writing fish shell completions that could
>> write one for BSPWM? I was just looking at the syntax and it seems like a
>> doozy.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/baskerville/bspwm/issues/459>
>>
>
>
>
> --
> Nathan Isom
> Computer Science
> Kansas State University
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by neeasade** [comment]
Attaching as paste because email isn't working so hot.

paste: https://ptpb.pw/qlMA/fish
