### ISSUE TITLE
Directional focus has stopped working between monitors

### ISSUE THREAD

**Issue by rr-** [baskerville/bspwm#460]
```
   screen 1      screen 2
+------------+-------------+
|            |  win | win  |
|  window 1  |  dow | dow  |
|            |   2  |  3   |
+------------+-------------+
```

I can `bspc node -f east` from `window 2` to `window 3` just fine, but trying to `bspc node -f west` from `window 2` to `window 1` gives exit code 1. On another note, it prints nothing, which sort of breaks #402.

I'm on ~~`0.9.1-32-g828c93f`~~ `0.9.1-41-g4bf21bd`.

**Comment by neeasade** [comment]
can confirm (no error message).

you might try something like the following:
``` sh
super +  {h,j,k,l}
    bspc node -f $dir || bspc monitor -f $dir; \
```

**Comment by rr-** [comment]
Thanks @neeasade, I've settled for

```
super + h
    bspc node -f west || bspc monitor -f west
super + j
    bspc node -f south || bspc monitor -f south
super + k
    bspc node -f north || bspc monitor -f north
super + l
    bspc node -f east || bspc monitor -f east
```

since 

```
super + {h,j,k,l}
    bspc node -f {west,south,north,east} || bspc monitor -f {west,south,north,east}
```

worked kind of funny due to the way token expansion works.

**Comment by baskerville** [comment]
I've removed this hardwired behavior because it can be achieved with the following binding:
```
super + {h,j,k,l}
	DIR={west,south,north,east}; \
	bspc node -f $DIR || bspc monitor -f $DIR
```
`node -f` fails because there's no matching windows and [I don't print error messages for this](http://www.linfo.org/rule_of_silence.html).

See #380 for a discussion on how DIR should behave in the 1+ monitors case.

**Comment by bcspragu** [comment]
What would be the equivalent way of replicating this behavior but for cross-monitor swaps (-s) instead of focusing (-f), the way super + shift +{h,j,k,l} was originally mapped. `bspc node -s $DIR || bspc monitor -s $DIR` doesn't work, nor does `bspc node -s $DIR || bspc desktop -s $DIR`
