### ISSUE TITLE
presel + focus_follows_pointer causes new window to not gain focus

### ISSUE THREAD

**Issue by Stebalien** [baskerville/bspwm#464]
**To reproduce:**

0. Enable focus_follows_pointer
1. Open a window.
2. Presel the window and put the cursor over the presel region.
3. Open another window (with a hotkey, without focusing anything else).

**Expected behavior:**

The new window is focused.

**Actual Behavior:**

The old window retains focus.

Note, this only happens if the cursor is over the presel region.

**Comment by neeasade** [comment]
I had a very similar issue recently filed and resolved, are you on latest?

**Comment by Stebalien** [comment]
No... (*sigh*)
