### ISSUE TITLE
bspc query --tree no longer works

### ISSUE THREAD

**Issue by shelvacu** [baskerville/bspwm#465]
There currently no easy way to get information about all monitors, useful for status scripts. It used to be I could just do `bspc query --tree` and I'd get a list of all the monitors and their desktops and their nodes. Now it insists that I specify a monitor, which means I first have to get a list of monitors and then run the command for each monitor.

Can we get `bspc query --tree` back? Please?

**Comment by baskerville** [comment]
`bspc wm -d`
