### ISSUE TITLE
Getting stuck with history_aware_focus

### ISSUE THREAD

**Issue by tsuflux** [baskerville/bspwm#467]
Thank you for fixing #466 this quick. I am experiencing another bug: When `history_aware_focus` is activated and I am in the configuration below I can only focus 1 and 4 or 2 and 3, i.e. one of the diagonals when using `bspc node -f {west,south,north,east}`.

```
+-----------------------+
|           |           |
|     1     |     2     |
|           |           |
|-----------|-----------|
|           |           |
|     3     |     4     |
|           |           |
+-----------------------+
```

**Comment by d125q** [comment]
I can confirm.
