### ISSUE TITLE
Issues with Steam windows

### ISSUE THREAD

**Issue by xintron** [baskerville/bspwm#468]
I have some issues with certain Steam windows opening where the size and behavior is not as expected. The window opens in a very small floating node and clicking it automatically focus the main steam window (and the desktop it is on) thereby switching away from the current desktop shown on that monitor.

I'm not sure if this is Steam behaving weirdly (I've had issues with steam and xmonad as well but not this weird) so feel free to give any input available to this issue and close it if it's not considered a bspwm problem per say.

Screenshot showing the minimal window (and clicking it will swap to the desktop to where the main Steam window is). 
![1462016799](https://cloud.githubusercontent.com/assets/40586/14935691/e64d244a-0eda-11e6-9d37-4bcef9f6620a.png)

**Comment by neeasade** [comment]
Out of curiosity, does `bspc config honor_size_hints true` change this?

On Sat, Apr 30, 2016 at 6:54 AM, Marcus Carlsson <notifications@github.com>
wrote:

> I have some issues with certain Steam windows opening where the size and
> behavior is not as expected. The window opens in a very small floating node
> and clicking it automatically focus the main steam window (and the desktop
> it is on) thereby switching away from the current desktop shown on that
> monitor.
>
> I'm not sure if this is Steam behaving weirdly (I've had issues with steam
> and xmonad as well but not this weird) so feel free to give any input
> available to this issue and close it if it's not considered a bspwm problem
> per say.
>
> Screenshot showing the minimal window (and clicking it will swap to the
> desktop to where the main Steam window is).
> [image: 1462016799]
> <https://cloud.githubusercontent.com/assets/40586/14935691/e64d244a-0eda-11e6-9d37-4bcef9f6620a.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/baskerville/bspwm/issues/468>
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by xintron** [comment]
@neeasade It does not work with `honor_size_hints true`. It still behaves the same. If Desktop 1 is focused it will pop up there (as a tiny window). Clicking the window (anywhere, even the close button gives this behavior) focuses the Desktop where the main steam window is (desktop 5 in my case).

Another weird issue is: running `bspc node --close` on the chat window triggers a shutdown of steam completely (as if it was issued in the Main steam window).

**Comment by xintron** [comment]
Found some more information about the Steam client and issues with WM's on Linux: https://github.com/ValveSoftware/steam-for-linux/issues/1040. Due to that it's hard to say if there is any issue with bspwm per say or if everything is related to their issues or if there is also something to be done within bspwm.

In my opinion this can be closed until Steam has implemented proper window handling.

**Comment by Lindenk** [comment]
But...that will never happen!

**Comment by maplepy** [comment]
As you said @Lindenk still hasn't happened yet
