### ISSUE TITLE
Some applications are not starting in state=tiled

### ISSUE THREAD

**Issue by edeustua** [baskerville/bspwm#469]
After the last couple updates, some of the applications are starting in state=floating by default. Moreover, even if I try to add a rule to explicitly force an application to start tiled, it wont work. It happens to me with mostly with zathura and libreoffice. I'm going to dig into this later this week, but am I missing something simple here? 

Thank in advance for any response.

**Comment by neeasade** [comment]
can't confirm.

`bspc rule -a Zathura state=tiled` ?

**Comment by edeustua** [comment]
Yes,

`zathura:* => state=tiled`

And I also tried Zathura but both are in wm_class.

**Comment by baskerville** [comment]
There's two problems with *WM_CLASS*:
- Despite its name, it contains both the class and the instance name.
- It starts with the instance name.

The correct rule is given by @neeasade.

**Comment by edeustua** [comment]
I knew it was a dumb thing. I remember trying with Zathura without luck before, though.

Anyway, I'm sorry for wasting your time.

Thank you very much.

**Comment by MrZammler** [comment]
Hi, sorry to hijack the thread, but I have a similar problem. Running latest git bspwm.

Whatever I try, I can't get libreoffice to start in tiled mode. It does so when I run it as standalone application, but not when opened through clicking a file in thunar (or a link in firefox etc). In the second case, it always starts in floating mode.

I've tried various combinations of the following without luck:

evas@winterland ~ $ bspc rule -l
Emacs:* => state=tiled
libreoffice:* => state=tiled
Libreoffice:* => state=tiled
libreoffice-writer:libreoffice => state=tiled
libreoffice:libreoffice-writer => state=tiled

Thanks!

**Comment by nick-ulle** [comment]
I'm having the same problem as @MrZammler. LibreOffice refuses to start in tiled mode even with explicit rules.
