### ISSUE TITLE
Using mouse to move windows

### ISSUE THREAD

**Issue by jamietanna** [baskerville/bspwm#470]
As of baskerville/sxhkd@674bb7c0db701a64760627861ca2898aedd037d0 and baskerville/bspwm@12edac86fa3be32f799bedca4c8f5c0287a735b0, the functionality to move/resize windows using the mouse bindings has been removed.

Is there any replacement for this that can be used, or is there another way you can recommend getting this functionality back?

**Comment by neeasade** [comment]
``` txt
 pointer_modifier
           Keyboard modifier used for moving or resizing windows. Accept the following values: shift, control, lock, mod1, mod2, mod3, mod4, mod5.

       pointer_action1, pointer_action2, pointer_action3
           Action performed when pressing pointer_modifier + button<n>. Accept the following values: move, resize_side, resize_corner, focus.
```

**Comment by jamietanna** [comment]
Oh thanks @neeasade! Also it looks like the main issue I had was that I was running sxkhd from the development version, but BSPWM from the Arch repos.
