### ISSUE TITLE
Feature request: presel modifier

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#471]
For querying node ID's that have presels active. 

Current solution with jq:
``` bash
bspc query -T -d | jq  '.. | .root?, .firstChild?, .secondChild? | select (.presel != null) | .id' 
```

**Comment by baskerville** [comment]
Maybe `query -N -d -n .!automatic`?

**Comment by neeasade** [comment]
Ha! yes. I was searching man page for `presel`. Thanks.
