### ISSUE TITLE
query windows within a node path

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#473]
Is there a way to query for window ID's within current focused node path? If I have a focused node with 2 children(both windows) would think something like one of the following might work: 
`bspc query -N -n @/.window`, `bspc query -N -n focused.window` -- alternatively I can `bspc query -T -n` and parse, was curious if I missed something. 

edit: command corrections. 

edit2: Here's the jq query I'm using for posterity: 

``` bash
 bspc query -T -n | jq '.. | .?, .root?, .firstChild?, .secondChild? | select (.client != null) | .id'
```

**Comment by baskerville** [comment]
As of e471298: `query -N -n .descendant_of.window`.

**Comment by neeasade** [comment]
Excellent, thanks.
