### ISSUE TITLE
desktop node loses focus on 4th manual/presel signal

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#474]
If I `bspc node -f @parent` up to the desktop (or any other node parent above 1 window), then `bspc node -p DIR` 4 times in varying directions, on the 4th time the `node -p` gets sent to a window node in the parent instead of to the parent itself. The 3rd manual/presel remains on the parent.

**Comment by baskerville** [comment]
I can't reproduce.

**Comment by neeasade** [comment]
Will update with more details/keybinds this evening (~8 hours)

On Mon, May 9, 2016 at 3:46 AM, Bastien Dejean <notifications@github.com>
wrote:

> I can't reproduce.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/baskerville/bspwm/issues/474#issuecomment-217808961>
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by neeasade** [comment]
When trying to consistently reproduce, I realized it was because I had `bspc focus_follows_pointer` set and it would change the focused node, causing the above to occur.
