### ISSUE TITLE
bspc node -v does not work

### ISSUE THREAD

**Issue by Djent-** [baskerville/bspwm#479]
`bspc node -v 20 0` as shown in the [docs](https://github.com/baskerville/bspwm/blob/master/doc/bspwm.1.asciidoc) and in the [example sxhkdrc](https://github.com/baskerville/bspwm/blob/master/examples/sxhkdrc) (all the way at the bottom) do not work. Running `bspc node -v 20 0` from a focused floating terminal shows `Invalid syntax.` The docs say `If NODE_SEL is omitted, focused is assumed.`

My sxhkdrc for reference is [here](https://github.com/Djent-/arch-config-2015/blob/2016/sxhkdrc).

**Comment by neeasade** [comment]
Can't confirm. What is your bspwm version?

On Fri, May 13, 2016 at 9:36 AM, Djent- <notifications@github.com> wrote:

> bspc node -v 20 0 as shown in the docs
> <https://github.com/baskerville/bspwm/blob/master/doc/bspwm.1.asciidoc>
> and in the example sxhkdrc
> <https://github.com/baskerville/bspwm/blob/master/examples/sxhkdrc> (all
> the way at the bottom) do not work. Running bspc node -v 20 0 from a
> focused floating terminal shows Invalid syntax. The docs say If NODE_SEL
> is omitted, focused is assumed.
>
> My sxhkdrc for reference is here
> <https://github.com/Djent-/arch-config-2015/blob/2016/sxhkdrc>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/baskerville/bspwm/issues/479>
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by Djent-** [comment]
bspwm -v
`0.9.1`
sxhkd -v
`0.5.6`

**Comment by neeasade** [comment]
You are referencing the _master_ branch docs while using _0.9.1_.

Switching to that tag shows:
https://github.com/baskerville/bspwm/blob/0.9.1/examples/sxhkdrc#L119

On Fri, May 13, 2016 at 9:57 AM, Djent- <notifications@github.com> wrote:

> bspwm -v
> 0.9.1
> sxhkd -v
> 0.5.6
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/baskerville/bspwm/issues/479#issuecomment-219067916>
>



-- 
Nathan Isom
Computer Science
Kansas State University
