### ISSUE TITLE
bspc node -d '^{1-9}' does nothing

### ISSUE THREAD

**Issue by tmathmeyer** [baskerville/bspwm#481]
I can send to the desktops by name, however the index no longer works. I don't see anything about this in the changelog. 

*I had mixed up what was going wrong before, so I've edited it to be a correct description of my errors.

**Comment by baskerville** [comment]
I can't reproduce.

Please provide the following information:
- Output of `bspwm -v`.
- Content of `bspwmrc`.
- Steps to reproduce the problem.

**Comment by tmathmeyer** [comment]
version: 0.9.1-69-g0b56bde (built from git)
bspwmrc: https://gist.github.com/tmathmeyer/ec1ff5f2e3378103ed21f88680c99848
relevant section of sxhkdrc: https://gist.github.com/tmathmeyer/6d6b43c1d5b66abe9317c294456250d1

All I do is open a terminal in an empty desktop (id:4) so that it is the only node. Then in the terminal, I run
```
bspc node -d '^1'
```
The window does not move to that desktop. 

I've created a screen recording of what I'm doing, if that helps: http://files.tmathmeyer.me/bspwm_bug.mp4

**Comment by baskerville** [comment]
Unfortunately, I still can't reproduce.

Could you provide the output of:

- `bspc query -D -d '^1'`.
- `bspc subscribe monitor desktop node`.
- `xev -root`.

?

Ultimately, you might debug this by setting a breakpoint at `messages.c:177`…

**Comment by tmathmeyer** [comment]
bspc query -> web
bspc subscribe -> no output, exits
xev -root -> hangs, no output

Interestingly enough, after killing and restarting X, it came back. All of my versioning information is the same, I suspect that there is some issue. If I can reproduce it, I will debug it then.
