### ISSUE TITLE
Show window focus in tree

### ISSUE THREAD

**Issue by dj95** [baskerville/bspwm#483]
For proper window handling in status bar, `bspc query -T -d` should show if a window is focused or not. Or is there another way to fetch the window focus with the window tree?

PS.: For what is the `icccmFocused`-key? It seems to be always `False`.

**Comment by dj95** [comment]
I found the `focusedNodeId`-key  in the root of the tree. But anyway it would be much cleaner, if the nodes have a key, which determines if they are focused or not.

**Comment by neeasade** [comment]
Typically getting focused node information can be done with node query
constraints. Some examples (AFK so typo prone):

Focused node: `bspc query -N -n`
Windows encompassed by the focused node: `bspc query -N -n
.descendant_of.window`
Focused node on a desktop or monitor: `bspc query -N -d <desktop_sel> -n
focused`, and `bspc query -N -m <monitor_sel> -n focused`

You can reference json information from the focused node down with `bspc
query -T -n`, and use information from that within your `bspc query -T -d`,
maybe.

What kind of use case are you going for?

On Wed, May 18, 2016 at 6:07 AM, Daniel Jankowski <notifications@github.com>
wrote:

> I found the focusedNodeId-key in the root of the tree. But anyway it
> would be much cleaner, if the nodes have a key, which determines if they
> are focused or not.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/baskerville/bspwm/issues/483#issuecomment-219994858>
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by dj95** [comment]
I want to generate a statusline for lemonbar with one bspc call, so that it wont slow down because of to many syscalls. Now I realized it by searching for the `focusedNodeId`-key and comparing it to the child node of the tree. It would be a lot easier, if seperate nodes provide this information by themselves, so you get the information, if a node is focused, even by calling `bspc query -T -n`.

**Comment by baskerville** [comment]
The JSON output reflects the internal structures.
