### ISSUE TITLE
`focus_follows_pointer` does not work if pointer is already over the unfocussed window

### ISSUE THREAD

**Issue by jamietanna** [baskerville/bspwm#485]
Create the following window setup, where:
- `[p]` indicates the position of the mouse
- `> c <` indicates the `c` node is focussed. 

```
+----------------------+
|         |            |
|   [p]   |     b      |
|         |            |
|    a    |------------|
|         |            |
|         |   > c <    |
|         |            |
+----------------------+
```

When moving the mouse over window `a`, the focussed window does not change. It will only change on the mouse moving over the border between windows.

Is this a bug, or intended behaviour?

**Comment by blendi-93** [comment]
u can read about this change here: https://github.com/baskerville/bspwm/commit/2b2ed4eb56c728c24f7e8c5a6b1d08ab0e2aea9c

**Comment by rnhmjoj** [comment]
I have `focus_follows_pointer` enabled but I also switch windows with `bspc node -f {prev,next}` when I'm working keyboard-only (and the pointer is hidden by unclutter). With https://github.com/baskerville/bspwm/commit/2b2ed4eb56c728c24f7e8c5a6b1d08ab0e2aea9c the pointer is still focusing even if it's not being moved/visible and it's causing flickering or lock the focus as @jamietanna said.

This sound a lot like [xkcd 1172](https://xkcd.com/1172/) but can I somehow get the old behavior back?

**Comment by baskerville** [comment]
I'm not against the aforementioned behavior but it requires a hack…

**Comment by rnhmjoj** [comment]
Thank you!
