### ISSUE TITLE
Feature request: ability to set reference node with a NODE_SEL

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#486]
If I have a given node id and I'm not currently focused on it, but would like to focus on something based on it, would be nice to say `bspc node -f @[NODE_SEL]/south`.

**Comment by baskerville** [comment]
As of 3a27fb6, the relative node paths will use the given reference as starting point.

For example, `query -N 0x00A00008 -n @parent` will return the parent of `0x00A00008`.

**Comment by neeasade** [comment]
That is handy -- I think what I'm really looking for is `bspc node [node_sel] -f [node_sel]` to work, as implied by:

```
 Node
       General Syntax
           node [NODE_SEL] COMMANDS

           If NODE_SEL is omitted, focused is assumed.

       Commands
           -f, --focus [NODE_SEL]
               Focus the selected or given node.
```

The script I was needing this for changed logic to not need this feature request, but the above doc snippet suggests it should be possible, and in a test with `bspc node <node id> -f south` it does not appear to be.  

Actually looking closer it's not mentioned that `<node id>` in the above sets the reference node, so this may be an invalid request.

**Comment by baskerville** [comment]
Your example can now be written as `node -f NODE_SEL#@south`.
