### ISSUE TITLE
Support for struts (_NET_WM_STRUT_PARTIAL)?

### ISSUE THREAD

**Issue by d125q** [baskerville/bspwm#487]
Are there any plans to add support for the [_NET_WM_STRUT_PARTIAL](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472578320) hint?  I understand that padding can be specified manually, but struts are far more flexible.  Perhaps space reserved by struts could be put at the very edge of the screens, followed by padding, followed by regular space.

**Comment by baskerville** [comment]
Why are struts more flexible?

**Comment by d125q** [comment]
Because the program sets them itself using internal logic.

**Comment by freundTech** [comment]
I agree that struts would be helpful.
Currently when you use a bar or dock and you change the height of it you have to also change the padding in bspwmrc.
With strut support you wouldn't have to do anything. The bar tells the window manager how much space it wants to reserve.

Changing it manualy is only a minor inconvenience, but it would still be great to see the "proper" way supported by bspwm.

**Comment by cellsheet** [comment]
+1 on this, I specify manual calculations to pad lemonbar at the top currently. Minor indeed, but helpful.
