### ISSUE TITLE
feature request: receptacles obey external rules

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#489]
eg with the [psuedo tiling](https://github.com/baskerville/bspwm/blob/master/examples/external_rules/pseudo_automatic_mode/external_rules) example would be nice if receptacles spawned this way too.

**Comment by baskerville** [comment]
Have you read the commit message for e8aa679?

The synchronicity of the receptacle insertion process is what makes it usable.

**Comment by neeasade** [comment]
I see, had not considered that.

It has just occured to me bspwm is flexible enough(thanks :tada:) that I can put my external rule logic in a script for receptacles anyway, so I'll go with that approach.
