### ISSUE TITLE
pointer_actions block sxhkd combos

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#490]
I’ve noticed that mouse bindings are now handled internally by bspwm and are not supported by sxhkd anymore. It would be convenient if a `kill` action could be added to replace previous `bspc node -c` actions. Alternatively, it might be convenient to be able to bind events to shell commands instead.

**Comment by baskerville** [comment]
What previous actions?

Isn't `bspc node pointed -k` what you're aiming for?

**Comment by eigengrau** [comment]
> Isn't bspc node pointed -k what you're aiming for?

Probably. I usually use focus follows pointer, so the effect should be the same. So, I just upgraded bspwm/sxhkd to the current HEAD, and, given that mouse bindings are now done in bspwm, and not supported by sxhkd anymore, I was looking for a way to replicate my current binding (`super + mouse3 ⇒ bspc node -c`).

We now have `pointer_action2`, but this only accepts a finite list of actions. It would be great to either allow for arbitrary shell commands, or to amend the list of pre-defined actions by a `kill` action.

**Comment by neeasade** [comment]
could you not in sxhkd have `super + mouse3 --> bspc node pointed -k`

**Comment by baskerville** [comment]
@eigengrau *sxhkd* still supports button bindings:
```
super + button3
	bspc node pointed -c
```

**Comment by eigengrau** [comment]
@baskerville thanks, I was confused by one commit and somehow got the impression mouse support was being removed from sxhkd. Then my issue actually is that the `super + button3` binding stopped working after updating from commit 1140 to 1206. I looked more closely into the output of my X session and the problem seems to be this:

```
Could not grab button 3 with modfield 64: the combination is already grabbed.
```

Can bspwm handle pointer actions in ways that don’t block binding the corresponding combos in sxhkd? Alternatively, could bspwm offer a `none` action to disable handling these key combos?

**Comment by eigengrau** [comment]
Thank you! :+1:

**Comment by thwischm** [comment]
Unfortunately, this doesn't allow for using bspwm mouse controls and also executing shell commands with the same key.
