### ISSUE TITLE
Make all clients on one desktop floating

### ISSUE THREAD

**Issue by NicolasCARPi** [baskerville/bspwm#491]
Hello,

I would like to have all windows opened in my desktop 3 to be floating.
I knew how to make it in the old version. But can't figure out how to do that with 0.9.1.

Please can you tell me ?

I tried:
~~~sh
bspc rule -a desktop=^3 state=floating
bspc rule -a desktop=^3 floating=on
~~~

Regards,
~Nicolas

**Comment by d125q** [comment]
```sh
bspc rule -a '*' desktop='^3' state=floating
```

**Comment by NicolasCARPi** [comment]
Ok, thanks to Dario who deleted his answer for some reason : 

~~~sh
bspc rule -a '*' desktop=^3 state=floating
~~~

Cheers :)

**Comment by neeasade** [comment]
You could listen for nodes to be managed, and react accordingly, something
like:

bspc subscribe node_manage | while read monitor desktop node; do
    [ "$desktop" == "targetDesktop" ] && bspc node $node -t floating
done

note: not at desktop to test.



Thanks,
Nathan

**Comment by baskerville** [comment]
https://github.com/baskerville/bspwm/issues/428#issuecomment-199985423

**Comment by baskerville** [comment]
As of a4a3eda, you can also write this as an external rule:
```shell
#! /bin/sh

FLOATING_DESKTOP_ID=$(bspc query -D -d '^3')
desk_id=$(bspc query -D -d "${5:-focused}")

[ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && echo "state=floating"
```

**Comment by NicolasCARPi** [comment]
Thanks ! :)
