### ISSUE TITLE
Some nodes not getting className/instanceName

### ISSUE THREAD

**Issue by noh4ck** [baskerville/bspwm#493]
I've found, after lots of frustration, that bspwm (at least for me) does not pick up className/instanceName for some programs.
Output of `bspc wm -d`
(I'm pretty sure it's this one, as there is no "client" without a name and inctance when I close the program)
```json
"client": {
    "className": "",
    "instanceName": "",
    "borderWidth": 2,
    "state": "tiled",
    "lastState": "tiled",
    "layer": "normal",
    "lastLayer": "normal",
    "urgent": false,
    "visible": true,
    "icccmFocus": false,
    "icccmInput": true,
    "minWidth": 0,
    "maxWidth": 0,
    "minHeight": 0,
    "maxHeight": 0,
    "wmStatesCount": 0,
    "wmState": [],
    "tiledRectangle": {
        "x": 685,
        "y": 5,
        "width": 672,
        "height": 754
    },
    "floatingRectangle": {
        "x": 169,
        "y": 82,
        "width": 1024,
        "height": 600
    }
}
```
This is the output of `xprop`
```
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_CLASS(STRING) = "Godot", "Godot"
WM_NAME(STRING) = "Nameless"
_NET_WM_DESKTOP(CARDINAL) = 1
```
I've tried to apply rules to this program, but nothing works
Output of `bspc rule -l`
```
Godot:* => state=floating
Nameless:* => state=floating
Godot:Godot => state=floating
Godot:Nameless => state=floating
*:Godot => state=floating
*:Nameless => state=floating
godot:* => state=floating
godot:godot => state=floating
```

Test program (64bit only):
[Program.zip](https://github.com/baskerville/bspwm/files/282984/Program.zip)

**Comment by baskerville** [comment]
As mentioned in a previous issue, what probably happens is that the program sets the *WM_CLASS* property on its window **after** the map request.

Do you have access to the source of this program?

**Comment by noh4ck** [comment]
@baskerville https://github.com/godotengine/godot/blob/master/platform/x11/os_x11.cpp#L195
Not sure if it's the source of the problem though, godot is a game engine, and it's a huge program.

**Comment by baskerville** [comment]
It should be fixed in *Godot* (the window is probably mapped in `context_gl_x11.cpp`).

There might be a workaround: in your external rules script, just wait for the *WM_CLASS* to appear on the window:

```shell
#! /bin/sh

wid=$1
class_name=$2

if [ -z "$class_name" ] ; then
	tries_left=20
	while [ "$tries_left" -gt 0 ] ; do
		xprop -id "$wid" WM_CLASS | grep "not found" > /dev/null || break
		sleep 0.05
		tries_left=$((tries_left - 1))
	done
	# if [ "$tries_left" -gt 0 ] ; then ... fi
fi
```

**Comment by noh4ck** [comment]
@baskerville I also figured that the mapping happened in `context_gl_x11.cpp`, so I moved the mapping call to the `set_context` function and it now seems to work. Will make a pull request to godot soon.

Thanks for pointing me in the right direction and thank you for the workaround script, will be using it until a new stable release of godot comes out!

You may mark this issue as solved.
