### ISSUE TITLE
bspwm logo

### ISSUE THREAD

**Issue by spcmd** [baskerville/bspwm#495]
Is there an official logo for bspwm? I can't seem to find nowhere. If there is no logo, is there a reason for not having one?

**Comment by neeasade** [comment]
At this time, not that I'm aware. There were previously these, with last
logo removed around 0.8 or thereabouts:

https://github.com/baskerville/bspwm/blob/0.1/resources/bspwm_logo.png
https://github.com/baskerville/bspwm/blob/0.6/logo/bspwm-logo.png

If there were to be another logo, I've thought it would be kinda neat to
have something like Wikipedia's binary tree pic replacing numbers with font
awesome icons representing desktops and windows or something.

tree: https://en.wikipedia.org/wiki/File:Binary_tree.svg

potential circle/icon fillers:
http://fontawesome.io/icon/desktop/
http://fontawesome.io/icon/terminal/
http://fontawesome.io/icon/firefox/

Thanks,
Nathan

**Comment by baskerville** [comment]
Here's the [current logo](http://imgur.com/gWtor5d).

**Comment by neeasade** [comment]
TIL there is a current logo. neat-o.

Thanks,
Nathan

**Comment by spcmd** [comment]
@neeasade I imagined something like these (I made them recently): [http://i.imgur.com/FQhzoLy.png](http://i.imgur.com/FQhzoLy.png)

But now that we know that bspwm has a current logo, unless @baskerville doesn't want a new logo, maybe this issue can be closed.

**Comment by Hebgbs** [comment]
> Here's the [current logo](http://imgur.com/gWtor5d).
Is there an SVG version of that you may have on-hand? Can't find such elsewhere.

**Comment by neeasade** [comment]
@Hebgbs the current version is svg: https://github.com/baskerville/bspwm/blob/master/artworks/bspwm_logo.svg
