### ISSUE TITLE
Monitors order

### ISSUE THREAD

**Issue by ttygde** [baskerville/bspwm#497]
I have two monitors: DVI-0 and VGA-0. Physically VGA-0 is on the left and DVI-0 is on the right. But in bspwm they are swapped so if I move mouse pointer to the right edge of DVI-0 it will reappear on the left edge of VGA-0. Is there a way to change that behaviour in bspwm? 

I can use xrandr and it helps, but I cannot make it persistent. 
`xrandr --output VGA-0 --auto --output DVI-0 --auto --right-of VGA-0`
That line helps if I type it manually and everything works as expected, but if I put it in xinitrc or if I use xorg.conf.d configurational file then monitors are in correct order, but desktops are swapped so all desktops that should be on the DVI-0 are on VGA-0 and vice versa. Changing these lines 

```
bspc monitor DVI-0 -d I II III IV V VI VII VIII
bspc monitor VGA-0 -d IX X XI XII XIII XIV
```
to these 
```
bspc monitor VGA-0 -d I II III IV V VI VII VIII
bspc monitor DVI-0 -d IX X XI XII XIII XIV
```
doesnt help.

**Comment by neeasade** [comment]
What is your bspwm version?

**Comment by ttygde** [comment]
The last version from github.

**Comment by neeasade** [comment]
as of https://github.com/baskerville/bspwm/commit/9ae96ebdcd486e6050f37552a58a88de4c1a92d7, monitors ar  selected by ID, not name -- you can use a loop with `bspc query -M` to accomplish assigning the correct desktops to the correct monitors. Some more discussion on this can be found here: https://github.com/baskerville/bspwm/issues/397

**Comment by neeasade** [comment]
Alternatively monitor index is also convienent:

```
bspc monitor ^1 -d I II III IV V VI VII VIII
bspc monitor ^2 -d IX X XI XII XIII XIV
```

**Comment by ttygde** [comment]
thanks @neeasade, it works.
