### ISSUE TITLE
Span window over multiple monitors?

### ISSUE THREAD

**Issue by imiric** [baskerville/bspwm#498]
Hi, and thanks for the wonderful WM.

Is there a way "maximize" a window to make it span multiple monitors? Currently, I have a setup of 3 desktops on 2 monitors, and sometimes have the need to momentarily expand a window over both monitors.

I know I can set it to floating and manually change its size, but is there a way of doing this automatically while keeping a tiled or fullscreen window state?

Thanks for your help.

Ivan

**Comment by neeasade** [comment]
> I know I can set it to floating and manually change its size, but is
there a way of doing this automatically while keeping a tiled or fullscreen
window state?

it sounds like you want the ability to check if a window is already in this
'multi fullscreen'  state -- one approach you can take is query the window
dimensions and compare them to monitor dimensions to determine if a window
is in that state.

Thanks,
Nathan

**Comment by blendi-93** [comment]
u could add a third virtual monitor across both real monitors

    bspc wm
            -a, --add-monitor <name> WxH+X+Y
               Add a monitor for the given name and rectangle.

so u can move ur window between smal real and big virtual monitor.

**Comment by imiric** [comment]
@blendi-93's tip works great, thanks!

Closing this.
