### ISSUE TITLE
Example keybindings don't work in 0.9.1

### ISSUE THREAD

**Issue by Anachron** [baskerville/bspwm#499]
#From my sxhkdrc

```
# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}
```

Won't do anything.

Typing `bspc node -z left -20 0` into the terminal gives me `Invalid Syntax.` and returns RC = 1.

**Comment by Anachron** [comment]
I found a "workaround" using your xdo-tool. https://github.com/windelicato/dotfiles/blob/master/.config/sxhkd/sxhkdrc#L61-L67

**Comment by neeasade** [comment]
the example bindings in master target master. in 0.9.1:

https://github.com/baskerville/bspwm/blob/0.9.1/examples/sxhkdrc#L111-L122

**Comment by Anachron** [comment]
Interesting, the Master is wrong but the tagged version is updated.
Is it planned to revert those changes of 0.9.1?
