### ISSUE TITLE
Example panel shows superfluous T with window title

### ISSUE THREAD

**Issue by fedemp** [baskerville/bspwm#50]
Using the example in the `panel` folder, the first `T` in the window title is not removed when piped to the bar.

In screenshot, _st_ is the window title.

![captura de pantalla - 150813 - 15 18 43](https://f.cloud.github.com/assets/735314/970471/4c9cbd4c-05d7-11e3-9185-2fa0390d9840.png)

**Comment by norwack** [comment]
@baskerville Yes, old issue but i have a quick question.

Is it possible to remove the "T", and if so, how would i go about doing that?

**Comment by baskerville** [comment]
Just remove the layout section from your panel (it starts with `L*)`).
