### ISSUE TITLE
bspc node --resize returns exit code 0

### ISSUE THREAD

**Issue by fenduru** [baskerville/bspwm#502]
When trying to resize a window whose edge cannot move (it is already at the edge of the desktop), bspc is returning exit code 0.

I previously had my sxhkd config set up to do:

```
alt + shift + h
  bspc window --edge left -40 || bspc window --edge right -40
```

This allowed me to have one hotkey, while avoiding having a noop if the window was at the edge. Is this change intended and if so is there another way I can accomplish what I had previously?

**Comment by baskerville** [comment]
As mentioned in the CHANGELOG, `bspc window -e DIR VALUE` has become `bspc node @DIR -r VALUE`.

**Comment by fenduru** [comment]
Ah, that seemed to work. Thanks! While it doesn't affect me, is there any reason that `bspc node --resize` doens't return exit code 1 in a similar manner?
