### ISSUE TITLE
Unwanted "Desktop" desktop

### ISSUE THREAD

**Issue by codylwalker** [baskerville/bspwm#506]
When I click in the gaps between windows or if I click inside the padding, then the current desktop changes to one named "Desktop". I never created a desktop with that name, and it doesn't appear at all in my bspwmrc.

Here's where I create the desktops:
bspc monitor -d I II III IV V VI VII VIII IX X

Also, when I drag a window, as soon as I hit a gap, it sends that window to the "Desktop" desktop.
Where is this other desktop being created from, and how can I prevent it?

bspwm version:
0.9.1-82-g8587bcd

sxhkd version:
0.5.6-4-g3b26f3d

**Comment by neeasade** [comment]
the "Desktop" desktop is created when a monitor is added before desktops
are specified. Do you have any monitor setup happening in your bspwmrc? or
a funky xrandr setup?

Thanks,
Nathan

**Comment by codylwalker** [comment]
Thanks for the reply. I removed an unneeded xrandr line and the issue resolved.
