### ISSUE TITLE
add --remove-monitor and --set-monitor

### ISSUE THREAD

**Issue by blendi-93** [baskerville/bspwm#507]
is it possible to add some more switches for monitor management, cuttently i can only do bspc wm --add-monitor <name> WxH+X+Y but as i have an ultrawide screen now it would be handy if i could split my monitor into 2 virtual monitors.

thx.

**Comment by baskerville** [comment]
The *monitor* domain already provides the relevant commands: `--remove` and `--rectangle`.

**Comment by blendi-93** [comment]
sry, didnt saw that. shame on me.
