### ISSUE TITLE
Breaks in behavior after update

### ISSUE THREAD

**Issue by dotpyfe** [baskerville/bspwm#508]
I'm using the aur package so I'm not sure which commit specifically introduced behavior changes (I would suspect it happened when the new bspc syntax was introduced?), but I have noticed a few things that seem to be broken:

moving the cursor no longer focuses to the window where cursor is, despite having focus_follows_pointer set to true

when i remove a monitor via xrandr, the desktop associated with it no longer gets deleted, despite having remove_disabled_monitors and remove_unplugged_monitors set to true

im pasting my bspwmrc in case it helps with anything

```
#! /bin/sh

bspc config border_width        2
bspc config window_gap          8 
bspc config top_padding        38 
bspc config bottom_padding      0

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focused_border_color "#BF5700"

bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true 
bspc config remove_disabled_monitors true 
bspc config click_to_focus true                                                                                 
bspc monitor -d I II III IV V VI VII VIII IX X                                  
 
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd floating=on
bspc rule -a crx_chlffgpmiacpedhhbkiomidkjlcfhogd floating=on 

tint3&
```

**Comment by neeasade** [comment]
>moving the cursor no longer focuses to the window where cursor is

some info here:
https://github.com/baskerville/bspwm/commit/2b2ed4eb56c728c24f7e8c5a6b1d08ab0e2aea9c

>when i remove a monitor via xrandr, the desktop associated with it no
longer gets deleted

I believe when a monitor is removed its desktops get merged into the still
connected monitor, not deleted. Unsure if previous behavior was different.

ref:
https://github.com/baskerville/bspwm/blob/fd6d09058b8fc16035ea61556947603b64a432b3/monitor.c#L509

Thanks,
Nathan

**Comment by dotpyfe** [comment]
so i guess the cursor bit will remain as is, thats not too big an issue.

i actually never tested the "merging" in the past, i only removed monitor via xrandr after removing all the terminals or whatever from that monitor. however, when i did that, the desktop would in fact be deleted. lets imagine i had had 3 "normal" desktops, i would have seen something like

`I II II`

then, after attaching a monitor via xrandr,

`I I III Desktop`

and after removal via xrandr, the `Desktop` entry would be deleted. now i just get a bunch of duplicates. so lets say i add and remove a monitor 3 times (i plug in an external at my desk, but move my laptop around during the day sometimes), i get something like

`I I III Desktop Desktop Desktop`

and so my status bar slowly becomes consumed by desktop entries

**Comment by neeasade** [comment]
Ah -- previously desktops were unique by their name, but now they have ID's
attached, allowing for duplicate named desktops. When you plug a monitor in
and don't assign desktops to it, it gets the default desktop name
"Desktop". so it goes:

- initial: laptop, I II III
- *plug in external* : laptop, I II III AND external, Desktop
- *unplug external*, Desktop merges: laptop, I II III Desktop

Repeat and you get the stacking you described. One solution to this is to
monitor for when you remove a monitor and and reset your desktops.
Something like:

while read msg; do
    bspc monitor -d I II III IV V VI VII VIII IX X
done < bspc subscribe monitor_remove

You could also make scripts to react to monitors being added and add named
desktops, etc.

Thanks,
Nathan

**Comment by dotpyfe** [comment]
gotcha, thanks for the info!
