### ISSUE TITLE
Focused monitor ID not updated after `bspc desktop -m next`

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#509]
After doing `desktop -m next` on a desktop containing a terminal on monitor A, the input focus will remain with the terminal window, now located on monitor B. However, `query -M -m` will still report the _old_ monitor ID (A) after the move. After issuing `desktop -m next` a second time, the terminal moves back to monitor A. Now, `query -M -m` will return the ID of monitor B. So, the internal notion of what monitor is focused seems to always be “one behind” for some reason.

I’ve also noticed that, after running `desktop -m next` three consecutive times, the terminal window will vanish and be orphaned.

Edit: I’ve been observing this using the current HEAD.

**Comment by baskerville** [comment]
Thanks for reporting.
