### ISSUE TITLE
hook for xrandr monitor change or resize event

### ISSUE THREAD

**Issue by sunaku** [baskerville/bspwm#511]
Hello,

I use the provided example panel script to run a lemonbar panel with bspwm. :smile_cat:  Whenever I undock my laptop from an external monitor and run `xrandr --auto`, bspwm correctly reconfigures itself for the smaller screen resolution of my laptop's internal display and the disconnection of one extra monitor.  :+1:

However, lemonbar does not. :cry:  Instead, it stubbornly retains its dimensions and position from the time before I undocked my laptop, thereby not appearing on my laptop's (much smaller) internal display. :scream:

A pull request https://github.com/LemonBoy/bar/pull/171 to make lemonbar smarter was rejected.  So I'm asking here if it would be possible for bspwm to provide some hook or event whenever it reconfigures itself after xrandr changes so that I can kill and restart lemonbar accordingly. :innocent: Ideally, if xrandr itself provided an event stream that I could consume (similar to `acpi_listen` for hardware events) then I could do all this outside bspwm. :sweat_smile:

Thanks for your consideration.

P.S. See also https://www.reddit.com/r/bspwm/comments/43d4ls/restarting_the_panel/

**Comment by baskerville** [comment]
You could listen to the *monitor* event group: `bspc subscribe monitor`.

**Comment by sunaku** [comment]
Brilliant! :bow: I've hooked into the `monitor_geometry` events successfully. :joy:  Thank you Bastien! :+1: 

```sh
bspc subscribe monitor_geometry | head -1 # wait for resize event
pkill -x panel
panel &
```
