### ISSUE TITLE
can't unfullscreen

### ISSUE THREAD

**Issue by aeosynth** [baskerville/bspwm#513]
if i start a program in fullscreen, i can't toggle that state natively, ie through the program's hotkeys, until i set it as tiled through bspwm. if the program starts tiled, i can toggle fullscreen natively. am i just misunderstanding something?

tested with `mpv` and a random gtk app, on stable and git (a6aa980c268f0fc2c2bef1935eec3892136933de)

**Comment by baskerville** [comment]
This is a consequence of #328.

**Comment by baskerville** [comment]
One possible solution:
```
super + {t,shift + t,s,f}
	bspc node -t '~{tiled,pseudo_tiled,floating,fullscreen}' || bspc node -t tiled
```

**Comment by aeosynth** [comment]
not for me; i'd like to use only the program hotkeys to manage fullscreen

**Comment by neeasade** [comment]
In the current scheme, this wouldn't be possible via only the program. In an application launched in fullscreen:

``` json
"client": {
    "className": "mpv",
    "instanceName": "gl",
    "borderWidth": 6,
    "state": "fullscreen",
    "lastState": "fullscreen",
    "layer": "above",
    "lastLayer": "normal",
    "urgent": false,
    "shown": true,
    "tiledRectangle": {
      "x": 1920,
      "y": 0,
      "width": 1920,
      "height": 1080
    },
``` 

I believe toggling via a program/application sets to lastState if fullscreen, rel snippet(?) from `events.c`:
``` c
	if (state == ewmh->_NET_WM_STATE_FULLSCREEN) {
		if (action == XCB_EWMH_WM_STATE_ADD) {
			set_state(m, d, n, STATE_FULLSCREEN);
		} else if (action == XCB_EWMH_WM_STATE_REMOVE) {
			if (n->client->state == STATE_FULLSCREEN) {
				set_state(m, d, n, n->client->last_state);
			}
		} else if (action == XCB_EWMH_WM_STATE_TOGGLE) {
			set_state(m, d, n, IS_FULLSCREEN(n->client) ? n->client->last_state : STATE_FULLSCREEN);
		}
```

One thing that might make your request feasible would be the ability to set lastState in a rule, something like `bspc rule -a mpv state=fullscreen lastState=tiled`. But I think that would imply you should have the ability to change lastState via bspc toggles elsewhere, which wouldn't make sense IMO.

**Comment by aeosynth** [comment]
works, thanks
