### ISSUE TITLE
Monitor focus events don't happen with empty monitors/desktops + focus_folllows_pointer

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#523]
With three monitors open, and windows open on the rightmost monitor, I cannot move my mouse over to the leftmost monitor and spawn dmenu/a terminal on that monitor(focus is left on the middle monitor). 

edit: FYI virtual monitors are not a factor in my setup/this issue

**Comment by baskerville** [comment]
The output of `bspc subscribe monitor desktop node` might be helpful.

**Comment by neeasade** [comment]
woops -- you see, the issue is there is no log going between the center and leftmost monitor in the scenario described above.

When launching the subscribe call in a terminal on the rightmost screen, and moving to the leftmost and back to the rightmost:
```
$ bspc subscribe desktop monitor node
monitor_focus 0x00800005
desktop_focus 0x00800005 0x00800008
monitor_focus 0x00800003
desktop_focus 0x00800003 0x00800009
node_focus 0x00800003 0x00800009 0x01800003
```

xrandr | grep ' conn':
```
DisplayPort-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
HDMI-0 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 477mm x 268mm
DVI-1 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 477mm x 268mm
```

misc info(when executing the subscribe above):
```
$ bspc query -M
0x00800001
0x00800005
0x00800003
$ bspc query -D
0x00800007
0x00800010
0x00800011
0x00800012
0x00800008
0x0080000D
0x0080000E
0x0080000F
0x00800009
0x0080000A
0x0080000B
0x0080000C
```

probably not needed but `bspc wm -d` output: http://sprunge.us/FURZ

version: current HEAD.

**Comment by baskerville** [comment]
Could you provide the output of `for wid in $(xdo id -N Bspwm -n root); do xwininfo -stats -events -id "$wid"; done`?

**Comment by baskerville** [comment]
Never mind: I was able to reproduce and I will investigate.
