### ISSUE TITLE
Bspwm not working properly with modesettings driver

### ISSUE THREAD

**Issue by lukasgierth** [baskerville/bspwm#525]
I tried to use bspwm without the xf86-video-intel driver and only with the mesa driver.
It is not possible to switch workspaces, or send windows there.
There also is a window gap even if the setting in the config says "0".

**Comment by reyqn** [comment]
I had to switch from xf86-video-intel driver too and ran into the same problem.
`bspc query -M` output is now eDP-1 instead of eDP1.
Editing my .config/bspwm/bspwmrc file to follow this change fixed it for me. Hope this helps

**Comment by lukasgierth** [comment]
Works great! Seems to be exactly the problem and solution i had.
