### ISSUE TITLE
node --resize should exit with a non-zero status on fail

### ISSUE THREAD

**Issue by Stebalien** [baskerville/bspwm#528]
If `bspc node --resize DIR X Y` fails to actually resize a window for some reason (e.g., the requested edge can't be moved), it should exit with a non-zero status. This makes it easier to write scripts.

**Comment by baskerville** [comment]
5a98b65 should address the edge case. Could you be explicit about the other cases?

**Comment by Stebalien** [comment]
That's the only case I can think of (I just didn't know if there were other cases I didn't know about). Thanks!
