### ISSUE TITLE
Attach focused node to leaf

### ISSUE THREAD

**Issue by Luke-Nukem** [baskerville/bspwm#532]
I know this isn't really the most appropriate place to ask, but as per title.

If I have a "biggest (root)" node on the left, and three on the right, I'd like to *attach* the focused right node to the "biggest" node, such that the screen is split in to (equal) quadrants. I'm having difficulty coming up with a worakble solution.

Any ideas? Or am I thinking about the tree incorrectly and what I want is something like a binary tree with a root and 3 children off that?

**Comment by neeasade** [comment]
adding reply here as well (original thread [here](https://www.reddit.com/r/bspwm/comments/4xw4uw/q_how_to_move_node_to_leaf/)

```
-n, --to-node NODE_SEL
               Transplant the selected node to the given node.
```

webm: https://u.teknik.io/9xVsz.webm

**Comment by Luke-Nukem** [comment]
Use of `local` is a good idea, thanks :+1:
