### ISSUE TITLE
Unfullscreen Floating Windows

### ISSUE THREAD

**Issue by Weker01** [baskerville/bspwm#533]
I am using bspwm 0.9.1-95-g70b477d

# Steps to reproduce

1. Open a new tiled Window.
2. Make it floating eg. `bspc node -t floating`
3. Make it fullscreen eg. `bspc node -t fullscreen`
4. Disable fullscreen eg. `bspc node -t \~fullscreen`
5. Disable floating eg. `bspc node -t \~floating`
6. See that the Window is in fullscreen mode

# Expected behavior

The Window should be tiled again?

Edit:
When the Window is Unfullscreened it goes into **floating mode**.

**Comment by d125q** [comment]
bspwm should probably keep a stack for each node to push and pop these states accordingly...

**Comment by neeasade** [comment]
This is expected behavior. 

```
 -t, --state [~](tiled|pseudo_tiled|floating|fullscreen)
               Set the state of the selected window. If ~ is present and the current state matches the given
               state, then the argument is interpreted as the last state.
```

in your example, when you `bspc node -t \~floating` the last state is `fullscreen`. 

to get your desired behavior via keybinds, you can do something like:

```
super + s
    bspc node -t $(bspc query -N -n -n .tiled >/dev/null && echo floating || echo tiled)

super + f
    bspc node -t ~fullscreen
```
