### ISSUE TITLE
bspc window -w last.manual in bspwm 0.9.1

### ISSUE THREAD

**Issue by Toqozz** [baskerville/bspwm#535]
Hi, it used to be the case that I could preselect an area of a window and then use the above command to move the currently focused window into that preselected area.

How can I get this behaviour in 0.9.1?

I have tried:
```
bspc node -s last.manual
bspc node -n last.manual
```

(I can no longer find the binding in the example sxhkdrc)

**Comment by baskerville** [comment]
This is a duplicate of #429.
