### ISSUE TITLE
bspc control --toggle-visibility

### ISSUE THREAD

**Issue by tu-maurice** [baskerville/bspwm#539]
Could you kindly point me into the direction where the bspc control --toggle-visibility feature has gone to?

**Comment by neeasade** [comment]
It was removed, and you can now toggle a `hidden` flag on nodes to set their visibility. 

```
-g, --flag hidden|sticky|private|locked[=on|off]

    Set or toggle the given flag for the selected node.
```

**Comment by tu-maurice** [comment]
the hidden flag isn't exactly the same thing. but i guess it has to suffice.

**Comment by neeasade** [comment]
Yeah, was implying from https://github.com/baskerville/bspwm/issues/381 that was intended -- might also checkout xdo's `hide` option.

**Comment by tu-maurice** [comment]
What kinda put me off using the hidden flag to emulate toggle-visibility is that newly created windows wouldn't get the hidden flag but ok. I made a small script hiding all nodes if there aren't any hidden windows and showing all nodes else. It should suffice.

Thanks for the quick help. Should've searched before creating an issue though.
