### ISSUE TITLE
Update example configuration files

### ISSUE THREAD

**Issue by alecive** [baskerville/bspwm#540]
I'm new to `bspwm` and `sxhkd`, but I found it difficult to have a MWE because of the fact that the example config files are not updated. For example, in the default `sxhkdrc` this is still present: `bspc pointer -g focus` whereas it should be replaced with `bspc node pointed -f`.

**Comment by baskerville** [comment]
The current [`sxhkdrc` example](https://github.com/baskerville/bspwm/blob/master/examples/sxhkdrc) doesn't contain the aforementioned command.

**Comment by alecive** [comment]
Ok I found the issue. Don't know why but the latest commit in my local copy of the `bspwm` repo dates back to March.
