### ISSUE TITLE
bspc query: how to find the biggest node on the current desktop

### ISSUE THREAD

**Issue by ikn** [baskerville/bspwm#543]
I've just upgraded to the latest bspwm from Git (AUR version went from 1116 to 1228).  I used to use the following to find the biggest node on the current desktop:

`bspc query -N -n biggest.tiled`

It seems that this now returns the biggest node across all desktops.  I've tried a few permutations, and it looks like `bspc query` accepts multiple constraint options now (`-d`, `-n`, `-m`), but I can't work out how to do this, and I can't work out from the documentation how you're supposed to do this.

`bspc query -N -n biggest -d focused` returns all nodes on the focused desktop, including non-leaf nodes
`bspc query -N -d focused -n biggest` returns the biggest leaf node across all desktops
`bspc query -N -n biggest -d .focused` returns the biggest leaf node across all desktops
`bspc query -N -d .focused -n biggest` returns the biggest leaf node across all desktops

**Comment by baskerville** [comment]
`biggest.tiled.local`

**Comment by ikn** [comment]
Thanks, missed that.

Are multiple constraint options to query supposed to be supported, then?  I think `bspc` used to give an error when called as in the 4 examples I gave, and now it doesn't, but the results don't seem quite as expected.

**Comment by baskerville** [comment]
It isn't supported but (_unintentionally_) works for certain cases: `query -N -d last.occupied -n .tiled.automatic`.

**Comment by ikn** [comment]
Okay, thanks for clarifying.  There would certainly be some ambiguities if it were supported with the current definitions of selectors.
