### ISSUE TITLE
Shortcut to launch terminal in a specific state

### ISSUE THREAD

**Issue by alecive** [baskerville/bspwm#550]
As written in the title, I would like to add a new shortcut to my `sxhkdrc` to launch a terminal in floating mode. I would like only that terminal to be in floating mode (whereas other terminals should be in tiling mode), so I cannot use a `bspc rule`. 

Is that possible to do so? I've been looking at `xdo` but there does not seem to be an option to change a state of a window (at least , as far as I understood).

**Comment by neeasade** [comment]
You could use a one shot rule, the entry in your sxhkd could be: 

```
super + Return
    bspc rule -a \* -o state=floating && $TERMINAL
```

and you could replace the `\*` with a more specific WM_CLASS (to match your term)

**Comment by baskerville** [comment]
Some terminals provide a flag for specifying an instance name. You can then create a rule that will only target windows having the terminal's class name and the chosen instance name.

Example:
```
bspc rule -a URxvt:abc state=floating
urxvt -name abc
```

**Comment by alecive** [comment]
Great, thank you!
