### ISSUE TITLE
Period in monitor_name

### ISSUE THREAD

**Issue by Weker01** [baskerville/bspwm#552]
I am using bspwm 0.9.1-99-g9dffb6f

# Problem
My primary Monitor has the monitor_name "DP-2.8" as seen in the output of: bspc query -T -m $(bspc query -M -m focused) and xrandr but I can't select the monitor by it's name.
`bspc query -M -m DP-2.8`
`query -m: Invalid modifier found in 'DP-2.8'.`

I don't have this problem with my secondary monitor called "DP-0"
`bspc query -M -m DP-0`
`0x00800003`

**Comment by baskerville** [comment]
That's unfortunate, but the name selector must have the lowest priority because it's unpredictable.

You can get around this by using the following function:
```
monitor_id_from_name() {
	bspc wm -d | jq ".monitors[] | select(.name == \"$1\").id"
}
```
