### ISSUE TITLE
Node resizing returns "invalid syntax"

### ISSUE THREAD

**Issue by mrkgnao** [baskerville/bspwm#555]
For some reason, commands like `bspc node -z left 0 20` do not work any more. I tried replacing `-z` with `--resize`, but to no avail.

I'm hacking around it using a one-off `split_ratio` change for now, since I only really need it for one thing (a thin tab sidebar in Chrome).

**Comment by baskerville** [comment]
The aforementioned command works for me (because I'm using a version of *bspwm* that provides this node command), but does nothing, because the *dy* component of the translation is ignored when moving the left side along the *x* axis.
