### ISSUE TITLE
Get the desktop name in desktop_focus events

### ISSUE THREAD

**Issue by nibogd** [baskerville/bspwm#557]
I'm using `bspc subscribe desktop_focus` for showing the current desktop name on the panel, so it'd be cool to have a flag which enables showing the desktop name instead of its ID with the event (`desktop_focus 0x00400001 1` instead of `desktop_focus 0x00400001 0x00400004`). Or just to have a command to get the desktop name by id.

Sorry if it exists and i missed it in documentation, i couldn't find such option.

**Comment by baskerville** [comment]
You can get the name with:
```
bspc query -T -d DESKTOP_ID | jshon -e name -u
```

But it might be preferable, if you want to avoid the round-trip, to maintain a hash table that maps desktop IDs to names by listening to `desktop_add` (the initial name is provided), `desktop_remove` and `desktop_rename`.

**Comment by nibogd** [comment]
Thank you!
