### ISSUE TITLE
Using colons in desktop names causes problems

### ISSUE THREAD

**Issue by ortango** [baskerville/bspwm#560]
If I do something like this `~$ bspc monitor -a 8\:eight`, I will get a new desktop named 8:eight (the colon will work fine with any monitor command).

But using any desktop command, ie `bspc desktop "eight:8" -r` results in `desktop: Invalid descriptor found in 'eight:8'.`

(? maybe funct:desktop_from_desc)

**Comment by rubik** [comment]
I can confirm. Furthermore, if I run

    bspc monitor -d 1:one 2:two 3 4

the command executes without errors but the desktop names are 1 2 3 4. Quoting and escaping don't seem to work.
