### ISSUE TITLE
Move window to next desktop and focus on it

### ISSUE THREAD

**Issue by alecive** [baskerville/bspwm#563]
Hello,

I would like to have a `sxhkd` shortcut with which I can move a window onto the next desktop and focus on it. I currently have this shortcut:

```
ctrl + alt + shift + {Down,Up}
	bspc node -d {next,prev}; \
	bspc desktop -f {next,prev}
```

I have two issues with that:
 1. The window loses focus. If in the `next` desktop there is already at least one node, that is the one that gains focus in place of the window I am moving.
 2. I cannot transfer the `{Down, Up}` information to the second command. To make it short, when I type `ctrl + alt + shift + Up` the result is that I get  `bspc node -d prev` but `bspc desktop -f` is always `prev` no matter what.

What am I doing wrong? Especially problem number 2 seems to be a bug to me.

**Comment by baskerville** [comment]
1. You can chain commands:
```
ctrl + alt + shift + {Down,Up}
	bspc node -d {next,prev} -f
```
2. This isn't a bug: the sequence syntax is distributive in this case. Here's the correct version:
```
ctrl + alt + shift + {Down,Up}
	DIR={next,prev}; \
	bspc node -d "$DIR"; \
	bspc desktop -f "$DIR"
```

**Comment by alecive** [comment]
This is great! Thank you @baskerville for the help!

**Comment by alecive** [comment]
@baskerville can you quickly explain me the reasoning behind the chain of commands? I believe I don't really get what is going on there. 

So with e.g. `bspc node -d next` you're moving the node to the next desktop, but how `bspwm` then knows that the `-f` flag is referring to moving focus to the next desktop as well? And how does the `bspwm` know that the node I'm moving is the one it should keep focus on?

**Comment by baskerville** [comment]
All the commands of the *node* domain apply to the selected node (the focused node by default). `-f` applies to the selected node which was moved to the *next* desktop with `-d next`.

Have a look at the [specs](https://github.com/baskerville/bspwm/wiki/Command-Syntax-Rewrite) for more details.

**Comment by olfREG314** [comment]
> 1. You can chain commands:
> 
> 
> ```
> ctrl + alt + shift + {Down,Up}
>     bspc node -d {next,prev} -f
> ```
> 
>     1. This isn't a bug: the sequence syntax is distributive in this case. Here's the correct version:
> 
> 
> ```
> ctrl + alt + shift + {Down,Up}
>     DIR={next,prev}; \
>     bspc node -d "$DIR"; \
>     bspc desktop -f "$DIR"
> ```

the above one didn't focus on the node that I sent, below one worked well for me( for people who switched to bspwm in 2022)
```
# send win to next or prev desktop & focus it
alt + ctrl + { Right,Left }
    DIR={next.local,prev.local}; \
    bspc node -d "$DIR" --follow
```
