### ISSUE TITLE
Focus the next node now needs .local. Update example sxhkd config?

### ISSUE THREAD

**Issue by gcoda** [baskerville/bspwm#565]
Sorry, casual user complaining.
Some time ago i noticed change of behavior. 
It took some time to figure out how make work like i used to with my barely modified config. 
In monocle mode switching to nodes on another desktop is undesirable default behavior for me
Will it be helpful to someone except me?

```
super + {_,shift + }c
  bspc node -f {next,prev}.local
```

**Comment by nathalie-tate** [comment]
omg, this has been bugging me for a while and I still hadn't gotten around to figuring out how to fix it. Thanks!

**Comment by dhensen** [comment]
Man I need to apologize, just two days ago I was figuring out the same thing... when I found it I was thinking about leaving a post here, but then decided not to at the last moment. At least now you did it 👍
