### ISSUE TITLE
Way to reliably crash the X server: Add a new monitor, then remove its default desktop, then 'bspc monitor --focus last'

### ISSUE THREAD

**Issue by masnes** [baskerville/bspwm#567]
The following commands executed in sequence reliably crash the X server:

```bash
# Example settings
CURRENT_MONITOR_ID=eDP1
NEW_MONITOR_ID=DP2
SOME_DESKTOP=VI

xrandr --output $NEW_MONITOR_ID --auto --right-of $CURRENT_MONITOR_ID --primary
```
A new monitor is added. Since there are no desktops on the monitor bspwm creates one called 'Desktop'

Now I populate it with a second desktop, which enables me to then remove 'Desktop'
```bash
bspc desktop $SOME_DESKTOP -m $NEW_MONITOR_ID
bspc desktop Desktop -r
```
Now I crash the X server
```bash
bspc monitor --focus last
```

**Comment by baskerville** [comment]
Thanks for reporting!
