### ISSUE TITLE
chromium defaults opening to 2nd desktop

### ISSUE THREAD

**Issue by cellsheet** [baskerville/bspwm#570]
Hello, in my personal dotfiles, I have chromium launching on login. However, with some recent update (I'm not sure which), chromium now defaults to opening to the 2nd desktop, even when preselecting. This doesn't happen with urxvt, or any other program (yet) that I have installed, just chromium.

**Comment by jgkamat** [comment]
Try removing [this line](https://github.com/cellsheet/dotfiles/blob/master/wm/bspwm/bspwmrc#L25) from your dotfiles. You might want to remove the other rules if you don't like them either.

**Comment by cellsheet** [comment]
Right - I don't even remember putting that in there even. Thanks for pointing out the obvious though, lol.

**Comment by jgkamat** [comment]
it happens to everyone :P 

Those lines are in the sample bspwmrc file, which is probably how you got them...
