### ISSUE TITLE
Click to focus broken?

### ISSUE THREAD

**Issue by saward** [baskerville/bspwm#574]
Hi,

Not sure if this is related to bspwm or not, but thought I'd ask here just in case.

I recently updated my packages on Arch, and now I can't click on certain programs to pass focus to them.  Examples include: chromium, Spider Oak client.

Examples I can click to focus on: konsole, steam windows.

Any ideas if this is related to a recent bspwm version, or something else?

Thanks

**Comment by saward** [comment]
Downgrading to bspwm-0.9.1 and sxhkd 0.5.6 has resolved this issue, so I strongly suspect it's an issue with the latest version of one of these packages.

**Comment by baskerville** [comment]
`bspc config click_to_focus true`.
