### ISSUE TITLE
LO Impress dragging action triggered when switching slide

### ISSUE THREAD

**Issue by mixedCase** [baskerville/bspwm#578]
Title. Here's a video showing the problem:
[vid.zip](https://github.com/baskerville/bspwm/files/605132/vid.zip)

The dragging animation is triggered with the first non-dragging click, second click switches slide correctly.

Regardless of where the window is positioned, the icon always starts from 0,0

**Comment by baskerville** [comment]
I can reproduce with `click_to_focus` set to `true`.

I will investigate.

**Comment by baskerville** [comment]
Thanks for reporting.

**Comment by mixedCase** [comment]
Thank you for taking the time to fix it!
