### ISSUE TITLE
query: Unknown option: '--names'

### ISSUE THREAD

**Issue by Alexander-Shukaev** [baskerville/bspwm#581]
According to the documentation the `--names` option could be used to retrieve names of objects instead of IDs.  That is, for instance, `bspc query -M -m --names`.  However, the result is: `query: Unknown option: '--names'.`.  Am I missing anything?

**Comment by neeasade** [comment]
version? `--names` was added after the release of `0.9.2`.

**Comment by Alexander-Shukaev** [comment]
Thank you for a quick turn:

```
bspwm -v
0.9.2
```

**Comment by Alexander-Shukaev** [comment]
Alright, I see what's going on now.  It's the next commit after the release `:(`.  Closed.
