### ISSUE TITLE
Save layout

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [baskerville/bspwm#582]
Is there a way to save layouts?. And why not?.

**Comment by alecive** [comment]
Duplicate of #371 (which is a duplicate of #259 ) ?

**Comment by baskerville** [comment]
Parametric layouts are possible thanks to receptacles.

**Comment by baskerville** [comment]
Have a look at `examples/receptacles`.

**Comment by eyvindbjartiandersen** [comment]
Could you provide a well documented way to use it?.
