### ISSUE TITLE
How to make negative padding work with the new behavior of window gaps?

### ISSUE THREAD

**Issue by Chrysostomus** [baskerville/bspwm#589]
I have been using window gaps with negative padding to keep gaps only between windows and not between window edges and screens edges. After updating to latest git version, following behavior ensues:

When lemonbar starts, there is top padding equal to window gap + panel height. 

I can rectify the situation by putting in my autostart after the panel script  

    sleep 1 &&  bspc config top_padding $(($PANEL_HEIGHT-$gap))

But that feels quite hackish. Is there a good way make new gap behavior work properly with negative padding and panels?

Btw, I really like that one does not need to set top padding for panel anymore if one does not want gaps.

**Comment by Chrysostomus** [comment]
Sorry for being dense, but how to use this update from user perspective? I updated to the latest git, but window gap is still added between panel and windows when the panel starts.

**Comment by baskerville** [comment]
You have to set the initial padding values before you launch the panel.

```shell
WG=$(bspc config window_gap)
for SIDE in top bottom left right; do bspc config ${SIDE}_padding -${WG}; done
```

**Comment by Chrysostomus** [comment]
Many thanks!
