### ISSUE TITLE
How can I give a different opacity to the borders of focused/nonfocused windows?

### ISSUE THREAD

**Issue by Brett99** [baskerville/bspwm#591]
Is there a bspwm/compton setting I can use to make the opacity of the borders around windows be different when the window is focused?

**Comment by neeasade** [comment]
compton, search the man page for 'active' - https://github.com/chjj/compton/blob/master/man/compton.1.asciidoc

**Comment by rien333** [comment]
@neeasade Right, but that makes the full window transparent. Not sure if this is solved.

**Comment by neeasade** [comment]
Wrong search term quoted above. the setting is `-e, --frame-opacity=OPACITY`. Here is an old shot where this is set: http://notes.neeasade.net/assets/img/desktops/full/2015-02-10.png (pretty clear on the left windows)
