### ISSUE TITLE
bspc monitor -f north && echo works to focus monitor on the right

### ISSUE THREAD

**Issue by quite** [baskerville/bspwm#594]
I have a LVDS1 --right-of VGA1 according to xrandr. When VGA1 focused, I can do `bspc monitor -f east` to focus the VGA1 on the right. But I can also do `-f north` for the same effect. `west` doesn't work, as expected, and `south` does not either. Is this intentional? That I can focus by latitude even through monitors are attached longitudinally.

**Comment by baskerville** [comment]
What's the output of `bspc wm -d | jq '.monitors[] | {name, rectangle}'`?

**Comment by quite** [comment]
```
{
  "name": "VGA1",
  "rectangle": {
    "x": 0,
    "y": 0,
    "width": 1680,
    "height": 1050
  }
}
{
  "name": "LVDS1",
  "rectangle": {
    "x": 1680,
    "y": 0,
    "width": 1366,
    "height": 768
  }
}
```

**Comment by baskerville** [comment]
I think it might be related to dcd62ea7f333d799e60a5161d401704eb34d944b…
