### ISSUE TITLE
Rootwindow is unclickabe

### ISSUE THREAD

**Issue by Chrysostomus** [baskerville/bspwm#595]
After updating, bspwm does not pass mouse clicks to rootwindow anymore, even if focus_follows_pointer is set to false.

    xev -root -event button 
does not give any output when desktop is clicked.

Why does it matter? I use it in script to spawn openbox style menus when clicking desktop and to switch desktops by scrolling. 

This is an example how it used to work:
![2016-12-19-151443_1920x1080_scrot](https://cloud.githubusercontent.com/assets/12002226/21314158/1d7f4120-c5fe-11e6-8d73-9903ae188742.png)

I would not care much for it otherwise, but it was used in Manjaro bspwm edition, and some user might have liked the feature. 

Is there a possible workaround for this?

**Comment by baskerville** [comment]
This is caused by 01e4116.

I can easily fix this issue, but unfortunately not without breaking `click_to_focus`.

**Comment by Chrysostomus** [comment]
Hmm.. That's pretty bad. While I like those rootmenus, click_to_focus is obviously more important, even though most people probably use focus_follows_pointer with a tiler. Then again, click_to_focus can be done with external tools, while I'm not sure if anything can be done if bspwm grabs the clicks. Difficult dilemma. 

Does bspwm report somewhere the keys it grabs? Perhaps I could build my script so that it would listen to bspwm instead of xprop. 

Or could maybe bspwm could itself run configurable commands when root window is clicked? But might be against the minimalistic nature of the wm... 

Or would it be possible to make mouse click grabbing toggle with the click_to_focus setting? That would limit the issue. 

Anyway, thanks for the explanation.

**Comment by baskerville** [comment]
In fact, there might be a workaround:
```
button3
	bspc query -N -n pointed > /dev/null || echo root
```

**Comment by Chrysostomus** [comment]
In sxhkdrc? I'll try it. Thanks!

**Comment by Chrysostomus** [comment]
Rigth, this works flawlessly:

```
~button1
	bspc query -N -n pointed > /dev/null || mygtkmenui -- .config/GTKmenu/LaunchMenu

~button2
	bspc query -N -n pointed > /dev/null || mygtkmenui -- .config/GTKmenu/BspwmWindowMenui
		
~button3
	bspc query -N -n pointed > /dev/null || mygtkmenui -- .config/GTKmenu/BspwmDesktopMenui

```
And now I can get rid of an extra process. Thanks, this was a major improvement! =)

**Comment by Chrysostomus** [comment]
Turns out that the solution is not fool proof. Lemonbar is also not considered a window, so actions are triggered there too,preventing the user from clicking buttons in it. But still, should be scriotable around.

**Comment by baskerville** [comment]
As of today, you can replace `bspc query -N -n pointed > /dev/null ||` with `xqp 0 $(xdo id -N Bspwm -n root) &&`.

[*xqp*](https://github.com/baskerville/xqp) is small utility I've just made.

**Comment by Chrysostomus** [comment]
Thanks! Is it packaged in arch yet, or should I package it myself?

I wrote this dash script (DidIClickDesktop.sh) to compare check if the clicked window is rootwindow:
```

#!/bin/dash
# Did I just click the desktop?

#Get the window id of the window that is under the pointer and set variable WINDOW to it
eval $(xdotool getmouselocation --shell)

#Get the window id of the rootwindow aka desktop and convert the id into decimal form that xdotool uses so we can easily compare the values
rootwindowid=$(($(lsw | head -1)))
#Compare window ids to see if window under mouse is the rootwindow. Returns false if not.
[ "$WINDOW" = "$rootwindowid" ]
```

depends on xdotool and wmutils, which are alreaydy installed in bspwm edition. But xqp seems very useful for all kinds of stuff.

**Comment by baskerville** [comment]
You might package it or request a merge of *xqp* in *wmutils*.

**Comment by Chrysostomus** [comment]
Latter seems to be the best o option, it belongs to that category.
