### ISSUE TITLE
Resize and move windows with mouse

### ISSUE THREAD

**Issue by H4x4g0N** [baskerville/bspwm#599]
Hello, I'm new to bspwm and I need help. I am using the arc and downloaded the "bspwm and sxhkd" packages from the official repositories, however I noticed that I can not move or resize windows using the mouse, I tried some solutions like "issues # 382" and it did not work, I installed everything and I reinstalled it Directly from github and it still does not resize if someone can help me where I'm going wrong. Here is my configuration bspwmrc and sxhkd, thank you all.
Sorry my bad english, iam from brazil.

sxhkd: http://pastebin.com/3M1iaRrD /
bspwmrc: http://pastebin.com/ALp2nwJu

**Comment by St1rling** [comment]
Try holding the super key

**Comment by H4x4g0N** [comment]
@St1rling I use the "Alt" key instead of the windows key, it always worked here in bspwm, I think the key itself has no difference or is it only possible to resize and move windows with the windows key?

**Comment by Chrysostomus** [comment]
You can choose the key you want to, but I think it defaults to super. From the manual:

```
pointer_modifier
           Keyboard modifier used for moving or resizing windows. Accept the
           following values: shift, control, lock, mod1, mod2, mod3, mod4,
           mod5.
```
So to use alt key, you could put in your bspwmrc

`bspc config pointer_modifier mod2
`
Or something like that. Test it from command line.

**Comment by H4x4g0N** [comment]
@Chrysostomus Thanks for the suggestion, I'll test later and I'll come back with the result.

**Comment by H4x4g0N** [comment]
I tried the option that the @Chrysostomus  but did not work, I tried also changing the sxhkd for a new one and it did not work, I also tried another mouse and nothing, I'll try other options here, if you happen to know of another procedure that I can do to try Reverse this situation please let me know... :(

Edit: If anything, I'm using a usb mouse exactly this model
Model: http://d2fvaoynuecth8.cloudfront.net/assets/01451/produtos/689/mouserazerabyssus00.jpg

**Comment by H4x4g0N** [comment]
Guys I solved my problem, I discovered that regardless of the key I use, bspwm somehow ignores this setting and only uses the windows key as a key to resize or move windows, I do not know this can be considered a bug since I tested With 3 different keyboards and in the 3 I had the same result, summarizing everything I said, regardless of the choice of key that I use to use in sxhkd the only key that it accepts to resize or move the windows is just the windows key, Thank you all for your help.

**Comment by Chrysostomus** [comment]
That kind of sounds that you got wrong to switch modifier... To be clear, I haven't tried the command I suggested, and it might very well be all wrong. I only meant it was probably something like that. 

Alternative is that the option listed in the manual does not work, in which case the issue should be still open.

**Comment by Chrysostomus** [comment]
"regardless of the choice of key that I use to use in sxhkd the only key that it accepts to resize or move the windows is just the windows key"  

In the current version, this option is not set in sxhkdrc, but in bspwmrc.

**Comment by H4x4g0N** [comment]
I understand that I'm starting in bspwm now and I'm noob yet, in that case how would I change the bspwmrc key to resize and move?

**Comment by Chrysostomus** [comment]
Start by trying the command in the terminal. Use tab to complete your command, word by word. I don't have access to my machine right now, but try finding the right command like this
Try running following:

    bspc config pointer_modifier

If I am right, it should give you output that tells you what the current modifier key is. Then you can set it to what you see fit. 

You can put 

     & &  echo success 

After the command you tried. If your terminal says "success"  after you run the command, then the command was successful. If not, syntax was somehow wrong. So something like this:

    bspc config pointers modifier mod2 && echo success 

Once you find the right command, put it into its own line in the file ~/.config/bspwm/bspwmrc. All commands in that file are ran when you start bspwm.

**Comment by Chrysostomus** [comment]
Btw, I'm not entirely sure if alt is mod1 or mod2. I use super key, which is mod4. I think alt_gr is mod5. But try what works.

**Comment by Chrysostomus** [comment]
Okay, I tried it now. The correct command that sets window moving key to alt is

     bspc config pointer_modifier mod1

**Comment by H4x4g0N** [comment]
I tried all the modkeys (1 to 5) just the windows key and altgr answered correctly, I think it's due to the fact that I'm using a usb keyboard and with that it should have a different key mapping than the native keyboard, I'll use it myself The windows key as the main key, thank you man.

**Comment by H4x4g0N** [comment]
I am trying to uninstall all the official packages of arch linux and installed it directly from git, now when I use the Alt key, I can only resize and move windows with the windows key, and when I change to windows I can only resize or move Windows with the "Alt" key, never with the same key that I chose to use, but now I'm going to go ahead, I'll close the topic here
