### ISSUE TITLE
Top Padding Initialization Bug

### ISSUE THREAD

**Issue by zamlz** [baskerville/bspwm#605]
Hi so I've been working on my panel recently and I've been using lemonbar.
However, my bspwm top_padding is not correctly accounting for it. I am using bspwm version 0.9.2. 

When I login to bspwm here is what the bar looks like.
![Image of bar](https://i.imgur.com/iikCgyD.png)

Here it is with a window open.
![Image of bar with window](https://i.imgur.com/nEiaCLK.png)

From my math, the top_padding value that should be used for bspwm is 48. That is exactly what I do in the bspwmrc file. I run the following command and verify that the padding value is 48.

`bspc config top_padding`

And this shows that it was 48. When I try to set the top padding to 48 it is able to fix itself this time.

`bspc config top_padding 48`
![Image of bar fixed](https://i.imgur.com/yfH7h6h.png)

And it stays fixed for the rest of the session.
So I've added the code to the end of the panel script and temporarily fixes the problem.

However the issue is, why does bspwm not like it when the bar is called after the calls in  bspwmrc?

**Comment by kjnirlp** [comment]
check #487
