### ISSUE TITLE
Issue when selecting next active node in multi-monitor setup

### ISSUE THREAD

**Issue by alecive** [baskerville/bspwm#608]
Hello, I have an issue while performing `bspc node -f next.active`. If I have a multi-monitor setup, and the current focus is on an empty desktop on e.g. monitor `eDP1`, I would expect this command to move focus on one of the applications open in the other active desktop, that is the desktop on monitor e..g `HDMI1`. Unfortunately, this does not happen. 

Is this a bug or a feature? Because it's a very minor annoyance but I believe this to be a bug.

**Comment by baskerville** [comment]
Allowing `(m, d, NULL)` as a reference raises a conceptual issue: if `next((m, d, NULL)) = n` then `prev(n) = (m, d, NULL)`?

**Comment by alecive** [comment]
Good point @baskerville . If I got it correctly, I would say no, though.

The behavior I would expect if one `d` is empty is:

 1. if `m1,d` is empty, `m2,d` has at least one node, and focus is on `m1,d`: both `next.active` and `prev.active` would switch to one of the nodes in `m2,d`
 2.  if `m1,d` is empty, `m2,d` has only one node, and focus is on `m2,d`: both `next.active` and `prev.active` would keep the focus on the only node available in `m2,d`.

I don't know if it is clear enough.

**Comment by baskerville** [comment]
> I don't know if it is clear enough.

It is, but the problem is that the commands of the `node` domain deal with nodes, not desktops.

The `next` descriptor of the `node` domain is relative to a reference node, and a NULL pointer isn't a node.

**Comment by baskerville** [comment]
Here's one problematic selector: `next.same_class`.

**Comment by alecive** [comment]
Ok now I understand.

Elevating the NULL pointer to `node` status does not seem to be the best choice here, so I suggest to label this issue as a `wontfix`, sadly for me.

Probably the best solution to work around my problem would be to implement a script in my `sxhdrc` file that, before selecting the next.active node, checks if the desktop is empty and in case this is true, it changes focus on the next desktop instead of focusing on the next node within the desktop. Would it be possible?

**Comment by alecive** [comment]
@baskerville what did https://github.com/baskerville/bspwm/commit/1a4f9dadcd96616df0172d6613369a654e73101c do? Because it does not seems to change the behavior.

**Comment by baskerville** [comment]
It allows NULL references.

So I'm not sure how it wouldn't change the behavior…

**Comment by alecive** [comment]
So I updated the repo, rebooted and tried to perform both `bspc node -f next.local` and `bspc node -f next.active` from both an empty desktop side by side with a desktop with one node, and vice versa. But nothing happened. Is this expected?

**Comment by baskerville** [comment]
Please note that `next.local`, by definition, won't resolve to anything with an empty desktop as reference.

Everything else works as expected for me.

Maybe you could provide the relevant configs (`bspwmrc`, `sxhkdrc`)?

**Comment by baskerville** [comment]
And, just to be sure, the output of `bspwm -v`?

**Comment by alecive** [comment]
Sorry, I realized it was not working because I forgot to `make install`. Now with `bspwm` at version `0.9.2-31-g4350573` I have the expected behavior: `next.active` switches focus to the node in the unfocused desktop if I am in an empty desktop.

 > Please note that `next.local`, by definition, won't resolve to anything with an empty desktop as reference.

This totally makes sense, and I would expect this behavior.

Thank you for the help!
