### ISSUE TITLE
Relatively change fractional node ratio

### ISSUE THREAD

**Issue by olmokramer** [baskerville/bspwm#609]
I have an sxhkd keybinding to change the ratio of the parent node of the focused node by `±0.05`, but i couldn't find an easier way to do this than

```sh
# {De,in}crease ratio of parent node of focused node.
super + {minus,plus}
	geom1=( $(xwinfo -g $(bspc query -N -n @parent/1)) ); \
	geom2=( $(xwinfo -g $(bspc query -N -n @parent/2)) ); \
	w1=$((geom1[0])) h1=$((geom1[1])); \
	w2=$((geom2[0])) h2=$((geom2[1])); \
	[ "$w1" = "$w2" ] && v1=$h1 v2=$h2 || v1=$w1 v2=$w2; \
	r=$(awk "BEGIN \{ print $v1 / ($v1 + $v2) {-,+} 0.05\}"); \
	bspc node @parent --ratio "$r"
```

Of course, this is not the end of the world (although I haven't even implemented range checks so that `0 <= r <= 1`), but I think it would be really useful if I could either:

1. Relatively change the fractional ratio of a node with the `node --resize` command. E.g. `bspc node NODE_SEL -r .1` would change the ratio of the node selected by `NODE_SEL` by `0.1`.
2. Query the current ratio of a node, although in this case I'd expect to be able to query even more node properties like geometry, orientation (whether it's split horizontally or vertically) etc.

I'd be happy to make a pull request that implements option 1.

**Comment by baskerville** [comment]
You can get the split ratio of the parent node with: `bspc query -T -n @parent | jshon -e splitRatio`.

**Comment by olmokramer** [comment]
Right, thanks! But still, what do you think of changing the fractional ratio by passing a number between -1 and 1? Such a value doesn't make sense when interpreted as pixels anyway... I'd still be happy to implement it, just want your opinion first so I don't waste my time :)

**Comment by baskerville** [comment]
Yes it would be fine. I guess you can easily tell if you're dealing with a floating point value by searching for the `.` character.

**Comment by olmokramer** [comment]
Awesome! It's in #610 :) Implementation is a bit different from what you describe, but I explained it in the PR. Guess I can close this now.
