### ISSUE TITLE
Mouse-resizing tiling window to max size breaks the layout

### ISSUE THREAD

**Issue by mikeroll** [baskerville/bspwm#613]
In tiling mode, having two windows `A` and `B`, use right mouse to resize `A` all the way to the right :
```
| A | B |
-->
|   A   |
```
And then we have these problems:
1. `B` has zero width. When resizing "normally" via default keyboard->`bspc node` bindings, the minimum `B`  width of 1 is enforced, so I guess only mouse mode is affected.
2. `A` cannot be resized anymore, neither with mouse nor keyboard.
3. `B` is now not on right/left/top/bottom, but everywhere at once, I can `bspc node -f` in any direction and still `B` will get selected.

Affects both stable 0.9.2 (using `bspc pointer`) and latest master (https://github.com/baskerville/bspwm/commit/4350573ad9aaabba6eceebbe93ed88a539145cac)

**Comment by baskerville** [comment]
It looks like a duplicate of #527.

**Comment by mikeroll** [comment]
Yes, exactly. Didn't see that one.
