### ISSUE TITLE
Issues with rofi window swtiching

### ISSUE THREAD

**Issue by noahl98** [baskerville/bspwm#615]
I'm not sure if this is the right place or this is even a bspwm specific issue, but I've been having an issue where [rofi](https://github.com/DaveDavenport/rofi) is only switching windows around 30-45% of the time. 

There was an issues submitted to the rofi github [here](https://github.com/DaveDavenport/rofi/issues/557) that describes the issue in more detail (see gyfcat links for video). The dev was unable to track down the source of the issue and suggested that its possible that bspwm could be causing the issue.

Here is the version info for my machine:
```
$ bspwm -v
0.9.2-19-gada559d
```
```
$ rofi -v
Version: 1.3.1-240-g98c625f-dirty (makepkg)
```
```
$ uname -r
4.9.8-1-ARCH
```
Distro: `Arch Linux`

[bspwmrc](https://gist.github.com/noahl98/318938553d5f56715f22d3fb03c912d7)

Let me know if there's any more info I can provide that might help.

**Comment by neeasade** [comment]
I see this appears resolved upstream in the linked issue.
