### ISSUE TITLE
How to use names

### ISSUE THREAD

**Issue by arawde** [baskerville/bspwm#616]
I've recently installed bspwm after a long break from Linux. I'm a bit confused on how to use `--names`. In my `bspwmrc`, i have the following:
```
bspc monitor LVDS-1 -d dev web mus mov img
bspc monitor HDMI-1 -d dev2 web2 mus2 mov2 img2
```
I used to use the command `bspc query -D -d` to retrieve the name of the current desktop. I can do `bspc query -D`, but that gives me a bunch of hex values. Now, I see there is an option for `--names`, but when i try `bspc query -D -d --names`, it tells me "Unknown option". Am i setting my names incorrectly, or am I misreading where `--names` should be used?

**Comment by neeasade** [comment]
What's your bspwm version? - - names were added just after 0.9.2 iirc

**Comment by arawde** [comment]
My mistake, I switched to the git package and everything was resolved.
