### ISSUE TITLE
Bspwm doens't draw windows

### ISSUE THREAD

**Issue by Tezkerek** [baskerville/bspwm#621]
A recent Arch Linux [update](https://www.archlinux.org/news/mesa-with-libglvnd-support-is-now-in-testing/) changed some video packages and now bspwm isn't drawing windows. As far as I know, other window managers aren't affected by this, but I've only tested `i3` and `xmonad`.

For example, if I open termite, the mouse pointer changes to text, and `pgrep termite` reveals that the program is running, but no window is drawn. For some reason, `lemonbar` is displayed and works, but that's not the case for `rofi`.

One time, after quitting bspwm and inspecting the `startx` output, I observed a couple of `Bad window: *error id*` lines, but I've since been unable to reproduce those errors.

The Xorg logs don't seem to reveal anything useful; the only errors are about vesa and fbdev.

**Comment by baskerville** [comment]
I can't reproduce.
```
$ termite -v
termite v12
```

**Comment by Tezkerek** [comment]
It happens with any window, not just termite. They're simply not displayed.

This issue appeared after that update, which removed `mesa-libgl` and `lib32-mesa-libgl` and replaced them (or rather upgraded) with `libglvnd` and `lib32-libglvnd`.

**Comment by Tezkerek** [comment]
I went through my bspwmrc and checked line by line to see what was causing the issue. The culprit seems to be `compton`, which makes sense given the updated packages. It may be an issue on my end.
