### ISSUE TITLE
Feature request: Access colors from the X database

### ISSUE THREAD

**Issue by aleprovencio** [baskerville/bspwm#624]
Hello, can we have this? The advantage is a centralized way of configuring colors, something like this:

https://i3wm.org/docs/userguide.html#xresources
https://github.com/jaagr/polybar/wiki/Configuration

**Comment by WhatNodyn** [comment]
Can't this be done through the xrdb utility in the startup script?
I think something like this, albeit more advanced, would be suitable:
```bash
xresource() {
  xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

# As an example
bspc config focused_border_color $(xresource focused_border_color)
```

**Comment by aleprovencio** [comment]
I was thinking more of using a library the way i3 does, but that's a very nice idea @WhatNodyn, thank you.

**Comment by aleprovencio** [comment]
@WhatNodyn, maybe you can help this https://github.com/thestinger/termite/issues/263 posting a similar bashrc script ?

**Comment by WhatNodyn** [comment]
@aleprovencio I'm not sure, I might need to dig in a bit more, since I don't think default colors for a terminal can be changed by processes running in it, unlike bspwm. 🙁

**Comment by aleprovencio** [comment]
@WhatNodyn , I can turn its background color to red by running "printf "%b" "\033]11;#ff0000\007"", does this help?

**Comment by WhatNodyn** [comment]
@aleprovencio A lot! I could stumble upon dylanaraps/wal and figure out how those escape sequences work! I'll be sending a Gist on the issue you referred to soon.

**Comment by aleprovencio** [comment]
thats awesome @WhatNodyn , looking forward to it!

**Comment by baskerville** [comment]
I agree with @thestinger.

**Comment by sagotsky** [comment]
@aleprovencio 

You probably don't care anymore, but here's a quick script for applying xterm's settings in xresources to termite.  This has to be run inside a terminal that already exists, but I imagine a wrapper could launch one and run this immediatley.

```
#!/bin/bash

# make termite use xresources colors

xrdb -query | grep -i 'xterm\*\(color\|background\|foreground\)' | while read resource_line ; do
  color="$(echo $resource_line | cut -f2 -d\* | tr -d ':' | sed -e 's/foreground/fg/' -e 's/background/bg/')"
  xtermcontrol --$color
done
```

**Comment by aleprovencio** [comment]
Yeah, I'm past on this @sagotsky, but thanks for this info.
