### ISSUE TITLE
Additional window rules for `bspc rule` 

### ISSUE THREAD

**Issue by alecive** [baskerville/bspwm#628]
In my (admittedly limited) understanding of `bspwm`, I've learned how to create default rules by using `xprop | grep WM_CLASS` to identify the window type I want to create a rule for.

But, more often than not, that is not enough to identify specific windows within the same application. I know that this is the application's fault, but still the problem exists. I raise here two issues that I am currently having:

 1. I would like to differentiate behavior between a standard Firefox window vs its private browsing counterpart.
 2. I would like to have the presenter mode of `WPS Presentation` to be automatically ran in fullscreen mode (whereas the standard app should be tiled)

In both those cases, their `WM_CLASS` is the same, but additional information can be extrapolated from e.g. `WM_NAME` (their window titles are different).

So my question is: is it possible with the current `bspwm` to identify windows by other than the `WM_CLASS` attribute? If not possible, would it make sense to implement this feature?

Another option (although I don't know if it makes sense) would be to implement something with `descendant_of`. For example, can I specify that any descendant of `WPS Presentation` should be fullscreen?

**Comment by alecive** [comment]
> Another option (although I don't know if it makes sense) would be to implement something with descendant_of. For example, can I specify that any descendant of WPS Presentation should be fullscreen?

Regarding this, I tried using the following two rules:

```
bspc rule -a descendant_of.Firefox state=fullscreen focus=on
bspc rule -a Firefox.descendant_of state=fullscreen focus=on
```

But neither of them worked.

**Comment by baskerville** [comment]
Search for `external_rules_command` in the manual.

**Comment by alecive** [comment]
Oh wow! I knew you got me covered :sunglasses: 

But now I would need some help. How can I integrate it with the `bspc rule -a`?

**Comment by sudo-nice** [comment]
@alecive 
Look here: https://github.com/baskerville/bspwm/tree/master/examples/external_rules

**Comment by alecive** [comment]
Oh, this is great, thanks!

Closing for now, I'll reopen if I have further questions.
