### ISSUE TITLE
High-DPI Screen

### ISSUE THREAD

**Issue by fluffywaffles** [baskerville/bspwm#631]
Can bspwm be convinced to do display scaling? gnome will, for instance, scale fonts, system UI, and user programs up automatically. Either that, or it chooses the 1920x1080 resolution by default?

What I really want is to be able to scale the contents of a bspwm window. Is there a way to do this?

**Comment by alecive** [comment]
I don't know if this helps, but I believe the scaling of windows does not belong to `bspwm`. I handle the scaling in my gnome-settings app, and everything is taken care of accordingly.

**Comment by fluffywaffles** [comment]
That doesn't really make sense. Why would I install gnome-settings if I'm not using gnome? Does bspwm depend on gnome?

**Comment by alecive** [comment]
What I meant, is that this feature belongs to your desktop environment, not your window manager.

**Comment by fluffywaffles** [comment]
... If I understand correctly, a desktop environment is just a bundle of a
window manager + utilities. In the case of bspwm, a desktop environment
might combine bspwm with lemonbar, dmenu, and urxvt. Gnome would combine
mutter with gnome-terminal and a bunch of other stuff. If I'm picking my
own window manager and components, I'm not using gnome -- I'm bundling my
own DE. Right? Maybe there's something I'm not getting here, but that seems
to be in line with what the Arch wiki says too:

https://wiki.archlinux.org/index.php/Desktop_environment

"A desktop environment bundles together a variety of components to provide
common graphical user interface elements such as icons, toolbars, ... Most
importantly, desktop environments provide their own window manager, which
can however usually be replaced with another compatible one."

So I can choose to use Gnome with bspwm instead of Mutter I guess, but I
shouldn't have too.

**Comment by Noah1989** [comment]
To change the DPI setting you can use xrandr on the command line:

`xrandr --dpi 144`

Common values are 96, 120 (25% higher), 144 (50% higher), 168 (75% higher), 192 (100% higher)

Alternatively, you can use any of the GUI tools that various desktop environments supply such as `gnome-settings`, `lxappearance` or `xfce4-apperance-settings`. These do the same thing. 

If you want to be oldschool you can even change the DPI setting in `/etc/X11/xorg.conf` (https://xkcd.com/963/)

Applications using decent toolkits such as GTK or Qt will respect this setting and scale their contents respectively.
