### ISSUE TITLE
Receptacle in wrong desktop

### ISSUE THREAD

**Issue by illusaen** [baskerville/bspwm#632]
I have 5 terminal windows I have set up on desktop 6 that I would like to be re-opened on startup. I used the receptacle system (using the example _induce_ python script in the repo) to grab rules that would make that happen. However, all but the first (_muttwork_) are opening in desktop **1** instead of **6**. 

```
bspc rule -a URxvt:muttwork -o node=@^1:^6:/1
bspc rule -a URxvt:ncmpcpp -o node=@^1:^6:/2/1
bspc rule -a URxvt:ranger -o node=@^1:^6:/2/2/1/1
bspc rule -a URxvt:weechat -o node=@^1:^6:/2/2/1/2
bspc rule -a URxvt:muttpersonal -o node=@^1:^6:/2/2/2

urxvtc -name 'muttwork' -e bash -c "mutt -F config"
urxvtc -name 'ncmpcpp' -e ncmpcpp
urxvtc -name 'ranger' -e ranger
urxvtc -name 'weechat' -e weechat
urxvtc -name 'muttpersonal' -e bash -c "mutt -F config2"
```

**Comment by baskerville** [comment]
You also need an initial state:
```sh
bspc wm -d | extract_canvas > bspwm-initial_state.json
```
And this state needs to be loaded from your `bspwmrc` (with `bspc wm -l "$BSPWM_INITIAL_STATE"`).

**Comment by illusaen** [comment]
Perfect. Thanks much!
