### ISSUE TITLE
Split root node

### ISSUE THREAD

**Issue by maln0ir** [baskerville/bspwm#634]
I'm trying to split root node on current desktop in following way:

      A          D
     / \   =>   / \
    B   C'     E'  A
                  / \
                 B   C

`C'` and `E'` are nodes focused before and after transformation.

According to the manual it should be possible to achieve with command like this:

    bspc node @focused:/ && <some program>

but it doesn't work as I expected: new window is created, but `NODE_SEL` expression seems to be ignored, because focused node (`C'`) is split, not root node (`A`).

Additional info:
    
    $ bspwm -v
    0.9.2
    $ pacman -Qe bspwm # ArchLinux
    bspwm 0.9.2-1
    $ cat .config/bspwm/bspwmrc
    #!/bin/sh

    panel_height=16
    border_width=1

    for side in right bottom left
    do
        bspc config ${side}_padding $border_width;
    done
    bspc config top_padding $(( $border_width + $panel_height ))

    bspc config focus_follows_pointer true

    bspc config border_width $border_width
    bspc config window_gap -$border_width

    bspc config normal_border_color "#282A2E"
    bspc config focused_border_color "#6C7A80"
    bspc config presel_feedback_color "#282A2E"

    bspc config single_monocle true
    bspc config borderless_monocle true

    bspc monitor DVI-D-1 --reset-desktops Meh 1st 2nd 3rd 4th
    bspc monitor DVI-I-1 --reset-desktops Web

    bspc monitor --focus DVI-D-1

**Comment by baskerville** [comment]
This: `bspc node @focused:/` isn't doing anything (and you'll get an error message as of c87c97a). What you might want to do is `bspc node @/ -p west -f`. Or if you want something more robust:
```sh
TARGET=$(bspc query -N @/ -n .ancestor_of)
bspc rule -a '*' -o node="$TARGET" split_dir=west
<some program>
```
