### ISSUE TITLE
Bspwm crash when trying to change layer of multiple windows at a time

### ISSUE THREAD

**Issue by Alkeryn** [baskerville/bspwm#635]
So here is an example :
I use the keys super + {m,ù,*} for moving to layer below,normal,above (i gave the right name to keys in sxhkd (m,ugrave,asterisk)

I use the shortcut super + b to select parent node (to select multiple node)

so admit that i have 2 tiled terminal and 3 floating terminal

so if i select all floating terminal using super + b and try to put them in the below layer (or any other ) bspwm instantly crash
Edit : (dont crash just with floating but with all types of windows)

My other demands (to not make another thread) :
What would have been neat is the option to change the state and flags of all selected nodes

and also the ability to select multiple nodes using the mouse

Also i would enjoy being able to select the last children of a branch and the last children of the brother branch, that would allow to reorganise the tree to switch from normal layout to a grid one in few step using the rotation tool

A nice thing would also be to allow to rearange the tree in a grid layout of instead fibonaci with just one or two shortcut  
or to have multiple choice in which patern the windows arrange themselves by default

And last but not least, being able to moove windows to a new space
ex: i have 3 windows in default fibonaci layout and being able to focus the botom right one and swipe it to the right (both with keyboard and mouse)
so it go from this layout : |=
to this ||| 
where lines are windows

**Comment by baskerville** [comment]
Fixed by 2154ea0.
