### ISSUE TITLE
feat: Infinite "zoom"

### ISSUE THREAD

**Issue by xftroxgpx** [baskerville/bspwm#638]
Is it possible to "zoom" window group 5 and 4 as fullscreen in state Z from https://github.com/baskerville/bspwm#manual-mode  ?
And then keep adding windows or such... and then zoom some more, and eventually zoom out to previous zoom view ... you get the idea :) Would be a fun feature to have OR think about having.

This kind of zoom would make tiling kind of less of a pain, since windows will be larger (cols, rows) when zoomed (since it's not a bitmap zoom).

Saying this without having tried bspwm at all, but have tried i3 a bit :)

Just a thought.
Cheers.

**Comment by neeasade** [comment]
This is currently marked in the TODO file, FYI.

https://github.com/baskerville/bspwm/blob/master/doc/TODO.md

**Comment by xftroxgpx** [comment]
Oh that's cool! I had no idea. It's there since at [least a year](https://github.com/baskerville/bspwm/blob/12edac86fa3be32f799bedca4c8f5c0287a735b0/doc/TODO.md) lookslike. Did not mean to steal any credit.

Cheers!
