### ISSUE TITLE
Override rule from terminal

### ISSUE THREAD

**Issue by alecive** [baskerville/bspwm#639]
I would like to override a `bspc rule` when manually launch some application from terminal.

I have for example `Firefox` that is configured with the following bspc rule: `bspc rule -a Firefox desktop=^5 focus=on`
Now I would like to run a new Firefox instance that does not follow that rule (but that e.g. is launched in the current desktop). Is it possible?

**Comment by baskerville** [comment]
Yes, with a *one shot* rule:
```sh
bspc rule -a Firefox -o desktop=focused && firefox
```

**Comment by alecive** [comment]
but that would change the rule for any other subsequent `firefox` instances, isn't it? Which means that I would have to re-set the previous rule afterwards.

**Comment by baskerville** [comment]
> But that would change the rule for any other subsequent `firefox` instances, isn't it? Which means that I would have to re-set the previous rule afterwards.

No: as the name of the flag implies, the one shot rule will cease to exist after being used once.

**Comment by alecive** [comment]
Oh sorry , I didn't notice the `-o`. Thank you as usual!
