### ISSUE TITLE
How to switch between floating windows?

### ISSUE THREAD

**Issue by theFool32** [baskerville/bspwm#640]
Hi, I want to know how to switch between floating windows when they are stacked together. Is there anyway like `alt+tab` on Windows does? I googled it and found nothing helpful.

BTW, how to maximum a floating window?

THX.

**Comment by theFool32** [comment]
I write a script to switch between windows in the same workspace.
I haven't learnt shell script so it is ugly and buggy.
Anyone has a better solution?

```shell
#! /bin/bash

list=`bspc query -N -d`
current=`bspc query -N -n`
if [[ ! -n $list ]]; then
    exit
fi

found=0
for w in $list
do
    if [[ $found == 1 ]]; then
        bspc node -f $w
        exit
    fi
    if [[ "$w"x = "$current"x ]]; then
        let found=1
    fi
done

for w in $list
do
    bspc node -f $w
    exit
done
```

**Comment by Fnux** [comment]
I think you are looking for this :
```
# Switch focus between the windows of the current desktop
super + {_,shift + } Tab
    bspc node -f {next,prev}.local
```

**Comment by Fnux** [comment]
To switch the state of a window (e.g. switch between `floating` and `fullscreen` states) :
```
# set the window state
super + {y,p,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}
```

**Comment by theFool32** [comment]
@Fnux  thanks for response.
`.local` does work.

I have tried `fullscreen`, but it becomes `floating` after switching to another floating window. How to  make it keep maximum?

**Comment by Fnux** [comment]
It works on my side (bspwm `0.9.1`). 

If I understand correctly :  
* You set the window to `fullscreen`
* You go to another workspace
* When you come back, the window is back to `floating` ?

**Comment by theFool32** [comment]
@Fnux 
No, just two floating window in the same workspace.

**Comment by Fnux** [comment]
Hum, you can do something like `bspc node -f next.local && bspc node -t fullscreen` but it's an awful workaround. Perhaps you can swap the windows instead ? I don't have the time to check right now.

**Comment by theFool32** [comment]
@Fnux  Maybe you are right, it's not suit for tiled window manager.
Thanks a lot.
