### ISSUE TITLE
Change window state based on title instead of class?

### ISSUE THREAD

**Issue by Brett99** [baskerville/bspwm#642]
I would like the "Discord Updater" window to always be pseudo-tiled. 

I tried using bspc -a "Discord Updater" to change the state, but this did not work. 

I cannot do it based on class, because normal Discord has the same class.

**Comment by msteen** [comment]
I have not tested it, but if you set the config setting `external_rules_command` to something like this, it should work:

    #!/usr/bin/env bash

    WID=$1

    if [[ $(xtitle $WID) == 'Discord Updater' ]]; then
      echo 'state=pseudo_tiled'
    fi

**Comment by jallbrit** [comment]
@Brett99 more recent commits have added options to add rules based on `WM_CLASS` and `WM_NAME`, which should solve your issue.
