### ISSUE TITLE
Taking a Youtube video out of fullscreen also takes the browser window out of fullscreen.

### ISSUE THREAD

**Issue by Brett99** [baskerville/bspwm#643]
If I have a fullscreen Chromium window and watch a Youtube video and put it in fullscreen, if I un-fullscreen it, the Chromium window is also taken out of fullscreen. 

Is it possible to have bspwm ignore requests to un-fullscreen the window if they did not come from the keyboard?

**Comment by neeasade** [comment]
possible duplicate of https://github.com/baskerville/bspwm/issues/343

**Comment by frnsys** [comment]
it doesn't seem like this is possible anymore because a node can only have one state, i.e. fullscreen or tiled, but not fullscreen _and_ tiled?

**Comment by Javyre** [comment]
Any updates on this?
I also miss this "feature" from other wms i used. 
Would be nice to have a flag or something added for nodes to behave this way.

**Comment by Javyre** [comment]
Thanks for the commit!
Is there a way to have this as a rule or as a command for non-global setting?
