### ISSUE TITLE
bspc rule -a not working with alacritty

### ISSUE THREAD

**Issue by Sh4d1** [baskerville/bspwm#647]
I have a rule in my config
`bspc rule -a Alacritty follow=on state=floating
`
where Alacritty is the name I get via xprop but it is not launching in floating mode.
Running on VoidLinux

**Comment by baskerville** [comment]
You could do `echo "$@" >> "$HOME"/.rules_cmd.log` from the *external rules command* to check that the window has the proper class name at the right moment in time.

**Comment by Sh4d1** [comment]
Hmm, how do you do it ? :p 
I tried with xtitle, it gives me the same title.
Also I can toggle the floating mode without problems

**Comment by neeasade** [comment]
> Hmm, how do you do it ? :p

- Create a script like `my_script.sh`, containing:

``` sh
#!/bin/sh
echo "$@" >> "$HOME"/.rules_cmd.log
```

-  `bspc config external_rules_command "/path/to/my_script.sh"`
- check the contens of the file `"$HOME"/.rules_cmd.log` to check class name in args, which come in the order of "window ID, class and instance names, monitor, desktop and node selectors" per the [documentation](https://github.com/baskerville/bspwm/blob/master/doc/bspwm.1.asciidoc#global-settings)

**Comment by Alkeryn** [comment]
Thank i was searching for it for a while but how do you stop the rule once you are done with your things ?

**Comment by neeasade** [comment]
@Alkeryn `bspc config external_rules_command ''`

**Comment by Alkeryn** [comment]
Thanks :P
