### ISSUE TITLE
JSON ordering in "bspc wm -l" matters

### ISSUE THREAD

**Issue by pjcj** [baskerville/bspwm#649]
It appears that the JSON used as input to "bspc wm -l" needs to be in a particular order.  The output of "bspc wm -d" meets those requirements.  But processing the output with standard JSON tools can change that order causing the "bspc wm -l" command to fail.

The extract_canvas script https://github.com/baskerville/bspwm/blob/master/examples/receptacles/extract_canvas processes such JSON can can cause problems.

Ideally, the format of the JSON should not matter.  Since it does, I have rewritten extract_canvas to keep the ordering.  It's available at https://github.com/pjcj/base/blob/master/utils/extract_bspwm_canvas - feel free to use it.

**Comment by baskerville** [comment]
Thanks for reporting.

**Comment by pjcj** [comment]
Thanks very much for looking at this so punctually.  I've tried to test it, but I'm afraid I'm still getting errors.  If it helps, I've been using the layout in https://gist.githubusercontent.com/pjcj/0eba4d8c23a56f9e2612bf58063aba5b/raw/4cbd93c014447a05aef0532ba4a6670915e1aac2/layout.json

**Comment by baskerville** [comment]
I can load the supplied layout fine.

Can you be more specific about the commands you use and the errors you get?

**Comment by pjcj** [comment]
OK, that's both good and bad news.  I get a segmentation fault from bspwm, but I can't give any more information than that at the moment.  I'll try again when I get a chance.  The process runs through various scripts so I'll try to create a minimal test case.

**Comment by baskerville** [comment]
Please note that I can easily produce a segfault with `bspc wm -l state.json` where `state.json` is a bogus state, for example `{"a": 0}`. That's a known problem.
