### ISSUE TITLE
Reversing the node sequence

### ISSUE THREAD

**Issue by ry-gon** [baskerville/bspwm#656]
Hi, this is probably a really dumb question but I can't figure it out for the life of me.

By default, nodes open in a 1 (left), 2 (top right), 3 (bottom right) order. For some reason, mine are now organizing themselves to be in a 1 (bottom right), 2 (top right), 3 (left) order, with the newest node always taking up the entire left side of the screen.

How do I reset it to act like it originally did? I want the first node opened to be the one that remains on the left. I imagine it's something as simple as a keybinding, but I've been looking through sxhkdrc with no results.

**Comment by baskerville** [comment]
You might have changed the value of `initial_polarity`?

**Comment by ry-gon** [comment]
Changing the value of `initial_polarity` seems to make the nodes open in a counter-clockwise fashion rather than clockwise, but the problem still persists.

**Comment by ry-gon** [comment]
Just realized this was me being forgetful and comparing bspwm to another wm without realizing it. Everything's working as intended.
