### ISSUE TITLE
Arduino IDE rendering issue

### ISSUE THREAD

**Issue by Alkeryn** [baskerville/bspwm#659]
Well arduino first don't pop on the center of my screen but on the left border of my left screen
when i use arduino context menu they don't deploy on the arduino windows 
and last but not least, when trying to make the arduino windows bigger, it only fill with empty grey space :/ 
here you can see
http://i.imgur.com/mmFWV7K.png

**Comment by Alkeryn** [comment]
and here the context menu that apears on the left screen :
http://i.imgur.com/IWAqUMT.png

**Comment by TheZoq2** [comment]
I used to have the same problem, have a look here https://wiki.archlinux.org/index.php/Java#Applications_not_resizing_with_WM.2C_menus_immediately_closing

**Comment by raycewest** [comment]
Just discovered I also have this issue - any luck this past year?

**Comment by jallbrit** [comment]
@Alkeryn please close the issue if your problem is solved.

**Comment by Alkeryn** [comment]
been a while but it was fixed by Zoq2's link
forgot about the issue later
