### ISSUE TITLE
Feature : Specify size and position in rules

### ISSUE THREAD

**Issue by JBouron** [baskerville/bspwm#660]
I'm thinking of a new feature that would allow the user to specify both the size and position on the screen in rules. Those would only be applied on floating windows naturally.

For instance, if the user want a program to run in floating state, with size 800x600, in the top left corner of the screen (0, 0), he could add the following rule : 
`bspc rule -a <class name> state=floating size=800x600 position=0;0`

This is a feature that I would like to have for some of my programs and I think other people may  appreciate it as well.

I am willing to implement it, but I first make this issue to see if there is already a way to achieve this.

Thanks

**Comment by baskerville** [comment]
There isn't any rule consequence for this (but anything can be achieved by external rules).

If you're willing to implement this, the syntax should be `rectangle=800x600+0+0`, (there's already a `parse_rectangle` function used by `monitor --rectangle`).
