### ISSUE TITLE
Focusing east across monitors sometimes focuses the wrong window

### ISSUE THREAD

**Issue by TheZoq2** [baskerville/bspwm#662]
With the following window setup:
```
|---------------| |---------------| 
|               | |       |       | 
|   window 1    | |window2|window3| 
|               | |       |       | 
|---------------| |---------------| 
Monitor 1 ^         Monitor 2
```
If window 1 is focused, and I execute `bspc node focused -f east`, window 3 gets focused instead of window 2. It also looks like window 2 gets focused for a very short time before 3 gets focused.

This also seems to happen if the window2 'node' is split into more more nodes.

However, if window 3 is split horizontally like this:
```
|---------------| |---------------| 
|               | |       |window4| 
|   window 1    | |window2|-------| 
|               | |       |window5| 
|---------------| |---------------| 
Monitor 1 ^         Monitor 2
```

Everhthing seems to work fine

Also, focusing west, east, north and south seem to work without issues

Here is a link to my dotfiles if they could cause issues. Most of the files in there are not used anymore but I havn't gotten around to cleaning them up https://github.com/TheZoq2/dotfiles/tree/master/.config/bspwm

**Comment by baskerville** [comment]
Does `bspc query -N -n east` return the correct value?

**Comment by TheZoq2** [comment]
Yes, query seems to work fine

**Comment by TheZoq2** [comment]
I tested it again and it looks like I did something wrong when testing it last time. `bspc query -N -n east` also returns the wrong node

**Comment by msteen** [comment]
@TheZoq2 Are you sure the problem lies with `bspwm` and not your script? I just tried to reproduce this issue, but was unable to do so (I am running the latest git master). Both `bspc node focused -f east` and `bspc query -N -n east` give correct results.

Why the Python script? Why not just use:

    super + {Left,Down,Up,Right}
      d={west,south,north,east}; \
      bspc node --focus $d || \
      bspc monitor --focus $d

    super + shift + {Left,Down,Up,Right}
      d={west,south,north,east}; \
      bspc node --swap $d || \
      bspc node --to-monitor $d

In my own config I also added priority to the preselected.

    super + shift + {Left,Down,Up,Right}
      d={west,south,north,east}; \
      bspc node --to-node "${d}.!automatic" || \
      bspc node $d --to-node 'focused.!automatic' || \
      bspc node --swap $d || \
      bspc node --to-monitor $d

An idea I took over from [this config](https://github.com/Stebalien/bspwm-config/blob/master/sxhkdrc).

**Comment by TheZoq2** [comment]
I just tried it and it seems to work in the current bspwm version so I guess the issue is fixed.

I didn't know you could do what my python script does just using sxhkd, I'll give that a try later
