### ISSUE TITLE
Feature: Tile only if presel

### ISSUE THREAD

**Issue by fredlebel** [baskerville/bspwm#664]
This is a feature request.

I would find useful an option to float all new windows by default unless there's a presel specified.  In which case a new window would be tiled into the presel position.

Thank you

**Comment by baskerville** [comment]
This can be achieved with the following external rule:
```sh
#! /bin/sh

target=$(bspc query -N -n '.!automatic.local' | head -n 1)

if [ -n "$target" ] ; then
	echo "node=${target}"
else
	echo "state=floating"
fi
```
