### ISSUE TITLE
Output window ID in bspc query -T results

### ISSUE THREAD

**Issue by IamCarbonMan** [baskerville/bspwm#666]
I'm using a script that parses the JSON output of `bspc query -T -m` to display a list of windows and desktops in lemonbar. Currently I need to run `bspc query -N -n <id>` for each window object to get a real window id from the bspwm id, in order to use tools like xdotool and xtitle via lemonbar clicks. It would be really useful if each window object in the JSON output had a `wid` property with the actual window id.

**Comment by baskerville** [comment]
A window ID is just a number, so the tools that work with window IDs should accept both the decimal **and** hexadecimal representation.

You can convert a decimal ID to an hexadecimal ID from a shell script with `wid=$(printf '0x%08X' "$id")`.

Please note that `bspc query -N -m` is a valid query.
