### ISSUE TITLE
Question about layout

### ISSUE THREAD

**Issue by vsr625** [baskerville/bspwm#667]
I am currently an i3 user, and thinking to switch to bspwm, and I just trying it out now. In i3wm whenever I open a new window, it opens to right of the currently selected window, and the previous windows still remain in their previous position as much as possible. But in bspwm it's opposite, whenever I open another windows, the previous positions of all the current windows is altered and the new window replaces the node which is currently focused. My question being, if it's possible to create a new windows without altering the positions of the existing windows. I know about preselecting position, but all i'm asking is if there is any other way to do this.

**Comment by ikn** [comment]
You can customise window positioning using external_rules_command.

**Comment by BenKerry** [comment]
An other solution might be the following rule: `bspc rule --add '*:*' private=on`

**Comment by jallbrit** [comment]
@vsr625 do you still have this problem? Have you tried using `bspc automatic_scheme`?
