### ISSUE TITLE
bspc query -D -d --layout

### ISSUE THREAD

**Issue by BenKerry** [baskerville/bspwm#672]
I would like to have something like `bspc query --desktops --desktop --layout` because currently you have to track the changes yourself or listen to `bspc subscribe desktop_layout`. A native solution similar to `--names` would solve this I think.

**Comment by msteen** [comment]
It will obviously be slow compared to a native solution, but you could use this to achieve what you want:

    bspc wm --dump-state | jq --raw-output ".monitors[].desktops[] | select(.id == $(printf '%d' $(bspc query --desktops --desktop))).layout"

**Comment by baskerville** [comment]
@msteen Simpler version:
```sh
bspc query -T -d | jshon -e layout -u
```

**Comment by msteen** [comment]
@baskerville Nice, I did not know about that option. It, `bspc query -T -d | jq -r .layout` if you do not have jshon, should also be a lot faster dumping everything and then filtering. Ah well, my version might still be useful to those that need to query things that cannot be queried with `bspc query`.

**Comment by BenKerry** [comment]
Hey big thanks. That's perfect for my needs.

**Comment by m-kru** [comment]
For those, who want to detect the desktop layout with standard tools.

```bash
	if bspc query -T -d | grep -q "\"layout\":\"tiled"
	then
		echo -n T
	else
		echo -n M
	fi
```

**Comment by emanuele6** [comment]
@m-kru in the git master version of `bspwm`, you can simply use `bspc query -D -d focused.tiled` and `bspc query -D -d focused.monocle` (there are also `.user_monocle` and `.user_tiled` if you are interested in the userLayout).

**Comment by m-kru** [comment]
@emanuele6 actually what is the difference between `"layout"` and `"userLayout"`?

**Comment by emanuele6** [comment]
RE: @m-kru
The userLayout is the layout that was set by the user with `bspc desktop -l LAYOUT` (or `tiled` by default).
The layout is the actual layout of the desktop. It can differ from the userLayout if you have `single_monocle` turned on for example.

If you have `single_monocle` turned on and you have only one window open in a desktop with `tiled` as the userLayout, the layout of that desktop will be `monocle`, but its userLayout will be `tiled`; if you then open a second window, both the layout and the userLayout will be `tiled`.
