### ISSUE TITLE
Is there a way to create mod?

### ISSUE THREAD

**Issue by karambaq** [baskerville/bspwm#673]
For example like in i3 resize mod:

bindsym $mod+r mode "resize"
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 5 px or 5 ppt
        bindsym k resize grow height 5 px or 5 ppt
        bindsym l resize shrink height 5 px or 5 ppt
        bindsym semicolon resize grow width 5 px or 5 ppt

        # same bindings, but for the arrow keys
        bindsym Left    resize grow     width   5 px or 5 ppt
        bindsym Down    resize shrink   height  5 px or 5 ppt
        bindsym Up      resize grow     height  5 px or 5 ppt
        bindsym Right   resize shrink   width   5 px or 5 ppt
        
        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"

**Comment by neeasade** [comment]
mode? 

you'd have to script your mode switch logic on your own. one approach people take is to switch which sxhkd file is currently active.

**Comment by karambaq** [comment]
@neeasade I mean, I want to print super + r and then resize my windows by arrows, and after I do that I tap Escape and exit this mode. Is there any example of things like this?

**Comment by neeasade** [comment]
yes - have 2 sxhkds, the first being 'normal mode' sxhkdrc_normal symlinked to the default location:

```
Super + r
rm ~/.config/sxhkd/sxhkdrc; \
  | ln -s ~/.config/sxhkd/sxhkdrc_mode ~/.config/sxhkd/sxhkdrc; \
  | pkill -USR1 -x sxhkd
```

in your 2nd sxhkdrc, bind the arrows, and have an ESC bound like:
```
Escape
rm ~/.config/sxhkd/sxhkdrc; \
  | ln -s ~/.config/sxhkd/sxhkdrc_normal ~/.config/sxhkd/sxhkdrc; \
  | pkill -USR1 -x sxhkd
```

I lifted these examples from howm, which does modes like this.

https://github.com/HarveyHunt/howm/tree/master/examples

**Comment by karambaq** [comment]
@neeasade I found. Thanks.
`super + r : {Left, Down, Up, Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}
`
