### ISSUE TITLE
Secondary monitor behaves as "primary" in bspwm.

### ISSUE THREAD

**Issue by kalq** [baskerville/bspwm#679]
I have a laptop that I connect a secondary monitor to via HDMI. Ever since the latest update that monitor behaves as the primary one in terms of desktop numbers. For example in my bspwrc I have the following:

`bspc monitor eDP1 -d 1 2 3 4 5`
`bspc monitor HDMI2 -d 6 7 8 9 10`

In the past this would let me use `super + {1-5}` for the desktops on my laptops actual screen and `super + {6-0}` for the desktops on the secondary monitor I plug in via HDMI. Now with 0.9.3 it's been reversed and it's really annoying because it goes against my muscle memory. Worse when I unplug the secondary monitor and I have a script to reset settings then I go back to using 1-5 for the desktops on the main laptop screen so it's not like I can get used to the new way of dealing with this.

Is there a way to fix this? The output of `bspc wm -d` has the plugged in secondary monitor appear first which really doesn't seem like the ideal way to do it.

**Comment by baskerville** [comment]
What's the output of `bspc wm -d | jq '.monitors[] | {name, rectangle}`?

**Comment by kalq** [comment]
`{
  "name": "HDMI2",
  "rectangle": {
    "x": 0,
    "y": 0,
    "width": 1920,
    "height": 1080
  }
}
{
  "name": "eDP1",
  "rectangle": {
    "x": 0,
    "y": 1080,
    "width": 2560,
    "height": 1600
  }
}
`

**Comment by baskerville** [comment]
The monitors are automatically sorted as of 4b035e0.

You can prevent this with the following script:

```sh
#! /bin/sh

MON_ID=$(bspc query -M -m "$1")
MON_POS="$2"

[ $(bspc query -M -m "$MON_POS") != "$MON_ID" ] && bspc monitor "$MON_POS" -s "$MON_ID"

bspc subscribe monitor_swap | while read msg ; do
	[ $(bspc query -M -m "$MON_POS") != "$MON_ID" ] && bspc monitor "$MON_POS" -s "$MON_ID"
done
```

And call it from your `bspwmrc`:
```sh
enforce_monitor_position eDP1 '^1' &
```
