### ISSUE TITLE
padding changes when stalonetray starts

### ISSUE THREAD

**Issue by ikn** [baskerville/bspwm#684]
When I log in, my bspwmrc runs `bspc config left_padding -2`.  When [stalonetray](http://stalonetray.sourceforge.net/) starts and shows up at the bottom of the screen, taking up only the left part, the left padding is changed so that the left border of the desktop lines up with the right border of stalonetray.  The active desktop instantly resizes; other desktops only resize when their trees change.  If I run the same padding command again, the padding is corrected and stays like that.

This started happening recently, when I upgraded bspwm.  I'm using the AUR package `bspwm-git` on Arch Linux, but I'm not exactly sure what the versions mean: `upgraded bspwm-git (1228-1 -> 1:0.9.2.r56.gcc3d306-1)`.

**Comment by baskerville** [comment]
This might be caused by the handling of `_NET_WM_STRUT_PARTIAL`.

**Comment by ikn** [comment]
Ah, looks like stalonetray was setting a left strut, since it decide which direction to use automatically based on geometry configuration.  Turns out I can override this, so it works now - thanks for the hint.
