### ISSUE TITLE
automatic monitor ordering fix 

### ISSUE THREAD

**Issue by Gingerbreadz** [baskerville/bspwm#686]
Looks like 4b035e0ac2e1b6832cd8edd2e229ffa9f33562ee breaks my monitors' order : I use ```bspc wm -a``` to create « virtual » monitors with custom geometries spanning across my displays (so they potentially have a bigger rectangle than my actual monitors), and according to this fix, they are to be listed first, but to me, it would be more convenient to have those « virtual » monitors listed last. For now, I added a series of ```bspc monitor XXX --swap ^n``` to manually order all of my monitors.

**Comment by msteen** [comment]
I doubt that there is any order to be found that satisfies everyone's use case, one of the beautiful things of `bspwm` is that it allows you to script it to your liking. So why not automate your use case with the following script:

    # Place the partial sorted list at the beginning
    # and append the missing ones from the complete list in the order they appear.
    # sort_partial <complete_list> <partial_sorted_list>
    function sort_partial() {
      printf '%s\n%s' "$2" "$1" | awk '!($0 in a) { a[$0]; print }'
    }
    function get_mon_list() {
      # There probably is a faster way, but this works.
      bspc wm --dump-state | jq --raw-output '.monitors[].name'
    }

    orig_mon_list=$(get_mon_list)

    # Add your virtual monitors.
    # bspc wm -a ...

    # Swap them in the order.
    i=1
    while read -r mon; do
      bspc monitor $mon --swap "^$i"
      ((i++))
    done <<< $(sort_partial $(get_mon_list) "$orig_mon_list" | head -n -1)

**Comment by baskerville** [comment]
I've added `wm --reorder-monitors` in b4c4707, the command works like `monitor --reorder-desktops`.

**Comment by msteen** [comment]
@baskerville That is a nice addition in general, thanks!

It simplifies the script I made to this:

    # Place the partial sorted list at the beginning
    # and append the missing ones from the complete list in the order they appear.
    # sort_partial <complete_list> <partial_sorted_list>
    function sort_partial() {
      printf '%s\n%s' "$2" "$1" | awk '!($0 in a) { a[$0]; print }'
    }
    function get_mon_list() {
      # There probably is a faster way, but this works.
      bspc wm --dump-state | jq --raw-output '.monitors[].name'
    }

    orig_mon_list=$(get_mon_list)

    # Add your virtual monitors.
    # bspc wm -a ...

    bspc wm --reorder-monitors $(sort_partial "$(get_mon_list)" "$orig_mon_list")

**Comment by baskerville** [comment]
> bspc wm --dump-state | jq --raw-output '.monitors[].name'

This can be written as `bspc query -M --names`.

**Comment by Gingerbreadz** [comment]
Thank you all for your answers ! 
I was hoping this to be unexpected behavior, so I would not have to script my way though, but b4c470784d98fd3371cf7d994a714cad83086ffc made it trivial to reorder monitors, exactly what I was looking for !

@msteen Your script is quite clever, personally I found ```bspc query -M --names``` to output the same as your ```get_mon_list()``` function. Ok, I ended up this script

    orig_mon_list=$(bspc query -M --names)

    # Add your virtual monitors.
    # bspc wm -a ...

    bspc wm --reorder-monitors $(echo "$orig_mon_list `bspc query -M --names`" | tr ' ' '\n' | uniq)

Again, thank you all, I think this is pretty much solved.

**Comment by msteen** [comment]
@Gingerbreadz I was just writing a script that was somewhat similar to what you needed and remembered why I was not using `uniq`, it only works on **adjacent** matching lines. Are you sure your script is correct and that you did not just get lucky with how `--reorder-monitors` happened to handle duplicate monitor names? If so, changing your script similar to this, would make it less dependent on the current implementation:

    bspc wm --reorder-monitors $(echo "$orig_mon_list"$'\n'"$(bspc query -M --names)" | awk '!($0 in a) { a[$0]; print }')

**Comment by Gingerbreadz** [comment]
@msteen I was also wondering why you did not use ```uniq``` in your previous answers ; and you're right, it only works for adjacent matching lines (I was just lucky :/). I found something quite similar to your awk approach, but a tiny bit shorter : :) 

`bspc wm --reorder-monitors $(echo -e "${orig_mon_list}\n$(bspc query -M --names)" | awk '!a[$0]++')`

It's the same idea, just using an associative array instead of an array : each input line is held as a key and on their first occurrence, its associated value is incremented and the default action (print) is triggered.
