### ISSUE TITLE
pointer_modifier with mod4 doesn't work as expected

### ISSUE THREAD

**Issue by NicolasCARPi** [baskerville/bspwm#687]
Hello,

`bspc config pointer_modifier shift` works as expected, and shift is the modifier. But I don't manage to bind it to the Super key (mod4), the key used for all the other WM shortcuts.

### Action:
`bspc config pointer_modifier mod4`

### Expected result:
All the mouse actions can be performed while pressing the Super key (aka mod4), the one with the Windoze logo on it.

### Actual result:
The move action works, but not the resize ones. They only work with shift, lock, control, mod1 and mod2.

Are you able to reproduce? Am I doing something wrong? I'm using 0.9.3 on Archlinux.

`xmodmap` output:

~~~
shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
~~~

Regards and thanks for this great piece of software :)

~Nico

**Comment by baskerville** [comment]
One thing you could do is to post the bindings you use.

And capture the potential errors: `sxhkd > ~/.sxhkd.log 2>&1 &`.

**Comment by NicolasCARPi** [comment]
I do not use any binding. I just launch the bspc config command in a shell and try out. As I understand, this part doesn't need sxhkd anymore but should be put in the .config/bspwm/bspwmrc.

I could try on another (Archlinux) computer and here it behaves as expected. So my guess is there is something wrong somewhere on the first computer, and the bug is in my config, not in the software :)

Closing.

Regards,
~Nico

**Comment by TheZoq2** [comment]
For anyone reading this in the future: I had the same issue and I think the fix is to run the config command before starting sxhkd. This means that you have to kill sxhkd and restart it if you try to change it on the fly, not in bspwmrc.

I could be wrong about that though
