### ISSUE TITLE
Refresh bspwm

### ISSUE THREAD

**Issue by Deomkan** [baskerville/bspwm#689]
Is it possible to refresh bspwm and apply the new settings? I would like to change the colors of borders without restarting

**Comment by MrAnno** [comment]
You can execute the config file as a shell script.

Duplicate of #332

**Comment by Deomkan** [comment]
Oh that's amazing, so it doesn't create another process?

**Comment by neeasade** [comment]
if my another process you mean another running instance of bspwm, no -- bspc is a client for configuring a running instance of bspwm.

**Comment by MrAnno** [comment]
It does create another process, but the process exits after executing the last command in your config. Just be careful not use "blocking" commands.

bspwm itself does the same: https://github.com/baskerville/bspwm/blob/b4c470784d98fd3371cf7d994a714cad83086ffc/src/settings.c#L40

A `fork()` and one simple `exec()` on the configuration file.

**Comment by Deomkan** [comment]
Ok nice explanation, thank you!
