### ISSUE TITLE
Shouldn't focus always follow

### ISSUE THREAD

**Issue by msteen** [baskerville/bspwm#691]
It could very well be I am missing something in the manual or that there is a very good reason for the current behavior, but I dislike that if you move/swap anything that is not local to your current desktop, that the focused entity loses its focus. For example:

    super + shift + {Left,Down,Up,Right}
      bspc node --swap {west,south,north,east}

Works exactly like I would expect, if I swap the focused node in a given direction, the focus will remain with the focused node. This is not the case for the following:

    super + {shift,alt} + {1-9,0}
      { bspc desktop --swap \
      , bspc node --to-desktop \
      } '^{1-9,0}'

This will keep the focus at the location it originally held, it will not follow the focused entity that is being moved. I say entity, because it could be a node, desktop or monitor. I can of course fix this myself by placing the necessary calls to `bspc {node,desktop,monitor} --focus last`, but I was wondering whether the default should not be addressed instead.

My point of view when executing command in the context of the focused, is that of the focused thing, so I expect to follow it, but it could very well be that in general most people find the current behavior more intuitive. If that happens to be the case, I will close the issue and will just have to deal with those additional focus fixes.

**Comment by baskerville** [comment]
You probably don't want that in the general case: maybe I just want to make some room in the focused desktop and that's the reason why and I'm moving windows around.

Please note that commands can be chained. Hence you can move the focused window *and* re-focus it: `node -d next -f`.

You'll still get an unwanted `node_focus` event for the `-d` command though.

I guess I could make a variant of `-d`.

**Comment by msteen** [comment]
Exactly, you would not want to do this in the general case, it should only apply to focused things, otherwise it would only worsen the loss of focus of things focused. My point is that I do not like that my focus is implicitly changed by commands when there is no need for it.

I tried chaining, since the manual said `COMMANDS`, plural, but I naively tried to change `bspc node --to-desktop next; bspc node --focus last` to `bspc node --to-desktop next --focus last`, which did not work. I now see that it should have been just `bspc node --to-desktop next --focus`. This simplifies things quite a bit:

    super + {_,shift + ,alt + }{comma,period}
      { cmd='bspc desktop --focus';   fix='';                          \
      , cmd='bspc desktop --swap';    fix='bspc desktop --focus last'; \
      , cmd='bspc node --to-desktop'; fix='bspc node --focus last';    \
      } $cmd {prev,next}; $fix

Can become just:

    super + {_,shift + ,alt + }{comma,period}
      { bspc desktop \
      , bspc desktop --swap \
      , bspc node --to-desktop \
      } {prev,next} --focus

It is not just `--to-desktop` that changes focus in unexpected ways (to me), the same holds true for `bspc desktop --swap`. I would expect it to keep the focus to the desktop I had focused before swapping and just follow it to its new position. An example of this would be the keybindings I showed above, if I keep pressing `super + shift + comma`, I can easily move my desktop around, but by default, I would have to press `super + comma` (change focus in this example) in between each.

Other examples of focus not behaving like I expect are `bspc desktop --to-monitor` and `bspc node --to-monitor`. Probably `bspc monitor --swap` as well, but I am not sure what it is supposed to do, since all it does for me is swap the desktops shown on my `lemonbar` for the relevant monitors, but the desktops are still shown on their original monitor.

**Comment by baskerville** [comment]
It makes sense.

**Comment by msteen** [comment]
Good to hear you understand my issue and understand why it would be more intuitive.

I just stumbled on another command that has this focus issue. I have a script that uses `--reorder-desktops` so that if I move a desktop back to its standard monitor it will automatically be swapped back to its standard position on that monitor. It works fine, but it also affects the focus. It would probably be fixed by fixing the general desktop swapping case, since it seems to use regular swapping to implement the reorder (I can see the swapping happening on my `lemonbar`), but know that the issue is also present in that command. I assume its the same for `--reorder-monitors`.
