### ISSUE TITLE
"bspc node -{c,k}" kill urxvtd instead of just urxvtc instance.

### ISSUE THREAD

**Issue by lebarondemerde** [baskerville/bspwm#692]
Hello,

I just installed bspwm v0.9.3 in my FreeBSD box. All configs still default but sxhkd call urxvtc instead of urxvt - "super + Return".

For some reason when I run **bspc node -{c,k}** it also kill urxvtd instead of killing just the focused urxvtc instance, and so all urxvtc windows close all together.

I am currently starting urxvtd from .xinitrc file, but tryied starting it from bspwmrc with the same result, wherever I use **eval $()** or not.

Thanks!

**Comment by neeasade** [comment]
`bspc node -k` does this (because it severes the x connection causing urxvtc to crash, crashing urxvtd as well), but I can't reproduce with `bspc node -c`

**Comment by lebarondemerde** [comment]
Yes, totally worked!

I will create a separated hotkey here then.

Thanks!
