### ISSUE TITLE
Sending a node to an empty desktop owned by another monitor activates it

### ISSUE THREAD

**Issue by Anthony25** [baskerville/bspwm#701]
Hi,
When I send a node to another desktop with `bspc node -d targeted_desktop`, I have a different behavior depending on which monitor owns it:
  - If the targeted desktop (empty or not) is owned by the same monitor than the currently focused one, the focus is kept on the current desktop after sending the node;
  - If the targeted desktop is owned by another monitor and already has one or several children, same behavior than before;
  - If the targeted desktop is owned by another monitor and is empty, the focus stays on the current desktop, but the other monitor M will mark the targeted desktop as active (it will switch the display to this desktop).

I think that this issue appeared between 0.9.2 and 0.9.3 (I was on 0.9.2 stable, and upgraded directly to 0.9.3).
Thanks!

**Comment by baskerville** [comment]
This regression comes from 68ecbc483885f85158e611216b4f0a68b76ff739.

**Comment by Anthony25** [comment]
Thanks a lot!
