### ISSUE TITLE
Can't use monitor name with dot

### ISSUE THREAD

**Issue by jaen** [baskerville/bspwm#704]
To work around a firmware DPMS bug I need to have my monitor in DP 1.2 mode. This makes the monitor report as `DP-0.8` instead of `DP-0`, but `bspc` doesn't seem to acknowledge this as a proper screen:
```
╭─jaen@hotaru  ~ ‹2.4.0› 
╰─$ bspc monitor "DP-0.8" -d VI VII VIII IX X          
monitor: Invalid modifier found in 'DP-0.8'.
```
Is there any reason for not accepting monitor names of this form?

**Comment by Weker01** [comment]
Duplicate of #552

**Comment by jaen** [comment]
Thanks, the linked issue did help.

**Comment by baskerville** [comment]
`%DP-0.8` will work as of 614a56b.
