### ISSUE TITLE
Feature request : merge borders

### ISSUE THREAD

**Issue by Alkeryn** [baskerville/bspwm#705]
So i have 1px borders but when two windows are next to each others it make a 2px border because they are next to each other
so an option(optional) to make borders merge / or superposate (one over the other) when they are touching would be neat

See : outer border are 1px
but inner ones are 2px because they aren't merged, which make uneven borders

**Comment by Alkeryn** [comment]
![image](https://user-images.githubusercontent.com/11599075/30250591-2e87dc60-9651-11e7-8c6b-7e18f90d9d49.png)

**Comment by Alkeryn** [comment]
![image](https://user-images.githubusercontent.com/11599075/30250598-48e6e93e-9651-11e7-88d4-33d4ffe24759.png)
Normal borders next to unmerged touching borders

**Comment by neeasade** [comment]
https://github.com/baskerville/bspwm/blob/master/examples/overlapping_borders/bspwmrc

**Comment by Alkeryn** [comment]
Wew you can script it ? well thanks
Though it hides my bar :/

**Comment by Alkeryn** [comment]
Fixed removing the top in the loop
