### ISSUE TITLE
border=on/off for bspc rules

### ISSUE THREAD

**Issue by Vixtron** [baskerville/bspwm#706]
I find being able to disable and enable window borders useful for my uses, so if it's possible to have a bspc rule to do it.

**Comment by baskerville** [comment]
The corresponding rule consequence already exists.

**Comment by Vixtron** [comment]
I see, it seem doesn't work, maybe I'm doing something wrong, I tried messing around with it and tried multiple things as well.

`bspc rule -a termite border=0`
