### ISSUE TITLE
Set border only to top of the window.

### ISSUE THREAD

**Issue by karambaq** [baskerville/bspwm#707]
I mean, just a line on the top of the window. Is it possible?

**Comment by neeasade** [comment]
This is currently not possible in bspwm. Perhaps you could fake it by writing your own border program that only highlights the top line ala [wmutils](https://github.com/wmutils/opt), but the window would still not fill the sides or bottom border. An alternative might be launching a lemonbar instance on top and spacing it with a receptacle (pretty hacky but possible).
