### ISSUE TITLE
Empty space at the top of the screen after hiding bar

### ISSUE THREAD

**Issue by Tezkerek** [baskerville/bspwm#711]
After I hide lemonbar, I am left with a blank space at the top of the monitor, where the bar used to be. I remember that xmonad had a function to reset the layout and cover that space, but I can't for the life of me figure out how to do this in bspwm.

I've tried `bspc node '@/' -E`, `bspc node -z top 0 30` too...
How do I do it?

**Comment by msteen** [comment]
Do you mean this: `bspc config top_padding 0`

**Comment by Tezkerek** [comment]
Huh, I remember trying it before with no result, but now it worked. Thanks!
