### ISSUE TITLE
Excluding floating windows from bspc rules

### ISSUE THREAD

**Issue by xiamaz** [baskerville/bspwm#713]
For some applications such as keepass or firefox, I would like to keep the main window on their own workspaces, but popups, such as a download window or a confirmation dialog should appear on the workspace I am currently working on.

I have noticed that these windows are automatically created as floating windows. So is it possible to create rules specifically for tiled windows or to exclude floating windows from the rules?

**Comment by baskerville** [comment]
As of 49caeb8, you can access the current value for the `state` key from the *external rules command* with
```sh
eval "$4"
if [ "$state" != "floating" ] ; then
```

**Comment by d125q** [comment]
Note that in the case of Firefox, the main window has `WM_CLASS(STRING) = "Navigator", "Firefox"` whereas other windows do not have the `"Navigator"` instance name.  You can use that to differentiate between them.

**Comment by xiamaz** [comment]
> As of 49caeb8, you can access the current value for the state key from the external rules command 

Thanks for the commit. I will try the new commit later, with some programs which don't expose different instance names.

> Note that in the case of Firefox, the main window has WM_CLASS(STRING) = "Navigator", "Firefox" whereas other windows do not have the "Navigator" instance name. You can use that to differentiate between them.

Thanks for the hint. For firefox and chromium this seems to work quite reliably to differentiate different window types.
