### ISSUE TITLE
Desktops on wrong monitor

### ISSUE THREAD

**Issue by kirreen** [baskerville/bspwm#715]
I do this:
bspc monitor HDMI-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX X
And in my polybar it looks right, as in, the workspaces names are on the right monitors. However, if I press Super + 2 to go to II on HDMI-1 I go to VII on eDP-1. So it seems like the workspaces stay where they are but get renamed.

**Comment by msteen** [comment]
What does your `sxhkd` configuration file look like? I tried switching desktops using both their index and name, and both work. This is the configuration I am using for switching between desktops:
```
super + {_,shift + ,alt + }{1-9,0}
  { bspc desktop \
  , bspc desktop --swap \
  , bspc node --to-desktop \
  } {1st,2nd,3rd,main,files,apps,terms,conf,webapps,media} --focus
```
And what version of `bspwm` are you using? I am using a local build based on the git commit d953f6fa7f1836590c59c9882d70919144a168e3.

**Comment by baskerville** [comment]
@msteen #691 was fixed, so the `--focus` at the end is no longer needed.

**Comment by msteen** [comment]
@baskerville Right, thanks for the reminder! I had not yet updated my config to reflect the fix. I now have this:
```
super + {_,shift + ,alt + }{1-9,0}
  { bspc desktop --focus \
  , bspc desktop --swap \
  , bspc node --to-desktop \
  } {1st,2nd,3rd,main,files,apps,terms,conf,webapps,media}
```

**Comment by kirreen** [comment]
My problem was the indexes not changing with monitor -d, but I changed sxhkdrc to use the labels of the workspaces instead. Did not know this was possible. Thanks!
