### ISSUE TITLE
Inconsistent polarity when floating and sticky node present

### ISSUE THREAD

**Issue by danikron** [baskerville/bspwm#719]
When I open two new nodes on an empty desktop then the second node will appear to the west, but if I open one node and then switch desktop to any other and back again before opening the second it will instead appear to the east (or reversed if initial_polarity is set to second_child).

**Comment by baskerville** [comment]
I can't reproduce.

**Comment by danikron** [comment]
Strange, I see it on two different machines, admittedly with similar settings. Any idea if there's anything that could cause that sort of behaviour on my end?

**Comment by baskerville** [comment]
Could you provide a `bspwmrc`?

**Comment by danikron** [comment]
https://github.com/danikron/dotfiles/blob/master/bspwm/bspwmrc

**Comment by danikron** [comment]
For clarity, [this](https://imgur.com/a/qvLdc) is what I'm seeing.

**Comment by danikron** [comment]
On further investigation this also happens with the example bspwmrc from this repo, but only when a sticky floating window is present (which is usually always the case for me, as I use a scratchpad).

**Comment by danikron** [comment]
This behaviour can also be reproduced in the following way:
1. Open a node (node 1) on an empty desktop (desktop 1).
2. Switch desktop (desktop 2).
3. Send a floating node (node 2) to desktop 1 (focus follows).
4. Switch focus to node 1.
5. Open a new node (node 3).
Node 3 will open to the opposite direction of node 1 as compared to just opening two nodes on an empty desktop (dependent on initial_polarity).
