### ISSUE TITLE
Segfault after clicking a monitor whose focused desktop just moved to another monitor

### ISSUE THREAD

**Issue by msteen** [baskerville/bspwm#720]
After updating my local git build of `bspwm` a few weeks ago, it has segfaulted a few times. I planned building it with debug mode to figure out what is going wrong, but it just happened again and I noticed the cause and I am now able to reproduce it consistently. If I move a desktop to another monitor it works fine, but if I click on the monitor from where the desktop was moved, it will cause `bspwm` to segfault. I would think this has to do with your fix for #691. It likely sets a invalid desktop on the monitor where the desktop was moved from, because if I first change the desktop for that monitor, then it will not segfault.

**Comment by baskerville** [comment]
Thanks.
