### ISSUE TITLE
Plugged in monitor displays only cursor

### ISSUE THREAD

**Issue by infernix** [baskerville/bspwm#723]
I'm using bspwm on a laptop with these relevant config settings:

```
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
```

When I plug in an external monitor on DP-1 I run:

```
xrandr --output DP-1 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output eDP-1 --mode 1920x1080 --pos 0x360 --rotate normal 
M=$(bspc query -M | wc -l)
bspc monitor $(bspc query -M | awk NR==2) -d I II III IV V VI
bspc monitor $(bspc query -M | awk NR==1) -d VII VIII IX X XI XII
```

The monitor is then detected:
```
bspc wm -d | jq '.monitors[] | {name, rectangle}'
{
  "name": "eDP-1",
  "rectangle": {
    "x": 0,
    "y": 360,
    "width": 1920,
    "height": 1080
  }
}
{
  "name": "DP-1",
  "rectangle": {
    "x": 1920,
    "y": 0,
    "width": 2560,
    "height": 1440
  }
}
```

And if I start a terminal on it and use xprop, I can see it detected. xprop on the root shows:
```
WM_NAME(STRING) = "DP-1"
WM_CLASS(STRING) = "root", "Bspwm"
```

However - nothing is displayed on the screen except the cursor. Not the tint2 bar, nor any window; not even the X root backdrop. It does seem fully functional given the xprop output when running a terminal on it.

I'm not sure how to go about debugging this further, any ideas?

**Comment by msteen** [comment]
Just some questions / ideas:

Did you also try a different window manager than `bspwm` on your laptop and did it work for that window manager? (Maybe there is a driver problem or some such)

Do you also experience the problem when the monitor is already plugged in when you start `bspwm`?

Can you move a floating window in the monitor?

**Comment by infernix** [comment]
> Did you also try a different window manager than bspwm on your laptop and did it work for that window manager? (Maybe there is a driver problem or some such)

Yes, no issue there.

> Do you also experience the problem when the monitor is already plugged in when you start bspwm?

No, if I restart xorg with monitors plugged in, it's all fine. This has been my workaround for the last few weeks :)

> Can you move a floating window in the monitor?

No, doesn't show up either.

**Comment by msteen** [comment]
What version of `bspwm` are you using? I will update mine to the latest git version (right now I am a few commits behind) and see if I can reproduce your problem.

**Comment by infernix** [comment]
I'm on 49caeb8ce8efdb0f4e82f52bc98b327b6049d776 here

**Comment by msteen** [comment]
I have been unable to reproduce it. You do see a red background if you run `xsetroot -solid '#FF0000'`, right? And does setting a sleep between your `xrandr ...` call and your first `bspc monitor ...` call help?

**Comment by infernix** [comment]
Sorry, this appeared to be compton at fault; killing it fixed the issue. Thanks for checking :)

**Comment by HuidaeCho** [comment]
> Sorry, this appeared to be compton at fault; killing it fixed the issue. Thanks for checking :)

Adding `--paint-on-overlay` worked for me.
```bash
compton --backend glx --paint-on-overlay&
```
