### ISSUE TITLE
Border=off rule not working

### ISSUE THREAD

**Issue by zacps** [baskerville/bspwm#724]
This is probably just me doing something wrong, but I can't figure out what.

bspwm version: 0.9.3
bspwmrc:
```
sxhkd &
bspc config border_width 1
bspc rule -a rofi border=off
```

Expected: The rofi window has no border
Result: The rofi window has the 1px border

**Comment by baskerville** [comment]
I guess that *rofi* isn't managed and therefore the rules aren't applied.

You could run `chwb -s 0 "$1"` from the external rules command…
