### ISSUE TITLE
Google Chrome Tabs cause Desktop to switch

### ISSUE THREAD

**Issue by Cynary** [baskerville/bspwm#735]
Trying to setup an automatically started desktop session. Got most of it working, except I have a web desktop which ends up always taking up focus because google chrome on startup automatically opens tabs from the previous session.

I confirmed that this is what causes focus to go to the google-chrome desktop. The steps to reproduce are:

1. Put a running google-chrome on a desktop
2. switch out of that desktop
3. run `google-chrome-stable 'about:blank'` (this specific page always opens in a new page)
4. You'll inadvertently get taken back to that desktop

I imagine chromium will have the same issue.

I want to be able to setup the environment in a way that the tabs don't get followed automatically. I tried adding a rule for Google-chrome for no following and while that works for new windows of chrome, it doesn't affect tabs. I also tried using external_rules_command but it didn't get triggered when a new tab was opened.

**Comment by baskerville** [comment]
Have you tried `bspc config ignore_ewmh_focus true`?

**Comment by Alkeryn** [comment]
@baskerville I believe the issue is that he set chrome to be opened on desktop x
so if he "split" chrome or open a new chrome windows, it opens it in the x windows
and auto focus it because he made it in the bspc rule

I think what he want is that when you open chrome it opens in x desktop
but after that if you open a new chrome windows it opens in the desktop you curently are

**Comment by Q3CPMA** [comment]
Hello,
I have the same problem with Firefox. I also tried `bspc config ignore_ewmh_focus true` to no avail.

**Comment by Cynary** [comment]
@Alkeryn that wasn't quite what I wanted. I think @baskerville interpreted it right.
Running `bspc config ignore_ewmh_focus true` fixed it for me :) Sorry for my delayed feedback!
