### ISSUE TITLE
Firefox doesnt resize on startup

### ISSUE THREAD

**Issue by xiamaz** [baskerville/bspwm#736]
I am not sure how to best word this problem, so it might have been asked before.

After a reboot the firefox window will remain the same size as before the last shutdown and does not resize to fit the current size. This is consistent for all layout changes, such as monocle, fullscreen etc.
Resizing the firefox window after startup fixes this issue.

This is relatively minor, although I wonder whether this behavior can be fixed somehow.

**Comment by msteen** [comment]
As far as I know this is not fixable from within the window manager. I have commented on this in another issue: https://github.com/baskerville/bspwm/issues/627#issuecomment-314431436

**Comment by alecive** [comment]
I agree with @msteen : it's a firefox issue rather than a window manager problem.
