### ISSUE TITLE
border_width ignored when window is moved to another monitor

### ISSUE THREAD

**Issue by madnight** [baskerville/bspwm#740]
I have:
```
bspc config -m DVI-1 border_width 3
bspc config -m DVI-0 border_width 0
```
Now if i spawn a window on DVI-0 it has a border width of 0. correct  
Now if i spawn a window on DVI-1 it has a border width of 3. correct  
Now if i spawn a window on DVI-1 and move it to DVI-0 it has a border width of 3 on DVI-0. wrong

**Comment by neeasade** [comment]
When acting on a desktop or monitor, setting `border_width` refers to node/window spawn config, not ongoing. When acting on a leaf node, border_width is set right away on targetted node. 

if you wanted something continuous, you could `bspc subscribe` for when nodes switch monitors and `bspc config border_width -n $node_id <mon_width>`, where `mon_width` varies by checking the new monitor.
