### ISSUE TITLE
[Question] About layout.

### ISSUE THREAD

**Issue by karambaq** [baskerville/bspwm#741]
It it possible, to move left bottom window to the right bottom corner(yellow field) and the left top window will fill all the left side? Sorry for my english.

![image](https://user-images.githubusercontent.com/14233969/32776565-05478f64-c944-11e7-8d47-cb5af49697ad.png)

**Comment by ttzhou** [comment]
Call`bspc node -p \~south` on right window; call `bspc node -n last.local.!automatic` on bottom left-window.

**Comment by karambaq** [comment]
@ttzhou 
![image](https://user-images.githubusercontent.com/14233969/33139551-ac9ff8e8-cfbe-11e7-9ed2-86a4f8ceeb54.png)

**Comment by ttzhou** [comment]
your shell is trying to interpret the '!' in its own language.

do `bspc node -n 'last.local.!automatic'`

**Comment by ttzhou** [comment]
@karambaq if resolved, can you close issue?

**Comment by karambaq** [comment]
@t
