### ISSUE TITLE
urgent_border_color not working?

### ISSUE THREAD

**Issue by tsukurimashou** [baskerville/bspwm#742]
From the changelog I noticed the option "urgent_border_color" being added but it doesn't seem to work.

I configured it this way on my bspwmrc:

bspc config urgent_border_color     "$grn"

But it does nothing, trying manually with bspc config urgent_border_color returns config: Unknown setting: 'urgent_border_color'

**Comment by neeasade** [comment]
It was removed in 0.9.1 -- listed under the changelog [here](https://github.com/baskerville/bspwm/blob/dacea30e21d57036b6f84f4409903318b47aa06a/doc/CHANGELOG.md#removals-1)
