### ISSUE TITLE
New floating JAVA windows get to the back

### ISSUE THREAD

**Issue by NicolasCARPi** [baskerville/bspwm#743]
Hello,

I have this script to have a particular desktop (3) where all windows are floating:

~~~bash
#!/bin/bash
FLOATING_DESKTOP_ID=$(bspc query -D -d '^3')

bspc subscribe node_manage | while read -a msg ; do
    desk_id=${msg[2]}
    wid=${msg[3]}
    [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
~~~

This is working fine BUT I have an issue with a Java app. The app is [Fiji](http://fiji.sc/). **All windows opened by this app will be to the background.** Forcing me to move them a bit to get them to front (just clicking it is not enough). The app itself will also be in the layer "below" upon start.

I tried `wmname LG3D`,  export _JAVA_AWT_WM_NONREPARENTING=1, adding a `-l above` to the above script. Without success.

**Do you see a way to work around this?** Even `bspc node "$wid" -l above` doesn't work on those window.

Here is what xprop is saying about it:

A dialog from the app:

~~~
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x26, 0x1e, 0x0, 0x0
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x4c, 0x0, 0xc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 0, 0
		program specified location: 0, 0
		program specified size: 400 by 400
		window gravity: NorthWest
_NET_WM_ICON(CARDINAL) = 	Icon (16 x 16):
-- icons removed --   


WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		window id # of group leader: 0x1c00007
WM_TRANSIENT_FOR(WINDOW): window id # 0x1c00007
WM_PROTOCOLS(ATOM): protocols  WM_TAKE_FOCUS, WM_DELETE_WINDOW
WM_CLASS(STRING) = "sun-awt-X11-XFileDialogPeer", "fiji-Main"
WM_CLIENT_LEADER(WINDOW): window id # 0x1c00008
_NET_WM_ICON_NAME(UTF8_STRING) = "Open Image Sequence..."
WM_ICON_NAME(STRING) = "Open Image Sequence..."
_NET_WM_NAME(UTF8_STRING) = "Open Image Sequence..."
WM_NAME(STRING) = "Open Image Sequence..."
~~~

An image opened with it:

~~~
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x1, 0x0, 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 24, 74
		program specified location: 24, 74
		program specified size: 1402 by 1056
		program specified maximum size: 1536 by 1178
		window gravity: NorthWest
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128):
-- logo removed --

WM_PROTOCOLS(ATOM): protocols  WM_TAKE_FOCUS, WM_DELETE_WINDOW
WM_CLASS(STRING) = "sun-awt-X11-XFramePeer", "fiji-Main"
WM_CLIENT_LEADER(WINDOW): window id # 0x1c00008
_NET_WM_ICON_NAME(UTF8_STRING) = "140304-0008_Position(2)_p000001t00000001z001c01.tif"
WM_ICON_NAME(STRING) = "140304-0008_Position(2)_p000001t00000001z001c01.tif"
_NET_WM_NAME(UTF8_STRING) = "140304-0008_Position(2)_p000001t00000001z001c01.tif"
WM_NAME(STRING) = "140304-0008_Position(2)_p000001t00000001z001c01.tif"
~~~

I'm not sure if this is a bug in bspwm or java being a pita…

bspwm version 0.9.3 on Archlinux.

Cheers,
~Nico

**Comment by baskerville** [comment]
Does `-l above` have any effect on an existing *Fiji* window?

**Comment by NicolasCARPi** [comment]
Hello,

No it doesn't. I'm using `bspc node 0x03200007 -l above`. Getting the node id from the script by adding `echo $wid` so I see the id of new windows. With or without the script launched (so in floating or not), the `-l above` command doesn't work on those windows.

**Comment by baskerville** [comment]
I'm assuming that the command returns without errors, otherwise it would mean that the *Fiji* windows aren't managed.

Have you tried the [Java hack script](https://github.com/sampowers/dotfiles/blob/master/bin/java_nonreparenting_wm_hack.sh)?

**Comment by NicolasCARPi** [comment]
The $? = 0. I've also realized that the command works for getting above normal window:

If I have from below to above:
- fiji window (java)
- terminal window (non java)
- another fiji window (java)

And I do a `-l above` on the first (below) java window, it'll get above the terminal but not above the other fiji window!

> Have you tried the Java hack script?
Yes, it doesn't help, the windows still appear at the back of each other.

Also, while trying to understand precisely the behavior, I have found that:

* if I don't touch/move the windows, the next window will be ON TOP (expected behavior). But if I moved the window, the next one to be opened will be below!

Steps to reproduce:

* download and install fiji (http://fiji.sc/#download)
* File > Open sample > Lena
* File > Open sample > any other image => it gets on top.
* Close all images (press w)
* File > Open sample > Lena
* move the image around a bit
* File > Open sample > any other image => it gets below!

**Comment by NicolasCARPi** [comment]
I'm closing this issue as I've switched back to another WM and won't be able to help/test furthermore. At least the issue is out and if users encounter similar problems, it will show up.

Cheers :)
