### ISSUE TITLE
Troubles with Clojure Incanter

### ISSUE THREAD

**Issue by KGOH** [baskerville/bspwm#746]
I can not decide is this [issue](https://github.com/incanter/incanter/issues/373) related to bspwm or Incanter library. Is it is bspwm problems, then this issue is copy of that issue

**Comment by baskerville** [comment]
Have you tried https://github.com/sampowers/dotfiles/blob/master/bin/java_nonreparenting_wm_hack.sh?

**Comment by KGOH** [comment]
@baskerville, problem solved! Thanks
