### ISSUE TITLE
`bspc query -N --names` returns window IDs instead of names

### ISSUE THREAD

**Issue by R3load** [baskerville/bspwm#748]
The output for `bspc query -N` is the same with and without the `--names` option.

`bspc query -N`:

	0x00600014
	0x00600016
	0x01000003
	0x00E00003
	0x00C00003
	0x0060001E
	0x014000BB
	0x02600008
	0x00600011
	0x01200007
	0x00800003
	0x02C00001
	0x00A00003
	0x0140000E
	0x03200003

`bspc query -N --names`:

	0x00600014
	0x00600016
	0x01000003
	0x00E00003
	0x00C00003
	0x0060001E
	0x014000BB
	0x02600008
	0x00600011
	0x01200007
	0x00800003
	0x02C00001
	0x00A00003
	0x0140000E
	0x03200003

Maybe I'm just confused and IDs *are* node names :) Or is this a bug?

**Comment by msteen** [comment]
This issue has already been fixed in the following commit: https://github.com/baskerville/bspwm/commit/01ad5c5c49098b093df5912a80b7015735b4d05e

So with the latest version of `bspwm` you would get:
```
console> bspc query -N --names
query -N: --names only applies to -M and -D.
```
