### ISSUE TITLE
Ignore focused window and follow preselection

### ISSUE THREAD

**Issue by Vintodrimmer** [baskerville/bspwm#749]
Good day,

Is there a possibility to make preselection ignore the currently active window?

For example, suppose I have 2 terminal emulators on the left side and one big window on the right. I'd like to launch the virtual machine from the upper-left terminal under the right window.

- I focus the right window and create preselection under it

-  I return to the terminal and launch the VM.

- Instead of spawning in the desired preselected area it spawns over the current terminal.

It would be ideal if bspwm would disregard the active window on the current desktop and strictly follow the preselection.

I might be doing something terribly wrong, though.

![select](https://raw.githubusercontent.com/Vintodrimmer/docs/master/1.png)
![launch](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2.png)

**Comment by neeasade** [comment]
You could create an external_rules script (a script for defining the entry point of new nodes) and in that script, check for preselections, and if there are any open on the current desktop, use that. I do that in mine here: [link](https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/interact/external_rules.sh#L30-L31)

**Comment by Vintodrimmer** [comment]
Thanks, that's just what I need.

**Comment by Vintodrimmer** [comment]
@neeasade Hello again, can you help me once more, please?

Is there any way to put an existing window into the preseletion? Say, it was floating and I make it tiled.

Or simply some way to emulate the herbstluftwm, where you can make a new frame and put any existing window there.

**Comment by neeasade** [comment]
> Is there any way to put an existing window into the preseletion? Say, it was floating and I make it tiled.

sure -- when I want to get more custom with my behavior, I outsource my sxhkd binding to a script, eg [link](https://github.com/neeasade/dotfiles/blob/88fc127f38031f112ce36bf8664fe7cae56c1f73/sxhkd/.config/sxhkd/sxhkdrc#L22-L23). So for example, say you have a keybinding for floating to tiled. You could have that call some `toggle.sh`, which queries for a presel node (`bspc query -N -d -n .\!automatic`) and then swaps your current focused floating node into that (`bspc node -n <presel node id>`). 

> Or simply some way to emulate the herbstluftwm, where you can make a new frame and put any existing window there.

You can do the same with receptacles (bspwm empty nodes) and replace them with a new window using external_rules or other.
