### ISSUE TITLE
no -m flag in xdo

### ISSUE THREAD

**Issue by derrickcope** [baskerville/bspwm#757]
in the /examples/panel/panel script line 21

    wid=$(xdo id -m -a "$PANEL_WM_NAME")

there is no -m flag for xdo

**Comment by baskerville** [comment]
The `-m` flag is in *xdo* 0.5.7.

**Comment by derrickcope** [comment]
thank you. I guess the package is out of date in Arch

**Comment by baskerville** [comment]
`xdo -v` gives you the version.
