### ISSUE TITLE
Make follow focused configurable

### ISSUE THREAD

**Issue by msteen** [baskerville/bspwm#758]
In issue #691 I proposed to make the default behavior to always follow the focused item, which I still believe to be the most intuitive default behavior, however it should be made easy to disable this behavior, since not wanting to follow focus is a common use case as well, and right now the only way to workaround this new default behavior is to do the following: `bspc node --flag hidden=on --to-desktop <desktop_sel> --flag hidden=off`, which users are likely not to come up with themselves or stumble upon it by reading one of these posts that mentions it. Instead of introducing different commands to choose between these behaviors, it would probably be better to introduce a new config option, just like `pointer_follows_focus`. That way users can set their preferred default behavior themselves, and can still change the behavior per use case, which is commonly done for `pointer_follows_focus` when swapping windows:
```
super + shift + {Left,Down,Up,Right}
  bspc config pointer_follows_focus true; \
  bspc node --swap {west,south,north,east}; \
  bspc config pointer_follows_focus false
```

**Comment by baskerville** [comment]
I think I'm going to have a `--follow` flag.

**Comment by msteen** [comment]
That could work as well, it would be consistent with what you have in the rule domain, but just like the current workaround, it would do nothing for e.g. `bspc desktop --to-monitor <monitor_sel>`. But then again I have not yet heard any complaints about following the focused desktop, so maybe that is less of a problem.

**Comment by oceans112** [comment]
I am on board with this. 
Thank you for your time guys.
