### ISSUE TITLE
Query desktop, monitor of window by window ID

### ISSUE THREAD

**Issue by lf-** [baskerville/bspwm#761]
I can't seem to find a simple way of getting desktop, and monitor IDs given a window/node ID (the one from xdo seems to be the node id as well). Digging through the source code, I found `locate_window(xcb_window_t win, coordinates_t *loc`, which seems like almost exactly what I want, but with further grepping, I couldn't seem to find anything exposing it through the bspc interface.

Am I missing something? Or is this a shortcoming of the tools available over the bspc interface? I also went digging through the output of `wm -d` and couldn't seem to find anything listing the nodes on each desktop or monitor.

**Comment by baskerville** [comment]
`bspc query -{M,D} -n <node_id>`
