### ISSUE TITLE
0.9.3 broke alt and super

### ISSUE THREAD

**Issue by fengshaun** [baskerville/bspwm#766]
Attempting to use 0.9.3, alt and super don't work anymore. sxhkd handles them properly with extra code in `parse.c`, but bspwm dosen't. mod1-5 don't do anything and seem to be ignored. `xev` correctly reports mod1 to correspond to Alt_L.

**Comment by neeasade** [comment]
Are you still using the pointer subdomain commands in your sxhkdrc? with 0.9.3 the pointer configuration changed. see https://github.com/baskerville/bspwm/issues/678

**Comment by fengshaun** [comment]
No. I'm using `bspc config pointer_modifier modN` with N = 1 to 5 which doesn't do anything.

**Comment by baskerville** [comment]
Are you launching `sxhkd` with `-m COUNT`?

**Comment by fengshaun** [comment]
Not using sxhkd right now. Just trying to get bspwm to work with alt key.

**Comment by baskerville** [comment]
> Not using sxhkd right now.

I'll rephrase the question: do you have a custom layout?

What's the output of `xmodmap`?

**Comment by fengshaun** [comment]
dvorak.

```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock      
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```
