### ISSUE TITLE
bspwm grabs some keyboard event when spawning a terminal

### ISSUE THREAD

**Issue by danr** [baskerville/bspwm#771]
Hi,

I use sxkhd to spawn urxvt, with `super +  c`. Sometimes (about 50% of the time) the terminal will not show the prompt until `super` is released. It is somehow related with bspwm because when running openbox + sxhkd (or xmonad) this never happens. 

Similarly, if I start `urxvt` from a running terminal the newly spawned will sometimes not show the prompt until a keydown event is sent to the terminal.

Is this a known problem? I have tried to search but found nothing, and I don't know any way of troubleshooting because I don't really know what programs intercept my events.

Thanks for help!

**Comment by danr** [comment]
Is there a timeout somewhere? I'm normally using `xset r rate 125 45`. Increasing  this to `xset r rate 250` seems to make the problem disappear.

**Comment by baskerville** [comment]
Have you tried `super + @c`?

**Comment by danr** [comment]
Apparently urxvt with `-depth 32` causes this if a composite manager is not running. If I either disable `URxvt.depth: 32` in my `.XResources` or run `xcompmgr`, the problem goes away. I don't know why this happens but apparently someone had the same problem in 2010: https://bbs.archlinux.org/viewtopic.php?id=11040

Closing as unrelated to bspwm/sxhkd.
