### ISSUE TITLE
Cannot move to next !occupied desktop

### ISSUE THREAD

**Issue by navdeepio** [baskerville/bspwm#772]
Issuing the command
`bspc desktop -f next.!occupied`

errors out with 

`-bash: !occupied: event not found`

Using bspwm 0.9.3(Arch)

**Comment by msteen** [comment]
Some characters used in the API have special meanings in shells, you should have used: `bspc desktop -f 'next.!occupied'`

**Comment by navdeepio** [comment]
I suspected this, and tried the command with
`bspc desktop -f "next.!occupied" but it failed for the same reason I guess. Using single quotes it works fine!
