### ISSUE TITLE
Moving node to selected location stopped working in new example sxhkdrc.

### ISSUE THREAD

**Issue by FrederikNS** [baskerville/bspwm#781]
Hi I just decided to switch to BSPWM yesterday.

I saw an old screencast where the user pre-selected a location and then picked a window to move there.

I couldn't seem to replicate that with the example sxhkd configuration, but I then discovered that a recent change seems to alter the behaviour.

Before https://github.com/baskerville/bspwm/commit/d0138af475541732d3f2ae25dff558c07062e24f it was indeed possible to do what I wanted. You preselect a split location, and then you focus the window you want to move and hit `super + y`. Your focused window moves to the preselected split location.

The command used to be

    bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused

but has been changed to:

    bspc node newest.marked.local -n newest.!automatic.local

The diff for the file reveals that a new command for marking a node has also been added (see the `sxhkdrc` file):

https://github.com/baskerville/bspwm/compare/baskerville:f83f...59a9

I have tried to mark nodes using the `super + ctrl + m` as well as using the preselection, but when I hit `super + y` nothing happens.

**Comment by baskerville** [comment]
What's the output of `bspwm -v`?

**Comment by FrederikNS** [comment]
I was running the newest master (commit: https://github.com/baskerville/bspwm/commit/59a9785786b3168dd2d979a0b87fa2faf4fefea1), I just switched back to 0.9.3, and updated my sxhkdrc from the old example. That made it work as I expected. It's probably safer for a newb like me to run stable :-P

**Comment by baskerville** [comment]
I was just checking if you were using the correct version.

One thing you could try (using the newest master) is to manually run `bspc node -g marked=on`, preselect another node and manually run `bspc node newest.marked.local -n newest.!automatic.local` (don't forget to escape `!`).

**Comment by jallbrit** [comment]
@FrederikNS are you still having this problem? The updated keybinding works for me.
