### ISSUE TITLE
bspc query -M --name not working well

### ISSUE THREAD

**Issue by struckoff** [baskerville/bspwm#783]
After update to 0.9.4 I got this behavior

```zsh
λ struckoff → ~ → bspc query --monitors --names      
MONITOR
MONITOR
```
when 
```zsh
λ struckoff → ~ → bspc query --monitors        
0x0020000A
0x00200007
```

**Comment by baskerville** [comment]
No, `--names` works fine.

My guess is that this message: `Couldn't retrieve monitors via RandR` is present in the outputs of `bspwm`, am I correct?

What's the output of `bspc wm -d | jq '.monitors[].rectangle'`?

**Comment by struckoff** [comment]
```json
{
  "x": 0,
  "y": 0,
  "width": 1920,
  "height": 1080
}
{
  "x": 0,
  "y": 0,
  "width": 1920,
  "height": 1080
}

```

**Comment by struckoff** [comment]
> My guess is that this message: Couldn't retrieve monitors via RandR is present in the outputs of bspwm, am I correct?

where should I see it if I run sessions with sddm ? Nothing similar in journalctl

**Comment by struckoff** [comment]
yep, got this message. But XRandr detect all correct. Here mine` xrandr --query`

https://gist.github.com/cb4d52cd0e69a04feda025a073596b92

**Comment by baskerville** [comment]
This must be related to 0785b39.

Maybe someone experiencing the same problem can inspect `update_monitors` and see why we end up with `mon == NULL` at the end of this function?

**Comment by struckoff** [comment]
if it helps
xcb_randr_get_screen_resources_reply - returns NULL, tryid code below
```C
#include <limits.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <xcb/xcb.h>
#include <xcb/randr.h>

int main(){
    xcb_connection_t *dpy = xcb_connect(0, 0);
    xcb_window_t root = xcb_generate_id(dpy);
    xcb_randr_get_screen_resources_cookie_t res = xcb_randr_get_screen_resources(dpy, root);
    xcb_randr_get_screen_resources_reply_t *sres = xcb_randr_get_screen_resources_reply(dpy, xcb_randr_get_screen_resources(dpy, root), NULL);
    if (&res == NULL){
        printf("cb_randr_get_screen_resources returns NULL\n");
    }else{
         printf("%d\n", res);
    }
    if (sres == NULL) {
         printf("xcb_randr_get_screen_resources_reply returns NULL\n");
	} else {
        printf("%d\n", sres);
    }
}
```

**Comment by ismboedev** [comment]
I have the same issue after the update. I found out, that this problem only appears, if the monitor is connected, while i start bspwm.

I have a xrandr command followed with `bspc monitor VGA1 -d 1 2 3` etc in my .bspwmrc. This does not work anymore and as struckoff said, it only detects `MONITOR MONITOR` with `bspc query -M --names`.
However, if i start bspwm and connect the monitor afterwards, it detects `VGA1` and `LVDS1` just fine and i can manually arrange my desktops on my two monitors.
