### ISSUE TITLE
Mouse resize behavior changed in 0.9.4 !?

### ISSUE THREAD

**Issue by bommel666** [baskerville/bspwm#784]
Before version 0.9.4, resizing windows with the mouse behave like this:
https://imgur.com/aBHUY4T

That was great!!!

Now, with version 0.9.4, it behaves like this:
https://imgur.com/LNJPfJH

The nearest window corner (or side when i use resize_side) now "jumps" to the mouse pointer and so the window shrinks to that position. This is very annoying (at least for me) because now you have to place the mouse very near to the corner/side to prevent this. 

(Yes, tiled windows also behave like that)

I use these mouse specific settings in my bspwmrc:

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus true

Is this a bug or the new desired behavior?

**Comment by baskerville** [comment]
This is a consequence of 0ba0ca3.

**Comment by HaoZeke** [comment]
How do we activate the relative option? @baskerville

Perhaps it should default to relative as that was the previous behavior..

**Comment by baskerville** [comment]
The constraint we have is that *relative* must be *false* if *honor_size_hints* is *true*.

**Comment by bommel666** [comment]
OK, i've checked honor_size_hints. For me, there is no difference if i set it to true or false (maybe i just don't see it). And i don't have the behavior shown here #752.
What can i do to get the old behavior back (besides downgrading to 0.9.3 of cause)?

**Comment by bommel666** [comment]
Thank's! :+1:
