### ISSUE TITLE
Balancing windows only vertically

### ISSUE THREAD

**Issue by Chrysostomus** [baskerville/bspwm#786]
I'm trying to write a script, which would constantly balance windows, but only vertically. Balancing @south and @north seems promising, but I'm having difficulty setting the starting point for the balancing act. Here is the current script:

```
#!/bin/dash

if [ "$(pgrep -cx euclid_balancer)" -gt 1 ] ; then 
	killall euclid_balancer && exit 0
else

bspc subscribe node_add node_remove node_state node_geometry | while read line; do
	for window in $(bspc query -N -n .window -d focused); do
		bspc node @north -B
	done
done

fi
```
The node path is obviously wrong and applies only to the focused node. I would want to apply the action to each window on the desktop, something like

```
for window in $(bspc query -N -n .window -d focused); do
		bspc node $window@north -B
	done
```

Can this be done? The manual should probably provide me with the answer, but I seem to be too dense to understand it.

**Comment by baskerville** [comment]
I'm not sure if it does what you want, but the last example can be written as:
```sh
for wid in $(bspc query -N -d -n .window); do
	bspc node "${wid}#@north" -B
done
```

**Comment by Chrysostomus** [comment]
Thanks! That does seem to be what I'm looking for
