### ISSUE TITLE
Multiple monitor problem after update

### ISSUE THREAD

**Issue by dawiss** [baskerville/bspwm#787]
Im using Manjaro bspwm, after last update i have problem with setting my monitors. 

```
bspc monitor DP1-2 -d v vi
monitor: Invalid descriptor found in 'DP1-2'.
```
my xrandr -q 

```
eDP1 connected primary (normal left inverted right x axis y axis)
1920x1080     60.05 +  59.93    48.04
DP1-1 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95*+
DP1-2 connected 1920x1200+1920+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1920x1200     59.95*+  59.95*

```
i can't put anyting on 2nd screen. eDP1 is disabled it's my notebook screen. 
currently im using:
community/bspwm-manjaro 0.9.4-11 [installed]

workspaces_multimonitor do not work too.

**Comment by c4tz** [comment]
Same Problem here (plain Arch Linux). I was able to downgrade back to 0.9.3, where `bspc monitor eDP1 -d 1 2 3` is working again.

**Comment by dawiss** [comment]
I downgraded to 0.9.4-8 and it's fine.

**Comment by ismboedev** [comment]
I have the same issue (Arch Linux). It has something to do with bspwm not detecting Monitors correctly   #783.
I have a workaround for now. If you connect the monitor after bspwm is started, everything works fine.
This works for me now, as i only use a second monitor at my office.
