### ISSUE TITLE
Newer versions of jetbrains IDEs draw all popups in center of screen?

### ISSUE THREAD

**Issue by zack6849** [baskerville/bspwm#789]
Hey there, i know similar issues have been addressed here before, notably #52 and #746, but the issue is now different for me

So, basically, as of the newest version of PHPStorm (2018.1), any sort of dropdowns and dialogs that should be directly under the button appear in the center of the screen, like this:
![2018-04-06-091928_1892x1052_scrot](https://user-images.githubusercontent.com/1343898/38423347-a0626436-397b-11e8-89d4-67367c282b91.png)

As you can see, if i open the file dialog, it shows up in the middle of the screen, which is... less than desireable

I've tried the following things:

- Set the WMNAME to LG3D
- Used the java fix script suggested in one of the other projects, included below
- Adding a rule to not manage the windows  (`bspc rule -a "sun-awt-X11-XFramePeer" manage=off`)

None of the above seemed to help.
Are you aware of this or do you have any ideas for how to fix it?

Thanks!

```
#!/bin/bash

# Fix X window manager name properties to work around java bugs with
# non-reparenting window managers.  This is a different solution from
# the wmname utility provided by suckless, as it is NetWM compatible,
# while wmname sets the value of _NET_SUPPORTING_WM_CHECK to root win.

IRONIC_WM_NAME="LG3D"
NET_WIN=$(xprop -root _NET_SUPPORTING_WM_CHECK | awk -F "# " '{print $2}')

if [[ "$NET_WIN" == 0x* ]]; then
    # xprop cannot reliably set UTF8_STRING, so we replace as string.
    # fortunately, jdk is OK with this, but wm-spec says use UTF8_STRING.
    xprop -id "$NET_WIN" -remove _NET_WM_NAME
    xprop -id "$NET_WIN" -f _NET_WM_NAME 8s -set _NET_WM_NAME "$IRONIC_WM_NAME"
else
    # even if we're not net compatible, do java workaround
    xprop -root -remove _NET_WM_NAME
    xprop -root -f _NET_WM_NAME 8s -set _NET_WM_NAME "$IRONIC_WM_NAME"
fi
```

**Comment by zack6849** [comment]
Edit: related issue in Jetbrains Issue Tracker: https://youtrack.jetbrains.com/issue/JRE-709

**Comment by zack6849** [comment]
It seems that removing the built-in JRE for phpstorm fixed the issue, for arch i just ran `aurman -R phpstorm-jre` and it fixed itself

**Comment by lans98** [comment]
> It seems that removing the built-in JRE for phpstorm fixed the issue, for arch i just ran
> aurman -R phpstorm-jre
> and it fixed itself

Indeed solution is to change the JRE that the IDE uses, by default it uses the bundled JRE, to change it follow this steps:


- Ctrl + Shift + A (Find Action) search for "Switch IDE Boot JDK"  
- Select your system JRE ubication, if not provide the path by the "..." button
- Restart your IDE

IntelliJ article: [Click me](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)

**Comment by Vrakfall** [comment]
Nevermind, I was to eager to tell about my problem as I tested it yesterday and still wasn't working today...
Actually, [this solution][1] from #841 solved my issue when switching the boot JDK had no effect at all. I'm leaving this here for other people that are still looking for fixing this problem.

[1]: https://github.com/baskerville/bspwm/issues/841#issuecomment-419708176
