### ISSUE TITLE
A hidden node affects new node layout

### ISSUE THREAD

**Issue by sudo-nice** [baskerville/bspwm#791]
Steps to reproduce:
1. Open a window.
2. Make it private.
3. Open another window.
4. Switch to the previous private window.
5. Open another window.

The windows layout will be the following:
![scheme1](https://i.imgur.com/lsvsir7.png)

But if we do:
1. Open a window.
2. Make it private.
3. Open another window.
4. Switch to the private window.
5. **Switch to another desktop and back.**
6. Open another window.

The windows layout will be:
![scheme2](https://i.imgur.com/Ojd7PB7.png)

---

I believe, I have not experienced that before upgrading to 0.9.4.
I use bspwm from debian repos:
Package: bspwm
Version: 0.9.4-1

**Comment by baskerville** [comment]
I can't reproduce.

**Comment by sudo-nice** [comment]
Looks like that was fixed in master, thanks.

**Comment by baskerville** [comment]
It looks like a5acc9a might be the cause of this regression.

**Comment by sudo-nice** [comment]
Thanks, I've reverted that commit and can't reproduce the bug anymore.
