### ISSUE TITLE
PCSX2 and Discord won't follow rule for desktop.

### ISSUE THREAD

**Issue by SokaN-D** [baskerville/bspwm#795]
I use:
`bspc rule -a PCSX2 desktop='^0'`
and it doesn't open in the designated desktop. 
I run xprop to check the windows' name and made sure the ones I used were the right ones. It was: WM_CLASS(STRING) = "PCSX2", "PCSX2"

Same thing with discord.

Any idea what's going on?

Thanks!

**Comment by baskerville** [comment]
The index notation starts at one, not zero.
