### ISSUE TITLE
Borderless monocle

### ISSUE THREAD

**Issue by vulgrim** [baskerville/bspwm#800]
`bspc config -d focused borderless_monocle <boolean>`  is global, not only limited for current desktop. 
BSPWM version 0.9.5, OS: Arch Linux

**Comment by jenniges** [comment]
This is also the case with `bspc config -m …` and also with the following settings:
* single_monocle
* gapless_monocle
* paddingless_monocle

**Comment by baskerville** [comment]
The `borderless_monocle` setting is in the *Global Settings* subsection of the *SETTINGS* section (cf. `man bspwm`).
