### ISSUE TITLE
No chaining of node selections after using PATH as REFERENCE# (resp. NODE#)

### ISSUE THREAD

**Issue by paul-dest** [baskerville/bspwm#804]
This command works fine and as expected:
`$ bspc node any.leaf#@II: -f`

But if the PATH selector is placed first:
```
$ bspc node @II:#any.leaf -f
node: Invalid descriptor found in '@II:#any.leaf'.
```

The same error if the PATH selector is reified to select a node, even a leaf node:
```
$ bspc node @II/1/1/1:#any.leaf -f
node: Invalid descriptor found in '@II/1/1/1:#any.leaf'.
```

That seems not to match to the spec in the man page:
```
           NODE_SEL := [NODE_SEL#](DIR|CYCLE_DIR|PATH|any|last|newest|
                                   older|newer|focused|pointed|
                                   biggest|<node_id>)[.[!]focused][.[!]automatic][.[!]local][.[!]active]
                                                     [.[!]leaf][.[!]window][.[!]STATE][.[!]FLAG][.[!]LAYER]
                                                     [.[!]same_class][.[!]descendant_of][.[!]ancestor_of]

```

What is the actual definition of NODE_SEL?
```
$ bspwm -v
0.9.4
```

**Comment by baskerville** [comment]
Note to myself: I remember why I wrote the original twisted version. `PATH` can contain a `DESKTOP_SEL`. And `DESKTOP_SEL` can contain a reference. Hence the last `#` character might not be the right one.

**Comment by baskerville** [comment]
As of db5b0cd, the interpretation of `NODE_SEL` should conform entirely with the specification.
