### ISSUE TITLE
firefox above everything

### ISSUE THREAD

**Issue by deadc0de6** [baskerville/bspwm#805]
Recently I noticed that when I start firefox (61.0b5) on a desktop, it won't allow any other window/node to be displayed next to it (be it in monocle or tiled mode). I can start other nodes (terminal or something) on the same desktop but they simply won't display as if firefox was in full screen mode. I'm however still able to get the focus on other windows (with `bspc node -f {next,prev}.local` or `bspc node -{f,s} {west,south,north,east}`) and send them to another desktop but on the same desktop as firefox they won't display anyhow.

I have nothing specific to firefox in my bspwm configs:
```
...
bspc config border_width            1
bspc config window_gap              10
bspc config top_padding             40
bspc config bottom_padding          25

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config click_to_focus          true
...
bspc monitor HDMI-0 -n L -d I II III IV V VI VII VIII IX X
```

My version 
```
bspwm -v  0.9.2
```

this happens on Debian stretch.

Thanks a lot for your help

**Comment by yrkv** [comment]
Try checking for any rules regarding firefox using:
bspc rule -l

It may be getting set somewhere else.

**Comment by deadc0de6** [comment]
it only happens on debian stretch with v0.9.2 as on arch linux, it works normally with version 0.9.5. I guess I just need to update on debian then ...
