### ISSUE TITLE
Visible window using monocle layout

### ISSUE THREAD

**Issue by sambazley** [baskerville/bspwm#807]
Is there any way to get the ID of the visible tiled window when using the monocle layout? I'm currently using `bspc query -N -n focused.tiled`, but this doesn't work when a floating window is focused.

**Comment by sambazley** [comment]
Currently using

```
nodes="$(bspc query -d $desktop -n .tiled -N)"
max=0
visible=0
for i in $nodes; do
    tmp=$(xprop -root | grep _NET_CLIENT_LIST_STACKING | grep -boi "$(echo ${i:2} | sed 's/^0*//')" | cut -d':' -f1)
    if [[ "$tmp" -gt "$max" ]]; then
        max=$tmp
        visible=$i
    fi
done
```

**Comment by baskerville** [comment]
This should work: `bspc query -N -n focused.tiled || bspc query -N -n last.tiled.local`.
