### ISSUE TITLE
Freeze caused by bspc in external rules script.

### ISSUE THREAD

**Issue by sambazley** [baskerville/bspwm#810]
bspwm can lock up if `bspc` is run from the external rules script. Since bspwm blocks until the script terminates, and `bspc` blocks until bspwm responds, the wm will freeze until bspc is killed.

Steps to reproduce:

1. Call bspc in the external rules script. I think a race condition is involved, since it seems like this can be reproduced more consistently if `bspc` is called after a delay (eg `sleep x`, or at the end of the script)
```
sleep 0.5
node=$(bspc query -N -n ".leaf.!window.local" | head -n1)
echo "node=$node"
```

2. Create a new window.

The blocking is caused by rule.c:331 and bspc.c:88.

**Comment by baskerville** [comment]
I can't reproduce.

You can easily create a lock up though, by calling `bspc` after having echoed a rule consequence.

**Comment by sambazley** [comment]
Oh, yeah, you're right, that's what's causing it. Moving the bspc call to the start of the file seems to have fixed it.
