### ISSUE TITLE
Feature: Tabs for monocle mode

### ISSUE THREAD

**Issue by pkillnine** [baskerville/bspwm#813]
It would be nice to see how many windows there are while displaying windows in the monocle mode, tabs would be one way to visualise this.

**Comment by neeasade** [comment]
Currently you can query the active node vs tiled nodes, and use that to build a tab display with lemonbar or some other software, I think is the intent. Here is an old screenshot showing a possiblity there (left monitor): http://i.imgur.com/df7WjjL.png

**Comment by pkillnine** [comment]
Thanks @neeasade , that will provide what i need
