### ISSUE TITLE
focusing a monitor changes visible desktop

### ISSUE THREAD

**Issue by jenniges** [baskerville/bspwm#819]
### General Information
- Bspwm version: 229b6fd878b33d3759196c2653378d7b3f9a45dd

### Problem description
I reported a similar issue a while back in #773, now it looks like I have found an additional case, where `bspc monitor -f …` focuses an unfocused desktop:

When sending a node to an unfocused desktop of an unfocused monitor. Focusing the monitor where the node was sent to, the desktop with the node gets focused. Expected is, that the monitor gets focused without changing the desktop of that monitor.

### Minimal config
```
xrandr --output A --auto
xrandr --output B --auto

bspc monitor A -d 1 2
bspc monitor B -d 3 4
```

### Reproduction steps
1. Open a window on desktop 1
2. `bspc node -to-desktop 4`
3. `bspc monitor -focus next` It doesn't matter how monitor is passed. (next, prev, B, …)

```
          original log                       human readable
                                             monitor A     monitor B
Before 1: WMA:F1:f2:LT:TT:G:mB:F3:f4:LT      M  F1 f2      m  F3 f4
After 1:  WMA:O1:f2:LT:TT:G:mB:F3:f4:LT      M  O1 f2      m  F3 f4
After 2:  WMA:F1:f2:LT:TT:G:mB:F3:o4:LT      M  F1 f2      m  F3 o4
After 3:  WmA:F1:f2:LT:TT:G:MB:f3:O4:LT      m  F1 f2      M  f3 O4
Expected: WmA:O1:f2:LT:TT:G:MB:F3:F4:LT      m  O1 f2      M  F3 o4
```
After 3, monitor B is focused and desktop 4, but expected desktop 3.

**Comment by baskerville** [comment]
Thanks for the report.

**Comment by jenniges** [comment]
Thank you for the quick fix. It works, but not right after the start of bspwm.
At some point, which I can't determine, it starts working.
Don't know if that matters, but I run bspwm through `startx` without a display manager.

Unfortunately bug №2 of #773 is happening again, and it creates a new one:

### General Information

- First affected bspwm version: 4e32d3b892acfbfc8bcb520e0c472bcd49067b44
- Latest working bspwm version: 229b6fd878b33d3759196c2653378d7b3f9a45dd


### Problem description

After swapping the focused, occupied destkop of the focused monitor (_A_), with the focused desktop of an unfocused monitor, `bspc monitor -f B` activates an occupied¹ desktop of monitor B.
It only happens when the desktop of monitor _A_ is occupied. While it doesn't matter if the desktop of monitor _B_ is free or occupied.

¹ It looks like that, the falsely activated desktop, is the last one beeing active before the current. In an environment with more than 2 desktops per monitor, I can manipulate and foresee which desktop will falsely be focused.


### Reproduction steps

_Config as above_

1. Open a window on focused desktop (1)
2. `bspc desktop -f 2`
3. `bspc monitor -f B`
4. Open a window on focused desktop (3)
5. `bspc desktop -s 2`
6. `bspc monitor -f A`

```
          original² log           human readable
                                  monitor A     monitor B
Before 1: WMA:F1:f2:mB:F3:f4      M  F1 f2      m  F3 f4
After 1:  WMA:o1:F2:mB:F3:f4      M  o1 F2      m  F3 f4
After 2:  WMA:o1:F2:mB:F3:f4      M  o1 F2      m  F3 f4
After 3:  WmA:o1:F2:MB:F3:f4      m  o1 F2      M  F3 f4
After 4:  WmA:o1:F2:MB:O3:f4      m  o1 F2      M  O3 f4
After 5:  WmA:o1:O3:MB:F2:f4      m  o1 O3      M  F2 f4
After 6:  WMA:O1:o3:mB:F2:f4      M  O1 o3      m  F2 f4
Expected: WMA:o1:O3:mB:F2:f4      M  o1 O3      m  F2 f4
```
² **Note:** I removed `LT:TT:G` from the original log, if it was present.

Step 6 focuses the correct monitor, but also changes the desktop.
