### ISSUE TITLE
single_monocle option cannot be toggled for a specific desktop

### ISSUE THREAD

**Issue by expectocode** [baskerville/bspwm#820]
Running `bspc config single_monocle on` to set this on globally, then `bspc config -d II single_monocle off` actually turns the option off globally, not just for desktop II. Changing another config option (I tried border_width) works as expected for a specific desktop.

I am on Fedora 28, running bspwm from GitHub at commit 4e32d3b892acfbfc8bcb520e0c472bcd49067b44 (latest).

**Comment by expectocode** [comment]
Looking into the code, I see that single_monocle belongs to a different class of config values that are always global, so my issue becomes more of a "please support my workflow".

My reason for wanting this feature is I sometimes have only one window open, and want the rest of the screen to be taken up by a receptacle, which doesn't count as a window to single_monocle, so for this one desktop I want single_monocle off so I can have this one window and some free space.

In general, if single_monocle is on, and a receptacle is added to a desktop with one window, there is no apparent change. This is quite strange behaviour.

**Comment by baskerville** [comment]
> In general, if single_monocle is on, and a receptacle is added to a desktop with one window, there is no apparent change.

This is fixed by 4be63b6.
