### ISSUE TITLE
Fullscreen sxiv with external rules

### ISSUE THREAD

**Issue by q3cpma** [baskerville/bspwm#822]
Hello,

I have some trouble mixing fullscreen sxiv and external rules. When using `sxiv -f` (starts in fullscreen), it gets fullscreened if I don't use external rules, but doesn't otherwise (I can still press `f` two times to put it in fullscreen). Something about EWMH not being handled before external rules or something?

Here's my config
```
#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            1
bspc config window_gap              10
bspc config top_padding 15
bspc config left_padding 0
bspc config bottom_padding 0
bspc config right_padding 0

bspc config click_to_focus          any
bspc config honor_size_hints        true
bspc config ignore_ewmh_focus       true

bspc config normal_border_color     "#aaaaaa"
bspc config active_border_color     "#aaaaaa"
bspc config focused_border_color    "#5555ff"

bspc config single_monocle          false
bspc config external_rules_command  ~/.config/bspwm/external_rules.sh

bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action3         resize_corner

bspc rule -a newsboat               desktop=^10
bspc rule -a neomutt                desktop=^10
bspc rule -a Gimp                   state=floating
bspc rule -a mpv                    state=floating
bspc rule -a Pinentry               state=floating
bspc rule -a retroarch              state=floating
bspc rule -a crawl:crawl            state=tiled
bspc rule -a floating               state=floating
bspc rule -a *:floating             state=floating

~/.config/lemonbar/bar.sh &
```

my external rules
```
#!/bin/sh

fwid=$(bspc query -N -n focused.automatic)

echo "$@" >~/log
xwininfo -id "$1" >>~/log
xprop -id "$1" >>~/log

if [ "$fwid" ]
then
    xwininfo -id "$fwid" | awk -F'[: ]+' '
    /(Width|Height): / {val[$2] = $3}
    END {print val["Width"], val["Height"]}' | \
        {
            read width height
            if [ $width -gt $height ]
            then
                out="split_dir=east"
            else
                out="split_dir=south"
            fi
            out="$out focus=on"
            # Keep fullscreen
            # [ "$(xprop -id "$1" _NET_WM_STATE)" = "_NET_WM_STATE_FULLSCREEN" ] &&
            #   out="$out state=fullscreen"
            echo "$out"
        }
fi
```

`sxiv myfile.png` and `sxiv -f myfile.png` give the exact same traces, so I can't do anything about it. Sxiv does fullscreen with https://github.com/muennich/sxiv/blob/master/window.c#L310, if this can help.

**Comment by baskerville** [comment]
My guess is that the fullscreen request is received while the external rule is still being processed  and hence discarded since the related window isn't managed yet.

One possible approach to solve this problem would be to queue the X events received for windows associated with a pending rule.

**Comment by q3cpma** [comment]
On Sun, Jul 22, 2018 at 02:17:50AM -0700, Bastien Dejean wrote:
> My guess is that the fullscreen request is received while the external rule is still being processed  and hence discarded since the related window isn't managed yet.
>
> One possible approach to solve this problem would be to queue the X events received for windows associated with a pending rule.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/baskerville/bspwm/issues/822#issuecomment-406852307

I see, that's what I feared.
