### ISSUE TITLE
Can't query receptacles off of node path

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#830]
to reproduce:

```
bspc node -p east
bspc node -i
bspc query -N -n '@parent.leaf.!window'
```

observe no output, while you can see the receptacle in `bspc query -N -n '.leaf.!window'`

**Comment by baskerville** [comment]
The descriptor in `@parent.leaf.!window` is `@parent`, hence it won't match the given modifiers, since `@parent` cannot be a leaf, by definition.

What you want is the list of nodes that match the given modifiers and are descendants of `@parent`:

```sh
bspc query -N '@parent' -n '.descendant_of.leaf.!window'
```

**Comment by neeasade** [comment]
Ah yepp, been a bit! Thanks!
