### ISSUE TITLE
[feature request] smooth motion

### ISSUE THREAD

**Issue by Brett99** [baskerville/bspwm#831]
I think it would look nice if window changes could be animated. For example, when swapping two windows, they could move to each others places, instead of just jumping right over. 

Also, a fading/scaling animation would be nice when full-screening windows, because some of my applications stutter when resized so suddenly. 

Is any of this possible through a compositor? (I already have resizing on workspace switching and new windows with compton)

If this shouldn't be a part of bspwm, what should I look into to implement it myself?

**Comment by Brett99** [comment]
Also, is it possible to make it so that mirroring my desktop uses the compton fade animation? This would help to mask the stuttering of some applications.

**Comment by Matrix89** [comment]
There's [this](https://github.com/BlackCapCoder/compton) compton fork but I don't think it's maintained

**Comment by Brett99** [comment]
Thanks. I guess this isn't a bspwm-related issue if it can be handled by compton.

The compton fork is cool, but seems to perform very poorly. Maybe I'll try making my own.

**Comment by vahnrr** [comment]
A **hacky** way to implement this without relying on picom, would be this sxhkd hotkey:

``` sh
super + ctrl + m : {_,shift + }{h,j,k,l}
        amount={1,2}; \
        for i in \{1..10\}; do \
            bspc node --move {-$amount 0,0 $amount, 0 -$amount,$amount 0}; \
            sleep 0.01; \
        done
```
