### ISSUE TITLE
Sticky Tile/Virtual Monitors

### ISSUE THREAD

**Issue by Stebalien** [baskerville/bspwm#85]
First off, these are more way out there proposals than immediate feature requests.

----

It would be kind of nice to have a "sticky" top level leaf. That is, a frame with a fixed location and size that contains all sticky windows. This would be extremely useful for chat windows etc.

Switching desktops:
![switch_desktops](https://f.cloud.github.com/assets/310393/1461353/2b938e7c-44a8-11e3-9830-7bbcc338ae47.png)

Resizing (no change but preserved across desktops):
![resize](https://f.cloud.github.com/assets/310393/1461352/2b92c5a0-44a8-11e3-8493-03e237b59194.png)

Move within frame:
![move](https://f.cloud.github.com/assets/310393/1461374/7952305e-44a9-11e3-9a48-6ce77ceb215d.png)

Move out of frame (unsticky):
![unsticky](https://f.cloud.github.com/assets/310393/1461375/815138cc-44a9-11e3-9b0b-00109cf6e4be.png)

Initialize frame:
![sticky](https://f.cloud.github.com/assets/310393/1461379/9d9ec5e4-44a9-11e3-95c8-72260ec39ff2.png)

The actual location of the sticky frame would probably have to be defined through a monitor specific setting.

---

Another possible (more general but more complex solution) is a "virtual monitor" system. That is, a monitor could be broken up into any number of virtual monitors in a tree structure. These virtual monitors would all contain their own sets of virtual desktops. However, this is probably unnecessarily complicated.

**Comment by blendi-93** [comment]
u could use the current git version:

`bspc wm -a <name> WxH+X+Y` adds a new monitor.

so on a 1920x1080 real monitor u could add 2 virtual monitors 1600x1080+0+0 and 320x1080+1600+0.

**Comment by neeasade** [comment]
@blendi-93 my impression was the goal of this was something like what @windelicato mentioned, a maybe generic way to group/frame nodes together and treat them as a singular node

**Comment by baskerville** [comment]
As of eb07d2f, non-leaf nodes can be flagged as sticky…

But @blendi-93's suggestion probably better fulfills the original intent.

**Comment by Stebalien** [comment]
Thanks!

**Comment by dieggsy** [comment]
@Stebalien how exactly are you achieving the original desired effect? i'm having trouble following...

**Comment by Stebalien** [comment]
Unfortunately, I've become enlightened in the church of Emacs and am now an EXWM user. I can't remember how I got this working.
