### ISSUE TITLE
[feature] padding_monocle mode for ultra-wide screens

### ISSUE THREAD

**Issue by alecive** [baskerville/bspwm#855]
As @holytrousers suggested [here](https://github.com/baskerville/bspwm/issues/729) it would be nice to have a padding_monocle mode to customize the amount of padding in the monocle mode (default would be 0 ie no padding).

The reason for having this mode is that, in ultra-wide screens, it is really annoying to have a single window span the entire workspace, especially with browsers (see [here](https://github.com/baskerville/bspwm/issues/729) for reference).

Just to give you an idea, here's my current browser window while writing this issue:

![image](https://user-images.githubusercontent.com/4378663/46217049-23a07480-c2fe-11e8-8047-4b167f33d113.png)

There's so much white that I'm getting blind! I know it's a first world problem, but I think that it would be nice to have anyway. Thanks!

**Comment by alecive** [comment]
Thanks @baskerville !!

**Comment by expectocode** [comment]
cool feature, minor annoyance: it's a global setting. I have one wide monitor and one narrow monitor, so it would be rather more useful to me as a monitor setting. Could it be changed to that?
