### ISSUE TITLE
visible polybar on fullscreen

### ISSUE THREAD

**Issue by bazeeel** [baskerville/bspwm#857]
I  see polybar on fullscreen youtube,vlc,mpv videos.
How can i solved this  ?

**Comment by phisch** [comment]
check this section for `wm-restack` [Configuration#bar-settings](https://github.com/jaagr/polybar/wiki/Configuration#bar-settings)

**Comment by bazeeel** [comment]
I tested but not working 100% i reaload polybar with keybinding and its visible again :(

**Comment by phisch** [comment]
The wm-restack feature implemented in polybar works fine for me. On the other hand, this is **not a bspwm issue**, you should then open a ticket regarding misbehaving `wm-restack` in the polybar repository. <- although i think it works as expected

**Comment by bazeeel** [comment]
Ok.Thank you
