### ISSUE TITLE
Precise window picking mechanism

### ISSUE THREAD

**Issue by sudo-nice** [baskerville/bspwm#858]
*This is a feature request*
The idea is quite straightforward, just look:

![image](https://raw.githubusercontent.com/t9md/t9md/1675510eaa1b789aeffbc49c1ae3b1e8e7dceabe/img/vim-choosewin.gif)

**Comment by neeasade** [comment]
Not exactly the same, but you might be interested in this script in the meantime (dmenu search window title): https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/interact/dmenu_windows

**Comment by sudo-nice** [comment]
Thank you, @neeasade, I know about this kind of window selectors (`rofi -show window`, e.g.), and it could be a help if the windows are heterogeneous. But to have a visual control might be more apparent sometimes, e.g. if there are several terminal windows opened with the same class, instance and title.
No doubt, the solution you proposed would be more helpful sometimes (a lot of overlapping floating windows).

**Comment by ikn** [comment]
http://ikn.org.uk/xorg-choose-window

I put this together a while back; it's pretty rough and simple, especially WRT the text rendering, but it works for me.  Can share my relevant sxhkd config if you're interested (as well as just switching window focus, I use it for swapping with and transplanting into specific windows).

**Comment by sudo-nice** [comment]
@ikn, thanks a lot, works just fine for me! If it was possible to change the fontname and fontsize, it would be perfect! :star2: 
>Can share my relevant sxhkd config if you're interested

Yes, please!

**Comment by ikn** [comment]
Don't keep your hopes up, I'm super lazy...

sxhkdrc:

https://github.com/ikn/config-stuff/blob/master/.config/sxhkd/sxhkdrc-bspwm

(search for xorg-choose-window), which refers to scripts in:

https://github.com/ikn/config-stuff/tree/master/.local/share/bspwm

**Comment by sudo-nice** [comment]
@ikn OK, thanks!
