### ISSUE TITLE
bspwm exits when running autorandr -c immediately after monitor change.

### ISSUE THREAD

**Issue by Jackojc** [baskerville/bspwm#865]
As the title suggests, I have a script I run when a monitor change is detected.

When I disconnect a monitor and run `autorandr -c`, bspwm exits and I'm kicked back out to the tty.

I'm pretty sure it has something to do with the following config options:
```
bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
```

If you need any more information, I can provide it.

**Comment by Jackojc** [comment]
I've been able to get it to reproduce itself if I'm running it for about 6 hours with firefox, sublime text, discord and a few terminals open.

When it kicks me out of X, it says "cannot open display :7" so I'm not sure if bspwm is actually crashing.

**Comment by Jackojc** [comment]
bspwm might be working as expected it seems. I think what ends up happening is that autorandr disables my other monitors before enabling the one I wish to switch to so bspwm ends up exiting because all of the displays have been disabled or disconnected. Not sure if there's any way around this problem.

**Comment by mcolligan** [comment]
I've also been getting this. I uninstalled autorandr but get the same problem even when using manual xrandr commands, even when switching on the new monitors and then turning off the previous one after a delay. The commands I used:

    xrandr --output DP-1 --auto --output DP-2 --auto --right-of DP-1
    sleep 0.1
    xrandr --output eDP-1 --off 
    sleep 0.1

Is this the backtrace that is useful? I can find other log info if needed. I wasn't sure what might be useful. It's from systemctl.

    Process 11393 (bspwm) of user 1000 dumped core.
                                                     
    Stack trace of thread 11393:
    #0  0x000056192f81d099 n/a (bspwm)
    #1  0x000056192f81844b n/a (bspwm)
    #2  0x000056192f8169ea n/a (bspwm)
    #3  0x000056192f817b22 n/a (bspwm)
    #4  0x000056192f814ac9 n/a (bspwm)
    #5  0x00007f2f9c9f5223 __libc_start_main (libc.so.6)
    #6  0x000056192f814dfa n/a (bspwm)

I replicated it a few times but couldn't find any pattern, other than 4-5 windows running (firefox, thunderbird, a few terminals).

**Comment by Jackojc** [comment]
Yeah it only seems to happen when I have a few windows open after running for a while.

**Comment by baskerville** [comment]
@mcolligan The backtrace will only be useful if *bspwm* was built with `make debug`.

**Comment by mcolligan** [comment]
I'll do that and try to replicate the issue.

**Comment by mcolligan** [comment]
This is the trace:

    Process 1946 (bspwm) of user 1000 dumped core.
    
    Stack trace of thread 1946:
    #0  0x0000556eacee50b4 focus_node (bspwm)
    #1  0x0000556eacee2bb2 transfer_desktop (bspwm)
    #2  0x0000556eacee1729 merge_monitors (bspwm)
    #3  0x0000556eacee238c update_monitors (bspwm)
    #4  0x0000556eaceeadc0 handle_event (bspwm)
    #5  0x0000556eacede40c main (bspwm)
    #6  0x00007ff6662db223 __libc_start_main (libc.so.6)
    #7  0x0000556eaceddaee _start (bspwm)

The problem does seem to go away with

    bspc config remove_unplugged_monitors	false
    bspc config remove_disabled_monitors	false

but it is difficult to be sure as it was flaky.

**Comment by Jackojc** [comment]
What happens with different combinations of the two flags?

**Comment by mcolligan** [comment]
It has happened a few times again but with both set to false. It's possible that my sequence of actions to switch monitors is not right, and once corrected there would be no problems. I've been racking my brain over the order of commands I should run when moving from my single laptop monitor (eDP-1) to two externals (DP-1 and DP-2, without eDP-1).

My latest attempt is the following, where I add the monitors to bspwm, transfer desktops to them, then activate them with xrandr.

    bspc wm -a DP-1 1920x1080+1920+0
    bspc wm -a DP-2 1920x1080+3840+0

    bspc desktop 1 --to-monitor DP-1
    bspc desktop 2 --to-monitor DP-1
    bspc desktop 3 --to-monitor DP-1
    bspc desktop 4 --to-monitor DP-2
    bspc desktop 5 --to-monitor DP-2
    bspc desktop 6 --to-monitor DP-2

    xrandr --output DP-1 --auto --right-of eDP-1 --output DP-2 --auto --right-of DP-1

    bspc monitor eDP-1 -r
    xrandr --output eDP-1 --off

Have I veered completely off in the wrong direction in this logic? Any advice is much appreciated.

**Comment by Jackojc** [comment]
I might aswell add that my monitor setup is pretty much the exact same, laptop monitor off, two external monitors on.

**Comment by baskerville** [comment]
`transfer_desktop` currently crashes if the transferred desktop contains a sticky node. I'm working on fixing all the bugs related to the handling of sticky nodes in corner cases.

**Comment by Jackojc** [comment]
Hmm, that could be it alright. I use a sticky terminal all the time.

**Comment by Jackojc** [comment]
Well what do you know @baskerville , not using any sticky windows fixes the problem. Is there another issue we can reference for this?

Does it work for you @mcolligan ?

**Comment by mcolligan** [comment]
That was it! Looks like it was a sticky terminal that was causing the trouble, the flakiness coming from whether or not it had been generated yet. Also, 

    bspc config remove_unplugged_monitors	true
    bspc config remove_disabled_monitors	true

do not seem to be problematic. I'm happy to consider this solved.

**Comment by Jackojc** [comment]
Guess not then...

**Comment by mcolligan** [comment]
I think that last commit did resolve it

**Comment by Jackojc** [comment]
Ah, I see.
