### ISSUE TITLE
Problem in Stacking Docks

### ISSUE THREAD

**Issue by simeir** [baskerville/bspwm#867]
Hello,

I am trying to create some widgets that are always above all windows using bar applications like polybar or lemonbar. To make them leave the edges of the screen and overlap with the other windows, I used the override-redirect option for polybar and -d option for lemonbar. When I was running them with these settings from the urxvt window, everything worked as I wanted. However, once I move the commands for the bar applications into bspwmrc, the bars are put into the lowest level of the window stack. All windows except for the root window are above the bars.

This can be tested by adding things like

`lemonbar -d -g200x200+20+20 -B#FF0000 &`

or

`polybar example &`

to bspwmrc. In the polybar case, in the settings file there must be a line

`override-redirect=true`

under

`[bar/example]`

I saw from EWMH's website that bars (docks) are generally always above other windows, and in i3 this does happen: even after I added the bars as startup applications into the config file, the bars still appeared above all windows. The author of polybar even added an option to put the bars below other windows on i3... Therefore, I think this is either a part of EWMH that is not in the subset bspwm supports, or a bug. If this is the former case, I want to make a feature request for this. 

Thanks!

**Comment by msteen** [comment]
I think it should be achievable by [using external rules](https://github.com/baskerville/bspwm/issues/857#issuecomment-427670436). You might want to use `xdo raise $wid` instead of that `xdo above ...` rule, otherwise it will be below full screen windows, which you likely do not want for popup style lemonbars.

**Comment by simeir** [comment]
> I think it should be achievable by [using external rules](https://github.com/baskerville/bspwm/issues/857#issuecomment-427670436). You might want to use `xdo raise $wid` instead of that `xdo above ...` rule, otherwise it will be below full screen windows, which you likely do not want for popup style lemonbars.

The external rules did solve my problem. Thank you very much!
