### ISSUE TITLE
Issue with positioning fullscreen overlay window

### ISSUE THREAD

**Issue by alekseyt** [baskerville/bspwm#868]
This is a question. I'm trying to run this application on bspwm:

![2018-11-03-222440_1024x768_scrot](https://user-images.githubusercontent.com/993454/47957050-d7f58080-dfb7-11e8-9c8c-7675bf17c17c.png)

Ideally vertical "dock" on the right would appear on the left where space was reserved for it, but for some reason bspwm is tiling this window and i can't understand why. 

This is fullscreen overlay with Xshape enabled and also ideally it would be positioned at 0,0 in that particular situation.

This is properties set on this window (also appear on screenshot):

```
_NET_WM_STRUT_PARTIAL(CARDINAL) = 65, 0, 0, 0, 0, 768, 0, 0, 0, 0, 0, 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
WM_CLASS(STRING) = "chromatic", "Chromatic"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_NAME(UTF8_STRING) = "Chromatic"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
_NET_WM_DESKTOP(CARDINAL) = 4294967295
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_ICON_NAME(STRING) = "Chromatic"
WM_NAME(STRING) = "Chromatic"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
```

`_NET_WM_WINDOW_TYPE` is set to `_NET_WM_WINDOW_TYPE_DOCK`, other props that worked in other WMs are set too (e.g. `_MOTIF_WM_HINTS`). I know that plank works fine and not being tiled, so i compared this to properties set on plank window:

```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 64
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 1023
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
		window id # of group leader: 0xa00001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
_GTK_MENUBAR_OBJECT_PATH(UTF8_STRING) = "/org/valapanel/appmenu/gtk/window/0"
_UNITY_OBJECT_PATH(UTF8_STRING) = "/org/valapanel/appmenu/gtk/window/0"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 10485782, 10485783
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0xa00015
WM_CLIENT_LEADER(WINDOW): window id # 0xa00001
_NET_WM_PID(CARDINAL) = 19106
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "localhost.localdomain"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 1024 by 64
		program specified maximum size: 1024 by 64
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "plank", "Plank"
WM_ICON_NAME(STRING) = "plank"
_NET_WM_ICON_NAME(UTF8_STRING) = "plank"
WM_NAME(STRING) = "plank"
_NET_WM_NAME(UTF8_STRING) = "plank"
```

Alas i can not spot the reason why plank is not being tiled, but this application is. I tried to set different properties differently, but without success.

Could you give me an idea of what can be wrong with this setup? Maybe i'm not setting required properties, or setting them wrongly or at the wrong time? What can i try to debug this? Any suggestions will be appreciated. 

I'm using bspwm 0.9.5. Thanks in advance.

**Comment by baskerville** [comment]
This could happen if the client sets `_NET_WM_WINDOW_TYPE` *after* being mapped.

You can check that in the external rules command.

**Comment by alekseyt** [comment]
You are right, window is mapped before `_NET_WM_WINDOW_TYPE` is set. I guess because GLX context has to be bound to already mapped window, there is explicit wait for that. I've also looked into external rules and after some tweaking this worked too even if window type is unset when window is mapped. This also helped me to better understand how i can approach such problems.

Thank you very much for you help and for bspwm, much appreciated.

![2018-11-04-133609_1024x768_scrot](https://user-images.githubusercontent.com/993454/47964230-534e4500-e03f-11e8-9e03-4eba05e83373.png)
