### ISSUE TITLE
2 problems with the layout after closing windows

### ISSUE THREAD

**Issue by zjeffer** [baskerville/bspwm#872]
Say I have the following layout X: 

```
 +-----------------------+  +-----------------------+ +-----------------------+
 |           |           |  |                       | |           |           |
 |     1     |     2     |  |           1           | |           |           |
 |           |           |  |                       | |           |           |
 |-----------|-----------|  |-----------------------| |     1     |     3     |
 |           |           |  |                       | |           |           |
 |     3     |     4     |  |           3           | |           |           |
 |           |           |  |                       | |           |           |
 +-----------------------+  +-----------------------+ +-----------------------+  

             X                          Y                         Z
```

If I close windows 2 and 4, I get layout Y. The problem is that I'd like to get layout Z instead. 

Now say I have the following layout X:

```
 +-----------------------+  +-----------------------+  +-----------------------+
 |           |           |  |           |     |     |  |           |           |
 |           |     2     |  |           |     |     |  |           |     3     |    
 |           |           |  |           |     |     |  |           |           |     
 |     1     |-----------|  |     1     |  3  |  4  |  |     1     |-----------|
 |           |     |     |  |           |     |     |  |           |           |     
 |           |  3  |  4  |  |           |     |     |  |           |     4     |    
 |           |     |     |  |           |     |     |  |           |           |    
 +-----------------------+  +-----------------------+  +-----------------------+  

             X                          Y                         Z
```

After closing window 2, I get layout Y, but I'd rather get layout Z.

How do I solve these problems?

(this took me half an hour to format lol)

**Comment by baskerville** [comment]
As of e9f0f42: `bspc config removal_adjustment longest_side`.

**Comment by zjeffer** [comment]
Holy shit you are actually amazing! That was quick, thanks!

**Comment by zjeffer** [comment]
@baskerville where can I donate?

**Comment by neeasade** [comment]
@zjeffer [link](https://github.com/baskerville/bspwm/blob/229b6fd878b33d3759196c2653378d7b3f9a45dd/doc/CONTRIBUTING.md#donations)

**Comment by mcolligan** [comment]
I am getting the second described behaviour even with 

    bspc config removal_adjustment longest_side

I assume that in layout X of the second description nodes 3 and 4 are meant to be the other way around i.e. the layout was created from spiral automatic tiling, and that layout Z is the unspiralling. If not, then I might be mistaken.

bspwm -v : 0.9.5-21-ge9f0f42

**Comment by zjeffer** [comment]
@baskerville I noticed that both situations still happen when moving the windows to a different monitor instead of closing them.
