### ISSUE TITLE
Closing floating windows should not trigger removal_adjustment

### ISSUE THREAD

**Issue by sudo-nice** [baskerville/bspwm#878]
Steps to reproduce:

1. Enable `bspc config removal_adjustment longest_side`
2. Have imbalanced (in terms of the above setting) windows structure.
3. Open a new floating window and close it.

Expected behavior: keep the tiled windows structure intact.
Actual behavior: the tiled windows structure is balanced to satisfy `removal_adjustment longest_side` setting.

**Comment by neeasade** [comment]
A workaround -- 

```
super + {_,shift} + w
    bspc query -N -n .focused.floating && bspc config removal_adjustment none; \
    bspc node -{c,k}; \
    sleep 0.1; \
    bspc config removal_adjustment longest_side
```

It appears to be racey/fails without the sleep.

**Comment by sudo-nice** [comment]
@neeasade Thank you, sometimes it might help indeed.
