### ISSUE TITLE
new automatic mode setting

### ISSUE THREAD

**Issue by lampenhauser** [baskerville/bspwm#882]
Hello,

I saw here on the github page, that a new automatic mode seems to have been implemented, and I would really like to use it. However, the version of bspwm I have installed (from the manjaro community repo) doesn't know the setting automatic_scheme, even though it has the same version number.

Is this just a matter of waiting until there will be a new bspwm version or am I getting something wrong?

Regards, Lukas

**Comment by sudo-nice** [comment]
Yes, you should just wait until the new release, or you can build the latest version of  bspwm by yourself from the sources.

**Comment by lampenhauser** [comment]
Ok, thanks a lot!
