### ISSUE TITLE
Pointer follows focus on mouse focus

### ISSUE THREAD

**Issue by vypxl** [baskerville/bspwm#884]
Is it possible to disable `pointer_follows_focus` if the focus was triggered by the pointer itself?
It is especially cumbersome if you have both `pointer_follows_focus` and `focus_follows_pointer` enabled, because the pointer then jumps around all the time.

I am thinking of a setting which only centers the pointer to the focused window if the focus was done by a `bspc node -f [NODE_SEL]`.

**Comment by neeasade** [comment]
the way I got around this was to disable `pointer_follows_focus`, and then surround my focus keybind with a toggle to turn it on (I only wanted it then I was pressing the keybind in a dir anyway)

**Comment by baskerville** [comment]
It would be great to provide reproduce steps for this, since `pointer_follows_focus` is already disabled when `focus_node` is triggered by `focus_follows_pointer`…

**Comment by vypxl** [comment]
For further reference, my config is in [my Dotfiles repo](https://github.com/vypxl/dotfiles/tree/master/files).
