### ISSUE TITLE
`bspc node --swap` across desktops changes focus

### ISSUE THREAD

**Issue by mishajw** [baskerville/bspwm#885]
Running `bspc node --swap NODE_SEL` where the `NODE_SEL` node is in the *same* monitor, the currently focused window remains focused. This allows you to move nodes around the screen easily.

However, when the `NODE_SEL` node is in a different monitor, the focus changes to the `NODE_SEL` node, breaking up smoothly moving nodes between monitors.

```
$ bspwm -v
0.9.3
```

**Comment by baskerville** [comment]
As of cba737e: `bspc node --swap NODE_SEL --follow`.
