### ISSUE TITLE
bspwm couldn't execute the configuration file

### ISSUE THREAD

**Issue by fr5208** [baskerville/bspwm#886]
On Slackware 14.2, bspwm was built from SlackBuilds. Bspwm and sxhkd run fine, but bspwmrc is not being executed. Permissions set to 755. Screenlayout.sh is a single line script that runs an xrandr configuration for my monitors.

~/.xinitrc:
`sh ~/.screenlayout.sh`
`sxhkd &`
`exec bspwm -c ~/.config/bspwm/bspwmrc 2>~/.bspwm.err >~/.bspwm.out`

~/.config/bspwm/bspwmrc
`urxvt &`

~/.bspwm.err gives the following message:
`Couldn't execute the configuration file.`

**Comment by BitExplorer** [comment]
@fr5208 I have the same issue, did you ever find a solution?

**Comment by wimstefan** [comment]
Making `~/.config/bspwm/bspwmrc` executable should solve the problem ...

**Comment by jallbrit** [comment]
@fr5208 are you still experiencing this bug?
