### ISSUE TITLE
Border color does not change until window state is changed.

### ISSUE THREAD

**Issue by ortango** [baskerville/bspwm#887]
Sorry if that title isn't quite correct.

Bug is as follows:

* set an unfocused window's border_width to 0.
* focused that window.
* set focused window's border_width to >0.

the focused window's border color will be normal_border_color, not focused_border_color.

I've been working around this by refocusing the focused window (bspc node focused -f).... well, honestly, not using this at all, but thought it was worth a report.
Also, it doesn't seem to happen in reverse (setting focused window bw to 0, then unfocus and set bw to >0 seems to work fine)

**Comment by baskerville** [comment]
Thanks.
