### ISSUE TITLE
specify position of newly created window

### ISSUE THREAD

**Issue by MeisterTea** [baskerville/bspwm#888]
Hi, I am using kitty as my term and I would like bspwm to place it wherever I want for me (let's say top: 0, left: 0)

Here is what I have in my external_rules file
~~~
#! /bin/sh

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")
state=$(echo "$4" | grep -oP '(?<=\bstate=)(\w+)')
if [ "$instance" = kitty ] && [ "$state" = floating ] ; then
  xdotool windowmove $1 0 0
fi

~~~

To be clear, kitty doesn't support position option and the author doesn't plan to do anything about it > https://github.com/kovidgoyal/kitty/issues/1211#issuecomment-445105243

The code I am using doesn't work. It seems at this point, the window is not available for external tools like xdotool.

So, my question is : **How I am supposed to move / specify position for a new window on bspwm if I can't "force" it on the called program itself ?**

full disclosure, the goal is to have something like this : https://www.reddit.com/r/unixporn/comments/7snf2z/bspwm_drawing_terminals/

Thank's

EDIT: If it can help, I managed to make it work but it's ugly ...

~~~
#! /bin/sh

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")
state=$(echo "$4" | grep -oP '(?<=\bstate=)(\w+)')
# ~/test.sh
if [ "$instance" = kitty ] && [ "$state" = floating ] ; then
  # it seems to work thank's to the delay of the term opening
  positionFile="$HOME/.config/bspwm/scripts/draw.tmp"
  source "$positionFile"
  rm "$positionFile"
  tmux new-session -d -s draw_tmp
  tmux send-keys "xdotool windowmove $1 $X $Y" C-m
  tmux detach -s draw_tmp
fi

~~~

~~~
#!/usr/bin/env bash
read -r X Y W H < <(slop -f "%x %y %w %h" -b 1 -t 0 -q)
printf "X=$X\nY=$Y" > ~/.config/bspwm/scripts/draw.tmp
bspc rule -a kitty -o state=floating & kitty -o initial_window_width=$W -o initial_window_height=$H -o remember_window_size=no

~~~

Thait said, I am still waiting for a better solution

**Comment by neeasade** [comment]
> So, my question is : How I am supposed to move / specify position for a new window on bspwm if I can't "force" it on the called program itself ?

I use xdotool to move the window after the fact (with a rule to set it to floating). Here is my script with a post demoing it:

https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/interact/dmenu_slop
https://www.reddit.com/r/unixporn/comments/3m58zw/script_wm_independent_slop_program_spawn/

**Comment by MeisterTea** [comment]
> > So, my question is : How I am supposed to move / specify position for a new window on bspwm if I can't "force" it on the called program itself ?
> 
> I use xdotool to move the window after the fact (with a rule to set it to floating). Here is my script with a post demoing it:
> 
> https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/interact/dmenu_slop
> https://www.reddit.com/r/unixporn/comments/3m58zw/script_wm_independent_slop_program_spawn/

Well, it seems to be just what I need except it executes every time you run dmenu right ?
How can you use dmenu without the slop part ? (I may have not read your script correctly)

**Comment by neeasade** [comment]
If I understand your concern, no, that's not an issue -- if you name the script dmenu_slop and put it in your path, you will still be able to run both dmenu_run and dmenu_slop. You can also skip the dmenu call entirely by passing the program in, eg `dmenu_slop kitty`.
