### ISSUE TITLE
Windows not taking up the full screen on 1920x1200

### ISSUE THREAD

**Issue by ar1a** [baskerville/bspwm#893]
Hi! I just installed bspwm on arch, and after hopping into it, it seems that bspwm thinks I have a 1920x1080 screen and is sizing the windows like so https://i.imgur.com/a4SU7AF.png (the bottom of the windows are a few pixels above 1080)

here is my bspwmrc

```
#! /bin/sh

sxhkd &

polybar Bar &
compton &
xrdb ~/.Xresources

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a discord desktop='^3'
bspc rule -a Screenkey manage=off
```

I have a single monitor setup

**Comment by baskerville** [comment]
What's the output of `bspc wm -d | jq '.monitors[].rectangle'`?

As a temporary fix, you could change the monitor's rectangle with `monitor -g`.

**Comment by ar1a** [comment]
```
~
❯ bspc wm -d | jq '.monitors[].rectangle'
{
  "x": 0,
  "y": 0,
  "width": 1920,
  "height": 1200
}

```

**Comment by stavpup** [comment]
> ```
> ~
> ❯ bspc wm -d | jq '.monitors[].rectangle'
> {
>   "x": 0,
>   "y": 0,
>   "width": 1920,
>   "height": 1200
> }
> ```
> EDIT: in the mean time i went back to i3

Can you try https://sourceforge.net/projects/manjarobspwmrespin/files/bspwm-mate/ ?

**Comment by MyNameIsCosmo** [comment]
What is the resolution of your monitor?
I'm curious as to the output of `xrandr`

**Comment by ar1a** [comment]
```
DVI-D-0 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm                      
   1920x1200     59.95*+
```

**Comment by ar1a** [comment]
(un)fortunately i've swapped monitors to a 1440p monitor and no longer experience this bug. This could either have been a bad version of bspwm, or a problem with 16:10.

If none of the maintainers have 16:10 monitors this issue is at an impass and could probably be closed.

**Comment by MyNameIsCosmo** [comment]
I had a similar issue when rotating my monitor.
What worked for me was calling `xrandr` in my `.xinitrc` before bspwm was started.

I may have access to a 16:10 external monitor to test out.

**Comment by jallbrit** [comment]
Can anyone reproduce, or should this issue be closed?

**Comment by IvanVolosyuk** [comment]
bspc wm -d | jq '.monitors[] | select (.name == "HDMI-1") .desktops[] | select(.name == "I").root.rectangle'                                                                                  
{                                                                                                                                                                                                                    
  "x": 0,                                                                                                                                                                                                            
  "y": 24,                                                                                                                                                                                                           
  "width": 1920,                                                                                                                                                                                                     
  "height": 1056                                                                                                                                                                                                     
}
bspc wm -d | jq '.monitors[] | select (.name == "HDMI-1") .rectangle'
{
  "x": 0,
  "y": 0,
  "width": 3840,
  "height": 2160
}
xrandr -q
...
HDMI-1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 708mm x 399mm
   3840x2160     30.00*   25.00    24.00    29.97    23.98    24.00  
...
Version: 0.9.10-2+build1

**Comment by ByteDrummer** [comment]
I've also encountered this issue. It happens in a vertical monitor layout if I unplug and plug in my top 1440p monitor several times while having another 1080p monitor below it. If the layout is horizontal, this doesn't happen.

The bounds reported by `bspc wm -d | jq '.monitors[].rectangle'` are correct, and the only way to expand them is to use `monitor -g` to set the dimension larger than the monitor actually is. 

It appears like the bounds get shrunk to the resolution of the smaller monitor but aren't expanded once the larger monitor is plugged back in.

**Comment by IvanVolosyuk** [comment]
I found a workaround I use for now:
```shell
bspc config right_padding 0
bspc config bottom_padding 0
```

**Comment by ByteDrummer** [comment]
Thanks! I added that to an autorandr postwitch script.

**Comment by mokchira** [comment]
Just to add in I also am encountering this on my laptop when I plug a larger monitor in via HDMI while bspwm is already running. xrandr recognizes the size of the monitor, and bspwm also lists the correct rectangle dimensions when I run `bspc query -T -m`, but still my tiled windows on the monitor take up only the same space they would if I opened them on the laptop built in monitor, leaving large gaps to the right and bottom.

@IvanVolosyuk 's workaround fixes it for me as well.

**Comment by m-kru** [comment]
I had the same issue on 16:9 2560x1440 screen. I had to put:
```
xrandr --output eDP-1 --off
xrandr --output HDMI-1-0 --primary
```
into `.xsessionrc` instead of `bspwmrc`.
