### ISSUE TITLE
Autostart not being executed

### ISSUE THREAD

**Issue by CrashyBang** [baskerville/bspwm#894]
I am running bspwm on Void Linux (no `systemd`) with [SDDM](https://wiki.archlinux.org/index.php/SDDM) as the display manager (not sure if any of that is relavent but on the off chance it is I have included it).

I have created a `.config/bspwm/autostart` file with the following content:
```
polybar example &
```
I have also tried
```
(sleep 1s && polybar example) &
```
As well as `chmod +x .config/bspwm/autostart`

All to no avail, I was wondering if there is something I am missing, I am aware that I can just add this to the bottom of my `bspwmrc` but seeing as `autostart` exists and this is the kind of stuff that should go there, I thought it best to ask.

**Comment by shellkr** [comment]
What do you mean with that 'autostart' exists? Not sure if there have been any changes lately but to my knowledge you have to start it somehow. You can not just put it in a directory and hope it to start.

A logical place for that is the 'bspwmrc' as other resources that you want have been started then.

**Comment by CrashyBang** [comment]
Hey @shellkr,

My understanding was based off [this](https://classicforum.manjaro.org/index.php?PHPSESSID=98q1b5jp6cndq2scmmqiged9d3&topic=18970.msg172986#msg172986) comment, that lead me to believe the `bspwm-session` automatically starts `~/.config/bspwm/autostart`.

Although I can't find any reference to `bspwm-session` in the code base and I am wondering if it is a Manjaro thing?

Cheers.

**Comment by shellkr** [comment]
That is probably your issue... by reading the thread it looks like a systemd service and as Void not using systemd would explain your issue. You will have to use the 'startx' way. So just update your '~/.xinitrc' and you should be good.

**Comment by CrashyBang** [comment]
Ahhhh that makes sense that it is a `systemd` thing, unfortunately I am using `sddm` to start the session so `.xinitrc` is out of the question, I will just add to the `bspwmrc` though which I am happy doing.
