### ISSUE TITLE
multi-monitor setups assigned keybinds error

### ISSUE THREAD

**Issue by archmj** [baskerville/bspwm#899]
## version
0.9.5

## Configuration
```bash
bspc query -M --names
```
- HDMI-2
- eDP-1

bspwmrc:  
```bash
bspc monitor HDMI-2 -d VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 900x520 --rotate normal  --output HDMI-2 --mode 1600x900 --pos 0x0 --rotate left --left-of eDP-1 --output VIRTUAL1 --off
```
## What behaviour you see
I have two monitors,  eDP-1 and HDMI-2. Problem is eDP-1 desktops get assigned keybinds [VI VII VIII IX X], instead of [I II III IV V].

## What behaviour you expect to see
eDP-1 desktops get assigned keybinds [I II III IV V],  and HDMI-2 assigned keybinds [VI VII VIII IX X].

**Comment by dieggsy** [comment]
Sorry - by keybinds, do you mean desktops/workspaces?

**Comment by archmj** [comment]
@dieggsy I want to display super + [1-5] on my laptop screen(eDP-1) and win + [6-0] on my external screen(HDMI-2). But now it is the opposite.
```ini
bspc monitor HDMI-2 -d VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V
```
```ini
bspc monitor eDP-1 -d VI VII VIII IX X
bspc monitor HDMI-2 -d I II III IV V
```
I adjusted the order, but the result was exactly the same. I re-run the loaded configuration and even restart the computer. When I run super + [1-5], it is still displayed on my extension screen.
- This is my Bspwm configuration：  
[https://gist.github.com/archmj/ecf9489a18d9c1e9b5bb9e04ac380602](https://gist.github.com/archmj/ecf9489a18d9c1e9b5bb9e04ac380602)

I have consulted the relevant information on this issue and still don't know how to solve it. I hope to get help. thank you very much.

**Comment by baskerville** [comment]
Monitors are sorted by visual order, if you want `^1` to match the first desktop of `eDP-1`, it needs to be on the left of `HDMI-2`.
 
You can, of course, swap the monitors: `bspc monitor eDP-1 -s HDMI-2`, but it would be preferable to avoid going against the natural ordering.
