### ISSUE TITLE
Loading state doesn't work

### ISSUE THREAD

**Issue by ym1234** [baskerville/bspwm#901]
I'm pretty sure I'm doing something wrong, but i'm making a script that generates a script to create the current layout.

```sh
#!/usr/bin/env bash
layout="$(bspc wm -d)"
canvas="$(./extract_canvas <(echo $layout))"
rules="$(./induce_rules <(echo $layout))"
windows="$(echo "$layout" | jq -r '.. | .? | select (.client.state != null) | .id')"
for i in $windows; do
	pid=$(xprop -id $i | grep "_NET_WM_PID(CARDINAL)")
	pid=${pid#*"= "}
	commandline="$(printf '%s\n%s & disown' "$commandline" $(tr '\000' ' ' < /proc/"$pid"/cmdline))"
done

script="bspc wm -l <(echo '$canvas')"
script+="$(printf '\n%s' "$rules")"
script+="$(printf '\n%s' "$commandline")"
echo "$script" > out.sh
```
now the problem is, the `bspc wm -l <(echo '$canvas')` doesn't work, the windows spawn and the rules are created correctly but the receptacles are not loaded, I tried saving the canvas to a file and loading it from there, but it still doesn't reload it.
(extract_canvas and induce_rules are from examples/receptacles)

Thanks!

**Comment by baskerville** [comment]
The problem might come from the fact that `wm -l` only accepts absolute paths.

**Comment by ym1234** [comment]
yup, that's it, thanks.
I think it'd be a good idea to put that in the manpage (or remove the restriction completely?)

**Comment by baskerville** [comment]
My bad: the path can be relative. The underlying C function is `open`.

The setting that require an absolute path is `external_rules_command` because of `execl`.

**Comment by ym1234** [comment]
Interesting, 
```
echo "$canvas" > out_canvas
script="bspc wm -l out_canvas"
```
and neither does `./out_canvas`, but $(realpath out_canvas) works

**Comment by baskerville** [comment]
Thanks, you've helped to uncover a general problem: the relative paths that the server might receive are resolved in relation to its own CWD, not the client's CWD.

**Comment by ym1234** [comment]
Oh, thanks makes sense, thanks!

One more question, is it possible to have receptacles whose state is floating? currently floating windows get tiled when they are recreated.

**Comment by baskerville** [comment]
Receptacles don't have states. You might want to enhance`induce_rules` instead:
```python
print('bspc rule -a {}:{} -o state={} node={}{}'.format(client['className'],
                                                        client['instanceName'],
                                                        client['state'],
                                                        prefix, '/'.join(path)))


```
