### ISSUE TITLE
Desktops not showing on correct monitors with monitors at variable heights

### ISSUE THREAD

**Issue by nebulaw2081d** [baskerville/bspwm#905]
I'm using the latest bspwm version (0.9.5-30-g644b200).

The desktop layout order is incorrect. Similar to #654, if I focus the first desktop, "I", it will focus the first desktop on the top right monitor, not the first desktop on the center monitor as I have specified. [Here](https://i.imgur.com/klZNjVn.png) is a picture of the physical layout of my monitors. If I reconfigure my monitor layout to look like [this](https://i.imgur.com/r1pVw5W.png), bspwm functions as expected, with focusing the first desktop resulting in the first desktop on the left-bottom monitor being focused.

Relevant lines from:

[bspwmrc](https://nebulacentre.ga/dotfiles/taroumaru/.config/bspwm/bspwmrc):
```
bspc monitor HDMI-1 -d I II III IV

bspc monitor DP-1 -d V VI VII

bspc monitor HDMI-0 -d VIII IX X
```
[.xinitrc](https://nebulacentre.ga/dotfiles/taroumaru/.xinitrc):

```
xrandr --output HDMI-1 -r 75 --mode 1920x1080 --primary --auto --output DP-1 --right-of HDMI-1 --mode 1920x1080 --auto --output HDMI-0 --mode 1600x900 --above DP-1 --auto
```

Output of `bspc wm -d | jq '.monitors[] | {name, rectangle}'`:
```
{
  "name": "HDMI-0",
  "rectangle": {
    "x": 1920,
    "y": 0,
    "width": 1600,
    "height": 900
  }
}
{
  "name": "HDMI-1",
  "rectangle": {
    "x": 0,
    "y": 900,
    "width": 1920,
    "height": 1080
  }
}
{
  "name": "DP-1",
  "rectangle": {
    "x": 1920,
    "y": 900,
    "width": 1920,
    "height": 1080
  }
}
```

**Comment by gbrlsnchs** [comment]
I have observed that bspwm sorts workspaces depending on the order of the monitors, which seems to be top to bottom, left to right.

This has also bothered me but makes total sense considering the names given to workspaces, being arbitrary, don't set their order internally (the one used by sxhkd, for example).

**Comment by nebulaw2081d** [comment]
@gbrlsnchs I also know that behavior is default. I was hoping there could be an option added to manually specify the order of monitors. I will look into a potential pull request.

**Comment by jallbrit** [comment]
@nebulaw2081d have you tried using `bspc monitor --swap` to change the internal ID of the monitors?

**Comment by nebulaw2081d** [comment]
@jallbrit Thank you very much! After swapping the monitors around a few times and some trial and error I have gotten the desired arrangement.
