### ISSUE TITLE
Option to Ignore EWMH Struts?

### ISSUE THREAD

**Issue by MyNameIsCosmo** [baskerville/bspwm#906]
I am using the latest `bspwm` from git (commit 644b200) and the latest `polybar`.
My current issue is that `bspwm` will respect monitor padding until `polybar` is reloaded, in which case it will increase the padding to whichever side `polybar` is.

I highly suspect this is due to the EWMH structs from #487 

This issue started out after reloading `polybar` config
See the following video for an example:
https://www.youtube.com/watch?v=PPF7ZfwZlsM
 
This seems to affect the current desktop, even though `bspc wm -d` states that the monitor padding is set and not the desktop padding. The other desktops do not seem to be affected until i either reload my configuration when on the desktop, or close all windows.

Would it be OK to add a configuration to ignore EWMH struts?
I'd be happy following up with a PR if it would be accepted

**Comment by Eel52** [comment]
I encounter this issue as well and have a workaround by creatibg a script module in Polybar and having it execute every second, the script simply runs `bspc config top_padding 25`, which seems to resolve it.

**Comment by MyNameIsCosmo** [comment]
Possibly related: #836

**Comment by Eel52** [comment]
Do you want me to test your patch before you submit it?

**Comment by MyNameIsCosmo** [comment]
Go ahead and test the PR if you'd like, it's a straight-forward configuration, and the impact should be minimal.
