### ISSUE TITLE
Where is mouse resizing behavior defined?

### ISSUE THREAD

**Issue by install-ubuntu** [baskerville/bspwm#910]
Where is the behavior for mouse resizing/moving windows defined? It's not in my sxhkdrc as I've seen some others say.

**Comment by MyNameIsCosmo** [comment]
Look at the Pointer Options in the config:
https://github.com/baskerville/bspwm/blob/master/doc/bspwm.1.asciidoc#global-settings

```
pointer_modifier
    Keyboard modifier used for moving or resizing windows. Accept the following values: shift, control, lock, mod1, mod2, mod3, mod4, mod5.

pointer_action1
pointer_action2
pointer_action3
    Action performed when pressing pointer_modifier + button<n>. Accept the following values: move, resize_side, resize_corner, focus, none.
```

If this doesn't satisfy you, check out:
https://github.com/Chrysostomus/bspwm-scripts/blob/master/configs/sxhkd/sxhkdrc#L192

**Comment by juacq97** [comment]
> check out: https://github.com/Chrysostomus/bspwm-scripts/blob/master/configs/sxhkd/sxhkdrc#L192

I checked out, I tried to put the command in terminal and I have this:

```
$ bspc pointer -g move
Unknown domain or command: 'pointer'.
```
