### ISSUE TITLE
[Question] Bind fixed numbers to Workspaces

### ISSUE THREAD

**Issue by Vitax** [baskerville/bspwm#920]
In my bspwmrc I have the lines:
```
# workspace settings per display
bspc monitor DVI-D-0 -d code chat terminal email text graphics games music
bspc monitor HDMI-0 -d browser reads
```

What this results in is, that my workspace browser is number 1, reads 2, code 3 etc....

Is it possible to bind lets say code to workspace 1, browser to 2 ... yada yada. 
Is a behaviour like this possible ? If not, I would find this realy helpful.

**Comment by dieggsy** [comment]
Are you just looking for rules? e.g. `bspc rule -a Firefox state=tiled desktop=^2` (or you might even be able to do e.g. `bspc rule -a Firefox state=tiled desktop=browser`. See `man bspc`, look for heading `Rule`.

**Comment by Vitax** [comment]
@dieggsy 
Not really, the shortcuts
```
# focus or send to the given desktop
alt + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'
```
behave as mentioned above, if I press alt + 1 I go the workspace browser, what I want instead is sxhkd sending me to the workspace code. So to be more precise is I want to predefine the numbering of the desktops (is it called that in bspwm).

**Comment by Vitax** [comment]
And the moment I write this comment I realize what to do :laughing:
