### ISSUE TITLE
Alt goes stuck

### ISSUE THREAD

**Issue by Alexander-Shukaev** [baskerville/bspwm#921]
I have the following in my configuration:

```
# Focus/move current node (window) to the given desktop:
alt + {_,shift + }{1-9,0}
  bspc {desktop -f,node -d} "$(bspc query -M -m)"/{1-9,10}
```

If I use that very quickly and repeatedly, i.e. literally spamming number keys while <kbd>Alt</kbd> is pressed, then at some point <kbd>Alt</kbd> will somehow remain stuck pressed even though I released it already.  This breaks the whole desktop and I cannot work with any application anymore as all of them think that <kbd>Alt</kbd> is still pressed.  It's easy to prove because in this case, even without pressing <kbd>Alt</kbd>, I can drag windows on left click or resize them upon right click or when I rotate mouse wheel in Emacs it shows me that I'm trying to perform <kbd>Alt</kbd> plus wheel input operation.  At this point I cannot even switch to another TTY or switch user or reboot.  I don't know how to debug this.  Any ideas?

**Comment by MyNameIsCosmo** [comment]
This ought to be opened in the [sxhkd](https://github.com/baskerville/sxhkd/) repo

Please open up an issue there and give us the following information:
Can you do a `sxhkd -v` and let us know the version your running?
Are you able to hit <kbd>ESC</kbd> to exit out?

**Comment by Alexander-Shukaev** [comment]
Done <baskerville/sxhkd#132>.
