### ISSUE TITLE
Next Official Release Date?

### ISSUE THREAD

**Issue by JKomoroski** [baskerville/bspwm#922]
Hello,

It looks like master is 10 months ahead of the last official release. Are there any plans for a version 0.9.6 in the near future?

Thanks for the great WM.

**Comment by shizonic** [comment]
Would like to know it too. It's a easier for package maintainers if there are regular releases.

BTW.: Thank you for your great work! It's my absolutely preferred WM !

**Comment by baskerville** [comment]
Done.

**Comment by gavsiu** [comment]
Would you be able to do another release or is it too early? I see that the annoying monocle bug was fixed recently. Thanks.

**Comment by shizonic** [comment]
Guess hotfixes are never "too early" ...

**Comment by shizonic** [comment]
Thanks @baskerville !
