### ISSUE TITLE
With automatic_scheme=alternate and one window floating, automatic insertion doesn't behave as expected.

### ISSUE THREAD

**Issue by zjeffer** [baskerville/bspwm#923]
I use the alternate insertion scheme and I found that if you have a window floating, the automatic insertion behaves as if the floating window is part of the tiled ones, so inserting a window doesn't 

I'm guessing you programmed the alternate insertion scheme by keeping a count of the amount of all the currently present windows, and not the amount of currently tiled windows. 

The alternate insertion scheme should behave the same way, whether there's a floating window or not. 

Thanks

**Comment by baskerville** [comment]
Can you provide an example?

**Comment by zjeffer** [comment]
Sure.

When I open three windows I get the following layout:

![image](https://user-images.githubusercontent.com/4633209/52522308-c8a36480-2c83-11e9-8c01-94174dba09ff.png)

If I float the bottom right window, I get this layout.

![image](https://user-images.githubusercontent.com/4633209/52522315-d953da80-2c83-11e9-9a19-acdcb1883be8.png)

Great. But if I then open a new tiled window **while the right tiled window is selected**, I get this layout:

![image](https://user-images.githubusercontent.com/4633209/52522324-15873b00-2c84-11e9-89ef-b22668b93471.png)

As you can see it creates a new window to the right, but instead, I want it to create a new window at the bottom right, like in this image:

![image](https://user-images.githubusercontent.com/4633209/52522394-2a180300-2c85-11e9-9065-bd2e1bcafeb5.png)

I do get this layout if I insert the new window while the floating window is selected instead of one of the tiled windows.
