### ISSUE TITLE
[Q] How does bspwm go into fullscreen as a video in browser is made fullscreen?

### ISSUE THREAD

**Issue by aesophor** [baskerville/bspwm#924]
Sorry for asking an off-topic question here!

I'm learning Xlib and implementing a wm. In my wm, when I use Firefox and make a youtube video fullscreen, the video only fills the window (but I expect it to fill the entire screen like in bspwm, dwm, i3, etc).

For example:
![](https://i.imgur.com/pvH8mCb.png)

I've tried using `xev -root` in i3. When a video in browser is made fullscreen, an XClientMessageEvent will be fired, so the wm knows when to set the browser to fill the entire screen. But in my wm it's not receiving this kind of XClientMessageEvent at all.

Can anybody help? If it is not appropriate to ask this here, please tell me and I'll close it.

**Comment by MyNameIsCosmo** [comment]
Check out the [ewmh spec](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472615568)

I think this functionality is implemented in [events.c](https://github.com/baskerville/bspwm/blob/master/src/events.c#L463)

**Comment by baskerville** [comment]
@aesophor You need to [set](https://github.com/baskerville/bspwm/blob/21a025b1e7292409efbc54a5a05c36fa2cfd5996/src/bspwm.c#L404) an appropriate event mask on the root window.

**Comment by aesophor** [comment]
@MyNameIsCosmo @baskerville Thank you very much!

I see that bspwm set  (1) SubstructureRedirect, (2) SubstructureNotify, (3) StructureNotify and (4) ButtonPress masks on the root window, so I tried setting (1)(2)(3), but the client message are still not fired (I tested with `xev -root`)... a bit weird :confused: 
```
XSelectInput(dpy_, root_window_, SubstructureNotifyMask | SubstructureRedirectMask | StructureNotifyMask);
```

Ah this is [a list of atoms](https://github.com/aesophor/Wmderland/blob/master/src/properties.cpp) supported by my WM, not sure if I missed anything.
