### ISSUE TITLE
bspc wm -r

### ISSUE THREAD

**Issue by lineber** [baskerville/bspwm#928]
This isn't a huge deal but in the example file for sxhdrc on this repository there is a command that I cannot get working.

Line 21 of the example sxhkdrc file:
```
# quit/restart bspwm                                                             
super + alt + {q,r}                                                              
          bspc {quit,wm -r}  
```
super+alt-q = Works
super+alt+r = NOT Working.

In terminal when I run 
`bspc wm -r`
I get the following error:
wm: Unkown command: '-r'.

Of course I use the following to reset but would like to get the example working correctly.
super + Escape
     pkill -USR1 -x sxhkd & ~/.config/bspwm/bspwmrc

**Comment by MyNameIsCosmo** [comment]
This feature was added via #904
Update to the latest *bspwm* release of 0.9.6

**Comment by lineber** [comment]
Ah, yes. I originally installed bpswm from the Fedora repo. Instead, I've now cloned the GitHub repo and installed directly, it now works perfectly. Please close this issue.

Fedora is really behind the current version in their repo is 0.9.2.

Name         : bspwm
Version      : 0.9.2
Release      : 5.fc29
Arch         : x86_64
Size         : 104 k
Source       : bspwm-0.9.2-5.fc29.src.rpm
Repo         : fedora

Thanks again.
