### ISSUE TITLE
single_monocle does not work for the first node on a desktop

### ISSUE THREAD

**Issue by wfrx** [baskerville/bspwm#929]
Version `0.9.6`. 
`single_monocle` with `gapless_monocle` and `borderless_monocle` does not work for the first node on a desktop. 

Monocle Layout works, if:
- I manually activate it with multiple nodes on the desktop
- I change the Layout of the single node from monocle to floating/pseudo-tiled and back
- I open multiple nodes on a desktop and close all but one
- I restart bspwm
- I close the single node on the desktop and then reopen it
- I de- and then reactivate `single_monocle` via `bspc`

It affects only the *first* node that's opened on a desktop, and only so long as I don't do anything else that affects the layout (e.g. opening more nodes, changing the layout, changing the layout config...). 

Also, the *first* desktop (the one that's focused when I start bspwm) is working as it should, on the others I have the issue described above. Once I do one of the actions that "fix" the issue, the particular desktop that's focused works fine from then on (until I log out). 

**EDIT**: I forgot to mention: If I add/remove desktops, every new desktop has the same issue.

This is my `bspwmrc`:
```
#! /bin/sh
bspc config window_gap 		5

# Single Window Settings
bspc config gapless_monocle     true
bspc config borderless_monocle  true
bspc config single_monocle 	true

# Automatic Splitting Settings
bspc config automatic_scheme	longest_side
bspc config initial_polarity	second_child

# Presel Settings
bspc config presel_feedback	false

# Mouse Settings
bspc config pointer_modifier	super
bspc config pointer_action1	move
bspc config pointer_action2	resize_side
bspc config pointer_action3	resize_corner

# Border Settings
bspc config focused_border_color 	"#d5c4a1"
bspc config normal_border_color 	"#282828"
bspc config border_width 		2

# Pointer Settings
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus	true

# Panel Settings
bspc config top_padding 	$PANEL_HEIGHT
panel &

# Keys
sxhkd &
```

**Comment by expectocode** [comment]
I have a similar issue, not as fully investigated so not sure if exactly the same. My symptoms: first window made on a desktop has gaps around the edge despite gapless_monocle. 

Creating a second window and closing it 'fixes ' it.

**Comment by zuglufttier** [comment]
I can confirm this as well on version 0.9.6.

**Comment by cglogic** [comment]
I fixed similar issue by moving "bspc monitor ..." before other lines in my config file.
