### ISSUE TITLE
Killing and starting `bspwm` again

### ISSUE THREAD

**Issue by Alexander-Shukaev** [baskerville/bspwm#930]
When killing (or otherwise shutting down) and starting `bspwm` again, I observe the following issues:

- `xfce4-panel` disappears (restarting it does not help, manually rerunning `bspwmrc` does not help);
- already running instance of `emacs` does not react on <kbd>F11</kbd> (fullscreen), but a new instance of `emacs` does and it goes fullscreen.  Why?

**Comment by baskerville** [comment]
Have you tried `wm -r`?

**Comment by Alexander-Shukaev** [comment]
Sorry for ignorance, but what is `wm`?

**Comment by dieggsy** [comment]
@Alexander-Shukaev it's a subcommand of `bspc`, `-r` was recently added for restarting bspwm.

**Comment by Alexander-Shukaev** [comment]
I haven't upgraded to this version yet and I will do so to give it a try.  However, I am surprised that the service

```
[Unit]
Description=BSPWM: Binary space partitioning window manager
Documentation=man:bspwm(1)
After=wm.target
Requires=wm.target
StartLimitIntervalSec=0
##
[Service]
ExecReload=/usr/bin/kill -HUP $MAINPID
ExecStart=/usr/bin/bspwm
ExecStop=/usr/bin/bspc quit
KillMode=process
Restart=on-failure
RestartSec=1
Type=simple
##
[Install]
WantedBy=wm.target
```

and in particular a sequence of `bspwm` and `bspc quit` (upon `systemctl restart bspwm`) do not achieve the desired effect.  For instance, this is what happens in this case:

```
Mar 03 12:44:50 g75vw systemd[1080]: Stopping BSPWM: Binary space partitioning window manager...
Mar 03 12:44:50 g75vw systemd[1080]: Stopped BSPWM: Binary space partitioning window manager.
Mar 03 12:44:50 g75vw systemd[1080]: Started BSPWM: Binary space partitioning window manager.
Mar 03 12:44:50 g75vw panel-31-whiske[1369]: Window 0x558797232b10 has not been made visible in GdkSeatGrabPrepareFunc
Mar 03 12:44:50 g75vw bspwm[8618]: Failed request: SetInputFocus, BadMatch: 0x0240001A.
Mar 03 12:44:50 g75vw bspwm[8618]: Failed to query the window tree.
Mar 03 12:44:50 g75vw bspwm[8618]: Failed to query the window tree.
```

Could those messages shed some light on the problem?

**Comment by Alexander-Shukaev** [comment]
A further question is whether `bspc wm -r` (in case it resolves the above problem) be used instead of `bspwm` (even when the previous instance is not running).  The point is that there is no dedicated `ExecRestart` in `systemd`.  Thus, `bspc wm -r` should essentially do the same what `bspwm` would do when no previous instance is running.

**Comment by Alexander-Shukaev** [comment]
Tested `bspc wm -r`.  It behaves more like "reload" rather than "restart", so the name is misleading.  That is it reused the initial PID of `bspwm` (does not start new instance) and merely rereads the `bspwmrc` configuration file.  This exactly satisfies the requirement of `ExecReload` (as per `systemd` service unit).  Anyway, the result is the same with respect to `xfce4-panel`, i.e. it disappears, though the process is still running.

**Comment by Alexander-Shukaev** [comment]
Some more findings:

- If I do `xdo raise $(xdo id -a xfce4-panel)`, the panel appears again, but then it stays on top of fullscreen windows as well (not desired) and also casts shadows on nearby windows (also not).
- If I do `xdo lower $(xdo id -a xfce4-panel)`, the panel disappears again.
- If I do `xdo above -t $(xdo id -N Bspwm -n root | sort | head -n 1) $(xdo id -a xfce4-panel)`, the panel also disappears.
- Thus, `raise` is the only action bring the panel back.
- Already running instance of `emacs` does not react on <kbd>F11</kbd> (fullscreen), but a new instance of `emacs` does and it goes fullscreen.  While all other already running instances of various applications can go fullscreen without that issue.  What's up with `emacs`?

**Comment by Alexander-Shukaev** [comment]
Right, so now I know what it was disappearing upon restart or reload: I actually had `xdo above -t $(xdo id -N Bspwm -n root | sort | head -n 1) $(xdo id -a xfce4-panel)` as part of my external rules.  If I remove it, restart `xfce4-panel` and then no matter how many times I reload or restart `bspwm`, the panel remains.  Good, but the idea of the above external rule was to keep the panel on the lower layer (not raised) as per above comment.  That is if I remove the above external rule, the panel is visible, but always raised and hence on top of fullscreen windows.  I saw other dudes having success with that rule in #1005, #857, #717, #696, #484.

**Comment by Alexander-Shukaev** [comment]
This looks like regression also with respect to #622.  I can only bring Conky up now with `raise` as well, while the previous solution with neither `above` the `root` window nor just `lower` work anymore.

**Comment by Alexander-Shukaev** [comment]
Turned out that stacking (with `above`) everything (including `xfce4-panel`) above `xfdesktop` is necessary.
