### ISSUE TITLE
Borders not drawn on VS Code

### ISSUE THREAD

**Issue by Meakk** [baskerville/bspwm#932]
I'm on Arch, if that matters.

VS Code borders look transparent (space is allocated but nothing is drawn).
I'm coming from i3 and it was working fine.
Calling chwb manually have no effect.

Any idea?

![2019-02-22-104607_544x218_scrot](https://user-images.githubusercontent.com/6069752/53234098-13af7580-368f-11e9-90dd-73b0f5bf5ec1.png)

**Comment by ZiJingToh** [comment]
Had the same issue, switching "Title Bar Style" under vscode's settings to "native" instead of "custom" fixes it.

**Comment by Meakk** [comment]
Thank you @ZiJingToh !
