### ISSUE TITLE
in 0.9.6.1 spiral mode is not longer default ?

### ISSUE THREAD

**Issue by icf20** [baskerville/bspwm#933]
i noticed that in version 0.9.6.1 spiral mode is not longer respected and windows open in a odd manner 

is this intended or is a bug?

workaround: downgrade to 0.9.5.1

**Comment by baskerville** [comment]
Have you read the [CHANGELOG](https://github.com/baskerville/bspwm/blob/master/doc/CHANGELOG.md)?

**Comment by icf20** [comment]
> Have you read the [CHANGELOG](https://github.com/baskerville/bspwm/blob/master/doc/CHANGELOG.md)?

no i dint, i dont expect software to change the default way it works simple because there is a update :rage:

**Comment by rvolosatovs** [comment]
I was surprised to see this change of behavior also - I assumed it was a bug at first.
That said, the project still did not reach `1.0.0`, so it's fully acceptable.

**Comment by HaoZeke** [comment]
@icf20 while I was also disappointed, there are no expectations in Foss.

That said it is silly for `bspwm` clone the features of `i3`. This was discussed a while ago on another issue and the gist was that it was hard for old stacking window manager users to work with the default layout.

I myself switched to `i3` anticipating this and other majority based changes.

**Comment by icf20** [comment]
i let this "fix" in case anyone google this

put this into bspwmrc 

```
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
```

i hope this help more people that the BS above
