### ISSUE TITLE
Unknown command --remove-desktops 

### ISSUE THREAD

**Issue by oyren** [baskerville/bspwm#934]
BSPWM Version: 0.9.6

``` sh
➜  ~ bspc monitor eDP1 --add-desktops 11
➜  ~ bspc monitor eDP1 --remove-desktops 11
monitor: Unknown command: '--remove-desktops'.
```

Expected behavior: Desktop would be removed.

**Comment by baskerville** [comment]
In 0.9.2, the monitor domain's `--remove-desktops` command was removed and a `--remove` command was added on the desktop domain.

**Comment by oyren** [comment]
Thanks, maybe it should be updated here (https://github.com/baskerville/bspwm/wiki/Command-Syntax-Rewrite).
Or am I looking at the wrong place?

**Comment by baskerville** [comment]
> Or am I looking at the wrong place?

Yes you are. Those changes are documented in `doc/CHANGELOG.md`.
