### ISSUE TITLE
Can't add rounded corners.

### ISSUE THREAD

**Issue by juacq97** [baskerville/bspwm#936]
I try to add rounded corners to my windows, but when I try to execute the command an error appears in the terminal. If I'm not wrong, that should be the command, but the autocomplete does not show it to me either. I am doing something wrong? My version of bspwm is 0.9.6.
![captura-2019-02-27_1](https://user-images.githubusercontent.com/7623047/53539790-364aef80-3ad0-11e9-8a18-02f58d4d558a.png)

**Comment by MyNameIsCosmo** [comment]
Rounded corners has not been merged into the master project yet.

You can check out the comments on #856 and additional comments in #848

**Comment by juacq97** [comment]
Oh, I see, I thought had already merged with Master, but it's a merge request. Thanks! I hope it will be merged soon hehe
