### ISSUE TITLE
shebang is incorrect in bspwmrc

### ISSUE THREAD

**Issue by ZoeFiri** [baskerville/bspwm#937]
expamples/bspwmrc shebang is `#! /bin/sh`, not `#!/bin/sh` led to some confusion when it wouldn't execute.

**Comment by HaoZeke** [comment]
Should be a pull request I guess....

**Comment by MarcinWieczorek** [comment]
It's not a bug.
> Blanks after ! are OK.
>Dennis Ritchie, Jan 10 1980
Source: https://en.wikipedia.org/wiki/Shebang_(Unix)
