### ISSUE TITLE
Node selector not behaving correctly

### ISSUE THREAD

**Issue by kwshi** [baskerville/bspwm#940]
For months, I had a hotkey bound to the command
```bash
bspc node next.active -f
```
which worked correctly for focusing the next active node in the "cyclic" direction.

This command no longer works.  Upon closer inspection, I think the node selector mechanism is broken in more ways than one:
```
# these commands give no output whatsoever--I am calling it from an active, focused terminal window
[kshi@dexi ~]$ bspc query -N .active
[kshi@dexi ~]$ bspc query -N .focused
[kshi@dexi ~]$ bspc query -N .window

# these commands output every single open node on every single desktop even when, according to documentation, it only makes sense for there to be one qualifying node (e.g. pointed)
[kshi@dexi ~]$ bspc query -N last
0x00600013
0x03C00003
0x0200013F
0x03000003
0x03400010
0x04600003
0x00600015
0x04000003
0x04200003
0x00600017
0x04E00003
0x05000003
0x00E00003
0x02E00003
[kshi@dexi ~]$ bspc query -N newest
0x00600013
0x03C00003
0x0200013F
0x03000003
0x03400010
0x04600003
0x00600015
0x04000003
0x04200003
0x00600017
0x04E00003
0x05000003
0x00E00003
0x02E00003
[kshi@dexi ~]$ bspc query -N focused
0x00600013
0x03C00003
0x0200013F
0x03000003
0x03400010
0x04600003
0x00600015
0x04000003
0x04200003
0x00600017
0x04E00003
0x05000003
0x00E00003
0x02E00003
[kshi@dexi ~]$ bspc query -N pointed
0x00600013
0x03C00003
0x0200013F
0x03000003
0x03400010
0x04600003
0x00600015
0x04000003
0x04200003
0x00600017
0x04E00003
0x05000003
0x00E00003
0x02E00003
[kshi@dexi ~]$ bspc query -N biggest
0x00600013
0x03C00003
0x0200013F
0x03000003
0x03400010
0x04600003
0x00600015
0x04000003
0x04200003
0x00600017
0x04E00003
0x05000003
0x00E00003
0x02E00003
[kshi@dexi ~]$ bspc query -N smallest
0x00600013
0x03C00003
0x0200013F
0x03000003
0x03400010
0x04600003
0x00600015
0x04000003
0x04200003
0x00600017
0x04E00003
0x05000003
0x00E00003
0x02E00003
[kshi@dexi ~]$ bspc query -N next
0x00600013
0x03C00003
0x0200013F
0x03000003
0x03400010
0x04600003
0x00600015
0x04000003
0x04200003
0x00600017
0x04E00003
0x05000003
0x00E00003
0x02E00003
[kshi@dexi ~]$ bspc query -N 0x03c00003
0x00600013
0x03C00003
0x0200013F
0x03000003
0x03400010
0x04600003
0x00600015
0x04000003
0x04200003
0x00600017
0x04E00003
0x05000003
0x00E00003
0x02E00003
```

**Comment by baskerville** [comment]
> For months, I had a hotkey bound to the command
> 
> ```shell
> bspc node next.active -f
> ```
> 
> which worked correctly for focusing the next active node in the "cyclic" direction.
> 
> This command no longer works.

As mentioned in the CHANGELOG, the meaning of `.active` changed. The selector you want is `next.active.!focused` but I'm sure you've already figured it out.

> Upon closer inspection, I think the node selector mechanism is broken in more ways than one:
> 
> `bspc query -N .active`

Maybe what you wanted to type was `bspc query -N -n .active`?

> `bspc query -N last`

Once again: `bspc query -N -n last`.

**Comment by kwshi** [comment]
Oh, thanks for clearing up the `bspc query` commands.  

I misinterpreted the documentation to indicate that the `-N [NODE_SEL]` was the filter, as opposed to the reference node.

Regarding the `next.active.!focused` fix: I'm afraid it still doesn't work.  The `next.active` selector isn't returning anything, and `next.active.!focused` doesn't return anything either:
```bash
[kshi@dexi ~]$ bspc query -N -n next.active
[kshi@dexi ~]$ bspc query -N -n 'next.active.!focused'
```

So my problem is that I don't have a reliable way to access the "next node on the same desktop".  What is the correct thing to do to achieve that, now that the behavior of `.active` has changed?

**Comment by baskerville** [comment]
The next node on the same desktop would be `next.local`…

**Comment by kwshi** [comment]
Cool--thanks!
