### ISSUE TITLE
How to spawn windows on the next immediate empty workspace?

### ISSUE THREAD

**Issue by redcoatzygote** [baskerville/bspwm#946]
If I wanted to spawn e.g. GIMP while on workspace 1 which has a browser open, what commands are needed to make it spawn in the next immediate empty workspace (2 if empty, or 3 if 2 also had a program in it)? Of course, GIMP would spawn in the current workspace if it was empty as well. I want to avoid the rules that assign programs to certain workspaces as sometimes I would already have stuff in them (I'd like GIMP to always start as the only window).
Thanks in advance.

**Comment by ikn** [comment]
`bspc desktop -f 'next.!occupied' && gimp`?

**Comment by redcoatzygote** [comment]
> 
> 
> `bspc desktop -f 'next.!occupied' && gimp`?

Thanks, but is there a rule for this that I can put in my bspwmrc? I open my programs with rofi so I'd rather not have a dedicated keybinding or manually type it out to spawn windows.

**Comment by neeasade** [comment]
`bspc rule -a \* -o desktop=$(bspc query -D -d 'next.!occupied')`, execute just before your rofi call.
