### ISSUE TITLE
`bspc query -N -d` doesn't apply the desktop filter

### ISSUE THREAD

**Issue by ikn** [baskerville/bspwm#947]
Before a recent change to `<node>.active`, I used to use `bspc node -f last.active` to swap between the two most recently active windows on visible desktops across all monitors.  I tried to replicate this with `bspc node -f "$(bspc query -N -n last -d .active)"`, but it doesn't seem to respect the `.active` filter at all.  In particular:

```
$ bspc query -N -d .active
0x00A00032
0x01200085
0x0080001B
0x01600025
0x01600068
```

I think this query is supposed to print nodes on desktops which match `.active`, but this isn't the case for node `0x01600068`:

```
$ bspc query -D -n 0x01600068
0x00A0000F
$ bspc query -D -d .active
0x00A00006
0x00A00007
```

Am I misunderstanding how this works?  I can't really make sense of the results of any `bspc query -N -d ...` command.

**Comment by baskerville** [comment]
It reminds me of #940.

**Comment by ikn** [comment]
As I read it, the issue in #940 was specifying the reference selector when the user wanted to specify the filter selector.  I'm not specifying the reference selector in any of my commands, so I don't see how it can be the same issue.
