### ISSUE TITLE
Browsers Firefox and Chromium open with "did not shut down properly/having trouble restoring sessions"

### ISSUE THREAD

**Issue by Babkock** [baskerville/bspwm#949]
I don't know if there's another Bspc command for exiting these browsers? But every time I close a browser window like a normal window (this happens both on my Raspberry Pi and laptop), and re-launch the browser later, it acts as if recovering from a crash or unexpected shutdown. Is there a way I can alter the behavior so it doesn't do this? Other window managers don't have this problem, but please correct me if the fault is my own/if there's something I can do about this.

Sorry if this issue exists, I didn't see it

**Comment by b17wise** [comment]
Xserver: 1.18.4
Firefox-esr: 60.6.1esr (64-bit)
```
$ uname -mpv
FreeBSD 12.0-RELEASE-p3 GENERIC  amd64 amd64
$ bspwm -version
0.9.7
```
Reproducible: Randomly
How to reproduce:  Open Firefox in full screen, then tile in with another window (xterm for example), close tiled Firefox, close xterm, open Firefox, issue is reproducible
 
![shot](https://user-images.githubusercontent.com/40580255/54936924-812e1a80-4f49-11e9-99bf-76d0589d68b5.png)

**Comment by jallbrit** [comment]
It appears that, as your pull request states, you were sending `bspc node -c -k` which is sending 2 kill signals to the processes. In your `sxhkd`, make sure you have `bspc node -c` for close, or `bspc node -k` for kill, but not both for the same keybinding.
