### ISSUE TITLE
can't install bspwm based on wiki

### ISSUE THREAD

**Issue by ViOrise** [baskerville/bspwm#952]
When i had started install bspwm (`cd bspwm && make && sudo make install`) error occurred. 

**Error:** 
```
cc -std=c99 -pedantic -Wall -Wextra -D_POSIX_C_SOURCE=200809L -DVERSION=\"0.9.7-1-g4e7c346\"  -c -o bspwm.o src/bspwm.c
make: cc: Command not found
<builtin>: recipe for target 'bspwm.o' failed
make: *** [bspwm.o] Error 127
```

**Comment by MyNameIsCosmo** [comment]
> `make: cc: Command not found`

You need a `c` compiler like `gcc` installed.

Refer to your distro's package manager to install `gcc` or use your preferred libc.

**Comment by ViOrise** [comment]
Thanks program installed well 

But...hm
Can i use bspwm in windows and subsystem ubuntu?

after `~$ bspwm`
I can see only error 
`The server closed the connection: socket, pipe or stream error.`
