### ISSUE TITLE
Show node number and type number to goto that node

### ISSUE THREAD

**Issue by imaojun** [baskerville/bspwm#953]
Whether it can be implemented like `Tmux`, the numeric number of node is displayed by the shortcut key, and then switched to the corresponding node by digital selection during display. When I have a lot of nodes in a window, I don't want to move the node on the neighbor until it is on the appropriate node.  

Example:  
I have 4 side-by-side nodes on a window. `Node[1 -4]`, when I am on `Node1`, how do I switch directly to `Node3` instead of switching to `Node2` and then to `Node3`.  

in `Tmux` , I can use this command to complete the panel switch in the same window.
```tmux
<prefix> q (Show pane numbers, when the numbers show up type the key to goto that pane)
```
Thank you. I love Bspwm.

**Comment by ikn** [comment]
#858

**Comment by imaojun** [comment]
@ikn good Idea! But it seems not works for me. i just  reference your `sxhkdrc` configuration about `xorg-choose-window`.  
when I try to use it,  It is worked for Show node letter number.But i type the key want to goto that node it not workes well. It exchanges the corresponding letter node instead of focusing on the corresponding letter node.
```
super + alt + s
    bspc node -s "$(xorg-choose-window aoeuhtns)" --follow
```

**Comment by sudo-nice** [comment]
@imaojun, that happens because you provide `-s` (swap) parameter, instead of `-f` (focus). Try it like this:
```sh
super + alt + s
  bspc node -f $(xorg-choose-window aoeuhtns -b $(bspc query -N -n focused))
```

**Comment by imaojun** [comment]
@sudo-nice Awesome. Thank you brothers.
