### ISSUE TITLE
Presel feedback color dosen't work when there is only one window

### ISSUE THREAD

**Issue by Alkeryn** [baskerville/bspwm#954]
So even though the presel works, there is no visual indication of it when there is only one window
i think it is linked to the single monocle mode
but that would be nice to have presel feedback on single monocle mode

**Comment by pjhalsli** [comment]
that's because the single window is in monocle mode.  and then it wouldn't make sense to have presel feedback as the windows are above each other.

mod + m and presel feedback will work as usual    ;)

**Comment by Alkeryn** [comment]
@pjhalsli I know that it is because of the single monocle mode
What i'm saying is that you should have presel feedback in single monocle mode since that's the only way to not have gap on a single window
