### ISSUE TITLE
How to remove  close, minimize, maximize buttons

### ISSUE THREAD

**Issue by imaojun** [baskerville/bspwm#957]
When I used manjaro-i3wm before, these three buttons are not displayed. I think this is great. Because when I use a tiled window, I can completely replace their functions with keyboard keys. So they are redundant and take up space. 

I want to know how to do this so that they don't show up.
thank you very much.

**Comment by mdutra** [comment]
Bspwm doesn't have these buttons. Some windows display them because some applications implement their own buttons, for example: Chromium and Gnome applications.

**Comment by imaojun** [comment]
@mdutra Ok, I will try it.
