### ISSUE TITLE
Inconsistent stacking order

### ISSUE THREAD

**Issue by baskerville** [baskerville/bspwm#96]
Steps to reproduce:
```
rule -a Gimp state=floating
gimp
```
Then, hit *Ctrl+n*: the newly created window appears behind the main window.

There's a discrepancy here, between the output of `bspc query -S` and the actual stacking order: *bspwm* thinks that the main window is below the two toolbar windows and the related X requests were made, yet the actual stacking order differs.

**Comment by flannelhead** [comment]
@baskerville, do you think this is still relevant? I can't reproduce this particular case, but I have had some newly created confirmation dialogs (eg. overwrite confirmation in Gimp) left below the other windows.

**Comment by baskerville** [comment]
Seems to be fixed.
