### ISSUE TITLE
Trouble cycling through windows + monitors, when 1 monitor inactive.

### ISSUE THREAD

**Issue by gdldg** [baskerville/bspwm#961]
I'm having trouble configuring bspwm/sxhkd to cycle through monitors with the same keys as cycling through active nodes - currently set to the default sxhkd config `super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east} ` which also allows me to swap nodes when pressing shift. I have a 3 monitor setup, the primary being monitor 2 in the middle, 1 to the left and 3 to the right. Monitor 1 is assigned desktops 1 and 2, monitor 2 has desktops 3-8 and monitor 3 has desktops 9 and 10. 
The scenario I'm looking for is, for example, having active nodes in monitors 1 and 2(or desktop 1 and 3 to 8 - whichever desktop is active on monitor 2), but none on 3(empty desktops 9/10). The way the default configuration is set up, pressing `super + {h,l}` would  change the focus through the active nodes between monitors/desktops 1 and 2/3~8, back and forth. Now, what I would like to do is that I want to focus the 3rd monitor(hitting `super + l` when on the rightmost active node on monitor 2) to spawn a new node. The problem I have is that the cycle ends at monitor 2 when pressing `super + l`, and the focus doesn't change to the monitor to the right due to no nodes being active on that desktop. I noticed this is possible using something like `super + {h,l} bspc monitor --focus {west, east}` and it works. However, I would like to keep the same hotkeys to cycle through the active nodes, and when no active node is on any monitor, whether east or west, to focus that monitor regardless of no active nodes being on the corresponding desktop. 
I tried: 
```
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east};\
        bspc monitor {--focus,_} {west,_,_,east}
```
which yielded strange results - swapping nodes within the same monitor. I also tried:
```
super + {_,shift + }{h,j,k,l}
        bspc {node, desktop} -{f,s} {west,south,north,east}
```
which also gave a different result.
I believe this is just a mis-configuration thing rather than an actual issue, and I apologize if this doesn't belong here, but I can't find any better place to get guidance. I saw someone post a similar issue regarding monitors, and someone else commenting on it, and they suggested them to open a new issue. I really enjoy bspwm this far, and having this working would definitely make it my perfect setup. Thanks!

**Comment by danikron** [comment]
Might be a little tricky to accomplish within the sxhkd config, but you could try making a control script along the lines of
```
#! /bin/sh
direction=$1
bspc node -f $direction || bspc monitor -f $direction
```
and then launch that from sxhkd. Plus the flags and whatever else.
I did [something similar](https://github.com/danikron/dotfiles/blob/master/sysscripts/bspwmcont.sh) myself to get the behaviour I want with a stickied scratchpad and moving root-nodes around between desktops and monitors.
