### ISSUE TITLE
Unable to move to node window to preselect on multi-screen

### ISSUE THREAD

**Issue by stxm** [baskerville/bspwm#963]
I have a multi screen setup using (ctrl + Y) I cant move node to a preselect on different screen.

I have tried:

```
bspc node newest.marked.local -n 'newest.!automatic.local'  <------ Does not work at all
bspc  -n 'newest.!automatic.local'  <------ Works only on same screen

```

bspwm -v:
0.9.7
sxhkd -v:
0.6.0

**Comment by ortango** [comment]
> -n 'newest.!automatic.local'

newest.!automatic.local is specifically targeting only preselection on the current desktop. so remove it.

the other part of your problem:

are you marking a node before you run the command?

**Comment by jallbrit** [comment]
@stxm RTFM, `.local` applies only to "the reference desktop". Please close the issue if your issue is solved, or respond and help us help you.
