### ISSUE TITLE
Automatically move node to desktop

### ISSUE THREAD

**Issue by BigfootN** [baskerville/bspwm#968]
Hello,

I am trying to add the following rule in my `bspwmrc`:

```
bspc rule -a spotify desktop=music
```

Unfortunately when opening spotify, it opens on the current desktop, not the `music` desktop.

My bspwm version is the following: `0.9.7`.

Thank you very much in advance for any help.

**Comment by mdutra** [comment]
The syntax:
```
bspc rule -a (<class_name>|*)[:(<instance_name>|*)] desktop=music
```

I believe spotify's `<class_name>` is "Spotify", not "spotify". You can find out with `xprop | grep WM_CLASS`.

So this will probably fix:

```
bspc rule -a Spotify desktop=music
```

**Comment by BigfootN** [comment]
Thank you for your response.

I tried your solution but unfortunately it still doesn't work.

And `xprop | grep WM_CLASS` returns:
```
WM_CLASS(STRING) = "spotify", "Spotify"
```

Thank you again in advance for any help.

**Comment by mdutra** [comment]
No problem.

Run this command to see if it prints your desktop name "music" (all lowercase):
```
bspc query -D --names
```

**Comment by BigfootN** [comment]
`bspc query -D --names` does return `music` in the list.

Thank you again in advance for any help.

**Comment by mdutra** [comment]
It seems to be a problem with Spotify as mentioned here #291.

**Comment by baskerville** [comment]
This is, indeed, a duplicate of #291.

**Comment by BigfootN** [comment]
Thank you for your precious help.
