### ISSUE TITLE
xrandr display name with a "." is not allowed

### ISSUE THREAD

**Issue by herzrasen** [baskerville/bspwm#969]
Hi,

when using xrandr to output my display names it returns a list containing `DP-3.1` and `DP-3.2`.

When trying to use these names in `bspc monitor` commands, it returns the error message `monitor: Invalid modifier found in 'DP-3.2'.`

Any way to enable the bspc to use these kind of display names?

Cheers

**Comment by baskerville** [comment]
This is mentioned at the beginning of the manual:
```
The special selector %<name> can be used to select a monitor or a desktop with an invalid name.
```

**Comment by herzrasen** [comment]
Sorry @baskerville, I overread it. Thanks for the fast response.
