### ISSUE TITLE
IPC-commands using MONITOR_SEL with a monitor with a dot in its name returns "Invalid modifier"

### ISSUE THREAD

**Issue by vegardsjo** [baskerville/bspwm#971]
I have two monitors, both having names with dots in them (thanks to the nvidia driver assigning these names, and AFAIK, they cannot be changed without access to the source)

Running the following command to change the desktop for one of the monitors fail:

```bspc desktop -f 'DP-0.1':^2```

The desktop does not change. bspc outputs ```desktop -f: Invalid modifier found in 'DP-0.1:^2'.```

NOTE: This is exactly the ipc command that that polybar sends when one clicks on a desktop

Running ```bspc desktop -f '%DP-0.1':^2``` outputs nothing, but does not change the desktop.

The %-prefix works for the query command, e.g.: ```bspc query -D %DP-0.1```. Perhaps this can incorporated into the other commands?

**Comment by baskerville** [comment]
You could use the form `^m:^n` that selects the *n*-th desktop in the *m*-th monitor.

Or you could rename the monitors using `monitor MON_SEL --rename …`.
