### ISSUE TITLE
invisible preselect

### ISSUE THREAD

**Issue by nagy135** [baskerville/bspwm#972]
When single_monocle option is turned on, preselect area is invisible on single window workspace. I kinda see the point of invisible preselect on monocle layout, but this automatic monocle option should disable it, shouldnt it? I mean setting up direction is trivial but when i m trying to specify splitting ratio it unusable for me.
If this is just my specific problem please let me know, so far i m convinced it is fault of single_monocle and i m considering it bug, not feature. Thank you

**Comment by baskerville** [comment]
It looks like a duplicate of #954.

**Comment by nagy135** [comment]
yes it is, my apologies
