### ISSUE TITLE
Fibonacci layout and spiral layout

### ISSUE THREAD

**Issue by DMaxter** [baskerville/bspwm#976]
I saw that there was a time when bspwm used to have a fibonacci layout, nut it was removed. Is there a way to have it back? I have tried `spiral` for a while but it is buggy. Windows don't behave the way fibonacci is supposed to (maybe because it's not it haha) and in the following example it shows what happens:
```C
 +-----------------------+  +-----------------------+  +-----------------------+
 |                       |  |           |           |  |           |           |
 |                       |  |           |           |  |           |     A     |
 |                       |  |           |           |  |           |           |
 |           A           |  |     A     |     B     |  |     C     |-----------|
 |           ^           |  |     ^     |           |  |           |           |
 |                       |  |           |           |  |           |     B     |
 |                       |  |           |           |  |           |           |
 +-----------------------+  +-----------------------+  +-----------------------+
```
If on state 2 the insertion point is B, the layout is the same, but A and B are on the left side and C on the right and if I remove C, now I get state 2 mirrored. If this is normal behaviour, I am asking, can fibonacci be here again, not saying default, but as an option?

**Comment by baskerville** [comment]
No, the aforementioned automatic insertion scheme was never removed and always behaved this way. The available automatic insertion schemes are described in the README.

**Comment by DMaxter** [comment]
But the way it os behaving is not the way described in the README
