### ISSUE TITLE
Per-node border colors?

### ISSUE THREAD

**Issue by protesilaos** [baskerville/bspwm#979]
I cannot set a color only for the specificied node. A change applies to all items instead.

```
bspc config -n "$(bspc query -N -n)" focused_border_color '#ffffff'
```

Whereas, for example, this works as expected only for the current node:

```
bspc config -n "$(bspc query -N -n)" border_width 10
```

***

bspwm: 0.9.5

**Comment by baskerville** [comment]
Yes, `focused_border_color` is in the *Global Settings*, while `border_width` is in the *Node Settings* (cf. `man bspwm`).

**Comment by protesilaos** [comment]
Thanks for the clarification!
