### ISSUE TITLE
Border width not working for decimal numbers

### ISSUE THREAD

**Issue by Vixtron** [baskerville/bspwm#988]
Set `bspc config border_width 1.5`
Does not appear to work, is it the intended behavior?

**Comment by eirenicon** [comment]
This works for me:
bspc config border_width        	2

**Comment by Vixtron** [comment]
> This works for me:
> bspc config border_width 2

It does, but i3 works with decimal numbers too, but bspwm does not. 
I was using `1.5`

**Comment by eirenicon** [comment]
I know nothing about the code but it may be that one (i3) is using an internal unit of measure that is translated to pixels and that the other (bspwm) is simply using pixel count. (It's hard to split a pixel).

**Comment by ten3roberts** [comment]
It is intended. The value for border_width is the amount of real pixels on your screen that the border should be wide. You cannot use half pixels.
