### ISSUE TITLE
Firefox window needs update after changing workspaces

### ISSUE THREAD

**Issue by personinblack** [baskerville/bspwm#993]
When I switch from one workspace to another workspace which contains a Firefox window, the window gets rendered improperly (showing the previous workspace) until I update it by clicking on it or scrolling.

Screenshots (the left window supposed to be Firefox):
![2019-08-05-233552_1920x1080_scrot](https://user-images.githubusercontent.com/24732321/62493691-65316400-b7da-11e9-9518-f15a26006e86.png)
![2019-08-05-233558_1920x1080_scrot](https://user-images.githubusercontent.com/24732321/62493696-682c5480-b7da-11e9-986d-2608410f2663.png)
![2019-08-05-234257_1920x1080_scrot](https://user-images.githubusercontent.com/24732321/62493844-c5c0a100-b7da-11e9-8d69-6f636e893710.png)

**Comment by Junak** [comment]
It looks like a driver issues i have.
I suggest you to try running compositor (like compton) or another driver.
Also i never observed any of those issues on WM with 24bit visual(Like i3 or awesome with --no-argb).

**Comment by sunnyxxchen** [comment]
I have this exact same issue. I'm running compton and tried fiddling around with the compton settings but couldn't get anything to work.

**Comment by Junak** [comment]
Do you have it with other WMs?

**Comment by personinblack** [comment]
I haven't experienced anything like this with any other WM. I don't want to use a compositor and I think I can live with this issue.

**Comment by sunnyxxchen** [comment]
Yeah, I can reproduce the issue in i3, so this isn't a bspwm-specific problem.

Thanks!

**Comment by ajayraj** [comment]
@sunnyxxchen did you ever discover a fix?

**Comment by sunnyxxchen** [comment]
@ajayraj Using picom with "backend = glx" and "xrender-sync-fence = true" _seems_ to be working for me. Let me know if it also works for you.

**Comment by ajayraj** [comment]
Will check it out soon and let you know thanks!
